-- BibleQuest account-first cloud additions.
-- DEPLOYED to the shared Karimen + BibleQuest Supabase project: zkfmgezvzugchcwppreq.
-- BibleQuest remains logically isolated through the bible_* prefix and RLS.
-- Karimen's exam_results and live_exams tables are not modified by this file.

alter table public.bible_profiles
  add column if not exists full_name text,
  add column if not exists preferred_name text,
  add column if not exists avatar jsonb not null default '{"face":"smile","outfit":"traveler","background":"olive","companion":"sheep"}'::jsonb,
  add column if not exists onboarding_complete boolean not null default false,
  add column if not exists last_active_at timestamptz;

alter table public.bible_congregation_members
  add column if not exists avatar jsonb not null default '{"face":"smile","outfit":"traveler","background":"olive","companion":"sheep"}'::jsonb;

create table if not exists public.bible_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  device_key uuid not null,
  label text not null check (char_length(label) between 1 and 80),
  platform text check (platform is null or char_length(platform) <= 40),
  app_version text check (app_version is null or char_length(app_version) <= 40),
  trusted boolean not null default true,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (user_id, device_key)
);

create table if not exists public.bible_notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  book_code text,
  book_name text,
  chapter integer check (chapter is null or chapter > 0),
  verse_start integer check (verse_start is null or verse_start > 0),
  verse_end integer check (verse_end is null or verse_end > 0),
  title text not null default '' check (char_length(title) <= 160),
  body text not null default '' check (char_length(body) <= 20000),
  tags text[] not null default '{}',
  note_type text not null default 'study' check (note_type in ('study','prayer','question','reflection','sermon','other')),
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (verse_end is null or verse_start is null or verse_end >= verse_start)
);

create table if not exists public.bible_progress_snapshots (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  schema_version integer not null default 1 check (schema_version between 1 and 100),
  updated_at timestamptz not null default now(),
  check (octet_length(state::text) <= 1000000)
);

create table if not exists public.bible_activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_key uuid,
  feature text not null check (char_length(feature) between 1 and 80),
  event_type text not null check (char_length(event_type) between 1 and 80),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (octet_length(metadata::text) <= 6000)
);

create index if not exists bible_devices_user_last_seen_idx on public.bible_devices(user_id,last_seen_at desc);
create index if not exists bible_notes_user_updated_idx on public.bible_notes(user_id,updated_at desc);
create index if not exists bible_notes_passage_idx on public.bible_notes(user_id,book_code,chapter);
create index if not exists bible_activity_user_created_idx on public.bible_activity_events(user_id,created_at desc);
create index if not exists bible_activity_feature_created_idx on public.bible_activity_events(feature,created_at desc);
create index if not exists bible_congregation_members_user_avatar_idx on public.bible_congregation_members(user_id) include (display_name, avatar);

alter table public.bible_devices enable row level security;
alter table public.bible_notes enable row level security;
alter table public.bible_progress_snapshots enable row level security;
alter table public.bible_activity_events enable row level security;

revoke all on public.bible_devices, public.bible_notes, public.bible_progress_snapshots, public.bible_activity_events from anon, authenticated;
grant select, insert, update, delete on public.bible_devices, public.bible_notes to authenticated;
grant select, insert, update on public.bible_progress_snapshots to authenticated;
grant select, insert on public.bible_activity_events to authenticated;
grant update (display_name, avatar) on public.bible_congregation_members to authenticated;

create policy "devices own read" on public.bible_devices for select to authenticated using ((select auth.uid()) = user_id);
create policy "devices own insert" on public.bible_devices for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "devices own update" on public.bible_devices for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "devices own delete" on public.bible_devices for delete to authenticated using ((select auth.uid()) = user_id);

create policy "notes own read" on public.bible_notes for select to authenticated using ((select auth.uid()) = user_id);
create policy "notes own insert" on public.bible_notes for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "notes own update" on public.bible_notes for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "notes own delete" on public.bible_notes for delete to authenticated using ((select auth.uid()) = user_id);

create policy "progress own read" on public.bible_progress_snapshots for select to authenticated using ((select auth.uid()) = user_id);
create policy "progress own insert" on public.bible_progress_snapshots for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "progress own update" on public.bible_progress_snapshots for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "activity own read" on public.bible_activity_events for select to authenticated using ((select auth.uid()) = user_id);
create policy "activity own insert" on public.bible_activity_events for insert to authenticated with check ((select auth.uid()) = user_id);

create policy "members update own public profile" on public.bible_congregation_members
for update to authenticated
using ((select auth.uid()) = user_id and private.is_bible_congregation_member(congregation_id))
with check ((select auth.uid()) = user_id and private.is_bible_congregation_member(congregation_id));
