const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const externalAttrs = 'target="_blank" rel="noopener noreferrer"';
const optionList = (items, selected, value = item => item.code, label = item => item.name) => items.map(item => `<option value="${escapeHtml(value(item))}" ${value(item) === selected ? 'selected' : ''}>${escapeHtml(label(item))}</option>`).join('');
const verseButton = (kind, verse, currentChapter) => verse ? `<button type="button" class="bq-context-nearby" data-context-jump="${verse.verse}"><small>${kind}</small><b>${currentChapter}:${verse.verse}</b><span>${escapeHtml(verse.text)}</span></button>` : '<div></div>';
function renderLexeme(entry) {
  const direction = entry.language === 'Hebrew' ? ' dir="rtl"' : '';
  const usages = entry.usages.length ? `<div class="bq-context-usage-list">${entry.usages.map(use => `<button type="button" data-context-ref="${escapeHtml(`${use.code}.${use.chapter}.${use.verse}`)}">${escapeHtml(use.reference)}</button>`).join('')}</div>` : '<p>No additional tagged uses in this book were returned.</p>';
  return `<article class="bq-context-lexeme"><div class="bq-context-lexeme-top"><div><small>${escapeHtml(entry.language)} · ${escapeHtml(entry.strong)}</small><strong${direction}>${escapeHtml(entry.lemma || '—')}</strong><em>${escapeHtml(entry.transliteration || '')}</em></div><span aria-hidden="true">${entry.language === 'Hebrew' ? 'א' : 'Ω'}</span></div><div class="bq-context-gloss"><b>Brief gloss</b><p>${escapeHtml(entry.gloss || 'No brief gloss in this source.')}</p></div>${entry.morphology ? `<div class="bq-context-morph">${escapeHtml(entry.morphology)}</div>` : ''}<details class="bq-context-usage"><summary>Tagged in ${entry.usageTotal} verse${entry.usageTotal === 1 ? '' : 's'} in this book</summary>${usages}${entry.usageTotal > entry.usages.length ? `<small>Showing ${entry.usages.length} of ${entry.usageTotal} tagged uses.</small>` : ''}<p>Same Strong’s tag does not guarantee the same nuance in every verse. Compare sentences and context.</p></details></article>`;
}
export function createContextLab({ reader, dialog }) {
  if (!reader || !dialog) throw new Error('Context Lab requires Reader and dialog boundaries.');
  let current = null, chapterData = null, operation = 0;
  const close = () => { if (dialog.open) dialog.close(); };
  const renderLoading = () => { dialog.innerHTML = `<section class="bq-context-shell"><header class="bq-context-top"><button type="button" class="bq-secondary-button" data-context-close>← Bible Reader</button><b>Hebrew & Greek Context</b><span>אΩ</span></header><div class="bq-context-empty"><b>Loading original-language context…</b></div></section>`; bind(); };
  const renderError = error => { dialog.innerHTML = `<section class="bq-context-shell"><header class="bq-context-top"><button type="button" class="bq-secondary-button" data-context-close>← Bible Reader</button><b>Hebrew & Greek Context</b><span>אΩ</span></header><div class="bq-context-empty"><b>Could not load the context tools.</b><p>${escapeHtml(error?.message || 'Context data is unavailable.')}</p></div></section>`; bind(); };
  const render = snapshot => {
    const chapters = Array.from({ length: snapshot.book.chapters }, (_, index) => index + 1), verses = chapterData?.verses || [], step = snapshot.external.find(link => link.id === 'step');
    const lexical = snapshot.available ? snapshot.entries.length ? `<div class="bq-context-section-title"><h2>${escapeHtml([...new Set(snapshot.entries.map(item => item.language))].join(' + '))} words in this verse</h2><small>${snapshot.entries.length} lexical entries${snapshot.coverage ? ` · ${snapshot.coverage.taggedVerses} tagged verses in ${escapeHtml(snapshot.book.name)}` : ''}</small></div><section class="bq-context-lexeme-grid">${snapshot.entries.map(renderLexeme).join('')}</section>` : '<div class="bq-context-empty"><b>No lexical tags found for this verse.</b><p>Some structural or name-heavy verses have limited tagging. Try a nearby verse.</p></div>' : `<div class="bq-context-empty"><b>Context pack is unavailable.</b><p>${escapeHtml(snapshot.reason)}</p></div>`;
    dialog.innerHTML = `<section class="bq-context-shell"><header class="bq-context-top"><button type="button" class="bq-secondary-button" data-context-close>← Bible Reader</button><b>Hebrew & Greek Context</b><span aria-hidden="true">אΩ</span></header><section class="bq-context-hero"><small>ORIGINAL-LANGUAGE CONTEXT LAB</small><h1>Look closer without turning a dictionary into doctrine.</h1><p>BSB verse tags connect this passage to brief Hebrew/Greek lexical data from STEPBible.</p></section><section class="bq-context-picker"><label>Book<select data-context-book>${optionList(reader.books, snapshot.book.code)}</select></label><label>Chapter<select data-context-chapter>${chapters.map(value => `<option value="${value}" ${value === snapshot.chapter ? 'selected' : ''}>${value}</option>`).join('')}</select></label><label>Verse<select data-context-verse>${verses.map(item => `<option value="${item.verse}" ${item.verse === snapshot.verse ? 'selected' : ''}>${item.verse}</option>`).join('')}</select></label></section><article class="bq-context-scripture"><small>BSB · ${escapeHtml(snapshot.reference)}</small><p><sup>${snapshot.verse}</sup> ${escapeHtml(snapshot.scripture.text)}</p></article><section class="bq-context-strip">${verseButton('PREVIOUS', snapshot.previous, snapshot.chapter)}<article><small>CURRENT VERSE</small><b>${snapshot.chapter}:${snapshot.verse}</b><span>Read the surrounding sentence before focusing on a word.</span></article>${verseButton('NEXT', snapshot.next, snapshot.chapter)}</section><section class="bq-context-caution"><b>Three rules for a safer word study</b><ol><li>Read the sentence and paragraph before isolating a word.</li><li>A lexicon gives a range of possible meanings; grammar and context narrow that range.</li><li>Do not build doctrine from etymology or one Strong’s entry alone.</li></ol><p>These are <b>words tagged to the BSB verse</b>, not a reconstructed word-for-word interlinear.</p></section>${lexical}<section class="bq-context-source"><b>Sources & limits</b><p>${escapeHtml(snapshot.source)} · ${escapeHtml(snapshot.license)}</p><p>${escapeHtml(snapshot.note)}</p>${step ? `<a ${externalAttrs} href="${escapeHtml(step.href)}">Open this verse in STEP Bible</a>` : ''}</section></section>`;
    bind();
  };
  async function load({ code, chapter, verse }) {
    const id = ++operation; renderLoading();
    try {
      const chapterResult = await reader.contextChapter(code, chapter); if (id !== operation) return; chapterData = chapterResult;
      const validVerse = chapterResult.verses.some(item => item.verse === Number(verse)) ? Number(verse) : chapterResult.verses[0]?.verse; if (!validVerse) throw new Error('No BSB verses are available for this chapter.');
      const snapshot = await reader.lexicalContext({ code, chapter, verse: validVerse }); if (id !== operation) return; current = { code: snapshot.book.code, chapter: snapshot.chapter, verse: snapshot.verse }; render(snapshot);
    } catch (error) { if (id === operation) renderError(error); }
  }
  function bind() {
    dialog.querySelector('[data-context-close]')?.addEventListener('click', close);
    dialog.querySelector('[data-context-book]')?.addEventListener('change', event => load({ code: event.target.value, chapter: 1, verse: 1 }));
    dialog.querySelector('[data-context-chapter]')?.addEventListener('change', event => load({ code: current.code, chapter: Number(event.target.value), verse: 1 }));
    dialog.querySelector('[data-context-verse]')?.addEventListener('change', event => load({ code: current.code, chapter: current.chapter, verse: Number(event.target.value) }));
    dialog.querySelectorAll('[data-context-jump]').forEach(button => button.addEventListener('click', () => load({ code: current.code, chapter: current.chapter, verse: Number(button.dataset.contextJump) })));
    dialog.querySelectorAll('[data-context-ref]').forEach(button => button.addEventListener('click', () => { const [code, chapter, verse] = String(button.dataset.contextRef || '').split('.'); load({ code, chapter: Number(chapter), verse: Number(verse) }); }));
  }
  async function open({ code, chapter, verse = 1 } = {}) { const state = reader.getState(), target = { code: code || state.book, chapter: Number(chapter || state.chapter), verse: Number(verse) || 1 }; if (!dialog.open) dialog.showModal(); await load(target); }
  return Object.freeze({ open, close, destroy() { operation++; close(); dialog.replaceChildren(); } });
}
