export const JAPANESE_VOCABULARY_TERMS = Object.freeze([
  { term:'御心', reading:'みこころ', meaning:'神の望み・意志', simple:'神が望んでおられること', en:"God's will" },
  { term:'福音', reading:'ふくいん', meaning:'よい知らせ', simple:'イエス・キリストによる救いの知らせ', en:'gospel / good news' },
  { term:'信仰', reading:'しんこう', meaning:'神を信じ、信頼すること', simple:'神を信頼して従うこと', en:'faith' },
  { term:'恵み', reading:'めぐみ', meaning:'受ける資格ではなく与えられる神の好意', simple:'神から無償で与えられるよいもの', en:'grace' },
  { term:'救い', reading:'すくい', meaning:'危険や罪から救われること', simple:'神が人を罪とその結果から救うこと', en:'salvation' },
  { term:'救う', reading:'すくう', meaning:'危険や苦しみから助け出す', simple:'助け出す', en:'to save' },
  { term:'罪', reading:'つみ', meaning:'神の御心に反すること', simple:'神との正しい関係を壊す考えや行い', en:'sin' },
  { term:'義', reading:'ぎ', meaning:'正しいこと・神の前で正しい状態', simple:'神が正しいとされること', en:'righteousness' },
  { term:'愛', reading:'あい', meaning:'相手の益を求める愛', simple:'大切にし、相手のためによいことを求めること', en:'love' },
  { term:'祈り', reading:'いのり', meaning:'神に語りかけること', simple:'神に感謝・願い・思いを伝えること', en:'prayer' },
  { term:'祈る', reading:'いのる', meaning:'神に語りかける', simple:'神に感謝や願いを伝える', en:'to pray' },
  { term:'弟子', reading:'でし', meaning:'師から学び、その道に従う人', simple:'イエスから学び、従う人', en:'disciple' },
  { term:'復活', reading:'ふっかつ', meaning:'死から再び生きること', simple:'死んだ者が再び生きること', en:'resurrection' },
  { term:'永遠', reading:'えいえん', meaning:'終わりがないこと', simple:'いつまでも続くこと', en:'eternal / eternity' },
  { term:'聖霊', reading:'せいれい', meaning:'神の霊', simple:'信じる者に働かれる神の霊', en:'Holy Spirit' },
  { term:'契約', reading:'けいやく', meaning:'互いに結ばれる確かな約束', simple:'神と人との重要な約束・関係', en:'covenant' },
  { term:'預言', reading:'よげん', meaning:'神から託されたことばを伝えること', simple:'神のことばを人々に伝えること', en:'prophecy' },
  { term:'預言者', reading:'よげんしゃ', meaning:'神から託されたことばを伝える人', simple:'神のメッセージを伝える人', en:'prophet' },
  { term:'赦し', reading:'ゆるし', meaning:'罪・過ちを赦すこと', simple:'責め続けず、罪を赦すこと', en:'forgiveness' },
  { term:'赦す', reading:'ゆるす', meaning:'罪・過ちを赦免する', simple:'罪や過ちをゆるす', en:'to forgive' },
  { term:'悔い改め', reading:'くいあらため', meaning:'考えと方向を改めて神に向くこと', simple:'間違った道から神のほうへ向き直ること', en:'repentance' },
  { term:'神の国', reading:'かみのくに', meaning:'神の支配・統治', simple:'神が王として治められること', en:'kingdom of God' },
  { term:'栄光', reading:'えいこう', meaning:'神のすばらしさ・尊さ', simple:'神の偉大さが現れること', en:'glory' },
  { term:'あがない', reading:'あがない', meaning:'代価を払って解放すること', simple:'代価によって自由にすること', en:'redemption' },
  { term:'贖い', reading:'あがない', meaning:'代価を払って解放すること', simple:'代価によって自由にすること', en:'redemption' },
  { term:'戒め', reading:'いましめ', meaning:'守るよう命じられた教え', simple:'神からの大切な命令や教え', en:'commandment' },
  { term:'知恵', reading:'ちえ', meaning:'正しく理解し判断する力', simple:'何がよいかを理解して選ぶ力', en:'wisdom' }
].sort((a,b)=>b.term.length-a.term.length).map(item=>Object.freeze({ ...item })));
