(() => {
  'use strict';
  const KEY='biblequest_accessibility_v1';let layer=null,queued=false;
  function state(){try{return {...{text:'normal',motion:'system',contrast:'normal'},...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{text:'normal',motion:'system',contrast:'normal'}}}function save(s){localStorage.setItem(KEY,JSON.stringify(s));apply()}
  function apply(){const s=state(),root=document.documentElement;root.dataset.bqText=s.text;root.dataset.bqMotion=s.motion;root.dataset.bqContrast=s.contrast;root.classList.toggle('bq-reduce-motion',s.motion==='reduce'||(s.motion==='system'&&matchMedia('(prefers-reduced-motion: reduce)').matches));schedule()}
  function audit(){queued=false;document.querySelectorAll('button,a,[role="button"]').forEach(el=>{if(el.getAttribute('aria-label')||el.textContent.trim())return;const t=el.getAttribute('title')||el.dataset.action||el.dataset.route;if(t)el.setAttribute('aria-label',String(t).replace(/[-_]/g,' '))});document.querySelectorAll('[id$="Layer"]:not(.hidden),.modern-sheet:not(.hidden)').forEach(el=>{if(el.closest('.reader-layer'))return;if(!el.hasAttribute('role'))el.setAttribute('role','dialog');if(!el.hasAttribute('aria-modal'))el.setAttribute('aria-modal','true')})}
  function schedule(){if(queued)return;queued=true;queueMicrotask(audit)}
  function ensure(){if(layer)return layer;layer=document.createElement('div');layer.className='accessibility-layer hidden';layer.id='bqAccessibility';document.body.appendChild(layer);return layer}
  function close(){ensure().classList.add('hidden');document.body.classList.remove('accessibility-open')}
  function render(){const s=state(),x=ensure();x.innerHTML=`<main class="accessibility-card"><header><button data-a11y-close>← BibleQuest</button><b>Accessibility</b><span>♿</span></header><label>Text size<select data-a11y="text"><option value="normal" ${s.text==='normal'?'selected':''}>Normal</option><option value="large" ${s.text==='large'?'selected':''}>Large</option><option value="xlarge" ${s.text==='xlarge'?'selected':''}>Extra large</option></select></label><label>Motion<select data-a11y="motion"><option value="system" ${s.motion==='system'?'selected':''}>Follow device</option><option value="reduce" ${s.motion==='reduce'?'selected':''}>Reduce motion</option><option value="full" ${s.motion==='full'?'selected':''}>Full motion</option></select></label><label>Contrast<select data-a11y="contrast"><option value="normal" ${s.contrast==='normal'?'selected':''}>Normal</option><option value="strong" ${s.contrast==='strong'?'selected':''}>Stronger contrast</option></select></label><p>Keyboard focus remains visible. Dialogs receive accessible semantics automatically. BibleQuest respects reduced-motion preferences.</p></main>`;x.classList.remove('hidden');document.body.classList.add('accessibility-open');x.querySelector('[data-a11y-close]').onclick=close;x.querySelectorAll('[data-a11y]').forEach(sel=>sel.onchange=()=>{const n=state();n[sel.dataset.a11y]=sel.value;save(n)})}
  function inject(){if(document.querySelector('[data-a11y-open]'))return;const host=document.querySelector('.modern-footer-row,.profile-panel,.profile-card,.modern-home');if(!host)return;const b=document.createElement('button');b.type='button';b.dataset.a11yOpen='1';b.className='a11y-entry';b.textContent='♿ Accessibility';b.onclick=render;host.appendChild(b)}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!ensure().classList.contains('hidden'))close()});new MutationObserver(()=>{schedule();inject()}).observe(document.documentElement,{childList:true,subtree:true});matchMedia('(prefers-reduced-motion: reduce)').addEventListener?.('change',apply);apply();setTimeout(inject,900);window.BQAccessibility={open:render,state,apply};
})();