(() => {
const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const STORE='biblequest_state_v2', today=()=>new Date().toISOString().slice(0,10);
const defaults={xp:0,streak:1,lastDay:null,answered:0,correct:0,books:{Genesis:0,Exodus:0,Gospels:0,Acts:0},seen:[],polls:{},achievements:[],situations:0};
let state=load(), view='home', game=null;
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return {...defaults}}}
function save(){localStorage.setItem(STORE,JSON.stringify(state));checkAchievements()}
function checkDay(){if(state.lastDay===today())return;const p=new Date();p.setDate(p.getDate()-1);state.streak=state.lastDay===p.toISOString().slice(0,10)?state.streak+1:1;state.lastDay=today();save()}
function checkAchievements(){const a=[];if(state.answered>=1)a.push('first');if(state.correct>=10)a.push('ten');if(state.correct>=25)a.push('twentyfive');if(state.xp>=250)a.push('xp250');if(state.situations>=3)a.push('wisdom3');state.achievements=[...new Set([...(state.achievements||[]),...a])];localStorage.setItem(STORE,JSON.stringify(state))}
function route(v,p){view=v;game=p||null;render();scrollTo({top:0,behavior:'smooth'})}
function nav(){return `<nav class="bottom"><button class="navbtn ${view==='home'?'active':''}" data-route="home"><b>🏡</b>Home</button><button class="navbtn ${view==='journey'?'active':''}" data-route="journey"><b>🗺️</b>Journey</button><button class="navbtn ${view==='discuss'?'active':''}" data-route="discuss"><b>💭</b>Discuss</button><button class="navbtn ${view==='profile'?'active':''}" data-route="profile"><b>🌱</b>Me</button></nav>`}
function shell(c){return `<main class="app"><header class="topbar"><div class="brand">Bible<span>Quest</span></div><div class="streak">🔥 ${state.streak} day${state.streak===1?'':'s'}</div></header>${c}</main>${nav()}`}
function home(){const pct=Math.min(100,Math.round(state.correct/BQ_QUESTIONS.length*100));const deep=BQ_DEEP_QUESTIONS[new Date().getDate()%BQ_DEEP_QUESTIONS.length];return shell(`<section class="hero"><div class="eyebrow">Your Bible journey</div><h1>Learn by playing.</h1><p>Facts → context → wisdom → reflection.</p><div class="progress"><i style="width:${pct}%"></i></div></section><div class="section-title"><h2>Play now</h2><small>${state.xp} XP</small></div><section class="grid"><button class="card big" data-action="daily"><div class="icon">⚡</div><h3>Daily 5</h3><p>Five quick questions mixing review and new material.</p></button><button class="card" data-action="quick"><div class="icon">🎯</div><h3>Quick Play</h3><p>Random Bible knowledge.</p></button><button class="card" data-action="detective"><div class="icon">🕵️</div><h3>Bible Detective</h3><p>Guess the person from clues.</p></button><button class="card" data-action="story"><div class="icon">📖</div><h3>Story Adventure</h3><p>Follow the story and understand the key moment.</p></button><button class="card" data-action="timeline"><div class="icon">⏳</div><h3>Timeline</h3><p>Put events in chronological order.</p></button><button class="card" data-action="context"><div class="icon">🧠</div><h3>Context Mode</h3><p>Less trivia. More “why did this happen?”</p></button><button class="card big" data-action="situation"><div class="icon">🧭</div><h3>Situations & Wisdom</h3><p>Real-life dilemmas. Choose a response, then examine the biblical principles behind it.</p></button></section><div class="section-title"><h2>Think deeper</h2></div><button class="card big" data-route="discuss"><div class="icon">💭</div><h3>Question for everyone</h3><p>${deep.q}</p></button><div class="section-title"><h2>Future</h2></div><div class="card locked big"><div class="icon">👥</div><h3>Study Together</h3><p>Reserved for live rooms, group polls, challenges and facilitator tools later.</p></div>`)}
function startQuestions(type='quick'){let bank=[...BQ_QUESTIONS];if(type==='context')bank=bank.filter(q=>q.level>=2);bank=shuffle(bank).slice(0,type==='daily'?5:10);route('quiz',{bank,index:0,score:0,answered:false,type})}
function quizView(){const q=game.bank[game.index];if(!q)return results();return shell(`<button class="back" data-route="home">← Back</button><section class="question-card"><div class="question-meta"><span>${q.book} · Level ${q.level}</span><span>${game.index+1}/${game.bank.length}</span></div><h2>${q.q}</h2><div class="choices">${q.choices.map((c,i)=>`<button class="choice" data-choice="${i}">${String.fromCharCode(65+i)}. ${c}</button>`).join('')}</div><div id="feedback"></div></section>`)}
function answerChoice(i){if(game.answered)return;game.answered=true;const q=game.bank[game.index],good=i===q.answer;state.answered++;if(good){state.correct++;state.xp+=10;game.score++}else state.xp+=3;state.seen=[...new Set([...state.seen,q.id])];bumpBook(q.book,good?5:2);save();$$('.choice').forEach((b,n)=>{if(n===q.answer)b.classList.add('correct');else if(n===i&&!good)b.classList.add('wrong');b.disabled=true});$('#feedback').innerHTML=`<div class="explain"><b>${good?'✅ Correct':'🌱 Learn this one'}</b><br>${q.why}<br><span class="ref">📖 ${q.ref}</span></div><div class="actions"><button class="primary" data-next>${game.index+1===game.bank.length?'See results':'Next question'}</button></div>`;bind()}
function bumpBook(book,n){let k=book;if(['Matthew','Mark','Luke','John'].includes(book))k='Gospels';if(state.books[k]===undefined)return;state.books[k]=Math.min(100,state.books[k]+n)}
function results(){return shell(`<section class="question-card"><div class="eyebrow">Round complete</div><h2>${game.score}/${game.bank.length} correct</h2><p>Mistakes still earn learning XP because they identify material worth reviewing.</p><div class="stats"><div class="stat"><b>${game.score*10+(game.bank.length-game.score)*3}</b><small>XP gained</small></div><div class="stat"><b>${Math.round(100*game.score/game.bank.length)}%</b><small>accuracy</small></div><div class="stat"><b>${state.streak}</b><small>day streak</small></div></div><div class="actions"><button class="primary" data-route="home">Home</button><button class="secondary" data-action="quick">Play again</button></div></section>`)}
function journey(){const rows=[['Genesis','🌳','Creation, Abraham, Joseph'],['Exodus','🏜️','Moses, rescue, covenant'],['Gospels','🐟','Life and teaching of Jesus'],['Acts','🔥','Early church and mission']];return shell(`<section class="panel"><div class="eyebrow">Learning path</div><h1>Bible Journey</h1><p>Progress increases as you work through questions.</p><div class="journey">${rows.map(([k,e,d])=>`<div class="journey-row"><div class="badge">${e}</div><div class="grow"><h3>${k}</h3><small>${d}</small><div class="mini-progress"><i style="width:${state.books[k]}%"></i></div></div><span class="pill">${state.books[k]}%</span></div>`).join('')}</div><div class="source-box" style="margin-top:14px"><b>Next:</b> this map will expand using imported public/open Bible datasets rather than a hand-written content ceiling.</div></section>`)}
function detective(){const d=pick(BQ_DETECTIVES);return shell(`<button class="back" data-route="home">← Back</button><section class="question-card"><div class="eyebrow">Bible Detective</div><h2>Who am I?</h2><div class="clues">${d.clues.map((x,i)=>`<div class="clue">${i+1}. ${x}</div>`).join('')}</div><input class="answer-input" id="detectiveAnswer" placeholder="Type the name…"><div class="actions"><button class="primary" data-check-detective="${d.id}">Check answer</button></div><div id="feedback"></div></section>`)}
function checkDetective(id){const d=BQ_DETECTIVES.find(x=>x.id===id),v=$('#detectiveAnswer').value.trim();if(!v)return;const good=v.toLowerCase()===d.answer.toLowerCase();state.answered++;if(good){state.correct++;state.xp+=12}else state.xp+=3;save();$('#feedback').innerHTML=`<div class="explain"><b>${good?'✅ Correct':'Answer: '+d.answer}</b><br><span class="ref">📖 ${d.ref}</span></div><div class="actions"><button class="primary" data-action="detective">Another</button></div>`;bind()}
function story(){route('storyPlay',{story:pick(BQ_STORIES),scene:0})}
function storyPlay(){const s=game.story;if(game.scene<s.scenes.length)return shell(`<button class="back" data-route="home">← Back</button><section class="question-card"><div class="question-meta"><span>${s.emoji} ${s.title}</span><span>${game.scene+1}/${s.scenes.length}</span></div><div class="story-scene">${s.scenes[game.scene]}</div><div class="actions"><button class="primary" data-story-next>${game.scene===s.scenes.length-1?'Checkpoint':'Continue'}</button></div></section>`);const q=s.checkpoint;return shell(`<section class="question-card"><div class="eyebrow">Story checkpoint</div><h2>${q.q}</h2><div class="choices">${q.choices.map((c,i)=>`<button class="choice" data-story-choice="${i}">${c}</button>`).join('')}</div><div id="feedback"></div></section>`)}
function storyAnswer(i){const q=game.story.checkpoint,good=i===q.answer;state.answered++;if(good){state.correct++;state.xp+=15}else state.xp+=4;save();$$('.choice').forEach((b,n)=>{if(n===q.answer)b.classList.add('correct');else if(n===i&&!good)b.classList.add('wrong');b.disabled=true});$('#feedback').innerHTML=`<div class="explain"><b>${good?'✅ You followed the story':'🌱 Revisit the key moment'}</b><br><span class="ref">📖 ${q.ref}</span></div><div class="actions"><button class="primary" data-action="story">Another story</button><button class="secondary" data-route="home">Home</button></div>`;bind()}
function timeline(){const t=structuredClone(pick(BQ_TIMELINES));t.current=shuffle([...t.items]);route('timelinePlay',t)}
function timelinePlay(){return shell(`<button class="back" data-route="home">← Back</button><section class="question-card"><div class="eyebrow">Timeline challenge</div><h2>${game.title}</h2><p>Move the events until they are in chronological order.</p><div class="timeline-list">${game.current.map((x,i)=>`<div class="timeline-item"><span>${i+1}. ${x}</span><span class="move"><button class="tiny" data-move="${i},-1">↑</button><button class="tiny" data-move="${i},1">↓</button></span></div>`).join('')}</div><div class="actions"><button class="primary" data-check-timeline>Check order</button></div><div id="feedback"></div></section>`)}
function move(i,d){const j=i+d;if(j<0||j>=game.current.length)return;[game.current[i],game.current[j]]=[game.current[j],game.current[i]];render()}
function checkTimeline(){const good=game.current.every((x,i)=>x===game.items[i]);state.answered++;if(good){state.correct++;state.xp+=20}else state.xp+=4;save();$('#feedback').innerHTML=`<div class="explain"><b>${good?'✅ Perfect order':'Not yet.'}</b>${good?'':'<br>Try again; your arrangement is preserved.'}</div>`;bind()}
function situation(){const s=pick(BQ_SITUATIONS);return shell(`<button class="back" data-route="home">← Back</button><section class="question-card"><div class="eyebrow">Situations & Wisdom</div><h2>${s.title}</h2><div class="scenario">${s.scenario}</div><div class="choices">${s.options.map((o,i)=>`<button class="choice" data-situation="${s.id},${i}">${o}</button>`).join('')}</div><div id="feedback"></div></section>`)}
function chooseSituation(id,i){const s=BQ_SITUATIONS.find(x=>x.id===id);state.situations++;state.xp+=6;save();$$('.choice').forEach(b=>b.disabled=true);$('#feedback').innerHTML=`<div class="explain"><span class="tag">WISDOM / APPLICATION</span><br><br><b>You chose:</b> ${s.options[i]}<br><br>${s.note}<br><span class="ref">📖 ${s.refs.join(' · ')}</span><br><br><small>This mode explores biblical principles and judgment. It is not treated as a one-answer doctrine quiz.</small></div><div class="actions"><button class="primary" data-action="situation">Another situation</button><button class="secondary" data-route="home">Home</button></div>`;bind()}
function discuss(){const p=BQ_DEEP_QUESTIONS[new Date().getDate()%BQ_DEEP_QUESTIONS.length],sel=state.polls[p.id];return shell(`<section class="panel"><div class="eyebrow">Open question</div><h1>${p.q}</h1><p>${p.context}</p><div class="poll-options">${p.options.map((o,i)=>`<button class="poll ${sel===i?'selected':''}" data-poll="${p.id},${i}">${o}</button>`).join('')}</div><div class="source-box" style="margin-top:14px"><b>Passages to examine:</b><br>${p.refs.join(' · ')}<br><br><b>Classification:</b> open question. The app does not present the poll winner as biblical authority.</div><div class="section-title"><h2>Community layer</h2></div><div class="card locked"><div class="icon">🗣️</div><h3>Public responses</h3><p>Coming with accounts, moderation and Supabase.</p></div></section>`)}
function profile(){const acc=state.answered?Math.round(state.correct/state.answered*100):0;const defs={first:['🌱','First Step','Answer your first question'],ten:['⭐','Ten Correct','Get 10 questions right'],twentyfive:['🏅','Growing Scholar','Get 25 questions right'],xp250:['🔥','250 XP','Reach 250 learning XP'],wisdom3:['🧭','Wisdom Explorer','Complete 3 situations']};return shell(`<section class="panel"><div class="eyebrow">Your progress</div><h1>Growing, not grinding.</h1><div class="stats"><div class="stat"><b>${state.xp}</b><small>XP</small></div><div class="stat"><b>${state.correct}</b><small>correct</small></div><div class="stat"><b>${acc}%</b><small>accuracy</small></div></div><div class="section-title"><h2>Achievements</h2></div>${Object.entries(defs).map(([id,[e,n,d]])=>`<div class="achievement" style="opacity:${state.achievements.includes(id)?1:.45}"><div class="medal">${e}</div><div><b>${n}</b><div style="color:var(--muted);font-size:13px">${d}</div></div></div>`).join('')}<div class="section-title"><h2>Content foundation</h2></div><div class="source-box">Production content will favor public-domain/open datasets: BSB/WEB Bible text, unfoldingWord questions and stories, STEPBible structured data, and OpenBible cross-references. Imported content will preserve source and license metadata.</div></section>`)}
function render(){checkDay();const html=view==='home'?home():view==='journey'?journey():view==='quiz'?quizView():view==='detective'?detective():view==='storyPlay'?storyPlay():view==='timelinePlay'?timelinePlay():view==='situation'?situation():view==='discuss'?discuss():view==='profile'?profile():home();$('#app').innerHTML=html;bind()}
function bind(){$$('[data-route]').forEach(x=>x.onclick=()=>route(x.dataset.route));$$('[data-action]').forEach(x=>x.onclick=()=>{const a=x.dataset.action;if(['quick','daily','context'].includes(a))startQuestions(a);else if(a==='detective')route('detective');else if(a==='story')story();else if(a==='timeline')timeline();else if(a==='situation')route('situation')});$$('[data-choice]').forEach(x=>x.onclick=()=>answerChoice(+x.dataset.choice));$$('[data-next]').forEach(x=>x.onclick=()=>{game.index++;game.answered=false;render()});$$('[data-check-detective]').forEach(x=>x.onclick=()=>checkDetective(x.dataset.checkDetective));$$('[data-story-next]').forEach(x=>x.onclick=()=>{game.scene++;render()});$$('[data-story-choice]').forEach(x=>x.onclick=()=>storyAnswer(+x.dataset.storyChoice));$$('[data-move]').forEach(x=>x.onclick=()=>{const [i,d]=x.dataset.move.split(',').map(Number);move(i,d)});$$('[data-check-timeline]').forEach(x=>x.onclick=checkTimeline);$$('[data-poll]').forEach(x=>x.onclick=()=>{const [id,i]=x.dataset.poll.split(',');state.polls[id]=+i;state.xp+=2;save();render()});$$('[data-situation]').forEach(x=>x.onclick=()=>{const [id,i]=x.dataset.situation.split(',');chooseSituation(id,+i)})}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
})();
