(() => {
  let assignments=[],progress=[],members=[],teams=[],role='',channel=null,message='',completingId='';
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const account=()=>window.BQAccount,client=()=>account()?.client?.(),session=()=>account()?.session?.();
  function cloud(){try{return JSON.parse(localStorage.getItem('biblequest_cloud_v1')||'{}')}catch{return {}}}
  const congregationId=()=>cloud().activeCongregationId||'';
  const leader=()=>['facilitator','leader','admin'].includes(role);
  function layer(){let x=document.getElementById('bqAssignmentLayer');if(!x){x=document.createElement('div');x.id='bqAssignmentLayer';x.className='completion-layer hidden';document.body.appendChild(x)}return x}
  function show(html){const x=layer();x.innerHTML=`<main class="completion-shell assignment-shell">${html}</main>`;x.classList.remove('hidden');document.body.classList.add('completion-open');bind();x.scrollTop=0}
  function close(){if(channel&&client())client().removeChannel(channel);channel=null;completingId='';layer().classList.add('hidden');document.body.classList.remove('completion-open')}
  const fmt=d=>d?new Intl.DateTimeFormat('en-PH',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(d)):'No deadline';
  const icon=t=>({reading:'📖','guided-study':'📘',mission:'🧭',quiz:'⚡',reflection:'💭',couples:'💞',group:'👥',custom:'✅'})[t]||'✅';
  function targetName(a){if(a.target_scope==='all')return 'Whole congregation';if(a.target_scope==='member')return members.find(x=>x.user_id===a.target_id)?.display_name||'Selected member';return teams.find(x=>x.id===a.target_id)?.name||'Selected team'}
  async function load(){
    const c=client(),s=session(),cid=congregationId();if(!c||!s||!cid)return render();
    const own=await c.from('bible_congregation_members').select('role').eq('congregation_id',cid).eq('user_id',s.user.id).eq('active',true).maybeSingle();if(own.error)throw own.error;role=own.data?.role||'';
    const calls=[c.from('bible_assignments').select('*').eq('congregation_id',cid).eq('active',true).order('due_at',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false}),c.from('bible_assignment_progress').select('*').order('updated_at',{ascending:false})];
    if(leader())calls.push(c.from('bible_congregation_members').select('user_id,display_name,role,avatar').eq('congregation_id',cid).eq('active',true).order('display_name'),c.from('bible_teams').select('id,name,kind').eq('congregation_id',cid).order('name'));
    const out=await Promise.all(calls);if(out[0].error)throw out[0].error;if(out[1].error)throw out[1].error;assignments=out[0].data||[];progress=out[1].data||[];
    if(leader()){members=out[2].data||[];teams=out[3].data||[]}else{members=[];teams=[]}
    render();subscribe();markSeen();
  }
  function ownProgress(id){return progress.find(x=>x.assignment_id===id&&x.user_id===session()?.user?.id)}
  function completionForm(a){return `<form class="assignment-submit" data-assignment-submit="${a.id}"><label>Optional response to your leader<textarea name="submission" maxlength="4000" rows="4" placeholder="Share only what you intentionally want your leader to receive."></textarea></label><small>Your private Bible notes and journal stay private. Only this submitted text is shared.</small><div><button type="button" class="secondary" data-assignment-cancel>Cancel</button><button>Complete task</button></div></form>`}
  function card(a){
    const p=ownProgress(a.id),done=p?.status==='completed',late=a.due_at&&!done&&new Date(a.due_at)<new Date(),rows=progress.filter(x=>x.assignment_id===a.id),completions=rows.filter(x=>x.status==='completed'),started=rows.filter(x=>x.status==='started').length;
    return `<article class="assignment-card ${done?'done':''} ${late?'late':''}"><div class="assignment-icon">${icon(a.assignment_type)}</div><div class="assignment-main"><div class="assignment-meta"><span>${esc(a.assignment_type.replace('-',' '))}</span><span>${esc(targetName(a))}</span><span>${a.points} pts</span></div><h3>${esc(a.title)}</h3>${a.instructions?`<p>${esc(a.instructions)}</p>`:''}${(a.scripture_refs||[]).length?`<div class="ref-chips">${a.scripture_refs.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}<small class="assignment-due">${late?'⚠️ Overdue · ':done?'✓ Completed · ':'Due · '}${esc(fmt(a.due_at))}</small>${!leader()&&!done&&completingId!==a.id?`<div class="assignment-actions"><button data-assignment-start="${a.id}" data-type="${a.assignment_type}">Start activity</button><button class="secondary" data-assignment-complete="${a.id}">Mark complete</button></div>`:''}${!leader()&&!done&&completingId===a.id?completionForm(a):''}${!leader()&&done&&p?.submission?`<div class="assignment-response own"><b>Your submitted response</b><p>${esc(p.submission)}</p></div>`:''}${!leader()&&done&&p?.leader_feedback?`<div class="leader-feedback"><b>Leader feedback</b><p>${esc(p.leader_feedback)}</p></div>`:''}${leader()?`<div class="assignment-leader-stats"><span><b>${completions.length}</b> completed</span><span><b>${started}</b> started</span><button class="secondary" data-assignment-archive="${a.id}">Archive</button></div><details class="assignment-results"><summary>${completions.length} completed · view submissions</summary>${completions.length?completions.map(x=>{const m=members.find(y=>y.user_id===x.user_id);return `<div class="assignment-response"><b>${esc(m?.display_name||'Member')}</b><small>${esc(fmt(x.completed_at))}</small>${x.submission?`<p>${esc(x.submission)}</p>`:'<p class="muted">No written submission.</p>'}<form data-assignment-feedback="${a.id}" data-user="${x.user_id}"><input name="feedback" maxlength="2000" value="${esc(x.leader_feedback||'')}" placeholder="Optional leader feedback"><button class="secondary">Save feedback</button></form></div>`}).join(''):'<p class="muted">No completions yet.</p>'}</details>`:''}</div></article>`}
  function render(error=''){
    if(!account()?.status?.().signedIn)return show(`<header class="completion-top"><button data-assignment-close>← BibleQuest</button><b>Assignments</b><span>📮</span></header><div class="completion-empty"><span>🔐</span><b>Sign in to receive church assignments.</b><p>Your tasks follow your BibleQuest account across devices.</p><button data-assignment-account>Open account</button></div>`);
    if(!congregationId())return show(`<header class="completion-top"><button data-assignment-close>← BibleQuest</button><b>Assignments</b><span>📮</span></header><div class="completion-empty"><span>⛪</span><b>Join a congregation first.</b><p>Assignments are pushed inside your active BibleQuest congregation.</p></div>`);
    show(`<header class="completion-top"><button data-assignment-close>← BibleQuest</button><b>Assignments & Tasks</b><span>📮</span></header><section class="completion-hero assignment-hero"><small>${leader()?'LEADER DESK':'FOR YOU'}</small><h1>${leader()?'Guide the next step.':'Your next faithful step.'}</h1><p>${leader()?'Send reading, study, reflection, quiz, group, couples, or custom tasks.':'Tasks from your leaders appear here and sync across your signed-in devices.'}</p></section>${message?`<div class="completion-message">${esc(message)}</div>`:''}${error?`<div class="completion-message error">${esc(error)}</div>`:''}${leader()?createForm():''}<div class="completion-section"><h2>${leader()?'Active assignments':'Assigned to you'}</h2><small>${assignments.length} active</small></div><section class="assignment-list">${assignments.length?assignments.map(card).join(''):`<div class="completion-empty"><span>🌱</span><b>No active assignments.</b><p>${leader()?'Create the first activity when your group is ready.':'Your leaders have not pushed a task yet.'}</p></div>`}</section><div class="privacy-note"><b>Privacy rule</b><p>Leaders see task completion and only the reflection/submission you intentionally send here. Your private Bible notes and journal are not exposed.</p></div>`)
  }
  function createForm(){return `<details class="assignment-create"><summary>＋ Create a new assignment</summary><form data-assignment-create><label>Title<input name="title" maxlength="120" required placeholder="Read John 1 and reflect"></label><label>Instructions<textarea name="instructions" maxlength="4000" rows="3" placeholder="What should members do or think about?"></textarea></label><div class="assignment-form-grid"><label>Type<select name="type"><option value="reading">Reading</option><option value="guided-study">Guided Study</option><option value="mission">Mission</option><option value="quiz">Quiz</option><option value="reflection">Reflection</option><option value="couples">Couples</option><option value="group">Group activity</option><option value="custom">Custom</option></select></label><label>Audience<select name="scope" data-assignment-scope><option value="all">Everyone</option><option value="member">One member</option><option value="team">One team</option></select></label></div><label data-assignment-target-wrap class="hidden">Target<select name="target" data-assignment-target></select></label><label>Scripture references<input name="refs" maxlength="500" placeholder="John 1; Psalm 23"></label><div class="assignment-form-grid"><label>Due<input name="due" type="datetime-local"></label><label>Completion points<input name="points" type="number" min="0" max="25" value="5"></label></div><button>Push assignment</button></form></details>`}
  async function create(form){const fd=new FormData(form),scope=String(fd.get('scope')),target=String(fd.get('target')||''),rawDue=String(fd.get('due')||''),dueAt=rawDue?new Date(rawDue).toISOString():null;const body={action:'create',congregationId:congregationId(),title:fd.get('title'),instructions:fd.get('instructions'),assignmentType:fd.get('type'),targetScope:scope,targetId:scope==='all'?null:target,scriptureRefs:String(fd.get('refs')||'').split(/[;,]/).map(x=>x.trim()).filter(Boolean),dueAt,points:Number(fd.get('points')||5)};const r=await client().functions.invoke('bq-assignment',{body});if(r.error)throw r.error;message='Assignment pushed to the selected audience.';await load()}
  async function complete(form){const id=form.dataset.assignmentSubmit,submission=String(new FormData(form).get('submission')||'').trim();const assignment=assignments.find(x=>x.id===id);const r=await client().functions.invoke('bq-assignment',{body:{action:'complete',congregationId:congregationId(),assignmentId:id,submission}});if(r.error)throw r.error;completingId='';message=`Completed${r.data?.awarded?` · +${r.data.awarded} pts`:''}.`;account()?.track?.('leader_assignment','completed',{assignment_id:id,assignment_type:assignment?.assignment_type||'custom',awarded:Number(r.data?.awarded)||0}).catch?.(()=>{});await load()}
  async function start(id,type){await client().functions.invoke('bq-assignment',{body:{action:'start',congregationId:congregationId(),assignmentId:id}}).catch(()=>{});account()?.track?.('leader_assignment','started',{assignment_id:id,assignment_type:type}).catch?.(()=>{});close();setTimeout(()=>{if(type==='reading')window.BQReader?.openLibrary?.();else if(type==='guided-study')window.BQStudy?.open?.();else if(type==='mission')window.BQMission?.open?.();else if(type==='couples')window.BQCouples?.open?.();else if(type==='group')window.BQGroupPlay?.open?.();else if(type==='reflection')window.BQNotes?.open?.();else if(type==='quiz'){if(window.BQOpenReview?.start)window.BQOpenReview.start();else document.querySelector('[data-modern-review]')?.click()}else document.querySelector('[data-daily]')?.click()},50)}
  async function feedback(form){const r=await client().functions.invoke('bq-assignment',{body:{action:'feedback',congregationId:congregationId(),assignmentId:form.dataset.assignmentFeedback,targetUserId:form.dataset.user,feedback:new FormData(form).get('feedback')}});if(r.error)throw r.error;message='Feedback saved.';await load()}
  async function archive(id){if(!confirm('Archive this assignment? Members will no longer see it as active.'))return;const r=await client().functions.invoke('bq-assignment',{body:{action:'archive',congregationId:congregationId(),assignmentId:id}});if(r.error)throw r.error;message='Assignment archived.';await load()}
  function updateTargets(){const scope=layer().querySelector('[data-assignment-scope]')?.value,wrap=layer().querySelector('[data-assignment-target-wrap]'),select=layer().querySelector('[data-assignment-target]');if(!wrap||!select)return;wrap.classList.toggle('hidden',scope==='all');select.innerHTML=scope==='member'?members.map(x=>`<option value="${x.user_id}">${esc(x.display_name)} · ${esc(x.role)}</option>`).join(''):scope==='team'?teams.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join(''):''}
  function bind(){const x=layer();x.querySelectorAll('[data-assignment-close]').forEach(b=>b.onclick=close);x.querySelector('[data-assignment-account]')?.addEventListener('click',()=>account()?.open?.());x.querySelector('[data-assignment-create]')?.addEventListener('submit',e=>{e.preventDefault();create(e.currentTarget).catch(err=>render(err.message||String(err)))});x.querySelector('[data-assignment-scope]')?.addEventListener('change',updateTargets);updateTargets();x.querySelectorAll('[data-assignment-start]').forEach(b=>b.onclick=()=>start(b.dataset.assignmentStart,b.dataset.type));x.querySelectorAll('[data-assignment-complete]').forEach(b=>b.onclick=()=>{completingId=b.dataset.assignmentComplete;render()});x.querySelectorAll('[data-assignment-cancel]').forEach(b=>b.onclick=()=>{completingId='';render()});x.querySelectorAll('[data-assignment-submit]').forEach(f=>f.onsubmit=e=>{e.preventDefault();complete(e.currentTarget).catch(err=>render(err.message||String(err)))});x.querySelectorAll('[data-assignment-feedback]').forEach(f=>f.onsubmit=e=>{e.preventDefault();feedback(e.currentTarget).catch(err=>render(err.message||String(err)))});x.querySelectorAll('[data-assignment-archive]').forEach(b=>b.onclick=()=>archive(b.dataset.assignmentArchive).catch(err=>render(err.message||String(err))))}
  function subscribe(){if(channel||!client()||!congregationId())return;channel=client().channel(`bq-assignments-${congregationId()}`).on('postgres_changes',{event:'*',schema:'public',table:'bible_assignments',filter:`congregation_id=eq.${congregationId()}`},payload=>{if(payload.eventType==='INSERT'&&!leader())toast(`📮 New assignment: ${payload.new.title||'BibleQuest task'}`);load().catch(()=>{})}).on('postgres_changes',{event:'*',schema:'public',table:'bible_assignment_progress'},()=>load().catch(()=>{})).subscribe()}
  function toast(text){let t=document.querySelector('.bq-task-toast');if(!t){t=document.createElement('button');t.className='bq-task-toast';t.onclick=()=>open();document.body.appendChild(t)}t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),6000)}
  function seenKey(){return `biblequest_assignments_seen_${congregationId()}`}
  function markSeen(){localStorage.setItem(seenKey(),JSON.stringify(assignments.map(x=>x.id)));window.dispatchEvent(new CustomEvent('bq-assignment-change'))}
  function unreadCount(){try{const seen=new Set(JSON.parse(localStorage.getItem(seenKey())||'[]'));return assignments.filter(x=>!seen.has(x.id)).length}catch{return 0}}
  async function open(){message='';completingId='';try{await load()}catch(e){render(e.message||String(e))}}
  window.BQAssignments={open,unreadCount,refresh:load};
})();
