(() => {
  const KEY='biblequest_avatar_style_v1';let selected=localStorage.getItem(KEY)||'starter',patched=false;
  const account=()=>window.BQAccount,client=()=>account()?.client?.(),session=()=>account()?.session?.();
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const STYLES=[
    {id:'starter',icon:'🌱',name:'Fresh Start',req:'Available from the beginning',test:()=>true,progress:()=> 'Ready'},
    {id:'sakura',icon:'🌸',name:'Sakura Pilgrim',req:'Reach a 7-day learning streak',test:m=>m.streak>=7,progress:m=>`${Math.min(m.streak,7)}/7 streak days`},
    {id:'scholar',icon:'🎓',name:'Little Scholar',req:'Answer 100 BibleQuest questions',test:m=>m.answered>=100,progress:m=>`${Math.min(m.answered,100)}/100 answers`},
    {id:'lantern',icon:'🏮',name:'Lantern Keeper',req:'Earn 500 XP',test:m=>m.xp>=500,progress:m=>`${Math.min(m.xp,500)}/500 XP`},
    {id:'scroll',icon:'📜',name:'Scroll Keeper',req:'Study 100 recall cards',test:m=>m.deck>=100,progress:m=>`${Math.min(m.deck,100)}/100 recall cards`},
    {id:'flame',icon:'🔥',name:'Steady Flame',req:'Reach a 30-day learning streak',test:m=>m.streak>=30,progress:m=>`${Math.min(m.streak,30)}/30 streak days`},
    {id:'shepherd',icon:'🐑',name:'Shepherd Friend',req:'Get 250 answers correct',test:m=>m.correct>=250,progress:m=>`${Math.min(m.correct,250)}/250 correct`},
    {id:'couple',icon:'💞',name:'Growing Together',req:'Complete 10 couples conversations',test:m=>m.couples>=10,progress:m=>`${Math.min(m.couples,10)}/10 conversations`},
    {id:'community',icon:'⛪',name:'Table Builder',req:'Complete 10 group sessions',test:m=>m.group>=10,progress:m=>`${Math.min(m.group,10)}/10 group sessions`},
    {id:'world',icon:'🌏',name:'Bible World Traveler',req:'Reach 50% in every Journey region',test:m=>m.mastery.length>=8&&m.mastery.every(x=>x>=50),progress:m=>`${m.mastery.filter(x=>x>=50).length}/8 regions at 50%`},
    {id:'crown',icon:'👑',name:'Crown of Curiosity',req:'Earn 2,500 XP',test:m=>m.xp>=2500,progress:m=>`${Math.min(m.xp,2500)}/2500 XP`}
  ];
  function metrics(){let a={},c={},community={};try{a=JSON.parse(localStorage.getItem('biblequest_state_v4')||'{}')}catch{}try{c=JSON.parse(localStorage.getItem('biblequest_couples_v1')||'{}')}catch{}try{community=JSON.parse(localStorage.getItem('biblequest_community_v1')||'{}')}catch{}const deck=Object.values(a.deckStats||{}).reduce((n,x)=>n+(Number(x?.seen)||0),0);const me=(a.profile?.name||account()?.profile?.()?.preferred_name||'').trim();const group=(community.sessions||[]).filter(x=>(x.participants||[]).includes(me)).length;return {xp:Number(a.xp)||0,streak:Number(a.streak)||0,answered:Number(a.answered)||0,correct:Number(a.correct)||0,deck,couples:(c.history||[]).length,group,mastery:Object.values(a.mastery||{}).map(Number)}}
  const style=id=>STYLES.find(x=>x.id===id)||STYLES[0];
  function unlocked(s,m=metrics()){return Boolean(s.test(m))}
  function layer(){let x=document.getElementById('bqAvatarVault');if(!x){x=document.createElement('div');x.id='bqAvatarVault';x.className='completion-layer hidden';document.body.appendChild(x)}return x}
  function close(){layer().classList.add('hidden');document.body.classList.remove('completion-open')}
  function decorate(avatar={}){return {...avatar,cosmetic:selected}}
  function patchAvatar(){if(patched||!window.BQAvatar)return;patched=true;const originalRender=window.BQAvatar.render.bind(window.BQAvatar),originalGlyph=window.BQAvatar.glyph.bind(window.BQAvatar),originalClean=window.BQAvatar.clean?.bind(window.BQAvatar);window.BQAvatar.render=(a={},size='')=>{const cosmetic=a?.cosmetic||'starter',s=style(cosmetic);return `<span class="avatar-cosmetic style-${cosmetic}">${originalRender(a,size)}${cosmetic!=='starter'?`<i class="cosmetic-mark">${s.icon}</i>`:''}</span>`};window.BQAvatar.glyph=(a={})=>`${originalGlyph(a)}${a?.cosmetic&&a.cosmetic!=='starter'?style(a.cosmetic).icon:''}`;if(originalClean)window.BQAvatar.clean=a=>({...originalClean(a),...(a?.cosmetic?{cosmetic:a.cosmetic}:{})})}
  function applyLocal(){patchAvatar();try{const p=account()?.profile?.();if(p?.avatar)p.avatar.cosmetic=selected}catch{}try{const k='biblequest_state_v4',a=JSON.parse(localStorage.getItem(k)||'{}');a.profile={...(a.profile||{}),avatar:{...(a.profile?.avatar||account()?.avatar?.()||{}),cosmetic:selected}};localStorage.setItem(k,JSON.stringify(a))}catch{}window.dispatchEvent(new CustomEvent('bq-avatar-style-change',{detail:{selected}}))}
  async function loadCloud(){if(!client()||!session())return;const r=await client().from('bible_avatar_cosmetics').select('selected_style').eq('user_id',session().user.id).maybeSingle();if(!r.error&&r.data?.selected_style){selected=r.data.selected_style;localStorage.setItem(KEY,selected);applyLocal()}}
  async function select(id){const s=style(id),m=metrics();if(!unlocked(s,m))return;selected=id;localStorage.setItem(KEY,id);applyLocal();const c=client(),u=session()?.user;if(c&&u){await c.from('bible_avatar_cosmetics').upsert({user_id:u.id,selected_style:id,updated_at:new Date().toISOString()},{onConflict:'user_id'});const base={...(account()?.profile?.()?.avatar||account()?.avatar?.()||{}),cosmetic:id};await c.from('bible_profiles').update({avatar:base,updated_at:new Date().toISOString()}).eq('user_id',u.id);await c.from('bible_congregation_members').update({avatar:base}).eq('user_id',u.id)}render('Avatar style equipped!')}
  function render(message=''){patchAvatar();const m=metrics(),current=style(selected),x=layer();x.innerHTML=`<main class="completion-shell avatar-vault-shell"><header class="completion-top"><button data-vault-close>← BibleQuest</button><b>Avatar Vault</b><span>🎁</span></header><section class="completion-hero avatar-vault-hero"><small>UNLOCK BY GROWING</small><h1>Your journey can change your look.</h1><p>Special avatar frames and companions stay locked until you complete real BibleQuest milestones.</p></section>${message?`<div class="completion-message">${esc(message)}</div>`:''}<section class="vault-current"><div class="vault-avatar">${window.BQAvatar?.render?.(decorate(account()?.avatar?.()||{}),'large')||'🙂'}</div><div><small>EQUIPPED</small><h2>${current.icon} ${esc(current.name)}</h2><p>Cosmetics appear beside your avatar in congregation surfaces and rankings.</p></div></section><div class="completion-section"><h2>Unlock collection</h2><small>${STYLES.filter(s=>unlocked(s,m)).length}/${STYLES.length}</small></div><section class="vault-grid">${STYLES.map(s=>{const ok=unlocked(s,m),active=s.id===selected;return `<button class="vault-card ${ok?'unlocked':'locked'} ${active?'active':''}" data-vault-style="${s.id}" ${ok?'':'disabled'}><div class="vault-icon">${ok?s.icon:'🔒'}</div><div><b>${esc(s.name)}</b><small>${ok?(active?'Equipped · tap another unlocked style':'Unlocked · tap to equip'):esc(s.req)}</small><em>${esc(s.progress(m))}</em></div>${active?'<i>✓</i>':''}</button>`}).join('')}</section><div class="privacy-note"><b>Fair-play note</b><p>Avatar rewards are cosmetic only. They do not increase scores or imply spiritual rank. Locked cards always show exactly how to unlock them.</p></div></main>`;x.classList.remove('hidden');document.body.classList.add('completion-open');x.querySelectorAll('[data-vault-close]').forEach(b=>b.onclick=close);x.querySelectorAll('[data-vault-style]:not([disabled])').forEach(b=>b.onclick=()=>select(b.dataset.vaultStyle).catch(()=>{}));x.scrollTop=0}
  async function open(){await loadCloud().catch(()=>{});render()}
  function boot(){const wait=()=>{if(window.BQAvatar){patchAvatar();applyLocal();setTimeout(()=>loadCloud().catch(()=>{}),1600)}else setTimeout(wait,100)};wait()}
  window.BQAvatarVault={open,selected:()=>selected,styles:STYLES};boot();
})();
