(()=>{'use strict';
const A=window.BQ2;
const STORIES=Array.isArray(window.BQ_STORIES)?window.BQ_STORIES:[];
const DEEP=Array.isArray(window.BQ_DEEP_QUESTIONS)?window.BQ_DEEP_QUESTIONS:[];
const SITUATIONS=Array.isArray(window.BQ_SITUATIONS)?window.BQ_SITUATIONS:[];
const {$,$$,esc,pageHead,shuffled,toast}=A;
const ensure=()=>{if(!Array.isArray(A.state.notes))A.state.notes=[];if(!Array.isArray(A.state.recordings))A.state.recordings=[];if(!A.state.familyNotes||typeof A.state.familyNotes!=='object')A.state.familyNotes={};A.save()};
function study(){ensure();$('#main').innerHTML=`${pageHead('Study & Reflect','Story journeys, practical wisdom, and open discussion prompts.')}<div class="game-menu"><button class="game-tile" id="storyStudy"><span class="icon">▤</span><strong>Story Journey</strong><p>Walk through a Bible story scene by scene, then answer a checkpoint.</p></button><button class="game-tile" id="wisdomStudy"><span class="icon">◇</span><strong>Wisdom Situations</strong><p>Apply biblical principles to work, money, relationships, and online life.</p></button><button class="game-tile" id="deepStudy"><span class="icon">?</span><strong>Deep Questions</strong><p>Open discussion prompts with multiple Scripture references.</p></button></div>`;$('#storyStudy').onclick=story;$('#wisdomStudy').onclick=situation;$('#deepStudy').onclick=deep}
function story(){const s=shuffled(STORIES)[0];if(!s)return toast('Story data unavailable');let scene=0;const paint=()=>{$('#main').innerHTML=`${pageHead(s.title,s.book,'<a class="btn secondary" href="#/study">Study</a>')}<div class="card quiz-card"><div class="quiz-meta"><span>Scene ${scene+1} / ${s.scenes.length}</span><span>${esc(s.book)}</span></div><div class="progress"><span style="width:${(scene+1)/s.scenes.length*100}%"></span></div><p class="question" style="font-size:19px">${esc(s.scenes[scene])}</p>${scene<s.scenes.length-1?'<button class="btn" id="nextScene">Next scene</button>':`<div class="section-title"><h2>Checkpoint</h2></div><p><strong>${esc(s.checkpoint.q)}</strong></p><div class="choices">${s.checkpoint.choices.map((x,i)=>`<button class="choice" data-story-answer="${i}">${esc(x)}</button>`).join('')}</div><div id="storyAnswer"></div>`}</div>`;if($('#nextScene'))$('#nextScene').onclick=()=>{scene++;paint()};$$('[data-story-answer]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.storyAnswer),ok=i===s.checkpoint.answer;$$('[data-story-answer]').forEach((x,n)=>x.classList.add(n===s.checkpoint.answer?'correct':n===i?'wrong':''));$('#storyAnswer').innerHTML=`<div class="answer-note"><strong>${ok?'Correct':'Review'}</strong> · ${esc(s.checkpoint.ref)}</div>`;A.activity(ok?18:7)})};paint()}
function situation(){const s=shuffled(SITUATIONS)[0];if(!s)return toast('Situation data unavailable');$('#main').innerHTML=`${pageHead('Wisdom Situation',s.title,'<a class="btn secondary" href="#/study">Study</a>')}<div class="card quiz-card"><p class="question" style="font-size:19px">${esc(s.scenario)}</p><div class="choices">${s.options.map((x,i)=>`<button class="choice" data-situation="${i}">${esc(x)}</button>`).join('')}</div><div id="situationResult"></div></div>`;$$('[data-situation]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.situation),best=2;$$('[data-situation]').forEach((x,n)=>x.classList.add(n===best?'correct':n===i?'wrong':''));$('#situationResult').innerHTML=`<div class="answer-note"><strong>Consider:</strong> ${esc(s.note)}<br><br><strong>References:</strong> ${s.refs.map(esc).join(' · ')}</div>`;A.activity(i===best?12:5)})}
function deep(){const d=shuffled(DEEP)[0];if(!d)return toast('Discussion data unavailable');$('#main').innerHTML=`${pageHead('Deep Question','Discussion, not a scored doctrine item.','<a class="btn secondary" href="#/study">Study</a>')}<div class="card quiz-card"><h2 class="question">${esc(d.q)}</h2><p>${esc(d.context)}</p><div class="choices">${d.options.map((x,i)=>`<button class="choice" data-deep="${i}">${esc(x)}</button>`).join('')}</div><div id="deepResult"></div></div>`;$$('[data-deep]').forEach(b=>b.onclick=()=>{$$('[data-deep]').forEach(x=>x.disabled=true);b.classList.add('correct');$('#deepResult').innerHTML=`<div class="answer-note"><strong>Your response:</strong> ${esc(b.textContent)}<br><br><strong>Read and compare:</strong> ${d.refs.map(esc).join(' · ')}<br><button class="btn secondary small" id="saveDeepNote" style="margin-top:10px">Save a note</button></div>`;$('#saveDeepNote').onclick=()=>{location.hash='#/notes';sessionStorage.setItem('bq2.note.seed',`${d.q}\n\nReferences: ${d.refs.join(', ')}\n\n`)}})}
function notes(){ensure();let seed=sessionStorage.getItem('bq2.note.seed')||'';sessionStorage.removeItem('bq2.note.seed');$('#main').innerHTML=`${pageHead('Private Notes','Stored only in this browser unless you export your BibleQuest backup.')}<div class="grid two"><div class="card"><div class="field"><label>Title / passage</label><input id="noteTitle" placeholder="e.g. John 15"></div><div class="field"><label>Note</label><textarea id="noteBody" rows="8">${esc(seed)}</textarea></div><button class="btn" id="addNote">Save note</button></div><div class="card"><div class="eyebrow">Saved notes</div><div id="noteList" class="mission-list"></div></div></div>`;const paint=()=>{$('#noteList').innerHTML=A.state.notes.length?A.state.notes.slice().reverse().map(n=>`<div class="mission-step" style="grid-template-columns:1fr auto"><span><strong>${esc(n.title||'Untitled')}</strong><small>${esc(n.date)} · ${esc(n.body.slice(0,100))}${n.body.length>100?'…':''}</small></span><button class="btn secondary small" data-delete-note="${n.id}">Delete</button></div>`).join(''):'<p class="note">No notes yet.</p>';$$('[data-delete-note]').forEach(b=>b.onclick=()=>{A.state.notes=A.state.notes.filter(n=>String(n.id)!==b.dataset.deleteNote);A.save();paint()})};paint();$('#addNote').onclick=()=>{const body=$('#noteBody').value.trim();if(!body)return toast('Write a note first.');A.state.notes.push({id:Date.now(),date:A.today(),title:$('#noteTitle').value.trim(),body});A.activity(4);A.save();$('#noteTitle').value='';$('#noteBody').value='';paint();toast('Note saved')}}
function recordings(){ensure();$('#main').innerHTML=`${pageHead('Recordings','A lightweight link library. Videos are never embedded in the app, so opening this page cannot freeze the BibleQuest runtime.')}<div class="grid two"><div class="card"><div class="field"><label>Title</label><input id="recTitle" placeholder="Sunday service / Bible study"></div><div class="field"><label>YouTube or recording URL</label><input id="recUrl" inputmode="url" placeholder="https://..."></div><button class="btn" id="addRecording">Add recording</button><p class="note">Links open in a separate browser tab/app. No iframe, autoplay, thumbnail polling, or live-room runtime is loaded here.</p></div><div class="card"><div class="eyebrow">Saved recordings</div><div id="recordingList" class="mission-list"></div></div></div>`;const paint=()=>{$('#recordingList').innerHTML=A.state.recordings.length?A.state.recordings.slice().reverse().map(r=>`<div class="mission-step" style="grid-template-columns:1fr auto"><span><strong>${esc(r.title)}</strong><small>${esc(r.url)}</small></span><span class="data-actions"><a class="btn small" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">Open</a><button class="btn secondary small" data-delete-rec="${r.id}">Delete</button></span></div>`).join(''):'<p class="note">No recording links saved yet.</p>';$$('[data-delete-rec]').forEach(b=>b.onclick=()=>{A.state.recordings=A.state.recordings.filter(r=>String(r.id)!==b.dataset.deleteRec);A.save();paint()})};paint();$('#addRecording').onclick=()=>{const title=$('#recTitle').value.trim(),raw=$('#recUrl').value.trim();let u;try{u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw new Error()}catch{return toast('Enter a valid http/https URL.')}A.state.recordings.push({id:Date.now(),title:title||'Recording',url:u.href});A.save();$('#recTitle').value='';$('#recUrl').value='';paint();toast('Recording link added')}}
const familyTopics=[
 ['Listening & understanding','Listen before answering; aim to understand before defending yourself.','James 1:19 · Proverbs 18:13'],
 ['Financial stewardship','Plan together, count the cost, and make money decisions transparent.','Luke 14:28–30 · Proverbs 21:5'],
 ['Shared responsibilities','Treat service at home and outside the home as shared stewardship, not scorekeeping.','Galatians 5:13 · Ecclesiastes 4:9–10'],
 ['Love & sacrifice','Ask what patient, truthful, sacrificial love requires in the present situation.','1 Corinthians 13:4–7 · Ephesians 5:21'],
 ['Parenting & family guidance','Teach through repeated conversation and through the example children actually see.','Deuteronomy 6:6–7 · Ephesians 6:4']
];
function family(){ensure();$('#main').innerHTML=`${pageHead('Couples & Family','Five discussion areas with Scripture references and private notes.')}<div class="grid two">${familyTopics.map((t,i)=>`<div class="card"><div class="eyebrow">Topic ${i+1}</div><h2>${esc(t[0])}</h2><p>${esc(t[1])}</p><p class="note">${esc(t[2])}</p><div class="field"><label>Our note / action</label><textarea rows="4" data-family-note="${i}">${esc(A.state.familyNotes[i]||'')}</textarea></div><button class="btn secondary small" data-family-save="${i}">Save</button></div>`).join('')}</div>`;$$('[data-family-save]').forEach(b=>b.onclick=()=>{const i=b.dataset.familySave;A.state.familyNotes[i]=$(`[data-family-note="${i}"]`).value.trim();A.save();toast('Family note saved')})}
A.route('study',study);A.route('notes',notes);A.route('recordings',recordings);A.route('family',family);
})();
