(()=>{'use strict';
const D=window.BQ2_DATA;
const QUESTIONS=Array.isArray(window.BQ_QUESTIONS)?window.BQ_QUESTIONS:[];
const KEY='biblequest.clean.v1',VERSION=1;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dateKey=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const today=()=>dateKey(new Date()),yesterday=()=>{const d=new Date();d.setDate(d.getDate()-1);return dateKey(d)};
const shuffled=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function defaults(){return{version:VERSION,profile:{name:'Explorer',xp:0,streak:0,lastActivity:null,totalActivities:0},mission:{},reader:{book:'JHN',chapter:1,read:{}},games:{played:0,correct:0,best:0},transform:{answers:{},lastResult:null},together:{games:0},badges:[],settings:{tutorialSeen:false}}}
function merge(base,extra){if(Array.isArray(base))return Array.isArray(extra)?extra:base;if(base&&typeof base==='object'){const out={...base};if(extra&&typeof extra==='object')for(const k of Object.keys(extra))out[k]=k in base?merge(base[k],extra[k]):extra[k];return out}return extra??base}
function readState(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&x.version===VERSION?merge(defaults(),x):defaults()}catch{return defaults()}}
let state=readState(),routes={};
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateStatus()}
function replaceState(x){state=merge(defaults(),x);save()}
function awardBadges(){const b=new Set(state.badges||[]);if(state.profile.totalActivities>=1)b.add('First Step');if(state.profile.streak>=3)b.add('3-Day Streak');if(state.profile.streak>=7)b.add('7-Day Streak');if(state.games.correct>=20)b.add('Bible Recall');if(Object.keys(state.reader.read||{}).length>=10)b.add('Reader');if(state.transform.lastResult)b.add('Reflection');state.badges=[...b]}
function activity(xp=0){const t=today();if(state.profile.lastActivity!==t){state.profile.streak=state.profile.lastActivity===yesterday()?state.profile.streak+1:1;state.profile.lastActivity=t}state.profile.xp+=xp;state.profile.totalActivities++;awardBadges();save()}
function toast(msg){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function route(name,fn){routes[name]=fn}
function routeName(){return((location.hash||'#/home').replace(/^#\/?/,'').split(/[?\/]/)[0]||'home')}
const NAV=[['home','⌂','Home'],['reader','▤','Learn'],['games','◆','Play'],['world','◌','Journey'],['more','⋯','More']];
function shell(){document.getElementById('app').innerHTML=`<div class="app-shell"><header class="topbar"><div class="topbar-inner"><a class="brand" href="#/home"><span class="brand-mark">BQ</span><span class="brand-copy"><strong>BibleQuest</strong><small>Clean rebuild</small></span></a><div class="status-cluster"><span class="pill gold" id="topXp"></span><span class="pill hide-mobile" id="topStreak"></span></div></div></header><main class="main" id="main"></main><nav class="bottom-nav"><div class="bottom-nav-inner">${NAV.map(([r,i,l])=>`<a class="nav-item" data-nav="${r}" href="#/${r}"><span class="nicon">${i}</span><span>${l}</span></a>`).join('')}</div></nav></div>`;updateStatus()}
function updateStatus(){const x=$('#topXp'),s=$('#topStreak');if(x)x.textContent=`${state.profile.xp} XP`;if(s)s.textContent=`${state.profile.streak} day${state.profile.streak===1?'':'s'} streak`}
function declaration(){return`<div class="declaration"><span class="cross">✝</span><span><strong>I confess that Jesus is Lord</strong> and the authority of my life.</span></div>`}
function pageHead(title,sub,action=''){return`<div class="page-head"><div><h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div>${action}</div>`}
function render(){const n=routeName();$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===n));window.scrollTo({top:0,behavior:'auto'});const fn=routes[n]||routes.home;if(fn)fn();else $('#main').innerHTML='<div class="error-box">Feature route is not available.</div>'}
function missionState(){const d=today();if(!state.mission[d])state.mission[d]={done:[],apply:'',reflect:''};return state.mission[d]}
function daily(){const n=Math.floor(new Date(today()).getTime()/86400000);return D.dailyPassages[Math.abs(n)%D.dailyPassages.length]}
function missionPct(){return Math.round(missionState().done.length/5*100)}
function completeMission(i,xp=8,silent=false){const m=missionState();if(!m.done.includes(i)){m.done.push(i);activity(xp);if(m.done.length===5){state.profile.xp+=25;save();if(!silent)toast('Daily Journey complete · +25 bonus XP')}else if(!silent)toast('Journey step completed')}save()}
function missionSteps(m){const steps=[['Retrieve','Answer from memory'],['Context','Read the passage itself'],['Learn','Strengthen one connection'],['Apply','Choose a real action'],['Reflect','Write one takeaway']];return steps.map((s,i)=>{const done=m.done.includes(i);return`<div class="mission-step ${done?'done':''}"><span class="step-num">${done?'✓':i+1}</span><span><strong>${s[0]}</strong><small>${s[1]}</small></span><span>${done?'Done':''}</span></div>`}).join('')}
function home(){const m=missionState(),p=missionPct(),d=daily(),icons=['▤','◆','◌','↟','♟','★'];$('#main').innerHTML=`${declaration()}<section class="hero"><div class="card emphasis mission-card"><div class="eyebrow">Today · ${esc(d.title)}</div><h1 class="mission-title">Continue My Journey — 4 min</h1><p class="mission-copy">Remember, read in context, learn, apply, and reflect. One meaningful activity protects your streak.</p><div class="progress-row"><div class="progress"><span style="width:${p}%"></span></div><span class="progress-label">${m.done.length}/5</span></div><a class="btn" href="#/mission">${p===100?'Review today’s journey':'Continue journey'}</a></div><div class="stats"><div class="stat"><b>${state.profile.xp}</b><span>XP</span></div><div class="stat"><b>${state.profile.streak}</b><span>Streak</span></div><div class="stat"><b>${state.profile.totalActivities}</b><span>Activities</span></div><div class="stat"><b>${state.badges.length}</b><span>Badges</span></div></div></section><div class="section-title"><h2>Explore BibleQuest</h2><small>Clean core</small></div><div class="grid three">${D.quickActions.map((a,i)=>`<a class="card action-card" href="${a.route}"><span class="action-icon">${icons[i]||'•'}</span><strong>${esc(a.label)}</strong><span>${esc(a.sub)}</span></a>`).join('')}</div><div class="section-title"><h2>Today’s five movements</h2><small>${p}% complete</small></div><div class="card"><div class="mission-list">${missionSteps(m)}</div></div>`}
function mission(){const m=missionState(),d=daily();$('#main').innerHTML=`${pageHead('Daily Journey',`${d.book} ${d.chapter}:${d.from}–${d.to} · ${d.title}`,'<a class="btn secondary" href="#/home">Home</a>')}<div class="grid two"><div class="card"><div class="eyebrow">1 · Retrieve</div><h2>Answer before revealing</h2><p id="missionQ"></p><div id="missionChoices" class="choices"></div><div id="missionAnswer"></div></div><div class="card"><div class="eyebrow">2 · Context</div><h2>Read the actual passage</h2><p>Open today’s passage in the rebuilt Bible reader.</p><button class="btn" id="missionRead">Open ${esc(d.book)} ${d.chapter}</button>${m.done.includes(1)?'<p><strong>✓ Context completed</strong></p>':''}</div><div class="card"><div class="eyebrow">3 · Learn</div><h2>Make one connection</h2><p>${esc(d.prompt)}</p><div class="focus-box">Notice who is speaking, who is listening, what happens before and after, and what the text actually claims.</div><button class="btn secondary" id="missionLearn">I reviewed the connection</button></div><div class="card"><div class="eyebrow">4 · Apply</div><h2>Turn it into action</h2><div class="field"><label>One concrete action today</label><textarea id="missionApply" rows="4">${esc(m.apply)}</textarea></div><button class="btn secondary" id="missionApplySave">Save action</button></div><div class="card"><div class="eyebrow">5 · Reflect</div><h2>One-sentence takeaway</h2><div class="field"><label>What should you remember?</label><textarea id="missionReflect" rows="4">${esc(m.reflect)}</textarea></div><button class="btn secondary" id="missionReflectSave">Save reflection</button></div><div class="card emphasis"><div class="eyebrow">Progress</div><h2>${missionPct()}% complete</h2><div class="progress-row"><div class="progress"><span style="width:${missionPct()}%"></span></div><span class="progress-label">${m.done.length}/5</span></div></div></div>`;
const q=shuffled(QUESTIONS)[0]||{q:'Who led Israel out of Egypt?',choices:['Moses','David','Peter','Paul'],answer:0,ref:'Exodus 3–14',why:'Moses led Israel out of Egypt.'};$('#missionQ').textContent=q.q;$('#missionChoices').innerHTML=q.choices.map((c,i)=>`<button class="choice" data-mi="${i}">${esc(c)}</button>`).join('');$$('[data-mi]').forEach(b=>b.onclick=()=>{const box=$('#missionAnswer');if(box.dataset.locked)return;box.dataset.locked='1';const chosen=Number(b.dataset.mi);$$('[data-mi]').forEach((x,i)=>x.classList.add(i===q.answer?'correct':i===chosen?'wrong':''));box.innerHTML=`<div class="answer-note"><strong>${chosen===q.answer?'Correct':'Review'}</strong> · ${esc(q.ref)}<br>${esc(q.why)}</div>`;completeMission(0,12)});$('#missionRead').onclick=()=>{sessionStorage.setItem('bq2.reader.jump',JSON.stringify({...d,mission:true}));location.hash='#/reader'};$('#missionLearn').onclick=()=>{completeMission(2,8);render()};$('#missionApplySave').onclick=()=>{const v=$('#missionApply').value.trim();if(!v)return toast('Write one concrete action first.');m.apply=v;completeMission(3,8);render()};$('#missionReflectSave').onclick=()=>{const v=$('#missionReflect').value.trim();if(!v)return toast('Write one takeaway first.');m.reflect=v;completeMission(4,8);render()}}
function tutorial(){if(state.settings.tutorialSeen)return;const w=document.createElement('div');w.className='modal-backdrop';w.innerHTML=`<div class="modal"><div class="eyebrow">Rebuilt from the base</div><h2>Welcome to clean BibleQuest</h2><p>One explicit runtime replaces the old layered feature injection.</p><div class="mission-list"><div class="mission-step"><span class="step-num">1</span><span><strong>Daily Journey</strong><small>One obvious 4-minute path</small></span></div><div class="mission-step"><span class="step-num">2</span><span><strong>Read</strong><small>66 bundled Bible book packs</small></span></div><div class="mission-step"><span class="step-num">3</span><span><strong>Play + Grow</strong><small>Games, Bible World, Transformation, group play</small></span></div></div><div class="modal-actions"><button class="btn" id="tutorialDone">Start</button></div></div>`;document.body.appendChild(w);$('#tutorialDone').onclick=()=>{state.settings.tutorialSeen=true;save();w.remove()}}
async function sw(){if(!('serviceWorker'in navigator))return;try{await navigator.serviceWorker.register('./bq2-sw.js',{scope:'./'})}catch(e){console.warn(e)}}
function boot(){shell();window.addEventListener('hashchange',render);if(!location.hash)history.replaceState(null,'','#/home');render();tutorial();sw();window.addEventListener('error',e=>{console.error(e.error||e.message);toast('A feature hit an error. Saved progress is intact.')});window.addEventListener('unhandledrejection',e=>{console.error(e.reason);toast('A request failed. Try again.')})}
route('home',home);route('mission',mission);
window.BQ2={get state(){return state},defaults,replaceState,save,activity,awardBadges,toast,route,render,$,$$,esc,today,shuffled,clamp,pageHead,daily,missionState,missionPct,completeMission};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);
})();
