(() => {
  const cache=new Map();let manifest=null,current={code:'JHN',chapter:3,verse:16},bookRows=[],context=null;
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fetchJson=async path=>{if(cache.has(path))return cache.get(path);const r=await fetch(path);if(!r.ok)throw new Error(`${path} returned ${r.status}`);const d=await r.json();cache.set(path,d);return d};
  function layer(){let x=document.getElementById('bqContextLab');if(!x){x=document.createElement('div');x.id='bqContextLab';x.className='completion-layer hidden';document.body.appendChild(x)}return x}
  function show(html){const x=layer();x.innerHTML=`<main class="completion-shell context-shell">${html}</main>`;x.classList.remove('hidden');document.body.classList.add('completion-open');bind();x.scrollTop=0}
  function close(){layer().classList.add('hidden');document.body.classList.remove('completion-open')}
  function readerState(){try{return JSON.parse(localStorage.getItem('biblequest_reader_v1')||'{}')}catch{return {}}}
  async function loadBook(code){manifest=manifest||await fetchJson('data/packs/manifest.json');const meta=(manifest.bible_books||[]).find(x=>x.code===code);if(!meta)throw new Error('Bible book not found');bookRows=await fetchJson(meta.path);try{context=await fetchJson(`data/packs/context/${code}.json`)}catch{context=null}return meta}
  function chooseValid(){const chapters=[...new Set(bookRows.map(x=>Number(x.c)))].sort((a,b)=>a-b);if(!chapters.includes(Number(current.chapter)))current.chapter=chapters[0]||1;const verses=bookRows.filter(x=>Number(x.c)===Number(current.chapter)).map(x=>Number(x.v));if(!verses.includes(Number(current.verse)))current.verse=verses[0]||1;return {chapters,verses}}
  function languageLabel(entries){const langs=[...new Set(entries.map(x=>x.language))];return langs.join(' + ')||'Original language'}
  function lexemeCard(entry){const rtl=entry.language==='Hebrew'?' dir="rtl"':'';return `<article class="lexeme-card"><div class="lexeme-top"><div><small>${esc(entry.language)} · ${esc(entry.strong)}</small><strong${rtl}>${esc(entry.lemma||'—')}</strong><em>${esc(entry.transliteration||'')}</em></div><span>${entry.language==='Hebrew'?'א':'Ω'}</span></div><div class="lexeme-gloss"><b>Brief gloss</b><p>${esc(entry.gloss||'No brief gloss in this source.')}</p></div>${entry.morphology?`<div class="morph-chip">${esc(entry.morphology)}</div>`:''}</article>`}
  async function render(message=''){
    try{
      const meta=await loadBook(current.code),{chapters,verses}=chooseValid();const row=bookRows.find(x=>Number(x.c)===Number(current.chapter)&&Number(x.v)===Number(current.verse));const verseId=`${current.code}.${current.chapter}.${current.verse}`;const strongs=context?.verses?.[verseId]||[];const entries=strongs.map(s=>context?.lexicon?.[s]).filter(Boolean);
      show(`<header class="completion-top"><button data-context-close>← BibleQuest</button><b>Hebrew & Greek Context</b><span>אΩ</span></header>
      <section class="completion-hero context-hero"><small>ORIGINAL-LANGUAGE CONTEXT LAB</small><h1>Look closer without turning a dictionary into doctrine.</h1><p>BSB verse tags connect this passage to brief Hebrew/Greek lexical data from STEPBible.</p></section>
      ${message?`<div class="completion-message">${esc(message)}</div>`:''}
      <section class="context-picker"><select data-context-book>${(manifest.bible_books||[]).map(b=>`<option value="${b.code}" ${b.code===current.code?'selected':''}>${esc(b.name)}</option>`).join('')}</select><select data-context-chapter>${chapters.map(c=>`<option ${c===current.chapter?'selected':''}>${c}</option>`).join('')}</select><select data-context-verse>${verses.map(v=>`<option ${v===current.verse?'selected':''}>${v}</option>`).join('')}</select></section>
      <article class="context-scripture"><small>BSB · ${esc(meta.name)} ${current.chapter}:${current.verse}</small><p><sup>${current.verse}</sup> ${esc(row?.t||'Verse unavailable')}</p></article>
      <div class="context-caution"><b>How to use this</b><p>A lexicon shows a word’s possible range and grammatical category. The sentence, paragraph, genre, historical setting, and the rest of Scripture still determine meaning. These are <b>words tagged to the BSB verse</b>, not a reconstructed word-for-word interlinear.</p></div>
      ${context?entries.length?`<div class="completion-section"><h2>${esc(languageLabel(entries))} words in this verse</h2><small>${entries.length} lexical entries</small></div><section class="lexeme-grid">${entries.map(lexemeCard).join('')}</section>`:`<div class="completion-empty"><span>🔎</span><b>No lexical tags found for this verse.</b><p>Try another verse; some structural or name-heavy verses have limited tagging.</p></div>`:`<div class="completion-empty"><span>📦</span><b>Context pack is still being prepared.</b><p>The app is ready for this book, but its compact Hebrew/Greek pack has not reached this deployment yet.</p></div>`}
      <div class="context-source"><b>Sources</b><p>Verse: Berean Standard Bible. Strong’s identifiers: BSB data. Lemma, transliteration, morphology and brief gloss: STEPBible TBESH/TBESG · CC BY 4.0.</p><p>Detailed interpretation remains a study task—not something BibleQuest infers from one dictionary entry.</p></div>`)
    }catch(e){show(`<header class="completion-top"><button data-context-close>← BibleQuest</button><b>Hebrew & Greek Context</b><span>אΩ</span></header><div class="completion-empty"><span>📚</span><b>Could not load the context tools.</b><p>${esc(e.message)}</p></div>`)}
  }
  function bind(){const x=layer();x.querySelectorAll('[data-context-close]').forEach(b=>b.onclick=close);x.querySelector('[data-context-book]')?.addEventListener('change',e=>{current.code=e.target.value;current.chapter=1;current.verse=1;render()});x.querySelector('[data-context-chapter]')?.addEventListener('change',e=>{current.chapter=Number(e.target.value);current.verse=1;render()});x.querySelector('[data-context-verse]')?.addEventListener('change',e=>{current.verse=Number(e.target.value);render()})}
  function injectReaderButton(){const actions=document.querySelector('#bqReaderLayer:not(.hidden) .reader-study-actions');if(!actions||actions.querySelector('[data-reader-context]'))return;const b=document.createElement('button');b.className='reader-secondary';b.dataset.readerContext='1';b.textContent='אΩ Hebrew / Greek context';b.onclick=()=>{const s=readerState();open({code:s.code||'JHN',chapter:Number(s.chapter)||1,verse:1})};actions.appendChild(b)}
  const obs=new MutationObserver(injectReaderButton);obs.observe(document.documentElement,{subtree:true,childList:true});
  async function open(opts={}){const s=readerState();current={code:opts.code||s.code||'JHN',chapter:Number(opts.chapter||s.chapter)||3,verse:Number(opts.verse)||16};await render()}
  window.BQContextLab={open,close};injectReaderButton();
})();
