(() => {
  const cache=new Map(),usageCache=new Map();let manifest=null,contextManifest=null,current={code:'JHN',chapter:3,verse:16},bookRows=[],context=null,currentMeta=null;
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fetchJson=async path=>{if(cache.has(path))return cache.get(path);const r=await fetch(path);if(!r.ok)throw new Error(`${path} returned ${r.status}`);const d=await r.json();cache.set(path,d);return d};
  function layer(){let x=document.getElementById('bqContextLab');if(!x){x=document.createElement('div');x.id='bqContextLab';x.className='completion-layer hidden';document.body.appendChild(x)}return x}
  function show(html){const x=layer();x.innerHTML=`<main class="completion-shell context-shell">${html}</main>`;x.classList.remove('hidden');document.body.classList.add('completion-open');bind();x.scrollTop=0}
  function close(){layer().classList.add('hidden');document.body.classList.remove('completion-open')}
  function readerState(){try{return JSON.parse(localStorage.getItem('biblequest_reader_v1')||'{}')}catch{return {}}}
  async function loadBook(code){manifest=manifest||await fetchJson('data/packs/manifest.json');contextManifest=contextManifest||await fetchJson('data/packs/context/manifest.json').catch(()=>null);const meta=(manifest.bible_books||[]).find(x=>x.code===code);if(!meta)throw new Error('Bible book not found');bookRows=await fetchJson(meta.path);try{context=await fetchJson(`data/packs/context/${code}.json`)}catch{context=null}currentMeta=meta;return meta}
  function chooseValid(){const chapters=[...new Set(bookRows.map(x=>Number(x.c)))].sort((a,b)=>a-b);if(!chapters.includes(Number(current.chapter)))current.chapter=chapters[0]||1;const verses=bookRows.filter(x=>Number(x.c)===Number(current.chapter)).map(x=>Number(x.v));if(!verses.includes(Number(current.verse)))current.verse=verses[0]||1;return {chapters,verses}}
  function languageLabel(entries){const langs=[...new Set(entries.map(x=>x.language))];return langs.join(' + ')||'Original language'}
  function usageFor(strong){const key=`${current.code}:${strong}`;if(usageCache.has(key))return usageCache.get(key);const refs=[];for(const [id,strongs] of Object.entries(context?.verses||{})){if(Array.isArray(strongs)&&strongs.includes(strong))refs.push(id)}usageCache.set(key,refs);return refs}
  const humanRef=id=>{const bits=String(id).split('.');return bits.length>=3?`${currentMeta?.name||bits[0]} ${bits[1]}:${bits[2]}`:id};
  function lexemeCard(entry){const rtl=entry.language==='Hebrew'?' dir="rtl"':'',uses=usageFor(entry.strong);return `<article class="lexeme-card"><div class="lexeme-top"><div><small>${esc(entry.language)} · ${esc(entry.strong)}</small><strong${rtl}>${esc(entry.lemma||'—')}</strong><em>${esc(entry.transliteration||'')}</em></div><span>${entry.language==='Hebrew'?'א':'Ω'}</span></div><div class="lexeme-gloss"><b>Brief gloss</b><p>${esc(entry.gloss||'No brief gloss in this source.')}</p></div>${entry.morphology?`<div class="morph-chip">${esc(entry.morphology)}</div>`:''}<details class="lexeme-usage"><summary>Tagged in ${uses.length} verse${uses.length===1?'':'s'} in ${esc(currentMeta?.name||current.code)}</summary><div class="usage-ref-list">${uses.slice(0,8).map(id=>`<button data-context-ref="${esc(id)}">${esc(humanRef(id))}</button>`).join('')}${uses.length>8?`<small>+${uses.length-8} more uses in this book</small>`:''}</div><p>Same Strong’s tag does not guarantee the same nuance in every verse. Compare sentences and context.</p></details></article>`}
  function nearby(row){const chapterRows=bookRows.filter(x=>Number(x.c)===Number(current.chapter)).sort((a,b)=>Number(a.v)-Number(b.v)),i=chapterRows.findIndex(x=>Number(x.v)===Number(current.verse));return {prev:i>0?chapterRows[i-1]:null,current:row,next:i>=0&&i<chapterRows.length-1?chapterRows[i+1]:null}}
  function contextStrip(n){return `<section class="verse-context-strip">${n.prev?`<button data-context-jump="${Number(n.prev.v)}"><small>PREVIOUS</small><b>${current.chapter}:${n.prev.v}</b><span>${esc(n.prev.t)}</span></button>`:'<div></div>'}<article><small>CURRENT VERSE</small><b>${current.chapter}:${current.verse}</b><span>Read the surrounding sentence before focusing on a word.</span></article>${n.next?`<button data-context-jump="${Number(n.next.v)}"><small>NEXT</small><b>${current.chapter}:${n.next.v}</b><span>${esc(n.next.t)}</span></button>`:'<div></div>'}</section>`}
  async function render(message=''){
    try{
      const meta=await loadBook(current.code),{chapters,verses}=chooseValid(),row=bookRows.find(x=>Number(x.c)===Number(current.chapter)&&Number(x.v)===Number(current.verse)),verseId=`${current.code}.${current.chapter}.${current.verse}`,strongs=context?.verses?.[verseId]||[],entries=strongs.map(s=>context?.lexicon?.[s]).filter(Boolean),coverage=contextManifest?.books?.find(x=>x.code===current.code),near=nearby(row);
      show(`<header class="completion-top"><button data-context-close>← BibleQuest</button><b>Hebrew & Greek Context</b><span>אΩ</span></header>
      <section class="completion-hero context-hero"><small>ORIGINAL-LANGUAGE CONTEXT LAB</small><h1>Look closer without turning a dictionary into doctrine.</h1><p>BSB verse tags connect this passage to brief Hebrew/Greek lexical data from STEPBible.</p></section>
      ${message?`<div class="completion-message">${esc(message)}</div>`:''}
      <section class="context-picker"><select data-context-book>${(manifest.bible_books||[]).map(b=>`<option value="${b.code}" ${b.code===current.code?'selected':''}>${esc(b.name)}</option>`).join('')}</select><select data-context-chapter>${chapters.map(c=>`<option ${c===current.chapter?'selected':''}>${c}</option>`).join('')}</select><select data-context-verse>${verses.map(v=>`<option ${v===current.verse?'selected':''}>${v}</option>`).join('')}</select></section>
      <article class="context-scripture"><small>BSB · ${esc(meta.name)} ${current.chapter}:${current.verse}</small><p><sup>${current.verse}</sup> ${esc(row?.t||'Verse unavailable')}</p></article>
      ${contextStrip(near)}
      <div class="context-caution"><b>Three rules for a safer word study</b><ol><li>Read the sentence and paragraph before isolating a word.</li><li>A lexicon gives a range of possible meanings; grammar and context narrow that range.</li><li>Do not build doctrine from etymology or one Strong’s entry alone.</li></ol><p>These are <b>words tagged to the BSB verse</b>, not a reconstructed word-for-word interlinear.</p></div>
      ${context?entries.length?`<div class="completion-section"><h2>${esc(languageLabel(entries))} words in this verse</h2><small>${entries.length} lexical entries${coverage?` · ${coverage.tagged_verses} tagged verses in ${esc(meta.name)}`:''}</small></div><section class="lexeme-grid">${entries.map(lexemeCard).join('')}</section>`:`<div class="completion-empty"><span>🔎</span><b>No lexical tags found for this verse.</b><p>Try another verse; some structural or name-heavy verses have limited tagging.</p></div>`:`<div class="completion-empty"><span>📦</span><b>Context pack is still being prepared.</b><p>The app is ready for this book, but its compact Hebrew/Greek pack has not reached this deployment yet.</p></div>`}
      <div class="context-source"><b>Sources & limits</b><p>Verse: Berean Standard Bible. Strong’s identifiers: BSB data. Lemma, transliteration, morphology and brief gloss: STEPBible TBESH/TBESG · CC BY 4.0.</p><p>BibleQuest intentionally packages brief lexical fields only. Detailed interpretation remains a study task—not something the app infers from one dictionary entry.</p></div>`)
    }catch(e){show(`<header class="completion-top"><button data-context-close>← BibleQuest</button><b>Hebrew & Greek Context</b><span>אΩ</span></header><div class="completion-empty"><span>📚</span><b>Could not load the context tools.</b><p>${esc(e.message)}</p></div>`)}
  }
  function jumpFromId(id){const bits=String(id).split('.');if(bits.length<3)return;current.code=bits[0];current.chapter=Number(bits[1])||1;current.verse=Number(bits[2])||1;render()}
  function bind(){const x=layer();x.querySelectorAll('[data-context-close]').forEach(b=>b.onclick=close);x.querySelector('[data-context-book]')?.addEventListener('change',e=>{current.code=e.target.value;current.chapter=1;current.verse=1;render()});x.querySelector('[data-context-chapter]')?.addEventListener('change',e=>{current.chapter=Number(e.target.value);current.verse=1;render()});x.querySelector('[data-context-verse]')?.addEventListener('change',e=>{current.verse=Number(e.target.value);render()});x.querySelectorAll('[data-context-jump]').forEach(b=>b.onclick=()=>{current.verse=Number(b.dataset.contextJump);render()});x.querySelectorAll('[data-context-ref]').forEach(b=>b.onclick=()=>jumpFromId(b.dataset.contextRef))}
  function injectReaderButton(){const actions=document.querySelector('#bqReaderLayer:not(.hidden) .reader-study-actions');if(!actions||actions.querySelector('[data-reader-context]'))return;const b=document.createElement('button');b.className='reader-secondary';b.dataset.readerContext='1';b.textContent='אΩ Hebrew / Greek context';b.onclick=()=>{const s=readerState();open({code:s.code||'JHN',chapter:Number(s.chapter)||1,verse:1})};actions.appendChild(b)}
  const obs=new MutationObserver(mutations=>{if(mutations.some(m=>!m.target.closest?.('[data-reader-context]')))injectReaderButton()});obs.observe(document.documentElement,{subtree:true,childList:true});
  async function open(opts={}){const s=readerState();current={code:opts.code||s.code||'JHN',chapter:Number(opts.chapter||s.chapter)||3,verse:Number(opts.verse)||16};await render()}
  window.BQContextLab={open,close};injectReaderButton();
})();
