(() => {
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const journey=[
    {icon:'🙏',title:'Pray Honestly',q:'Ano ang gusto mong ipag-pray ng partner mo para sa’yo ngayon—at anong support ang helpful?',ref:'Philippians 1:9–11'},
    {icon:'👂',title:'Listen First',q:'Share one concern for two minutes. Ang listener ay magpa-paraphrase muna bago magbigay ng advice.',ref:'James 1:19'},
    {icon:'💛',title:'Notice the Good',q:'Name one specific thing your partner did recently that made life lighter or better.',ref:'1 Thessalonians 5:11'},
    {icon:'🕊️',title:'Repair Gently',q:'Name one small recurring tension. Own one part without adding “pero ikaw…”.',ref:'Matthew 7:3–5'},
    {icon:'🏠',title:'Build the Home',q:'Anong atmosphere ang gusto ninyong maramdaman sa bahay? What one habit can support it?',ref:'Colossians 3:12–15'},
    {icon:'🤝',title:'Serve Together',q:'What realistic need can you serve together without overcommitting?',ref:'Galatians 5:13'},
    {icon:'✝️',title:'Us & God',q:'What is one way your relationship can help each of you follow Christ more faithfully this month?',ref:'Hebrews 10:24–25'}
  ];
  let pair=null,invite='',message='';
  const account=()=>window.BQAccount,client=()=>account()?.client?.(),session=()=>account()?.session?.();
  function layer(){let x=document.getElementById('bqCoupleCloudLayer');if(!x){x=document.createElement('div');x.id='bqCoupleCloudLayer';x.className='innovation-layer hidden';document.body.appendChild(x)}return x}
  function show(html){const x=layer();x.innerHTML=`<main class="innovation-app couple-cloud-app">${html}</main>`;x.classList.remove('hidden');document.body.classList.add('innovation-open');bind();x.scrollTop=0}
  function close(){layer().classList.add('hidden');document.body.classList.remove('innovation-open')}
  async function invoke(body){const r=await client().functions.invoke('bq-couple',{body});if(r.error)throw r.error;if(r.data?.error)throw new Error(r.data.error);return r.data}
  async function open(){if(!session()||!client())return show(`<header class="innovation-top"><button data-couple-cloud-close>← BibleQuest</button><b>Couple Journey</b><span>💞</span></header><section class="innovation-hero"><h1>Link two BibleQuest accounts.</h1><p>Each partner keeps a separate account. Only intentionally shared couple commitments, completed journey items, and pair-linked couples challenges belong to the pair.</p><button data-couple-account>Open account</button></section>`);try{const s=await invoke({action:'status'});pair=s.pair||null;await render()}catch(e){show(`<header class="innovation-top"><button data-couple-cloud-close>← BibleQuest</button><b>Couple Journey</b><span>💞</span></header><div class="innovation-message error">${esc(e.message||String(e))}</div>`)} }
  async function render(){if(!pair||pair.status==='ended')return unpaired();if(pair.status==='pending')return pending();return active()}
  function unpaired(){show(`<header class="innovation-top"><button data-couple-cloud-close>← BibleQuest</button><b>Couple Journey</b><span>💞</span></header><section class="innovation-hero"><small>TWO ACCOUNTS · ONE SHARED JOURNEY</small><h1>Grow together without sharing a password.</h1><p>Create a private pair code and let your spouse join from their own BibleQuest account.</p></section>${message?`<div class="innovation-message">${esc(message)}</div>`:''}<div class="couple-pair-grid"><button data-couple-create><span>🔗</span><b>Create pair code</b><small>Share an 8-character code with your spouse.</small></button><form data-couple-join><b>I have a pair code</b><input name="code" maxlength="8" placeholder="ABC234XY" required><button>Link our accounts</button></form></div><div class="innovation-note"><b>Privacy rule</b><p>Your private Bible notes, Transformation results, passwords, and personal account data are never shared with your partner by pairing.</p></div>`)}
  function pending(){show(`<header class="innovation-top"><button data-couple-cloud-close>← BibleQuest</button><b>Couple Journey</b><span>⏳</span></header><section class="innovation-hero"><small>WAITING FOR YOUR PARTNER</small><h1>Pair request created.</h1><p>${invite?`Share this code: <strong class="pair-code">${esc(invite)}</strong>`:'Generate a fresh code and share it with your spouse.'}</p><div class="study-actions"><button data-couple-create>${invite?'Generate new code':'Get pair code'}</button><button class="secondary" data-couple-refresh>Check if partner joined</button></div></section>`)}
  function challengeHtml(rows){if(!rows.length)return '';return `<h3 class="innovation-section-title">Shared challenge progress</h3><div class="couple-shared-list">${rows.slice(0,12).map(x=>{const [key,title='Couples Challenge']=String(x.body||'').split('|'),day=key.split(':').pop()||'?';return `<article><p>🏁 ${esc(title)} · Day ${esc(day)}</p><small>Pair-linked completion · ${new Date(x.created_at).toLocaleDateString()}</small></article>`}).join('')}</div><div class="innovation-note"><b>How this works</b><p>For a congregation challenge marked as Couples, the first linked partner who marks a day complete records that day once in your shared Couple Journey. Individual challenge points remain personal.</p></div>`}
  async function active(){const shared=await client().from('bible_couple_shared').select('*').eq('pair_id',pair.id).order('created_at',{ascending:false}).limit(60);const rows=shared.data||[],done=new Set(rows.filter(x=>x.item_type==='journey').map(x=>x.body.split('|')[0])),challengeRows=rows.filter(x=>x.item_type==='challenge');show(`<header class="innovation-top"><button data-couple-cloud-close>← BibleQuest</button><b>Couple Journey</b><span>${done.size}/7</span></header><section class="innovation-hero"><small>LINKED COUPLE ACCOUNTS</small><h1>One conversation at a time.</h1><p>No marriage score. The goal is honest conversation, better listening, concrete repair, and shared growth with Christ.</p></section>${message?`<div class="innovation-message">${esc(message)}</div>`:''}<div class="couple-journey-list">${journey.map((j,i)=>`<button class="${done.has(String(i+1))?'done':''}" data-couple-step="${i}"><span>${done.has(String(i+1))?'✓':j.icon}</span><div><b>${i+1}. ${esc(j.title)}</b><small>${esc(j.ref)}</small></div></button>`).join('')}</div>${challengeHtml(challengeRows)}<h3 class="innovation-section-title">Shared commitments</h3><div class="couple-shared-list">${rows.filter(x=>x.item_type==='commitment').map(x=>`<article><p>${esc(x.body)}</p><small>${new Date(x.created_at).toLocaleDateString()}</small></article>`).join('')||'<div class="innovation-note">No shared commitments yet.</div>'}</div><button class="secondary danger" data-couple-leave>Unlink couple accounts</button>`)}
  function step(i){const j=journey[i];show(`<header class="innovation-top"><button data-couple-refresh>← Journey</button><b>${esc(j.title)}</b><span>${j.icon}</span></header><section class="couple-step"><small>STEP ${i+1} · ${esc(j.ref)}</small><h1>${esc(j.q)}</h1><div class="conversation-rules"><b>Conversation rule</b><p>Ask before assuming. Paraphrase before disagreeing. Scripture is not a weapon to win against your spouse.</p></div><form data-couple-complete data-step="${i}"><label>One shared commitment (optional)<textarea name="commitment" maxlength="800" placeholder="This week we will…"></textarea></label><button>Complete this conversation</button></form></section>`)}
  async function create(){const d=await invoke({action:'create'});pair=d.pair;invite=d.inviteCode||'';message='Pair code ready.';render()}
  async function join(form){const code=String(new FormData(form).get('code')||'').trim();const d=await invoke({action:'join',code});pair=d.pair;message='Accounts linked.';render()}
  async function complete(form){const i=Number(form.dataset.step),commit=String(new FormData(form).get('commitment')||'').trim(),rows=[{pair_id:pair.id,author_id:session().user.id,item_type:'journey',body:`${i+1}|${journey[i].title}`}];if(commit)rows.push({pair_id:pair.id,author_id:session().user.id,item_type:'commitment',body:commit});const r=await client().from('bible_couple_shared').insert(rows);if(r.error)throw r.error;window.BQCommunity?.awardPoints?.(window.BQCommunity?.read?.().activeName||'You',4,'couples','Couples Conversation',{completed:1,pair_cloud:true});await account()?.track?.('couple_journey','completed',{step:i+1});message='Conversation saved to your shared couple journey.';active()}
  async function leave(){if(!confirm('Unlink the couple accounts? Shared items stay in history but the pair becomes inactive.'))return;await invoke({action:'leave',pairId:pair.id});pair=null;invite='';message='Couple accounts unlinked.';unpaired()}
  function bind(){const x=layer();x.querySelectorAll('[data-couple-cloud-close]').forEach(b=>b.onclick=close);x.querySelector('[data-couple-account]')?.addEventListener('click',()=>account()?.open?.());x.querySelectorAll('[data-couple-create]').forEach(b=>b.onclick=()=>create().catch(e=>{message=e.message;unpaired()}));x.querySelector('[data-couple-join]')?.addEventListener('submit',e=>{e.preventDefault();join(e.currentTarget).catch(err=>{message=err.message;unpaired()})});x.querySelectorAll('[data-couple-refresh]').forEach(b=>b.onclick=open);x.querySelectorAll('[data-couple-step]').forEach(b=>b.onclick=()=>step(+b.dataset.coupleStep));x.querySelector('[data-couple-complete]')?.addEventListener('submit',e=>{e.preventDefault();complete(e.currentTarget).catch(err=>alert(err.message))});x.querySelector('[data-couple-leave]')?.addEventListener('click',()=>leave().catch(e=>alert(e.message)))}
  window.BQCoupleCloud={open};
})();
