(() => {
  'use strict';
  const KEY='biblequest_first_five_v1';let queued=false;
  const account=()=>window.BQAccount,session=()=>account()?.session?.(),cloud=()=>window.BQCloud?.status?.()||{};
  function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
  function app(){try{return JSON.parse(localStorage.getItem('biblequest_state_v4')||'{}')}catch{return {}}}
  function journey(){try{return window.BQJourneyLoop?.read?.()||{}}catch{return {}}}
  function dismissed(){return state().dismissed===true}
  function checks(){const a=app(),j=journey(),g=cloud(),earned=Number(a.answered||0)>0||Number(a.xp||0)>0;return [{key:'account',label:'Account ready',done:Boolean(session()?.user),action:null},{key:'journey',label:'Complete your first Daily Journey step',done:Boolean(j.completedSteps>0||j.done?.recall||a.dailyDone),action:'journey'},{key:'unlock',label:'Earn your first progress unlock',done:earned,action:'journey'},{key:'badge',label:'Reach your first badge milestone',done:(a.achievements||[]).length>0,action:'journey'},{key:'church',label:'Connect with your congregation',done:Boolean(g.activeCongregation?.id),action:'ministry'}]}
  function render(){queued=false;if(!session()?.user||dismissed())return;const home=document.querySelector('.modern-home');if(!home)return;let card=home.querySelector('[data-first-five]'),rows=checks(),done=rows.filter(x=>x.done).length;if(done===rows.length){const s=state();if(!s.completedAt){s.completedAt=new Date().toISOString();save(s)}card?.remove();return}if(!card){card=document.createElement('section');card.dataset.firstFive='1';card.className='first-five-card';const daily=home.querySelector('.today-journey-card');daily?.after(card)}card.innerHTML=`<header><div><small>YOUR FIRST 5 MINUTES</small><b>${done}/5 foundations ready</b></div><button type="button" data-first-five-dismiss aria-label="Dismiss first steps">×</button></header><p>Start with the journey. BibleQuest will reveal the larger app as your account begins to have meaningful progress.</p><div class="first-five-list">${rows.map(r=>`<button type="button" class="${r.done?'done':''}" ${r.action?`data-first-five-action="${r.action}"`:''} ${r.done||!r.action?'disabled':''}><span>${r.done?'✓':'○'}</span><b>${r.label}</b></button>`).join('')}</div>`;card.querySelector('[data-first-five-dismiss]').onclick=()=>{const s=state();s.dismissed=true;save(s);card.remove()};card.querySelectorAll('[data-first-five-action]').forEach(b=>b.onclick=()=>{if(b.dataset.firstFiveAction==='journey')window.BQJourneyLoop?.open?.();else window.BQMinistry?.open?.()})}
  function schedule(){if(queued)return;queued=true;queueMicrotask(render)}new MutationObserver(schedule).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});window.addEventListener('bq-journey-change',schedule);window.addEventListener('bq-cloud-board-change',schedule);window.addEventListener('bq-account-created',schedule);setTimeout(render,1300);window.BQFirstFive={refresh:render,state};
})();