(() => {
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const parse=(k,f={})=>{try{return {...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return {...f}}};
  const APP='biblequest_state_v4';
  const tracks=[
    {code:'GEN',book:'Genesis',chapter:12,title:'Called to Go',theme:'Calling, trust, and blessing',observe:'Ano ang mismong ipinagawa kay Abram? Ano ang ipinangako?',understand:'Which promises concern Abram, and which concern other people through him?',discuss:'Paano magkaiba ang faith at impulsiveness kapag may major decision?',apply:'Name one decision where faith should include both obedience and wise preparation.',pray:'Pray for courage to obey clearly and humility to plan wisely.'},
    {code:'PSA',book:'Psalms',chapter:23,title:'The Shepherd Psalm',theme:'Trust, provision, presence',observe:'List the images used for God’s care in this psalm.',understand:'Which lines describe comfort, and which describe danger that still exists?',discuss:'How is biblical trust different from pretending nothing is difficult?',apply:'Identify one fear where you need faithful action plus trust.',pray:'Pray honestly about the valley, not only the desired outcome.'},
    {code:'MAT',book:'Matthew',chapter:5,title:'Kingdom Character',theme:'Jesus’ teaching and lived discipleship',observe:'Which qualities and actions does Jesus call blessed or important?',understand:'What parts address inner character, not only visible behavior?',discuss:'Which teaching is easiest to admire but hardest to practice?',apply:'Choose one concrete action for the next 48 hours.',pray:'Ask for character change, not only better circumstances.'},
    {code:'JHN',book:'John',chapter:3,title:'Jesus and Nicodemus',theme:'New birth, belief, light',observe:'What questions does Nicodemus ask, and how does Jesus answer them?',understand:'Notice the movement from new birth to belief, judgment, and light.',discuss:'Why can sincere religious knowledge still leave someone confused?',apply:'Write one question about faith you want to examine honestly.',pray:'Ask for openness to truth even when it challenges assumptions.'},
    {code:'ACT',book:'Acts',chapter:2,title:'A Church Is Born',theme:'Spirit, witness, community',observe:'What happens publicly, and how do people respond?',understand:'What practices describe the early community after the sermon?',discuss:'Which of those practices can a modern congregation imitate without pretending the cultural setting is identical?',apply:'Choose one community practice to strengthen this week.',pray:'Pray for courage, generosity, learning, and genuine fellowship.'},
    {code:'ROM',book:'Romans',chapter:12,title:'A Changed Life',theme:'Renewal, service, relationships',observe:'List the commands and relational behaviors in the chapter.',understand:'How does renewed thinking connect to practical relationships?',discuss:'Which instruction is hardest when conflict becomes personal?',apply:'Pick one relationship and one Romans 12 action.',pray:'Pray for transformed thinking that becomes visible behavior.'}
  ];
  const eras=[
    ['🌍','Creation & Beginnings',['GEN'],'Genesis'],['🏕️','Patriarchs',['GEN'],'Genesis'],['🌊','Exodus & Law',['EXO','LEV','NUM','DEU'],'Exodus'],['🏰','Land & Kingdom',['JOS','JDG','RUT','1SA','2SA','1KI','2KI'],'History'],['🎵','Wisdom & Worship',['JOB','PSA','PRO','ECC','SNG'],'Wisdom'],['📜','Prophets',['ISA','JER','LAM','EZK','DAN','HOS','JOL','AMO','OBA','JON','MIC','NAM','HAB','ZEP','HAG','ZEC','MAL'],'Prophets'],['✝️','Jesus & Gospels',['MAT','MRK','LUK','JHN'],'Gospels'],['🔥','Acts & Early Church',['ACT'],'Acts'],['✉️','Letters & Revelation',['ROM','1CO','2CO','GAL','EPH','PHP','COL','1TH','2TH','1TI','2TI','TIT','PHM','HEB','JAS','1PE','2PE','1JN','2JN','3JN','JUD','REV'],'Letters']
  ];
  const people=[
    {kind:'person',name:'Abraham',clues:['Left his homeland after God’s call','Father of Isaac','Connected to a covenant promise'],refs:'Genesis 12; 15; 22',place:'Canaan'},
    {kind:'person',name:'Joseph',clues:['Received dreams when young','Was sold by his brothers','Rose to authority in Egypt'],refs:'Genesis 37–50',place:'Egypt'},
    {kind:'person',name:'Moses',clues:['Raised near Pharaoh’s household','Encountered God at a burning bush','Led Israel out of Egypt'],refs:'Exodus 2–20',place:'Egypt / Sinai'},
    {kind:'person',name:'Ruth',clues:['A Moabite widow','Stayed with Naomi','Became part of David’s family line'],refs:'Ruth 1–4',place:'Moab / Bethlehem'},
    {kind:'person',name:'David',clues:['Shepherd and musician','Defeated Goliath','Became king of Israel'],refs:'1 Samuel 16–17; 2 Samuel',place:'Bethlehem / Jerusalem'},
    {kind:'person',name:'Elijah',clues:['Prophet during Ahab’s reign','Confronted prophets of Baal','Associated with Mount Carmel'],refs:'1 Kings 17–19',place:'Israel / Carmel'},
    {kind:'person',name:'Esther',clues:['A Jewish woman who became queen','Mordecai was her relative and adviser','Risked approaching the king'],refs:'Esther 2–8',place:'Susa'},
    {kind:'person',name:'Peter',clues:['A fisherman','One of Jesus’ twelve disciples','Preached publicly in Acts 2'],refs:'Gospels; Acts 1–12',place:'Galilee / Jerusalem'},
    {kind:'person',name:'Paul',clues:['Previously persecuted believers','Encountered Jesus on the road to Damascus','Carried the gospel across many cities'],refs:'Acts 9–28',place:'Damascus / Mediterranean'},
    {kind:'person',name:'Priscilla',clues:['Worked alongside Aquila','Met Paul in Corinth','Helped explain the way of God to Apollos'],refs:'Acts 18',place:'Corinth / Ephesus'},
    {kind:'place',name:'Bethlehem',clues:['Connected with Ruth and David','A town in Judah','Jesus was born here'],refs:'Ruth 1; 1 Samuel 16; Matthew 2',place:'Judah'},
    {kind:'place',name:'Jerusalem',clues:['David made it his royal city','The temple stood here','Central to Jesus’ final week and Acts 2'],refs:'2 Samuel 5; Gospels; Acts 2',place:'Judah'},
    {kind:'place',name:'Damascus',clues:['Ancient Syrian city','Saul traveled toward it to arrest believers','His encounter with Jesus changed his mission'],refs:'Acts 9',place:'Syria'},
    {kind:'place',name:'Corinth',clues:['Paul stayed and worked here','Priscilla and Aquila lived here','Two New Testament letters bear its church’s name'],refs:'Acts 18; 1–2 Corinthians',place:'Achaia'},
    {kind:'place',name:'Ephesus',clues:['Paul spent extended ministry time here','Connected with a major public disturbance in Acts','One New Testament letter addresses believers here'],refs:'Acts 19; Ephesians',place:'Asia Minor'}
  ];
  const challengeTemplates=[
    {key:'gospel7',title:'7-Day Gospel Challenge',type:'reading',days:7,desc:'One Gospel-focused reading and reflection each day.',steps:['Mark 1','Mark 2','Mark 4','Mark 5','Mark 8','Mark 10','Mark 15–16']},
    {key:'proverbs30',title:'30-Day Proverbs Challenge',type:'wisdom',days:30,desc:'A chapter of Proverbs most days, with one practical wisdom takeaway.',steps:Array.from({length:30},(_,i)=>`Proverbs ${i+1}`)},
    {key:'acts28',title:'Acts Month',type:'reading',days:28,desc:'Walk through the growth, conflicts, mission, and expansion of the early church.',steps:Array.from({length:28},(_,i)=>`Acts ${i+1}`)},
    {key:'couples7',title:'Couples Week',type:'couples',days:7,desc:'Seven short Christ-centered conversations and listening practices.',steps:['Gratitude','Listen First','Prayer','Repair','Dreams','Service','Us & God']},
    {key:'family7',title:'Family Bible Night Week',type:'group',days:7,desc:'Seven simple family prompts mixing reading, discussion, and prayer.',steps:['Creation','Courage','Wisdom','Kindness','Forgiveness','Service','Hope']}
  ];
  function layer(id){let x=document.getElementById(id);if(!x){x=document.createElement('div');x.id=id;x.className='innovation-layer hidden';document.body.appendChild(x)}return x}
  function show(id,html,bind){const x=layer(id);x.innerHTML=`<main class="innovation-app">${html}</main>`;x.classList.remove('hidden');document.body.classList.add('innovation-open');bind?.(x);x.scrollTop=0}
  function close(id){layer(id).classList.add('hidden');if(!document.querySelector('.innovation-layer:not(.hidden)'))document.body.classList.remove('innovation-open')}
  async function loadPack(code){const m=await fetch('data/packs/manifest.json').then(r=>r.json()),meta=(m.bible_books||[]).find(x=>x.code===code);if(!meta)throw new Error('Bible pack unavailable');return fetch(meta.path).then(r=>r.json())}
  function activeName(){const s=window.BQCommunity?.read?.();return s?.activeName||parse(APP).profile?.name||'You'}
  function award(points,category,source,meta={}){window.BQCommunity?.awardPoints?.(activeName(),points,category,source,meta);window.BQAccount?.track?.(source.toLowerCase().replace(/\s+/g,'_'),'completed',meta).catch?.(()=>{})}

  // Guided Study
  let studyTrack=null,studyStep=0,studyRows=[];
  const steps=['Read','Observe','Understand','Discuss','Apply','Pray'];
  async function openStudy(track=null){if(!track){show('bqStudyLayer',`<header class="innovation-top"><button data-study-close>← BibleQuest</button><b>Guided Study</b><span>📘</span></header><section class="innovation-hero"><small>READ → OBSERVE → UNDERSTAND → DISCUSS → APPLY → PRAY</small><h1>A study guide, not a replacement pastor.</h1><p>Choose a passage. BibleQuest keeps the Scripture text separate from observation and discussion prompts.</p></section><div class="innovation-card-grid">${tracks.map((t,i)=>`<button data-study-track="${i}"><span>📖</span><b>${esc(t.title)}</b><small>${esc(t.book)} ${t.chapter} · ${esc(t.theme)}</small></button>`).join('')}</div>`,x=>{x.querySelector('[data-study-close]').onclick=()=>close('bqStudyLayer');x.querySelectorAll('[data-study-track]').forEach(b=>b.onclick=()=>openStudy(tracks[+b.dataset.studyTrack]))});return}studyTrack=track;studyStep=0;try{studyRows=(await loadPack(track.code)).filter(v=>Number(v.c)===track.chapter)}catch{studyRows=[]}renderStudy()}
  function renderStudy(){const t=studyTrack,i=studyStep,label=steps[i],content=i===0?`<article class="study-scripture" data-bq-scripture="BSB">${studyRows.map(v=>`<p><sup>${v.v}</sup>${esc(v.t)}</p>`).join('')}</article>`:i===1?`<h1>${esc(t.observe)}</h1><p>Stay close to what the passage actually says before jumping to application.</p>`:i===2?`<h1>${esc(t.understand)}</h1><p>Use context and the surrounding chapter. A prompt is not a new doctrine.</p>`:i===3?`<h1>${esc(t.discuss)}</h1><p>Listen first. Different applications can be discussed without pretending every interpretation is equally supported.</p>`:i===4?`<h1>${esc(t.apply)}</h1><textarea data-study-note placeholder="Write one concrete next step…"></textarea>`:`<h1>${esc(t.pray)}</h1><textarea data-study-note placeholder="Write a prayer or something you want to remember…"></textarea>`;show('bqStudyLayer',`<header class="innovation-top"><button data-study-list>← Studies</button><b>${esc(t.title)}</b><span>${i+1}/6</span></header><div class="study-steps">${steps.map((s,n)=>`<span class="${n===i?'active':n<i?'done':''}">${n+1}<small>${s}</small></span>`).join('')}</div><section class="study-card"><small>${label.toUpperCase()} · ${esc(t.book)} ${t.chapter} · BSB</small>${content}<div class="study-actions">${i?'<button class="secondary" data-study-prev>← Back</button>':''}<button data-study-next>${i===5?'Finish study':'Next →'}</button></div></section>`,x=>{x.querySelector('[data-study-list]').onclick=()=>openStudy();x.querySelector('[data-study-prev]')?.addEventListener('click',()=>{studyStep--;renderStudy()});x.querySelector('[data-study-next]').onclick=async()=>{const note=x.querySelector('[data-study-note]')?.value?.trim();if(note&&window.BQNotes?.open){window.BQAccount?.track?.('guided_study','reflection_saved',{book:t.code,chapter:t.chapter,step:label}).catch?.(()=>{});localStorage.setItem('biblequest_study_draft_v1',JSON.stringify({bookCode:t.code,bookName:t.book,chapter:t.chapter,title:`${t.title} · ${label}`,body:note}))}if(studyStep<5){studyStep++;renderStudy()}else{award(5,'reading','Guided Study',{completed:1,book:t.code,chapter:t.chapter});show('bqStudyLayer',`<header class="innovation-top"><button data-study-close>← BibleQuest</button><b>Study complete</b><span>✓</span></header><section class="innovation-hero"><small>ONE PASSAGE · SIX MOVEMENTS</small><h1>${esc(t.title)} complete.</h1><p>You read, observed, understood, discussed, applied, and prayed. Revisit the passage later rather than treating one session as mastery.</p><div class="study-actions"><button data-study-again>Choose another study</button><button class="secondary" data-study-notes>Open Bible Notes</button></div></section>`,y=>{y.querySelector('[data-study-close]').onclick=()=>close('bqStudyLayer');y.querySelector('[data-study-again]').onclick=()=>openStudy();y.querySelector('[data-study-notes]').onclick=()=>window.BQNotes?.open?.({bookCode:t.code,bookName:t.book,chapter:t.chapter})})}}})}

  // Personal Mission
  function mission(){const s=parse(APP),m=s.mastery||{},areas=['Genesis','Exodus','History','Wisdom','Prophets','Gospels','Acts','Letters'],weak=areas.sort((a,b)=>(m[a]||0)-(m[b]||0))[0]||'Gospels',due=window.BQOpenReview?.countDue?.()||0;const rec=due?{icon:'🧠',title:`${due} reviews are due`,text:'Start with retrieval practice before adding more new material.',action:'review'}:(weak==='Gospels'?{icon:'✝️',title:'Strengthen the Gospels',text:'Read a Gospel passage, then retrieve what you remember.',action:'study'}:weak==='Wisdom'?{icon:'🧭',title:'Practice biblical wisdom',text:'Use a real-life situation, then connect it back to Scripture.',action:'wisdom'}:{icon:'🗺️',title:`Explore ${weak}`,text:'Your Journey evidence is lighter here. Do one focused activity.',action:'world'});show('bqMissionLayer',`<header class="innovation-top"><button data-mission-close>← BibleQuest</button><b>My Mission</b><span>🎯</span></header><section class="mission-card"><small>PERSONAL · ABOUT 6 MINUTES</small><div class="mission-icon">${rec.icon}</div><h1>${esc(rec.title)}</h1><p>${esc(rec.text)}</p><div class="mission-plan"><div><span>1</span><b>Retrieve</b><small>Answer before revealing.</small></div><div><span>2</span><b>Read</b><small>Check the actual passage.</small></div><div><span>3</span><b>Connect</b><small>Make one practical connection.</small></div></div><button data-mission-start="${rec.action}">Start this mission</button></section>`,x=>{x.querySelector('[data-mission-close]').onclick=()=>close('bqMissionLayer');x.querySelector('[data-mission-start]').onclick=e=>{close('bqMissionLayer');const a=e.currentTarget.dataset.missionStart;if(a==='review')document.querySelector('[data-open-review]')?.click();else if(a==='study')openStudy(tracks.find(t=>t.code==='JHN'));else if(a==='wisdom')document.querySelector('[data-action="situation"]')?.click();else world()}})}

  // Bible World
  function world(){const s=parse(APP),m=s.mastery||{},avatar=window.BQAvatar?.render?.(window.BQAccount?.avatar?.())||'🙂';show('bqWorldLayer',`<header class="innovation-top"><button data-world-close>← BibleQuest</button><b>Bible World</b><span>🗺️</span></header><section class="innovation-hero world-hero"><div class="world-avatar">${avatar}</div><div><small>YOUR BIBLE JOURNEY</small><h1>Travel through the biblical story.</h1><p>Regions show exploration evidence—not a judgment of spiritual maturity. Nothing is permanently locked.</p></div></section><div class="world-map">${eras.map((e,i)=>{const pct=Math.max(0,Math.min(100,Number(m[e[3]]||0)));return `<button data-world-era="${i}"><span class="world-node">${e[0]}</span><div><b>${esc(e[1])}</b><small>${e[2].length} book${e[2].length>1?'s':''} · ${pct}% explored</small><i><em style="width:${pct}%"></em></i></div></button>`}).join('')}</div>`,x=>{x.querySelector('[data-world-close]').onclick=()=>close('bqWorldLayer');x.querySelectorAll('[data-world-era]').forEach(b=>b.onclick=()=>eraDetail(+b.dataset.worldEra))})}
  function eraDetail(i){const e=eras[i];show('bqWorldLayer',`<header class="innovation-top"><button data-world-back>← World</button><b>${esc(e[1])}</b><span>${e[0]}</span></header><section class="innovation-hero"><small>EXPLORE THE REGION</small><h1>${esc(e[1])}</h1><p>Books: ${e[2].join(' · ')}</p></section><div class="innovation-card-grid"><button data-era-read><span>📖</span><b>Read</b><small>Open the Bible shelf and choose a book from this era.</small></button><button data-era-review><span>🧠</span><b>Review</b><small>Use adaptive recall to strengthen memory.</small></button><button data-era-explore><span>🧑‍🤝‍🧑</span><b>Characters & Places</b><small>Meet people and locations connected to Scripture.</small></button></div>`,x=>{x.querySelector('[data-world-back]').onclick=world;x.querySelector('[data-era-read]').onclick=()=>{close('bqWorldLayer');window.BQReader?.openLibrary?.()||document.querySelector('[data-reader-open]')?.click()};x.querySelector('[data-era-review]').onclick=()=>{close('bqWorldLayer');document.querySelector('[data-open-review]')?.click()};x.querySelector('[data-era-explore]').onclick=()=>explorer()})}

  // Characters & Places
  let explorerItem=null,clue=0;
  function explorer(){show('bqExplorerLayer',`<header class="innovation-top"><button data-explorer-close>← BibleQuest</button><b>Characters & Places</b><span>🧭</span></header><section class="innovation-hero"><small>SCRIPTURE-GROUNDED EXPLORATION</small><h1>People, places, relationships.</h1><p>Curated from Scripture with STEPBible/OpenBible resources used as reference data. The game avoids inventing hidden facts.</p></section><div class="innovation-card-grid"><button data-explorer-mode="person"><span>🕵️</span><b>Who Am I?</b><small>Reveal clues about a Bible person.</small></button><button data-explorer-mode="place"><span>📍</span><b>Where Is It?</b><small>Identify a biblical place from clues.</small></button><button data-explorer-mode="connections"><span>🔗</span><b>Connections</b><small>See people, places, and Scripture references together.</small></button></div>`,x=>{x.querySelector('[data-explorer-close]').onclick=()=>close('bqExplorerLayer');x.querySelectorAll('[data-explorer-mode]').forEach(b=>b.onclick=()=>explorerMode(b.dataset.explorerMode))})}
  function explorerMode(kind){if(kind==='connections'){show('bqExplorerLayer',`<header class="innovation-top"><button data-explorer-back>← Explorer</button><b>Connections</b><span>🔗</span></header><div class="connection-list">${people.map(p=>`<article><span>${p.kind==='person'?'👤':'📍'}</span><div><b>${esc(p.name)}</b><small>${esc(p.place)} · ${esc(p.refs)}</small><p>${esc(p.clues[1])}</p></div></article>`).join('')}</div>`,x=>x.querySelector('[data-explorer-back]').onclick=explorer);return}const pool=people.filter(p=>p.kind===kind);explorerItem=pool[Math.floor(Math.random()*pool.length)];clue=0;renderExplorerQuiz()}
  function renderExplorerQuiz(){const p=explorerItem;show('bqExplorerLayer',`<header class="innovation-top"><button data-explorer-back>← Explorer</button><b>${p.kind==='person'?'Who Am I?':'Where Is It?'}</b><span>${p.kind==='person'?'🕵️':'📍'}</span></header><section class="explorer-quiz"><small>CLUE ${clue+1} OF ${p.clues.length}</small><h1>${esc(p.clues[clue])}</h1>${clue<p.clues.length-1?'<button data-explorer-clue>Another clue</button>':''}<button class="secondary" data-explorer-answer>Reveal answer</button></section>`,x=>{x.querySelector('[data-explorer-back]').onclick=explorer;x.querySelector('[data-explorer-clue]')?.addEventListener('click',()=>{clue++;renderExplorerQuiz()});x.querySelector('[data-explorer-answer]').onclick=()=>show('bqExplorerLayer',`<header class="innovation-top"><button data-explorer-back>← Explorer</button><b>Answer</b><span>✓</span></header><section class="explorer-answer"><small>${p.kind.toUpperCase()}</small><h1>${esc(p.name)}</h1><p>${esc(p.clues.join(' · '))}</p><div><b>Scripture</b><span>${esc(p.refs)}</span></div><div><b>Place</b><span>${esc(p.place)}</span></div><button data-explorer-next>Next one</button></section>`,y=>{award(2,'knowledge','Bible Explorer',{completed:1});y.querySelector('[data-explorer-back]').onclick=explorer;y.querySelector('[data-explorer-next]').onclick=()=>explorerMode(p.kind)})})}

  // Congregation challenges
  async function challenges(){const c=window.BQAccount?.client?.(),s=window.BQAccount?.session?.(),cid=(()=>{try{return JSON.parse(localStorage.getItem('biblequest_cloud_v1')||'{}').activeCongregationId||''}catch{return ''}})();let active=[];if(c&&s&&cid){const r=await c.from('bible_challenges').select('*').eq('congregation_id',cid).eq('active',true).order('starts_on',{ascending:false}).limit(20);active=r.data||[]}show('bqChallengeLayer',`<header class="innovation-top"><button data-challenge-close>← BibleQuest</button><b>Church Challenges</b><span>🏁</span></header><section class="innovation-hero"><small>SEASONS · HABITS · SHARED MOMENTUM</small><h1>Grow together without turning faith into a score.</h1><p>Leaders can launch a challenge. Completion can be celebrated; private reflections remain private.</p></section>${active.length?`<h3 class="innovation-section-title">Active in your congregation</h3><div class="challenge-list">${active.map(a=>`<button data-challenge-open="${a.id}"><span>🏁</span><div><b>${esc(a.title)}</b><small>${esc(a.challenge_type)} · starts ${esc(a.starts_on)}</small></div></button>`).join('')}</div>`:''}<h3 class="innovation-section-title">Ready-made challenges</h3><div class="challenge-list">${challengeTemplates.map((t,i)=>`<button data-challenge-template="${i}"><span>${t.type==='couples'?'💞':t.type==='wisdom'?'🧭':'📖'}</span><div><b>${esc(t.title)}</b><small>${t.days} days · ${esc(t.desc)}</small></div></button>`).join('')}</div>`,x=>{x.querySelector('[data-challenge-close]').onclick=()=>close('bqChallengeLayer');x.querySelectorAll('[data-challenge-template]').forEach(b=>b.onclick=()=>challengeTemplate(+b.dataset.challengeTemplate));x.querySelectorAll('[data-challenge-open]').forEach(b=>b.onclick=()=>openCloudChallenge(b.dataset.challengeOpen))})}
  function challengeTemplate(i){const t=challengeTemplates[i];const c=window.BQAccount?.client?.(),s=window.BQAccount?.session?.(),cid=(()=>{try{return JSON.parse(localStorage.getItem('biblequest_cloud_v1')||'{}').activeCongregationId||''}catch{return ''}})();show('bqChallengeLayer',`<header class="innovation-top"><button data-challenge-back>← Challenges</button><b>${esc(t.title)}</b><span>🏁</span></header><section class="challenge-detail"><small>${t.days}-DAY TEMPLATE</small><h1>${esc(t.title)}</h1><p>${esc(t.desc)}</p><div class="challenge-days">${t.steps.slice(0,14).map((v,n)=>`<span><b>${n+1}</b>${esc(v)}</span>`).join('')}${t.steps.length>14?`<span><b>+${t.steps.length-14}</b>more days</span>`:''}</div>${c&&s&&cid?'<button data-challenge-launch>Launch for congregation</button>':'<div class="innovation-note">Join a cloud congregation to launch this for everyone. You can still use the plan personally.</div>'}</section>`,x=>{x.querySelector('[data-challenge-back]').onclick=challenges;x.querySelector('[data-challenge-launch]')?.addEventListener('click',async()=>{const role=await c.from('bible_congregation_members').select('role').eq('congregation_id',cid).eq('user_id',s.user.id).eq('active',true).maybeSingle();if(!['facilitator','leader','admin'].includes(role.data?.role||'')){alert('Only a facilitator, leader, or admin can launch a congregation challenge.');return}const end=new Date();end.setDate(end.getDate()+t.days-1);const r=await c.from('bible_challenges').insert({congregation_id:cid,created_by:s.user.id,title:t.title,challenge_type:t.type,template_key:t.key,starts_on:new Date().toISOString().slice(0,10),ends_on:end.toISOString().slice(0,10),metadata:{days:t.days,steps:t.steps}});if(r.error)alert(r.error.message);else challenges()})})}
  async function openCloudChallenge(id){const c=window.BQAccount?.client?.(),s=window.BQAccount?.session?.();if(!c||!s)return;const r=await c.from('bible_challenges').select('*').eq('id',id).single();if(r.error)return;const t=r.data,steps=t.metadata?.steps||[],p=await c.from('bible_challenge_progress').select('day_key').eq('challenge_id',id).eq('user_id',s.user.id),done=new Set((p.data||[]).map(x=>x.day_key));show('bqChallengeLayer',`<header class="innovation-top"><button data-challenge-back>← Challenges</button><b>${esc(t.title)}</b><span>${done.size}/${steps.length}</span></header><section class="challenge-detail"><h1>${esc(t.title)}</h1><p>Tap a day after you actually complete it. Completion is shared; your private notes are not.</p><div class="challenge-progress-days">${steps.map((v,i)=>`<button class="${done.has(String(i+1))?'done':''}" data-challenge-day="${i+1}"><b>${done.has(String(i+1))?'✓':i+1}</b><span>${esc(v)}</span></button>`).join('')}</div></section>`,x=>{x.querySelector('[data-challenge-back]').onclick=challenges;x.querySelectorAll('[data-challenge-day]').forEach(b=>b.onclick=async()=>{const day=b.dataset.challengeDay;const q=await c.from('bible_challenge_progress').upsert({challenge_id:id,user_id:s.user.id,day_key:day,completed_at:new Date().toISOString()},{onConflict:'challenge_id,user_id,day_key'});if(!q.error){award(3,t.challenge_type==='couples'?'couples':'consistency','Church Challenge',{completed:1,challenge_id:id,day});openCloudChallenge(id)}})})}

  window.BQStudy={open:openStudy};window.BQMission={open:mission};window.BQWorld={open:world};window.BQExplorer={open:explorer};window.BQChallenges={open:challenges};
})();
