(() => {
  const CLOUD='biblequest_cloud_v1';
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const parse=(k,f={})=>{try{return {...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return {...f}}};
  const localDay=()=>{const d=new Date(),x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
  const PRESETS={pray:['🙏','Praying for you'],cheer:['👏','Keep going!'],heart:['💛','Glad we’re growing together'],word:['📖','Keep in the Word'],flame:['🔥','Nice consistency!']};
  let client=null,session=null,activeCongregationId='',ownRole='member',groups=[],membersByGroup={},congregationMembers=[],statuses=[],encouragements=[],channel=null,lastInvite='';

  function layer(){let x=document.getElementById('bqJourneyGroups');if(!x){x=document.createElement('div');x.id='bqJourneyGroups';x.className='journey-groups-layer hidden';document.body.appendChild(x)}return x}
  function show(html){const x=layer();x.innerHTML=`<main class="journey-groups-app">${html}</main>`;x.classList.remove('hidden');document.body.classList.add('journey-groups-open');x.scrollTop=0;return x}
  function close(){layer().classList.add('hidden');document.body.classList.remove('journey-groups-open');channel?.unsubscribe?.();channel=null}
  async function getClient(){client=window.BQAccount?.client?.()||window.BQ_SUPABASE_CLIENT||client;if(!client)for(let i=0;i<20&&!client;i++){await new Promise(r=>setTimeout(r,100));client=window.BQAccount?.client?.()||window.BQ_SUPABASE_CLIENT||null}return client}
  async function auth(){const c=await getClient();if(!c)return null;const r=await c.auth.getSession();session=r.data?.session||null;return session}
  function activeId(){return parse(CLOUD,{activeCongregationId:''}).activeCongregationId||''}
  function canCreate(){return ['facilitator','leader','admin','pastor'].includes(ownRole)}
  async function invoke(action,body={}){const {data,error}=await client.functions.invoke('bq-journey-group',{body:{action,...body}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}

  async function load(){
    if(!await auth()){renderSignedOut();return}
    activeCongregationId=activeId();if(!activeCongregationId){renderNoCongregation();return}
    const own=await client.from('bible_congregation_members').select('role').eq('congregation_id',activeCongregationId).eq('user_id',session.user.id).eq('active',true).maybeSingle();if(own.error)throw own.error;ownRole=own.data?.role||'member';
    const g=await client.from('bible_groups').select('id,owner_id,congregation_id,name,description,schedule_text,max_members,active,created_at').eq('congregation_id',activeCongregationId).eq('active',true).order('created_at');if(g.error)throw g.error;groups=g.data||[];
    const groupIds=groups.map(x=>x.id);membersByGroup={};statuses=[];encouragements=[];
    if(groupIds.length){
      const gm=await client.from('bible_group_members').select('group_id,user_id,role,joined_at').in('group_id',groupIds).eq('active',true);if(gm.error)throw gm.error;(gm.data||[]).forEach(x=>(membersByGroup[x.group_id]||(membersByGroup[x.group_id]=[])).push(x));
      const allIds=[...new Set((gm.data||[]).map(x=>x.user_id))];if(allIds.length){const cm=await client.from('bible_congregation_members').select('user_id,display_name,avatar,role').eq('congregation_id',activeCongregationId).in('user_id',allIds).eq('active',true);if(cm.error)throw cm.error;congregationMembers=cm.data||[];const st=await client.from('bible_daily_journey_status').select('user_id,journey_date,status,completed_steps,total_steps,updated_at').eq('journey_date',localDay()).in('user_id',allIds);if(st.error)throw st.error;statuses=st.data||[]}
      const en=await client.from('bible_group_encouragements').select('id,group_id,sender_id,recipient_id,kind,created_at').in('group_id',groupIds).order('created_at',{ascending:false}).limit(40);if(en.error)throw en.error;encouragements=en.data||[];
    }
    render();subscribe();
  }
  function person(id){return congregationMembers.find(x=>x.user_id===id)||{display_name:'Member',avatar:{}}}
  function glyph(a){return window.BQAvatar?.glyph?.(a)||'🙂'}
  function groupProgress(g){const ms=membersByGroup[g.id]||[],done=ms.filter(m=>statuses.find(s=>s.user_id===m.user_id)?.status==='complete').length;return {done,total:ms.length}}
  function encouragementHtml(g){const list=encouragements.filter(x=>x.group_id===g.id).slice(0,4);if(!list.length)return '<small class="group-no-cheer">No encouragements yet today. Be the first.</small>';return `<div class="group-cheer-list">${list.map(x=>{const p=person(x.sender_id),preset=PRESETS[x.kind]||['💛','Encouragement'];return `<span>${preset[0]} <b>${esc(p.display_name||'Member')}</b> · ${esc(preset[1])}</span>`}).join('')}</div>`}
  function groupCard(g){const ms=membersByGroup[g.id]||[],p=groupProgress(g),mine=ms.find(x=>x.user_id===session.user.id),leader=mine?.role==='leader'||g.owner_id===session.user.id;return `<article class="journey-group-card"><header><div><small>WEEKLY JOURNEY GROUP</small><h2>${esc(g.name)}</h2><p>${esc(g.schedule_text||'Meet when your group decides')}</p></div><div class="group-complete-ring"><b>${p.done}/${p.total}</b><small>done today</small></div></header>${g.description?`<p class="group-desc">${esc(g.description)}</p>`:''}<div class="journey-group-members">${ms.map(m=>{const pp=person(m.user_id),done=statuses.find(s=>s.user_id===m.user_id)?.status==='complete';return `<div title="${esc(pp.display_name||'Member')}"><span>${glyph(pp.avatar)}</span><i class="${done?'done':''}"></i><small>${esc(pp.display_name||'Member')}</small></div>`}).join('')}</div><div class="group-progress-bar"><i style="width:${p.total?Math.round(p.done/p.total*100):0}%"></i></div>${encouragementHtml(g)}<div class="group-actions"><button data-group-cheer="${g.id}">💛 Encourage</button>${leader?`<button data-group-code="${g.id}">🔑 New code</button>`:''}</div></article>`}
  function render(){const x=show(`<header class="journey-groups-head"><button data-group-close>← BibleQuest</button><b>Journey Groups</b><span>👥</span></header><section class="journey-groups-hero"><small>2–6 PEOPLE · ONE CONGREGATION</small><h1>Small enough to notice when someone is missing.</h1><p>See only simple completion progress and encouragement. Private notes, reflections and answers stay private unless someone intentionally shares them elsewhere.</p></section>${lastInvite?`<section class="group-invite-reveal"><small>NEW GROUP CODE</small><code>${esc(lastInvite)}</code><p>Share this with people in your congregation. Creating a new code replaces the old one.</p></section>`:''}<div class="journey-groups-list">${groups.length?groups.map(groupCard).join(''):'<section class="group-empty"><span>🌱</span><h2>No Journey Group yet.</h2><p>Join your weekly small group with its code, or ask a leader to create one.</p></section>'}</div><section class="group-join-create"><form data-group-join><h3>Join a small group</h3><div><input name="code" maxlength="12" placeholder="Group code" required><button>Join</button></div></form>${canCreate()?`<details><summary>Leader: create a Journey Group</summary><form data-group-create><label>Group name<input name="name" maxlength="60" placeholder="Tsukuba Life Group" required></label><label>Weekly schedule<input name="schedule" maxlength="100" placeholder="Wednesday · 7:00 PM"></label><label>Short description<input name="description" maxlength="240" placeholder="Weekly Bible journey and fellowship"></label><label>Maximum members<select name="max"><option>6</option><option>5</option><option>4</option><option>3</option><option>2</option></select></label><button>Create group</button></form></details>`:''}</section>`);bind(x)}
  function renderSignedOut(){const x=show(`<header class="journey-groups-head"><button data-group-close>← BibleQuest</button><b>Journey Groups</b><span>👥</span></header><section class="group-empty"><span>☁️</span><h2>Sign in to join your small group.</h2><p>Journey Groups sync completion across members while keeping private study content private.</p><button data-open-account>Open account</button></section>`);x.querySelector('[data-group-close]').onclick=close;x.querySelector('[data-open-account]').onclick=()=>{close();window.BQAccount?.open?.()}}
  function renderNoCongregation(){const x=show(`<header class="journey-groups-head"><button data-group-close>← BibleQuest</button><b>Journey Groups</b><span>👥</span></header><section class="group-empty"><span>⛪</span><h2>Join your congregation first.</h2><p>Small groups live inside a congregation so codes cannot pull unrelated people into the same church group.</p></section>`);x.querySelector('[data-group-close]').onclick=close}
  function bind(x){x.querySelector('[data-group-close]').onclick=close;x.querySelector('[data-group-join]')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');btn.disabled=true;try{await invoke('join',{invite_code:new FormData(e.currentTarget).get('code')});lastInvite='';await load()}catch(err){alert(err.message||String(err))}finally{btn.disabled=false}});x.querySelector('[data-group-create]')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),btn=e.currentTarget.querySelector('button');btn.disabled=true;try{const r=await invoke('create',{congregation_id:activeCongregationId,name:fd.get('name'),schedule_text:fd.get('schedule'),description:fd.get('description'),max_members:Number(fd.get('max'))||6});lastInvite=r.invite_code||'';await load()}catch(err){alert(err.message||String(err))}finally{btn.disabled=false}});x.querySelectorAll('[data-group-code]').forEach(b=>b.onclick=async()=>{try{const r=await invoke('rotate_code',{group_id:b.dataset.groupCode});lastInvite=r.invite_code||'';await load()}catch(err){alert(err.message||String(err))}});x.querySelectorAll('[data-group-cheer]').forEach(b=>b.onclick=()=>openCheer(b.dataset.groupCheer))}
  function openCheer(groupId){const x=show(`<header class="journey-groups-head"><button data-back-groups>← Group</button><b>Send encouragement</b><span>💛</span></header><section class="cheer-picker"><h1>Simple encouragement, not another chat feed.</h1><p>Choose a preset. No public ranking and no pressure to perform spirituality.</p>${Object.entries(PRESETS).map(([k,v])=>`<button data-cheer="${k}"><span>${v[0]}</span><b>${esc(v[1])}</b></button>`).join('')}</section>`);x.querySelector('[data-back-groups]').onclick=()=>render();x.querySelectorAll('[data-cheer]').forEach(b=>b.onclick=async()=>{const row={group_id:groupId,sender_id:session.user.id,recipient_id:null,kind:b.dataset.cheer};const r=await client.from('bible_group_encouragements').insert(row);if(r.error){alert(r.error.message);return}await load()})}
  function subscribe(){if(channel||!client||!activeCongregationId)return;channel=client.channel(`bq-journey-groups-${activeCongregationId}`).on('postgres_changes',{event:'*',schema:'public',table:'bible_daily_journey_status'},()=>load().catch(()=>{})).on('postgres_changes',{event:'*',schema:'public',table:'bible_group_members'},()=>load().catch(()=>{})).on('postgres_changes',{event:'INSERT',schema:'public',table:'bible_group_encouragements'},()=>load().catch(()=>{})).subscribe()}
  async function open(){try{await load()}catch(err){const x=show(`<header class="journey-groups-head"><button data-group-close>← BibleQuest</button><b>Journey Groups</b><span>⚠️</span></header><section class="group-empty"><h2>Could not load the group yet.</h2><p>${esc(err.message||String(err))}</p><button data-group-retry>Try again</button></section>`);x.querySelector('[data-group-close]').onclick=close;x.querySelector('[data-group-retry]').onclick=open}}
  window.BQJourneyGroups={open,refresh:load};
})();
