(() => {
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const discussions=[
    {type:'discussion',icon:'💬',title:'Conversation Circle',q:'Ano ang difference ng forgiveness at restored trust?',follow:'Paano magiging parehong gracious at wise ang boundaries?',refs:['Luke 17:3–4','Proverbs 22:3']},
    {type:'discussion',icon:'👂',title:'Listen First',q:'Ano ang isang bagay na madalas nating sagutin bago muna natin maintindihan?',follow:'Bago sumagot, i-paraphrase muna ang narinig mo.',refs:['James 1:19','Proverbs 18:13']},
    {type:'wisdom',icon:'🧭',title:'Wisdom Table',q:'Kailan nagiging poor planning ang tinatawag nating “trusting God”?',follow:'Magbigay ng isang real-life example ng faithful planning.',refs:['Luke 14:28–30','James 4:13–15']},
    {type:'discussion',icon:'🤝',title:'Community',q:'Ano ang nakakatulong para maging safe ang church group sa honest questions?',follow:'Anong response ang nakakatulong kapag may nag-share ng doubt o failure?',refs:['Galatians 6:1–2','James 1:19']},
    {type:'wisdom',icon:'🏠',title:'Family & Work',q:'Paano mo malalaman kung healthy diligence pa o unhealthy overwork na?',follow:'Anong responsibility natin sa provision, rest, family, at limits?',refs:['1 Timothy 5:8','Mark 6:31']}
  ];
  const polls=[
    {q:'Which way helps you learn Scripture best?',choices:['Reading','Games','Discussion','Teaching others']},
    {q:'For the next congregation challenge, what sounds most useful?',choices:['Gospels','Proverbs','Acts','Couples/Family']},
    {q:'What usually makes a Bible discussion memorable?',choices:['Good question','Personal story','Context','Practical action']}
  ];
  let room=null,isHost=false,channel=null,hostQuestion=null,message='';
  const account=()=>window.BQAccount;
  const client=()=>account()?.client?.();
  const session=()=>account()?.session?.();
  function cloudState(){try{return JSON.parse(localStorage.getItem('biblequest_cloud_v1')||'{}')}catch{return {}}}
  function activeCongregation(){return cloudState().activeCongregationId||''}
  function layer(){let x=document.getElementById('bqRoomLayer');if(!x){x=document.createElement('div');x.id='bqRoomLayer';x.className='innovation-layer hidden';document.body.appendChild(x)}return x}
  function show(html){const x=layer();x.innerHTML=`<main class="innovation-app room-app">${html}</main>`;x.classList.remove('hidden');document.body.classList.add('innovation-open');bind();x.scrollTop=0}
  function close(){unsubscribe();layer().classList.add('hidden');document.body.classList.remove('innovation-open');room=null;isHost=false;hostQuestion=null}
  function code(){const a=new Uint8Array(6);crypto.getRandomValues(a);return [...a].map(x=>alphabet[x%alphabet.length]).join('')}
  async function role(){const c=client(),s=session(),cid=activeCongregation();if(!c||!s||!cid)return '';const r=await c.from('bible_congregation_members').select('role').eq('congregation_id',cid).eq('user_id',s.user.id).eq('active',true).maybeSingle();return r.data?.role||''}
  function signedIn(){return Boolean(client()&&session())}
  function home(error=''){
    const cid=activeCongregation();
    show(`<header class="innovation-top"><button data-room-close>← BibleQuest</button><b>Live BibleQuest Room</b><span>📡</span></header><section class="innovation-hero"><small>ONE ROOM · MANY PHONES</small><h1>Sabay-sabay na BibleQuest.</h1><p>Host a live quiz, poll, verse hunt, wisdom question, or conversation topic. Members join with a short room code.</p></section>${message?`<div class="innovation-message">${esc(message)}</div>`:''}${error?`<div class="innovation-message error">${esc(error)}</div>`:''}${!signedIn()?'<div class="innovation-note"><b>Sign in required</b><p>Live Rooms use your BibleQuest account so identities, avatars, congregation membership, and results are consistent across phones.</p><button data-room-account>Open account</button></div>':!cid?'<div class="innovation-note"><b>Join a congregation first</b><p>Live Room codes only work inside your active BibleQuest congregation.</p><button data-room-community>Open congregation</button></div>':`<section class="room-entry-grid"><form data-room-host><small>FOR FACILITATORS / LEADERS</small><h3>Start a room</h3><input name="title" maxlength="80" placeholder="Friday Bible Night" value="BibleQuest Live"><button>Start live room</button></form><form data-room-join><small>FOR MEMBERS</small><h3>Join a room</h3><input name="code" maxlength="8" placeholder="ABC234" autocomplete="off" required><button class="secondary">Join with code</button></form></section><div class="innovation-note"><b>Live modes</b><p>⚡ Quiz · 📊 poll · 🔎 verse hunt · 💬 discussion · 🧭 wisdom. Discussion modes reward participation, not “who sounds most spiritual.”</p></div>`}`)
  }
  async function host(form){const r=await role();if(!['facilitator','leader','admin'].includes(r))throw new Error('Only a facilitator, leader, or admin can start a live room.');const cid=activeCongregation(),s=session(),title=String(new FormData(form).get('title')||'BibleQuest Live').trim().slice(0,80),roomCode=code();const q=await client().from('bible_shared_sessions').insert({congregation_id:cid,created_by:s.user.id,session_type:'live-room',title,room_code:roomCode,status:'lobby',state:{round:0,activity:'lobby'},metadata:{version:1}}).select('*').single();if(q.error)throw q.error;room=q.data;isHost=true;await joinParticipant();subscribe();renderRoom()}
  async function join(form){const value=String(new FormData(form).get('code')||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8);const r=await client().from('bible_shared_sessions').select('*').eq('room_code',value).neq('status','ended').maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error('Room not found. Check the code and make sure you joined the same congregation.');room=r.data;isHost=room.created_by===session().user.id;await joinParticipant();subscribe();renderRoom()}
  async function joinParticipant(){const r=await client().from('bible_session_participants').upsert({session_id:room.id,user_id:session().user.id,participation_points:0},{onConflict:'session_id,user_id'});if(r.error)throw r.error}
  async function participants(){const r=await client().from('bible_session_participants').select('user_id,participation_points,created_at').eq('session_id',room.id);if(r.error)return [];const ids=r.data.map(x=>x.user_id);if(!ids.length)return [];const m=await client().from('bible_congregation_members').select('user_id,display_name,avatar').eq('congregation_id',room.congregation_id).in('user_id',ids);const by=new Map((m.data||[]).map(x=>[x.user_id,x]));return r.data.map(x=>({...x,...(by.get(x.user_id)||{})}))}
  function unsubscribe(){if(channel&&client())client().removeChannel(channel);channel=null}
  function subscribe(){unsubscribe();const c=client();if(!c||!room)return;channel=c.channel(`bq-room-${room.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'bible_shared_sessions',filter:`id=eq.${room.id}`},p=>{room=p.new;renderRoom()}).on('postgres_changes',{event:'*',schema:'public',table:'bible_session_participants',filter:`session_id=eq.${room.id}`},()=>renderRoom()).subscribe()}
  async function renderRoom(){if(!room)return;const people=await participants(),st=room.state||{},activity=st.activity||'lobby';let body='';if(activity==='lobby')body=`<section class="room-stage"><div class="room-code"><small>ROOM CODE</small><strong>${esc(room.room_code)}</strong></div><h1>${esc(room.title||'BibleQuest Live')}</h1><p>${people.length} joined · waiting for the host.</p>${isHost?hostControls():''}</section>`;else body=activityView(st,people);show(`<header class="innovation-top"><button data-room-close>← Leave</button><b>${esc(room.title||'Live Room')}</b><span class="room-live">● LIVE</span></header><div class="room-people">${people.map(p=>`<span>${window.BQAvatar?.glyph?.(p.avatar)||'🙂'} ${esc(p.display_name||'Member')}</span>`).join('')}</div>${body}`)}
  function hostControls(){return `<div class="room-host-controls"><b>Start an activity</b><div class="room-mode-grid"><button data-room-start="quiz">⚡ Quiz</button><button data-room-start="poll">📊 Poll</button><button data-room-start="hunt">🔎 Verse Hunt</button><button data-room-start="discussion">💬 Talk</button><button data-room-start="wisdom">🧭 Wisdom</button></div></div>`}
  async function loadQuestions(){if(window.BQ_QUESTIONS)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='data/questions.js';s.onload=resolve;s.onerror=reject;document.body.appendChild(s)})}
  async function start(type){let payload={};const round=Number(room.state?.round||0)+1;if(type==='quiz'){await loadQuestions();const pool=window.BQ_QUESTIONS||[];const q=pool[Math.floor(Math.random()*pool.length)];hostQuestion=q;payload={activity:'quiz',round,q:q.q,choices:q.choices,ref:q.ref,book:q.book}}else if(type==='poll'){const p=polls[Math.floor(Math.random()*polls.length)];hostQuestion=null;payload={activity:'poll',round,q:p.q,choices:p.choices}}else if(type==='hunt'){const hunts=[['John 3:16','Find the verse about God loving the world.'],['James 1:19','Find the instruction about listening and speaking.'],['Romans 12:2','Find the verse about renewing the mind.'],['Matthew 6:33','Find what Jesus says to seek first.'],['Micah 6:8','Find what the LORD requires.']];const h=hunts[Math.floor(Math.random()*hunts.length)];hostQuestion=null;payload={activity:'hunt',round,ref:h[0],q:h[1]}}else{const d=discussions.filter(x=>type==='wisdom'?x.type==='wisdom':x.type==='discussion');const p=d[Math.floor(Math.random()*d.length)];hostQuestion=null;payload={activity:type,round,q:p.q,follow:p.follow,refs:p.refs,title:p.title}}const u=await client().from('bible_shared_sessions').update({status:'active',state:payload,updated_at:new Date().toISOString()}).eq('id',room.id).eq('created_by',session().user.id).select('*').single();if(u.error)throw u.error;room=u.data;renderRoom()}
  function activityView(st,people){const hostNext=isHost?`<div class="room-host-bar"><button data-room-next>Next activity</button><button class="secondary" data-room-end>End room</button></div>`:'';if(st.activity==='quiz')return `<section class="room-stage"><small>ROUND ${st.round} · BIBLE QUIZ</small><h1>${esc(st.q)}</h1><div class="room-answer-grid">${(st.choices||[]).map((x,i)=>`<button data-room-answer="${i}">${esc(x)}</button>`).join('')}</div><p>${esc(st.ref||'')}</p>${isHost?'<button class="secondary" data-room-score>Score this round</button>':''}${hostNext}</section>`;if(st.activity==='poll')return `<section class="room-stage"><small>ROUND ${st.round} · LIVE POLL</small><h1>${esc(st.q)}</h1><div class="room-answer-grid">${(st.choices||[]).map(x=>`<button data-room-choice="${esc(x)}">${esc(x)}</button>`).join('')}</div><div data-room-poll-results></div>${hostNext}</section>`;if(st.activity==='hunt')return `<section class="room-stage"><small>ROUND ${st.round} · VERSE HUNT</small><div class="room-ref">${esc(st.ref)}</div><h1>${esc(st.q)}</h1><button data-room-complete>Found it / done</button>${hostNext}</section>`;return `<section class="room-stage conversation"><small>ROUND ${st.round} · ${st.activity==='wisdom'?'WISDOM TABLE':'CONVERSATION'}</small><h1>${esc(st.q)}</h1><div class="room-deeper"><b>Go deeper</b><p>${esc(st.follow||'')}</p></div><p class="room-refs">${(st.refs||[]).map(esc).join(' · ')}</p><button data-room-complete>We discussed / I participated</button>${hostNext}</section>`}
  async function respond(response){const row={session_id:room.id,user_id:session().user.id,round_no:Number(room.state?.round||0),response,updated_at:new Date().toISOString()};const r=await client().from('bible_room_responses').upsert(row,{onConflict:'session_id,user_id,round_no'});if(r.error)throw r.error;message='Response saved.';if(room.state?.activity==='poll')pollTotals();else renderRoom()}
  async function pollTotals(){const r=await client().rpc('bible_room_poll_totals',{p_session:room.id,p_round:Number(room.state?.round||0)});const host=layer().querySelector('[data-room-poll-results]');if(!host)return;if(r.error){host.textContent='Vote saved.';return}const total=(r.data||[]).reduce((a,x)=>a+Number(x.total||0),0);host.innerHTML=`<div class="poll-bars">${(room.state?.choices||[]).map(c=>{const n=Number((r.data||[]).find(x=>x.choice===c)?.total||0),pct=total?Math.round(n/total*100):0;return `<div><span>${esc(c)}</span><b>${n} · ${pct}%</b><i style="width:${pct}%"></i></div>`}).join('')}</div>`}
  async function scoreRound(){if(!isHost||!hostQuestion)return;const r=await client().from('bible_room_responses').select('user_id,response').eq('session_id',room.id).eq('round_no',Number(room.state?.round||0));if(r.error)throw r.error;const correct=(r.data||[]).filter(x=>Number(x.response?.answer)===Number(hostQuestion.answer));if(!correct.length){message='No correct submitted answers this round.';return renderRoom()}const claims=correct.map(x=>({sourceEventId:`live:${room.id}:${room.state.round}:${x.user_id}`,source:'Team Bible Sprint',category:'knowledge',claimedPoints:10,targetUserId:x.user_id,meta:{room_id:room.id,round:room.state.round}}));const s=await client().functions.invoke('bq-score',{body:{congregationId:room.congregation_id,claims}});if(s.error)throw s.error;message=`Scored ${s.data?.accepted||0} correct answer(s).`;renderRoom()}
  async function end(){const r=await client().from('bible_shared_sessions').update({status:'ended',ended_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',room.id).eq('created_by',session().user.id);if(r.error)throw r.error;message='Room ended.';home()}
  function bind(){const x=layer();x.querySelectorAll('[data-room-close]').forEach(b=>b.onclick=close);x.querySelector('[data-room-account]')?.addEventListener('click',()=>account()?.open?.());x.querySelector('[data-room-community]')?.addEventListener('click',()=>{close();window.BQCommunity?.open?.()});x.querySelector('[data-room-host]')?.addEventListener('submit',async e=>{e.preventDefault();try{await host(e.currentTarget)}catch(err){home(err.message||String(err))}});x.querySelector('[data-room-join]')?.addEventListener('submit',async e=>{e.preventDefault();try{await join(e.currentTarget)}catch(err){home(err.message||String(err))}});x.querySelectorAll('[data-room-start]').forEach(b=>b.onclick=()=>start(b.dataset.roomStart).catch(e=>{message=e.message;renderRoom()}));x.querySelectorAll('[data-room-answer]').forEach(b=>b.onclick=()=>respond({answer:Number(b.dataset.roomAnswer)}).catch(e=>{message=e.message;renderRoom()}));x.querySelectorAll('[data-room-choice]').forEach(b=>b.onclick=()=>respond({choice:b.dataset.roomChoice}).catch(e=>{message=e.message;renderRoom()}));x.querySelector('[data-room-complete]')?.addEventListener('click',()=>respond({completed:true}).catch(e=>{message=e.message;renderRoom()}));x.querySelector('[data-room-score]')?.addEventListener('click',()=>scoreRound().catch(e=>{message=e.message;renderRoom()}));x.querySelector('[data-room-next]')?.addEventListener('click',()=>{hostQuestion=null;renderRoom().then(()=>{const controls=layer().querySelector('.room-host-bar');if(controls)controls.outerHTML=hostControls();bind()})});x.querySelector('[data-room-end]')?.addEventListener('click',()=>end().catch(e=>{message=e.message;renderRoom()}));if(room?.state?.activity==='poll')setTimeout(pollTotals,50)}
  window.BQLiveRooms={open:()=>home(),joinCode:c=>{home();setTimeout(()=>{const i=layer().querySelector('[data-room-join] input');if(i){i.value=c;i.form.requestSubmit()}},0)}};
})();
