(() => {
  'use strict';
  const BUCKET='biblequest-announcements';
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let layer=null,rows=[],role='member',siteRole='',tab='all',loading=false,coverUrls=new Map();
  const account=()=>window.BQAccount,client=()=>account()?.client?.(),session=()=>account()?.session?.(),cloud=()=>window.BQCloud?.status?.()||{},congregation=()=>cloud().activeCongregation||null;
  const editor=()=>['owner','admin'].includes(siteRole)||['leader','pastor','admin'].includes(role);
  function youtube(value,type){
    let u;try{u=new URL(String(value||'').trim())}catch{throw new Error('Enter a valid YouTube URL.')}
    const host=u.hostname.toLowerCase().replace(/^www\./,'').replace(/^m\./,'');
    if(!['youtube.com','youtu.be'].includes(host))throw new Error('Only youtube.com or youtu.be links are accepted.');
    if(type==='youtube_video'){
      let id='';if(host==='youtu.be')id=u.pathname.split('/').filter(Boolean)[0]||'';else if(u.pathname==='/watch')id=u.searchParams.get('v')||'';else{const m=u.pathname.match(/^\/(?:shorts|embed)\/([A-Za-z0-9_-]{6,20})/);id=m?.[1]||''}
      if(!/^[A-Za-z0-9_-]{6,20}$/.test(id))throw new Error('Could not find a valid YouTube video ID in that link.');return {url:u.href,id};
    }
    if(type==='youtube_playlist'){
      const id=u.searchParams.get('list')||'';if(!/^[A-Za-z0-9_-]{10,120}$/.test(id))throw new Error('Could not find a valid YouTube playlist ID.');return {url:u.href,id};
    }
    if(host!=='youtube.com'||!/^\/(?:@|channel\/|c\/|user\/)/.test(u.pathname))throw new Error('Use a YouTube channel URL such as youtube.com/@channel or /channel/UC…');
    return {url:u.href,id:null};
  }
  function ensureLayer(){if(layer)return layer;layer=document.createElement('div');layer.id='bqMediaLayer';layer.className='media-layer hidden';document.body.appendChild(layer);return layer}
  function close(){ensureLayer().classList.add('hidden');document.body.style.removeProperty('overflow')}
  async function access(){const c=client(),s=session(),g=congregation();if(!c||!s||!g)throw new Error('Sign in and select a congregation first.');role=g.role||'member';const a=await c.from('bible_app_access').select('role,active').eq('user_id',s.user.id).maybeSingle();if(a.error)throw a.error;siteRole=a.data?.active?String(a.data.role||''):''}
  async function covers(){const c=client();await Promise.all(rows.filter(x=>x.cover_path&&!coverUrls.has(x.cover_path)).map(async x=>{const r=await c.storage.from(BUCKET).createSignedUrl(x.cover_path,3600);if(!r.error&&r.data?.signedUrl)coverUrls.set(x.cover_path,r.data.signedUrl)}))}
  async function load(){await access();const g=congregation(),r=await client().from('bible_media_library').select('*').eq('congregation_id',g.id).order('featured',{ascending:false}).order('display_order',{ascending:true}).order('created_at',{ascending:false}).limit(120);if(r.error)throw r.error;rows=r.data||[];await covers();render()}
  function typeLabel(t){return t==='youtube_channel'?'CHANNEL':t==='youtube_playlist'?'PLAYLIST':'VIDEO'}
  function embedUrl(x){return x.media_type==='youtube_playlist'?`https://www.youtube-nocookie.com/embed/videoseries?list=${encodeURIComponent(x.youtube_id||'')}`:`https://www.youtube-nocookie.com/embed/${encodeURIComponent(x.youtube_id||'')}?rel=0`}
  function card(x){const cover=x.cover_path?coverUrls.get(x.cover_path):'',canPlay=x.media_type!=='youtube_channel'&&x.youtube_id;return `<article class="media-card ${x.featured?'featured':''}" data-media-id="${x.id}" data-bq-content-key="media:${x.id}" data-bq-reportable="1"><div class="media-cover" ${cover?`style="background-image:url('${esc(cover)}')"`:''}><span>${x.media_type==='youtube_channel'?'📺':x.media_type==='youtube_playlist'?'▶️':'🎬'}</span></div><div class="media-copy"><small>${x.featured?'★ FEATURED · ':''}${typeLabel(x.media_type)}</small><h3>${esc(x.title)}</h3>${x.description?`<p>${esc(x.description)}</p>`:''}<div class="media-actions">${canPlay?`<button type="button" class="play" data-media-play="${x.id}">▶ Play here</button>`:''}<a href="${esc(x.youtube_url)}" target="_blank" rel="noopener noreferrer">Open on YouTube ↗</a><button type="button" data-media-report="${x.id}">⚑ Report</button></div><div data-media-player="${x.id}"></div></div>${editor()?`<div class="media-editor-actions"><button data-media-feature="${x.id}">${x.featured?'★ Unfeature':'☆ Feature'}</button><button data-media-up="${x.id}">↑ Earlier</button><button data-media-down="${x.id}">↓ Later</button><button data-media-edit="${x.id}">Edit</button><button class="danger" data-media-archive="${x.id}">Archive</button></div>`:''}</article>`}
  function createForm(){if(!editor())return '';return `<details class="media-create"><summary>＋ Add handpicked YouTube media</summary><form data-media-create><label>Type<select name="type"><option value="youtube_video">Specific video</option><option value="youtube_playlist">Playlist</option><option value="youtube_channel">Channel</option></select></label><label>YouTube link<input name="url" type="url" placeholder="https://www.youtube.com/watch?v=…" required></label><label>Title<input name="title" maxlength="160" required></label><label>Description<textarea name="description" rows="4" maxlength="2500" placeholder="Why are you recommending this?"></textarea></label><div class="media-inline"><label>Publish<input name="publish" type="datetime-local"></label><label>Order<input name="order" type="number" value="0" min="-999" max="999"></label></div><label><span><input name="featured" type="checkbox"> Feature this item</span></label><label>Optional cover/banner image<input name="cover" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></label><div class="media-note">Specific videos and playlists embed only after a member taps Play here, using YouTube's privacy-enhanced <b>youtube-nocookie.com</b> player. Channels open as curated links.</div><button type="submit">Publish media</button></form></details>`}
  function render(error=''){const g=congregation(),x=ensureLayer(),shown=rows.filter(r=>tab==='all'||(tab==='featured'?r.featured:r.media_type===tab));x.innerHTML=`<main class="media-app"><header class="media-top"><button data-media-close>← BibleQuest</button><b>Videos & Media</b><span>🎬</span></header><section class="media-hero"><small>${esc(g?.name||'CONGREGATION')}</small><h1>Handpicked videos, playlists & channels</h1><p>Only media selected by authorized BibleQuest ministry leaders appears here. YouTube content is external; opening or playing it is subject to YouTube's service and policies.</p></section>${error?`<section class="media-section">${esc(error)}</section>`:''}${createForm()}<div class="media-tabs"><button data-media-tab="all" class="${tab==='all'?'active':''}">All</button><button data-media-tab="featured" class="${tab==='featured'?'active':''}">Featured</button><button data-media-tab="youtube_video" class="${tab==='youtube_video'?'active':''}">Videos</button><button data-media-tab="youtube_playlist" class="${tab==='youtube_playlist'?'active':''}">Playlists</button><button data-media-tab="youtube_channel" class="${tab==='youtube_channel'?'active':''}">Channels</button></div><section class="media-grid">${shown.length?shown.map(card).join(''):'<div class="media-empty">No curated media has been published here yet.</div>'}</section></main>`;x.classList.remove('hidden');document.body.style.overflow='hidden';bind()}
  async function uploadCover(file,gid){if(!file||!file.size)return null;if(file.size>5*1024*1024)throw new Error('Cover image must be 5 MB or smaller.');if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw new Error('Cover must be JPEG, PNG, WebP, or GIF.');const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase()||'jpg',path=`${gid}/media/${crypto.randomUUID()}.${ext}`,r=await client().storage.from(BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(r.error)throw r.error;return path}
  async function createMedia(form){const fd=new FormData(form),g=congregation(),s=session(),type=String(fd.get('type')||'youtube_video'),parsed=youtube(fd.get('url'),type),file=form.elements.cover?.files?.[0],cover=await uploadCover(file,g.id),publish=String(fd.get('publish')||'').trim(),row={congregation_id:g.id,created_by:s.user.id,media_type:type,title:String(fd.get('title')||'').trim(),description:String(fd.get('description')||'').trim(),youtube_url:parsed.url,youtube_id:parsed.id,cover_path:cover,featured:fd.get('featured')==='on',display_order:Math.max(-999,Math.min(999,Number(fd.get('order')||0))),publish_at:publish?new Date(publish).toISOString():new Date().toISOString(),active:true};const r=await client().from('bible_media_library').insert(row);if(r.error)throw r.error;await load()}
  async function patch(id,changes){const r=await client().from('bible_media_library').update({...changes,updated_at:new Date().toISOString()}).eq('id',id).eq('congregation_id',congregation().id);if(r.error)throw r.error;await load()}
  async function edit(id){const x=rows.find(r=>r.id===id);if(!x)return;const title=prompt('Media title:',x.title);if(title===null)return;const description=prompt('Description:',x.description||'');if(description===null)return;await patch(id,{title:String(title).trim().slice(0,160),description:String(description).trim().slice(0,2500)})}
  function play(id){const x=rows.find(r=>r.id===id),host=ensureLayer().querySelector(`[data-media-player="${CSS.escape(id)}"]`);if(!x||!host||!x.youtube_id)return;host.className='media-player';host.innerHTML=`<iframe src="${embedUrl(x)}" title="${esc(x.title)}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`}
  function report(id){const x=rows.find(r=>r.id===id);if(!x)return;window.BQContentReport?.openFor?.({key:`media:${x.id}`,contentType:'other',source:'congregation-media',ref:x.youtube_url,text:x.title,answer:x.description,surfaceTitle:'Videos & Media'})||window.BQContentReport?.open?.()}
  function bind(){const x=ensureLayer();x.querySelector('[data-media-close]').onclick=close;x.querySelectorAll('[data-media-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.mediaTab;render()});x.querySelector('[data-media-create]')?.addEventListener('submit',e=>{e.preventDefault();createMedia(e.currentTarget).catch(err=>render(err.message||String(err)))});x.querySelectorAll('[data-media-play]').forEach(b=>b.onclick=()=>play(b.dataset.mediaPlay));x.querySelectorAll('[data-media-report]').forEach(b=>b.onclick=()=>report(b.dataset.mediaReport));x.querySelectorAll('[data-media-feature]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.mediaFeature);patch(r.id,{featured:!r.featured}).catch(err=>render(err.message||String(err)))});x.querySelectorAll('[data-media-up]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.mediaUp);patch(r.id,{display_order:(Number(r.display_order)||0)-1}).catch(err=>render(err.message||String(err)))});x.querySelectorAll('[data-media-down]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.mediaDown);patch(r.id,{display_order:(Number(r.display_order)||0)+1}).catch(err=>render(err.message||String(err)))});x.querySelectorAll('[data-media-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.mediaEdit).catch(err=>render(err.message||String(err))));x.querySelectorAll('[data-media-archive]').forEach(b=>b.onclick=()=>{if(confirm('Archive this curated media item?'))patch(b.dataset.mediaArchive,{active:false}).catch(err=>render(err.message||String(err)))})}
  async function open(){if(loading)return;loading=true;try{await load()}catch(err){render(err.message||String(err))}finally{loading=false}}
  function inject(){const home=document.querySelector('.modern-home');if(!home||home.querySelector('[data-media-entry]'))return;const anchor=home.querySelector('[data-ministry-entry]')||home.querySelector('.modern-footer-row')||home.lastElementChild;const card=document.createElement('section');card.className='media-entry';card.dataset.mediaEntry='1';card.innerHTML='<div><b>🎬 Videos & Media</b><small>Handpicked videos · playlists · recommended channels</small></div><button type="button" data-media-open>Open library</button>';anchor?.insertAdjacentElement(anchor?.matches?.('[data-ministry-entry]')?'afterend':'beforebegin',card);card.querySelector('button').onclick=open}
  document.addEventListener('click',e=>{if(e.target.closest?.('[data-media-open]'))open()});new MutationObserver(inject).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setTimeout(inject,900);
  window.BQMediaLibrary={open,refresh:load,parseYoutube:youtube};
})();