(() => {
  'use strict';
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
  let layer=null,role='member',messages=[],polls=[],votes=new Map(),totals=new Map(),loading=false;
  const account=()=>window.BQAccount,client=()=>account()?.client?.(),session=()=>account()?.session?.();
  const cloud=()=>window.BQCloud?.status?.()||{};const congregation=()=>cloud().activeCongregation||null;const leader=()=>['facilitator','leader','pastor','admin'].includes(role);
  function ensureLayer(){if(layer)return layer;layer=document.createElement('div');layer.className='ministry-layer hidden';layer.id='bqMinistryLayer';document.body.appendChild(layer);return layer}
  function close(){ensureLayer().classList.add('hidden');document.body.style.removeProperty('overflow')}
  function refsHtml(rows=[]){return rows.length?`<div class="ministry-refs">${rows.map(x=>`<span>📖 ${esc(x)}</span>`).join('')}</div>`:''}
  async function load(){const c=client(),s=session(),g=congregation();if(!c||!s||!g)throw new Error('Sign in and select a congregation first.');const own=await c.from('bible_congregation_members').select('role').eq('congregation_id',g.id).eq('user_id',s.user.id).eq('active',true).maybeSingle();if(own.error)throw own.error;role=own.data?.role||'member';const [m,p,v]=await Promise.all([c.from('bible_ministry_messages').select('*').eq('congregation_id',g.id).eq('active',true).order('publish_at',{ascending:false}).limit(50),c.from('bible_polls').select('*').eq('congregation_id',g.id).eq('active',true).order('created_at',{ascending:false}).limit(30),c.from('bible_poll_votes').select('poll_id,option_index').eq('user_id',s.user.id)]);if(m.error)throw m.error;if(p.error)throw p.error;if(v.error)throw v.error;messages=m.data||[];polls=p.data||[];votes=new Map((v.data||[]).map(x=>[x.poll_id,x.option_index]));totals=new Map();await Promise.all(polls.map(async poll=>{const r=await c.rpc('bible_poll_totals',{p_poll:poll.id});if(!r.error)totals.set(poll.id,r.data||[])}));render()}
  function messageCard(x){return `<article class="ministry-card"><small>${esc(x.message_type.toUpperCase())}</small><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p>${refsHtml(Array.isArray(x.scripture_refs)?x.scripture_refs:[])}<div class="ministry-meta"><span>${new Date(x.publish_at).toLocaleString()}</span></div>${leader()?`<button class="ministry-archive" data-message-archive="${x.id}">Archive</button>`:''}</article>`}
  function pollCard(p){const opts=Array.isArray(p.options)?p.options:[],mine=votes.get(p.id),rows=totals.get(p.id)||[],closed=p.closes_at&&new Date(p.closes_at)<=new Date();return `<article class="ministry-card"><small>POLL${closed?' · CLOSED':''}</small><h3>${esc(p.prompt)}</h3>${p.context?`<p>${esc(p.context)}</p>`:''}${refsHtml(Array.isArray(p.scripture_refs)?p.scripture_refs:[])}<div class="ministry-poll-options">${opts.map((o,i)=>{const n=Number(rows.find(r=>Number(r.option_index)===i)?.total||0);return `<button type="button" data-poll="${p.id}" data-option="${i}" class="${mine===i?'voted':''}" ${closed?'disabled':''}><span>${esc(o)}</span><b>${n}</b></button>`}).join('')}</div><div class="ministry-meta"><span>${rows.reduce((n,r)=>n+Number(r.total||0),0)} votes</span>${p.closes_at?`<span>Closes ${new Date(p.closes_at).toLocaleString()}</span>`:''}</div>${leader()?`<button class="ministry-archive" data-poll-close="${p.id}">Close poll</button>`:''}</article>`}
  function createForms(){if(!leader())return '';return `<details class="ministry-create"><summary>＋ Publish devotional / message</summary><form data-message-create><label>Type<select name="type"><option value="devotional">Devotional</option><option value="announcement">Announcement</option><option value="activity">Activity</option><option value="encouragement">Encouragement</option></select></label><label>Title<input name="title" maxlength="120" required></label><label>Message<textarea name="body" maxlength="6000" rows="5" required></textarea></label><label>Scripture references<input name="refs" maxlength="500" placeholder="John 15:5; Psalm 23"></label><button>Publish to congregation</button></form></details><details class="ministry-create"><summary>＋ Create congregation poll</summary><form data-poll-create><label>Question<input name="prompt" maxlength="240" required></label><label>Context<textarea name="context" maxlength="1000" rows="3"></textarea></label><label>Choices<input name="options" maxlength="800" placeholder="One choice per line" required></label><label>Scripture references<input name="refs" maxlength="500" placeholder="James 1:19; Proverbs 18:13"></label><label>Close after<select name="hours"><option value="24">24 hours</option><option value="72">3 days</option><option value="168">7 days</option><option value="0">No automatic close</option></select></label><button>Create poll</button></form></details>`}
  function render(error=''){const g=congregation(),x=ensureLayer();x.innerHTML=`<main class="ministry-app"><header class="ministry-top"><button data-ministry-close>← BibleQuest</button><b>Congregation Ministry</b><span>⛪</span></header><section class="ministry-hero"><small>${esc(g?.name||'CONGREGATION')} · ${esc(role.toUpperCase())}</small><h1>Devotionals, tasks, messages & polls</h1><p>Leaders and pastors can guide activities here. Members see congregation messages, vote in polls, and open their assigned tasks.</p></section>${error?`<div class="ministry-card">${esc(error)}</div>`:''}<section class="ministry-actions"><button data-ministry-assignments>📮 Assignments</button><button data-ministry-groups>👥 Journey Groups</button><button data-ministry-live>📡 Live Room</button></section>${createForms()}<section class="ministry-section"><h2>Messages & devotionals</h2><div class="ministry-list">${messages.length?messages.map(messageCard).join(''):'<div class="ministry-empty">No ministry messages yet.</div>'}</div></section><section class="ministry-section"><h2>Congregation polls</h2><div class="ministry-list">${polls.length?polls.map(pollCard).join(''):'<div class="ministry-empty">No persistent congregation polls yet.</div>'}</div></section></main>`;x.classList.remove('hidden');document.body.style.overflow='hidden';bind()}
  async function createMessage(form){const fd=new FormData(form),g=congregation(),s=session(),row={congregation_id:g.id,created_by:s.user.id,message_type:String(fd.get('type')||'announcement'),title:String(fd.get('title')||'').trim(),body:String(fd.get('body')||'').trim(),scripture_refs:String(fd.get('refs')||'').split(/[;,]/).map(x=>x.trim()).filter(Boolean)};const r=await client().from('bible_ministry_messages').insert(row);if(r.error)throw r.error;await load()}
  async function createPoll(form){const fd=new FormData(form),g=congregation(),s=session(),options=String(fd.get('options')||'').split(/\n|\|/).map(x=>x.trim()).filter(Boolean).slice(0,8);if(options.length<2)throw new Error('Enter at least two poll choices, one per line.');const hours=Number(fd.get('hours')||0),closes=hours?new Date(Date.now()+hours*3600000).toISOString():null,row={congregation_id:g.id,created_by:s.user.id,prompt:String(fd.get('prompt')||'').trim(),context:String(fd.get('context')||'').trim()||null,options,scripture_refs:String(fd.get('refs')||'').split(/[;,]/).map(x=>x.trim()).filter(Boolean),content_class:'open_question',closes_at:closes,active:true};const r=await client().from('bible_polls').insert(row);if(r.error)throw r.error;await load()}
  async function vote(id,index){const s=session();const r=await client().from('bible_poll_votes').upsert({poll_id:id,user_id:s.user.id,option_index:index},{onConflict:'poll_id,user_id'});if(r.error)throw r.error;await load()}
  async function archiveMessage(id){const r=await client().from('bible_ministry_messages').update({active:false,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;await load()}
  async function closePoll(id){const r=await client().from('bible_polls').update({active:false,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;await load()}
  function bind(){const x=ensureLayer();x.querySelector('[data-ministry-close]').onclick=close;x.querySelector('[data-ministry-assignments]').onclick=()=>{close();window.BQAssignments?.open?.()};x.querySelector('[data-ministry-groups]').onclick=()=>{close();window.BQJourneyGroups?.open?.()};x.querySelector('[data-ministry-live]').onclick=()=>{close();window.BQLiveRooms?.open?.()||document.querySelector('[data-live-room]')?.click()};x.querySelector('[data-message-create]')?.addEventListener('submit',e=>{e.preventDefault();createMessage(e.currentTarget).catch(err=>render(err.message||String(err)))});x.querySelector('[data-poll-create]')?.addEventListener('submit',e=>{e.preventDefault();createPoll(e.currentTarget).catch(err=>render(err.message||String(err)))});x.querySelectorAll('[data-poll]').forEach(b=>b.onclick=()=>vote(b.dataset.poll,Number(b.dataset.option)).catch(err=>render(err.message||String(err))));x.querySelectorAll('[data-message-archive]').forEach(b=>b.onclick=()=>archiveMessage(b.dataset.messageArchive).catch(err=>render(err.message||String(err))));x.querySelectorAll('[data-poll-close]').forEach(b=>b.onclick=()=>closePoll(b.dataset.pollClose).catch(err=>render(err.message||String(err))))}
  async function open(){if(loading)return;loading=true;try{await load()}catch(e){render(e.message||String(e))}finally{loading=false}}
  function inject(){const home=document.querySelector('.modern-home');if(!home||home.querySelector('[data-ministry-entry]'))return;const host=home.querySelector('.modern-footer-row')||home.lastElementChild||home;const card=document.createElement('section');card.className='ministry-entry';card.dataset.ministryEntry='1';card.innerHTML='<div><b>⛪ Congregation Ministry</b><small>Devotionals · assignments · messages · polls</small></div><button type="button" data-ministry-open>Open</button>';host.before(card);card.querySelector('button').onclick=open}
  document.addEventListener('click',e=>{if(e.target.closest?.('[data-ministry-open]'))open()});new MutationObserver(inject).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setTimeout(inject,800);
  window.BQMinistry={open,refresh:load};
})();