(() => {
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let context={},current=null,message='',error='';
  function layer(){let x=document.getElementById('bqNotesLayer');if(!x){x=document.createElement('div');x.id='bqNotesLayer';x.className='notes-layer hidden';document.body.appendChild(x)}return x}
  function account(){return window.BQAccount}
  function client(){return account()?.client?.()}
  function session(){return account()?.session?.()}
  function show(html){const x=layer();x.innerHTML=`<main class="notes-app">${html}</main>`;x.classList.remove('hidden');document.body.classList.add('notes-open');bind();x.scrollTop=0}
  function close(){layer().classList.add('hidden');document.body.classList.remove('notes-open');current=null;message='';error=''}
  function refText(n){if(!n?.book_name)return 'General note';let r=`${n.book_name}${n.chapter?` ${n.chapter}`:''}`;if(n.verse_start)r+=`:${n.verse_start}${n.verse_end&&n.verse_end!==n.verse_start?`–${n.verse_end}`:''}`;return r}
  async function list(){
    if(!session()||!client())return show(`<header class="notes-top"><button data-notes-close>← Back</button><b>My Notes</b><span></span></header><section class="notes-panel"><div class="notes-empty">Sign in to use private cloud notes.</div></section>`);
    let q=client().from('bible_notes').select('id,book_code,book_name,chapter,verse_start,verse_end,title,body,tags,note_type,pinned,created_at,updated_at').eq('user_id',session().user.id).order('pinned',{ascending:false}).order('updated_at',{ascending:false}).limit(250);
    if(context.bookCode)q=q.eq('book_code',context.bookCode);if(context.chapter)q=q.eq('chapter',context.chapter);
    const {data,error:e}=await q;if(e){error=e.message;return renderList([])}renderList(data||[])
  }
  function renderList(rows){
    const filtered=Boolean(context.bookCode||context.chapter);
    show(`<header class="notes-top"><button data-notes-close>← BibleQuest</button><b>My Notes</b><button data-note-new>＋ New</button></header><section class="notes-panel"><div class="notes-hero"><small>PRIVATE CLOUD NOTEBOOK</small><h1>${filtered?`Notes for ${esc(context.bookName||'this passage')}${context.chapter?` ${context.chapter}`:''}`:'Your Bible notebook'}</h1><p>Questions, prayers, observations and study notes follow your account across devices.</p></div>${message?`<div class="notes-message">${esc(message)}</div>`:''}${error?`<div class="notes-message error">${esc(error)}</div>`:''}<div class="notes-actions">${filtered?'<button class="note-secondary" data-notes-all>Show all notes</button>':''}<button class="note-primary" data-note-new>${filtered?'Write on this chapter':'New note'}</button></div><div class="notes-private">🔒 Notes are private to your account. Congregation members and leaderboards cannot read note text.</div><div class="note-grid" style="margin-top:12px">${rows.map(n=>`<button class="note-card" data-note-edit="${n.id}"><div class="top"><b>${esc(n.title||refText(n))}</b>${n.pinned?'<span>📌</span>':''}</div><small>${esc(refText(n))} · ${esc(n.note_type)}</small><p>${esc(n.body||'No text yet')}</p><div>${(n.tags||[]).slice(0,6).map(t=>`<span class="note-tag">${esc(t)}</span>`).join('')}</div></button>`).join('')||'<div class="notes-empty">No notes here yet. Write the first one.</div>'}</div></section>`)
  }
  function editForm(n={}){current=n;const ctx={book_code:n.book_code??context.bookCode??'',book_name:n.book_name??context.bookName??'',chapter:n.chapter??context.chapter??'',verse_start:n.verse_start??'',verse_end:n.verse_end??'',title:n.title??'',body:n.body??'',tags:(n.tags||[]).join(', '),note_type:n.note_type||'study',pinned:Boolean(n.pinned)};show(`<header class="notes-top"><button data-notes-list>← Notes</button><b>${n.id?'Edit note':'New note'}</b><span>🔒</span></header><section class="notes-panel"><form class="note-form" data-note-form><div class="note-ref-grid"><label>Book<input name="book_name" value="${esc(ctx.book_name)}" placeholder="Genesis"></label><label>Chapter<input name="chapter" type="number" min="1" value="${esc(ctx.chapter)}"></label><label>Verse<input name="verse_start" type="number" min="1" value="${esc(ctx.verse_start)}" placeholder="1"></label></div><input type="hidden" name="book_code" value="${esc(ctx.book_code)}"><label>To verse (optional)<input name="verse_end" type="number" min="1" value="${esc(ctx.verse_end)}"></label><label>Note type<select name="note_type">${[['study','Study note'],['prayer','Prayer'],['question','Question'],['reflection','Reflection'],['sermon','Sermon note'],['other','Other']].map(([v,t])=>`<option value="${v}" ${ctx.note_type===v?'selected':''}>${t}</option>`).join('')}</select></label><label>Title<input name="title" maxlength="160" value="${esc(ctx.title)}" placeholder="What stood out?"></label><label>Your note<textarea name="body" maxlength="20000" placeholder="Write what you noticed, a question, a prayer, or something you want to remember…">${esc(ctx.body)}</textarea></label><label>Tags<input name="tags" value="${esc(ctx.tags)}" placeholder="faith, family, prayer"></label><label><span><input name="pinned" type="checkbox" ${ctx.pinned?'checked':''}> Pin this note</span></label><button class="note-primary">Save to my account</button>${n.id?'<button type="button" class="note-secondary" data-note-delete>Delete note</button>':''}<div class="notes-private">This note is stored in your private BibleQuest account and is not used as a leaderboard answer.</div></form></section>`)}
  async function save(form){const fd=new FormData(form),num=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?n:null},tags=String(fd.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,20);const row={user_id:session().user.id,book_code:String(fd.get('book_code')||'').trim()||null,book_name:String(fd.get('book_name')||'').trim()||null,chapter:num(fd.get('chapter')),verse_start:num(fd.get('verse_start')),verse_end:num(fd.get('verse_end')),note_type:String(fd.get('note_type')||'study'),title:String(fd.get('title')||'').trim().slice(0,160),body:String(fd.get('body')||'').trim().slice(0,20000),tags,pinned:fd.get('pinned')==='on',updated_at:new Date().toISOString()};if(!row.body&&!row.title)throw new Error('Write a title or note first.');let r;if(current?.id)r=await client().from('bible_notes').update(row).eq('id',current.id).eq('user_id',session().user.id);else r=await client().from('bible_notes').insert(row);if(r.error)throw r.error;await account()?.track?.('notes',current?.id?'updated':'created',{book_code:row.book_code,chapter:row.chapter,note_type:row.note_type});message='Note saved to your account.';error='';current=null;list()}
  async function remove(){if(!current?.id||!confirm('Delete this private note?'))return;const r=await client().from('bible_notes').delete().eq('id',current.id).eq('user_id',session().user.id);if(r.error)throw r.error;message='Note deleted.';current=null;list()}
  async function loadOne(id){const r=await client().from('bible_notes').select('*').eq('id',id).eq('user_id',session().user.id).single();if(r.error)throw r.error;editForm(r.data)}
  function bind(){const x=layer();x.querySelectorAll('[data-notes-close]').forEach(b=>b.onclick=close);x.querySelectorAll('[data-notes-list]').forEach(b=>b.onclick=()=>list());x.querySelectorAll('[data-note-new]').forEach(b=>b.onclick=()=>editForm());x.querySelectorAll('[data-notes-all]').forEach(b=>b.onclick=()=>{context={};list()});x.querySelectorAll('[data-note-edit]').forEach(b=>b.onclick=()=>loadOne(b.dataset.noteEdit).catch(e=>{error=e.message;list()}));x.querySelector('[data-note-form]')?.addEventListener('submit',async e=>{e.preventDefault();try{await save(e.currentTarget)}catch(err){error=err.message||String(err);editForm(current||{})}});x.querySelector('[data-note-delete]')?.addEventListener('click',()=>remove().catch(e=>{error=e.message;editForm(current||{})}))}
  function readerContext(){const root=document.querySelector('#bqReaderLayer:not(.hidden) .reader-chapter');if(!root)return null;const practice=root.querySelector('[data-reader-practice]');const title=root.querySelector('.reader-title-row h1')?.textContent?.trim()||'';const m=title.match(/^(.*)\s+(\d+)$/);return {bookCode:practice?.dataset.readerPractice||'',bookName:m?.[1]||'',chapter:Number(m?.[2])||null}}
  function injectReader(){const actions=document.querySelector('#bqReaderLayer:not(.hidden) .reader-study-actions');if(!actions||actions.querySelector('[data-reader-notes]'))return;const b=document.createElement('button');b.className='reader-secondary reader-note-btn';b.setAttribute('data-reader-notes','1');b.textContent='📝 Notes on this chapter';actions.appendChild(b);const source=document.querySelector('#bqReaderLayer:not(.hidden) .reader-source');if(source&&/Backend:\s*none/i.test(source.textContent||''))source.innerHTML='<b>Bible text:</b> Berean Standard Bible (BSB), public-domain/CC0 data. <b>Notes & progress:</b> private cloud sync when signed in.'}
  document.addEventListener('click',e=>{const btn=e.target.closest('[data-reader-notes]');if(btn){e.preventDefault();context=readerContext()||{};message='';error='';list()};const open=e.target.closest('[data-notes-open]');if(open){e.preventDefault();context={};message='';error='';list()}});
  new MutationObserver(injectReader).observe(document.documentElement,{childList:true,subtree:true});injectReader();
  window.BQNotes={open:(ctx={})=>{context=ctx;message='';error='';return list()},close};
})();