(() => {
  'use strict';
  let rows=[],layer=null,channel=null,queued=false;
  const account=()=>window.BQAccount,client=()=>account()?.client?.(),session=()=>account()?.session?.();
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
  const icon=t=>({assignment:'📮',feedback:'💬',devotional:'📖',announcement:'📣',activity:'🧭',encouragement:'💛',poll:'📊',award:'🏅',media:'🎬',info:'🔔'})[t]||'🔔';
  function ensure(){if(layer)return layer;layer=document.createElement('div');layer.id='bqNotificationLayer';layer.className='notification-layer hidden';document.body.appendChild(layer);return layer}
  function close(){ensure().classList.add('hidden');document.body.classList.remove('notification-open')}
  function ago(iso){const m=Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/60000));return m<1?'now':m<60?`${m}m`:m<1440?`${Math.floor(m/60)}h`:`${Math.floor(m/1440)}d`}
  async function load(){const c=client(),s=session();if(!c||!s){rows=[];renderBadge();return}const r=await c.from('bible_notifications').select('*').eq('user_id',s.user.id).or(`expires_at.is.null,expires_at.gt.${new Date().toISOString()}`).order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;rows=r.data||[];renderBadge();subscribe()}
  function unread(){return rows.filter(x=>!x.read_at).length}
  function inject(){const host=document.querySelector('.top-actions');if(!host||host.querySelector('[data-notifications-open]')||!session()?.user)return;const b=document.createElement('button');b.type='button';b.className='notification-button';b.dataset.notificationsOpen='1';b.innerHTML='<span>🔔</span><i data-notification-count hidden></i>';b.title='BibleQuest inbox';b.onclick=open;host.prepend(b);renderBadge()}
  function renderBadge(){inject();const n=unread();document.querySelectorAll('[data-notification-count]').forEach(x=>{x.hidden=!n;x.textContent=n>99?'99+':String(n)});window.dispatchEvent(new CustomEvent('bq-notification-change',{detail:{unread:n}}))}
  function card(x){return `<button type="button" class="notification-item ${x.read_at?'':'unread'}" data-notification-id="${x.id}" data-kind="${esc(x.action_kind||'')}"><span>${icon(x.notification_type)}</span><div><b>${esc(x.title)}</b>${x.body?`<p>${esc(x.body)}</p>`:''}<small>${ago(x.created_at)} · ${esc(x.notification_type)}</small></div>${x.read_at?'':'<i></i>'}</button>`}
  function render(){const x=ensure();x.innerHTML=`<main class="notification-app"><header><button data-notifications-close>← BibleQuest</button><div><small>YOUR CONGREGATION</small><b>Inbox</b></div><button data-notifications-read-all ${unread()?'':'disabled'}>Mark all read</button></header><section class="notification-list">${rows.length?rows.map(card).join(''):'<div class="notification-empty"><span>🌱</span><b>No notifications yet.</b><p>Assignments, leader feedback, devotionals, polls, handpicked media and recognition will appear here.</p></div>'}</section></main>`;x.classList.remove('hidden');document.body.classList.add('notification-open');x.querySelector('[data-notifications-close]').onclick=close;x.querySelector('[data-notifications-read-all]').onclick=markAll;x.querySelectorAll('[data-notification-id]').forEach(b=>b.onclick=()=>activate(b.dataset.notificationId,b.dataset.kind))}
  async function mark(id){const c=client(),row=rows.find(x=>x.id===id);if(!c||!row||row.read_at)return;const now=new Date().toISOString(),r=await c.from('bible_notifications').update({read_at:now}).eq('id',id);if(!r.error){row.read_at=now;renderBadge()}}
  async function markAll(){const c=client(),s=session();if(!c||!s)return;const now=new Date().toISOString(),r=await c.from('bible_notifications').update({read_at:now}).eq('user_id',s.user.id).is('read_at',null);if(r.error)return;rows.forEach(x=>x.read_at=x.read_at||now);render()}
  async function activate(id,kind){await mark(id);close();if(kind==='assignment')window.BQAssignments?.open?.();else if(kind==='ministry')window.BQMinistry?.open?.();else if(kind==='recognition')window.BQRecognition?.open?.()||window.BQMinistry?.open?.();else if(kind==='media')window.BQMediaLibrary?.open?.();else window.BQMinistry?.open?.()}
  async function open(){try{await load();render()}catch(e){const x=ensure();x.innerHTML=`<main class="notification-app"><header><button data-notifications-close>← BibleQuest</button><b>Inbox unavailable</b></header><div class="notification-empty"><p>${esc(e.message||String(e))}</p></div></main>`;x.classList.remove('hidden');x.querySelector('[data-notifications-close]').onclick=close}}
  function subscribe(){const c=client(),s=session();if(!c||!s)return;if(channel)c.removeChannel(channel);channel=c.channel(`bq-notify-${s.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'bible_notifications',filter:`user_id=eq.${s.user.id}`},()=>load().catch(()=>{})).subscribe()}
  function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;inject()})}
  new MutationObserver(schedule).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});window.addEventListener('bq-account-created',()=>setTimeout(()=>load().catch(()=>{}),500));setTimeout(()=>load().catch(()=>{}),1400);window.BQNotifications={open,refresh:load,unread};
})();