(() => {
  let online=[],feed=[],channel=null,timer=null,booted=false,currentCid='',renderQueued=false;
  const account=()=>window.BQAccount,client=()=>account()?.client?.(),session=()=>account()?.session?.();
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function cloud(){try{return JSON.parse(localStorage.getItem('biblequest_cloud_v1')||'{}')}catch{return {}}}
  const congregationId=()=>cloud().activeCongregationId||'';
  const invisibleKey=()=>`biblequest_invisible_${session()?.user?.id||'guest'}`;
  const invisible=()=>localStorage.getItem(invisibleKey())==='1';
  function layer(){let x=document.getElementById('bqPresenceLayer');if(!x){x=document.createElement('div');x.id='bqPresenceLayer';x.className='completion-layer hidden';document.body.appendChild(x)}return x}
  function close(){layer().classList.add('hidden');document.body.classList.remove('completion-open')}
  async function heartbeat(){const c=client(),s=session(),cid=congregationId();if(!c||!s||!cid||invisible())return;await c.from('bible_presence').upsert({congregation_id:cid,user_id:s.user.id,last_seen_at:new Date().toISOString(),surface:document.querySelector('.reader-layer:not(.hidden)')?'Bible Reader':document.querySelector('.completion-layer:not(.hidden)')?'Study tools':'BibleQuest'},{onConflict:'congregation_id,user_id'});await refresh()}
  async function setInvisible(value){localStorage.setItem(invisibleKey(),value?'1':'0');if(value&&client()&&session()&&congregationId())await client().from('bible_presence').delete().eq('congregation_id',congregationId()).eq('user_id',session().user.id);else await heartbeat();await refresh();scheduleStrip();if(!layer().classList.contains('hidden'))render()}
  async function refresh(){const c=client(),cid=congregationId();if(!c||!cid){online=[];feed=[];scheduleStrip();return}const cutoff=new Date(Date.now()-120000).toISOString();const p=await c.from('bible_presence').select('user_id,last_seen_at,surface').eq('congregation_id',cid).gte('last_seen_at',cutoff).order('last_seen_at',{ascending:false});if(p.error)return;const ids=(p.data||[]).map(x=>x.user_id);let members=[];if(ids.length){const m=await c.from('bible_congregation_members').select('user_id,display_name,avatar,role').eq('congregation_id',cid).in('user_id',ids);members=m.data||[]}const by=new Map(members.map(x=>[x.user_id,x]));online=(p.data||[]).map(x=>({...x,...(by.get(x.user_id)||{})}));const f=await c.from('bible_score_events').select('user_id,category,points,source,created_at').eq('congregation_id',cid).order('created_at',{ascending:false}).limit(15);if(!f.error){const fids=[...new Set((f.data||[]).map(x=>x.user_id))],need=fids.filter(id=>!by.has(id));if(need.length){const m=await c.from('bible_congregation_members').select('user_id,display_name,avatar').eq('congregation_id',cid).in('user_id',need);(m.data||[]).forEach(x=>by.set(x.user_id,x))}feed=(f.data||[]).map(x=>({...x,...(by.get(x.user_id)||{})}))}scheduleStrip();window.dispatchEvent(new CustomEvent('bq-presence-change'))}
  function avatar(row){return window.BQAvatar?.glyph?.(row.avatar)||'🙂'}
  function scheduleStrip(){if(renderQueued)return;renderQueued=true;queueMicrotask(()=>{renderQueued=false;renderStrip()})}
  function renderStrip(){const home=document.querySelector('.modern-home');if(!home)return;let strip=home.querySelector('[data-presence-strip]');if(!account()?.status?.().signedIn||!congregationId()||!online.length){strip?.remove();return}if(!strip){strip=document.createElement('button');strip.dataset.presenceStrip='1';strip.className='presence-strip';strip.onclick=open;const focus=home.querySelector('.modern-focus');focus?.after(strip)}const next=`<span class="presence-pulse"></span><div class="presence-faces">${online.slice(0,4).map(x=>`<i>${avatar(x)}</i>`).join('')}</div><b>${online.length} online</b><small>${online.length>4?`+${online.length-4} more · `:''}Community Live</small><em>›</em>`;if(strip.innerHTML!==next)strip.innerHTML=next}
  function render(){const signed=account()?.status?.().signedIn,cid=congregationId();const body=!signed?`<div class="completion-empty"><span>🔐</span><b>Sign in to see Community Live.</b><p>Online status is available only inside your congregation.</p></div>`:!cid?`<div class="completion-empty"><span>⛪</span><b>Join a congregation first.</b><p>Your online circle is scoped to your active congregation.</p></div>`:`<section class="presence-controls"><div><b>${invisible()?'You are invisible':'You appear online'}</b><small>Online expires automatically after about 2 minutes without a heartbeat.</small></div><button class="secondary" data-presence-toggle>${invisible()?'Appear online':'Go invisible'}</button></section><div class="completion-section"><h2>Online now</h2><small>${online.length}</small></div><section class="presence-grid">${online.length?online.map(x=>`<article><span>${avatar(x)}</span><div><b>${esc(x.display_name||'Member')}</b><small>${esc(x.surface||'BibleQuest')} · ${esc(x.role||'member')}</small></div><i></i></article>`).join(''):'<div class="completion-empty"><span>🌙</span><b>No one else is showing online.</b><p>Presence is intentionally temporary, not permanent tracking.</p></div>'}</section><div class="completion-section"><h2>Recent congregation activity</h2><small>public score events only</small></div><section class="presence-feed">${feed.length?feed.map(x=>`<article><span>${avatar(x)}</span><div><b>${esc(x.display_name||'Member')}</b><p>${esc(x.source||x.category)} · +${Number(x.points)||0} pts</p></div><small>${new Date(x.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></article>`).join(''):'<p class="muted">No recent scored activity yet.</p>'}</section><div class="privacy-note"><b>Presence privacy</b><p>Only congregation members can see this. BibleQuest shares preferred name, avatar, current app surface and a short-lived heartbeat—not email, full name, private notes or exact device location.</p></div>`;const x=layer();x.innerHTML=`<main class="completion-shell presence-shell"><header class="completion-top"><button data-presence-close>← BibleQuest</button><b>Community Live</b><span>🟢</span></header><section class="completion-hero presence-hero"><small>WHO'S AROUND</small><h1>Study feels warmer when the room feels alive.</h1><p>See who is currently active and celebrate recent learning without exposing private study content.</p></section>${body}</main>`;x.classList.remove('hidden');document.body.classList.add('completion-open');x.querySelectorAll('[data-presence-close]').forEach(b=>b.onclick=close);x.querySelector('[data-presence-toggle]')?.addEventListener('click',()=>setInvisible(!invisible()).catch(()=>{}));x.scrollTop=0}
  async function open(){await refresh().catch(()=>{});render()}
  function subscribe(){const c=client(),cid=congregationId();if(!c||!cid)return;if(channel&&currentCid===cid)return;if(channel)c.removeChannel(channel);currentCid=cid;channel=c.channel(`bq-presence-db-${cid}`).on('postgres_changes',{event:'*',schema:'public',table:'bible_presence',filter:`congregation_id=eq.${cid}`},()=>refresh().catch(()=>{})).subscribe()}
  async function ready(){if(!account()?.status?.().signedIn||!client()||!congregationId()){online=[];feed=[];scheduleStrip();return}subscribe();if(!invisible())await heartbeat().catch(()=>{});await refresh().catch(()=>{});clearInterval(timer);timer=setInterval(()=>heartbeat().catch(()=>{}),45000)}
  function boot(){if(booted)return;booted=true;setTimeout(ready,1400);window.addEventListener('bq-cloud-board-change',ready);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')ready()});const app=document.getElementById('app');if(app){const obs=new MutationObserver(scheduleStrip);obs.observe(app,{childList:true})}}
  window.BQPresence={open,count:()=>online.length,refresh,setInvisible};boot();
})();
