(()=>{'use strict';
const root=document.getElementById('psychApp');
if(!root)return;
const STORE='biblequest_psychometrics_v1';
const getState=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}};
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]||m));
const LEVEL=m=>m>=3.5?'high':m<2.5?'low':'mid';
const GENERIC={high:'This tendency showed up strongly in your answers.',mid:'Your answers were mixed or moderate, so context may matter more than a single label.',low:'This tendency showed up less strongly in your answers.',prompt:'Notice where this pattern helps you, where it costs you, and what situations make it stronger or weaker.'};
const I={
'Neuroticism / Emotional Reactivity':{high:'You reported stronger sensitivity to worry, frustration, discouragement and pressure. This often means emotions register quickly and intensely.',mid:'Your emotional reactivity appears mixed: some situations may affect you strongly while others do not.',low:'You reported relatively steady emotional responses and lower stress reactivity.',prompt:'Which situations reliably raise your emotional intensity? What do you do in the first five minutes after that happens?'},
'Extraversion':{high:'You tend to gain energy from interaction, activity and outward engagement.',mid:'You appear able to use both social engagement and solitude depending on the situation.',low:'You tend to prefer lower stimulation, selective interaction or more time alone.',prompt:'When does your social style help connection, and when does it become over-talking, withdrawal, avoidance or fatigue?'},
'Openness to Experience':{high:'You tend to be drawn to ideas, imagination, novelty, complexity and new perspectives.',mid:'You show a mix of curiosity and preference for the familiar.',low:'You tend to prefer concrete, familiar and established approaches.',prompt:'Where does your openness level help good judgment, and where might it become novelty-seeking or resistance to new evidence?'},
'Agreeableness':{high:'You tend to prioritize cooperation, trust, sympathy and interpersonal harmony.',mid:'You appear to balance cooperation with directness depending on context.',low:'You tend to be more skeptical, competitive or direct and less motivated by harmony alone.',prompt:'Do you more often avoid necessary conflict, or create unnecessary conflict? What evidence do you have?'},
'Conscientiousness':{high:'You tend to plan, organize, persist and regulate behavior toward goals.',mid:'Your structure and follow-through appear context-dependent.',low:'You tend to prefer flexibility and spontaneity and may use less structure or advance planning.',prompt:'Where does structure help you, and where does it become rigidity? Where does flexibility help you, and where does it become avoidable disorder?'},
'Anxiety':{high:'You tend to anticipate possible problems and experience worry readily.',mid:'Worry seems situational rather than consistently high or low.',low:'You tend to experience less anticipatory worry.',prompt:'Does worry usually improve your preparation, or mostly consume attention after useful planning is already done?'},
'Anger':{high:'Irritation and anger may activate quickly when something feels wrong, blocked or unfair.',mid:'Your anger response appears situational.',low:'You are less likely to become irritated or angry quickly.',prompt:'What usually sits underneath your anger: threat, disrespect, injustice, loss of control, fatigue, or something else?'},
'Depression':{high:'You endorsed more items involving sadness, discouragement or negative self-evaluation. This is a personality-facet result, not a clinical diagnosis.',mid:'Your answers show some but not consistently strong low-mood tendencies.',low:'You endorsed fewer low-mood and self-critical items on this facet.',prompt:'When discouraged, what thoughts repeat? How long do they last, and what reliably helps or worsens them?'},
'Self-Consciousness':{high:'You may be highly aware of how others see you and more uncomfortable when you feel evaluated.',mid:'Concern about social evaluation appears context-dependent.',low:'You tend to feel less inhibited by social evaluation.',prompt:'How often do you change, delay or silence a useful action mainly because you imagine how you will be judged?'},
'Immoderation':{high:'Strong urges or immediate rewards may sometimes compete strongly with long-term goals.',mid:'Impulse control appears mixed by situation or type of temptation.',low:'You report relatively strong restraint around urges and appetites.',prompt:'Which urges are hardest to interrupt, and what conditions make self-control easier before the urge becomes intense?'},
'Vulnerability':{high:'Under heavy pressure you may feel overwhelmed or less able to think and act effectively.',mid:'Your ability to stay effective under pressure varies by situation.',low:'You tend to remain comparatively steady and functional under stress.',prompt:'What are your earliest signs of overload, and what support or structure works best before you reach that point?'},
'Friendliness':{high:'You tend to approach people warmly and form connections relatively easily.',mid:'Your interpersonal warmth depends on context and familiarity.',low:'You tend to be more reserved or selective about closeness.',prompt:'Does your style create the relationships you actually want, or are there people you unintentionally overwhelm or keep too distant?'},
'Gregariousness':{high:'You tend to enjoy groups, crowds and frequent social contact.',mid:'You can enjoy groups but do not consistently seek them.',low:'You tend to prefer smaller groups, solitude or less frequent social stimulation.',prompt:'Are you using people or solitude to recharge, or sometimes using either one to avoid something uncomfortable?'},
'Assertiveness':{high:'You tend to speak up, take charge and influence direction.',mid:'You can lead or follow depending on the context.',low:'You may be less inclined to take charge or state your position forcefully.',prompt:'When should you speak sooner? When should you listen longer before directing the situation?'},
'Activity Level':{high:'You tend to maintain a fast pace and stay busy.',mid:'Your preferred pace varies by demand and interest.',low:'You tend to prefer a slower or less continuously active pace.',prompt:'Is your pace helping important work, or is it creating busyness, procrastination, fatigue or missed priorities?'},
'Excitement-Seeking':{high:'You are more drawn to stimulation, intensity, novelty and risk.',mid:'You enjoy some stimulation without consistently seeking it.',low:'You generally prefer lower-risk, lower-intensity situations.',prompt:'When does your risk preference create growth, and when does it create avoidable danger or missed opportunities?'},
'Cheerfulness':{high:'Positive emotion and visible enthusiasm appear relatively accessible to you.',mid:'Your positive affect varies by context.',low:'You may experience or display less frequent high-energy positive emotion.',prompt:'Do you use positivity to connect honestly, or sometimes to cover discomfort? If lower, do others mistake quietness for negativity?'},
'Imagination':{high:'You tend to generate vivid possibilities, mental images and internal scenarios.',mid:'You use imagination but remain fairly grounded in the concrete.',low:'You tend to focus more on concrete reality than fantasy or imagined possibilities.',prompt:'When does imagination produce useful options, and when does it drift into distraction, overthinking or unrealistic expectations?'},
'Artistic Interests':{high:'You tend to notice and value art, beauty and aesthetic experience.',mid:'Aesthetic interest is present but not dominant.',low:'Artistic or aesthetic experience is less central to your attention.',prompt:'What kinds of beauty or expression actually move you, and what does that reveal about what you value?'},
'Emotionality':{high:'You tend to notice and experience emotions strongly, including other people’s emotions.',mid:'Emotional awareness and intensity are mixed.',low:'You may experience emotions less intensely or give them less attention.',prompt:'Do you treat feelings as useful information, commands, noise, or something to hide? Which approach causes problems for you?'},
'Adventurousness':{high:'You tend to prefer variety and change over routine and familiarity.',mid:'You balance novelty with familiarity.',low:'You tend to prefer predictable, familiar and established ways of doing things.',prompt:'Are you changing because change is useful, or because routine feels boring? Are you staying because it is wise, or because change feels threatening?'},
'Intellect':{high:'You tend to enjoy abstract ideas, difficult material and theoretical discussion.',mid:'You can engage abstract ideas but do not always seek them.',low:'You tend to prefer concrete and practical information over abstraction.',prompt:'Does your thinking style lead to clearer action, or do you sometimes over-intellectualize or dismiss useful complexity?'},
'Liberalism / Values Openness':{high:'This historical IPIP facet suggests greater willingness to question conventional values in its item set.',mid:'Your answers to this historical values-openness facet were mixed.',low:'This historical IPIP facet suggests greater preference for conventional or established values in its item set.',prompt:'Treat this score cautiously: the items mix political and moral-content wording, so use it as a clue about openness to convention—not as a verdict on politics, theology or character.'},
'Trust':{high:'You tend to assume good intentions and accept other people’s words more readily.',mid:'Your trust varies by person and evidence.',low:'You tend to be cautious, skeptical or slow to trust.',prompt:'Where has your trust level protected relationships, and where has it led to naivety, cynicism or isolation?'},
'Morality / Straightforwardness':{high:'You report low willingness to manipulate, cheat or exploit others for advantage.',mid:'Your answers are mixed on directness versus self-serving tactics.',low:'Your answers suggest greater willingness to use indirect or self-serving tactics in some situations.',prompt:'Which situations tempt you to hide motives, shade the truth or manage impressions rather than communicate directly?'},
'Altruism':{high:'You tend to notice others’ needs and enjoy helping.',mid:'Helping behavior appears selective or context-dependent.',low:'You are less naturally drawn toward helping or giving time to others.',prompt:'Do you help in ways people actually need, or in ways that mainly make you feel useful? If lower, what keeps you from engaging?'},
'Cooperation':{high:'You tend to avoid hostility, retaliation and unnecessary conflict.',mid:'Your conflict style varies by context.',low:'You may be more willing to argue, confront or retaliate.',prompt:'When does cooperation become avoidance? When does confrontation become aggression rather than useful honesty?'},
'Modesty':{high:'You are less inclined toward self-promotion or claims of superiority.',mid:'Your self-presentation varies by context.',low:'You may be more comfortable emphasizing your strengths, status or achievements.',prompt:'Can you describe strengths accurately without exaggerating or shrinking them? What do you want other people to think of you?'},
'Sympathy':{high:'You tend to feel concern for people who are suffering or disadvantaged.',mid:'Your sympathetic response varies by situation.',low:'You may be less emotionally affected by other people’s difficulties.',prompt:'Does empathy lead to effective help and good boundaries, or to over-involvement, detachment or judgment?'},
'Self-Efficacy':{high:'You tend to expect that you can handle tasks successfully and make things happen.',mid:'Your confidence in execution depends on the task.',low:'You may doubt your ability to handle tasks or produce results.',prompt:'Is your confidence based on evidence and learning, or on overconfidence or underestimation of your actual ability?'},
'Orderliness':{high:'You prefer organization, tidiness and predictable placement of things.',mid:'You use some organization without needing strong order everywhere.',low:'You tolerate more disorder and may use fewer systems for organizing things.',prompt:'Which systems genuinely reduce friction, and which standards of order cost more time or stress than they are worth?'},
'Dutifulness':{high:'You strongly value keeping promises, rules and commitments.',mid:'Your commitment to rules and promises is context-sensitive.',low:'You may be more flexible about rules or commitments when circumstances change.',prompt:'Which commitments deserve firmness, and where might duty become rigidity—or flexibility become unreliability?'},
'Achievement-Striving':{high:'You tend to work hard, set demanding standards and pursue accomplishment.',mid:'Your drive varies by meaning, interest or context.',low:'You may place less emphasis on achievement, extra effort or competitive accomplishment.',prompt:'What are you trying to prove through achievement—or avoid through under-engagement? Which goals are actually worth the effort?'},
'Self-Discipline':{high:'You tend to start and follow through on planned tasks even when motivation drops.',mid:'Follow-through varies by task and context.',low:'Starting, sustaining or completing planned tasks may be more difficult.',prompt:'Which part fails most often: starting, resisting distraction, continuing when bored, or finishing? Design around that specific failure point.'},
'Cautiousness':{high:'You tend to think through consequences before acting.',mid:'Your deliberation varies by situation.',low:'You tend to decide and act more quickly with less advance deliberation.',prompt:'When does caution improve judgment, and when does it become delay? When does speed help, and when does it create preventable mistakes?'},
'Appreciation of Beauty':{high:'Beauty and excellence tend to capture your attention strongly.',mid:'You notice beauty but it is not consistently central.',low:'Aesthetic experience is less prominent in your attention.',prompt:'What reliably evokes awe or appreciation in you, and how does that affect your attention, gratitude or priorities?'},
'Capacity for Love':{high:'You report being able to give and receive close affection relatively easily.',mid:'Your comfort with closeness varies by relationship.',low:'Giving, receiving or trusting close affection may be more difficult.',prompt:'What happens when someone gets emotionally close—openness, fear, control, withdrawal, overdependence, or something else?'},
'Teamwork':{high:'You tend to identify with groups, contribute to shared goals and support teammates.',mid:'You can work collaboratively but also value independence.',low:'You may prefer autonomy and find group dependence less comfortable.',prompt:'In groups, do you over-function, under-participate, dominate, disappear, or contribute proportionately?'},
'Curiosity':{high:'You are drawn toward questions, exploration and varied interests.',mid:'Curiosity is selective.',low:'You tend to have a narrower set of interests or less drive to explore unfamiliar topics.',prompt:'Which questions are worth pursuing deeply, and which ones are only novelty that keeps you from finishing what matters?'},
'Fairness':{high:'You strongly value equal treatment and consistent rights or standards.',mid:'Your fairness judgments appear context-sensitive.',low:'You may apply standards more selectively based on relationships or preferences.',prompt:'Would you judge the same behavior the same way if the person, group or role were reversed?'},
'Forgiveness / Mercy':{high:'You tend to release grudges and allow people another chance.',mid:'Forgiveness varies with the offense and relationship.',low:'You may hold hurt or resentment longer and find fresh starts harder.',prompt:'Can you distinguish forgiveness, reconciliation, restored trust and removal of consequences instead of treating them as the same thing?'},
'Gratitude':{high:'You readily notice benefits and feel or express appreciation.',mid:'Gratitude varies with circumstances.',low:'You may notice what is missing more readily than what has been received.',prompt:'What do you repeatedly take for granted? What genuine good is present even while a problem remains real?'},
'Hope / Optimism':{high:'You tend to expect workable possibilities and positive outcomes.',mid:'Your expectations are mixed or context-dependent.',low:'You may expect problems or negative outcomes more readily.',prompt:'Is your expectation evidence-based? What is the realistic best case, worst case and most likely case?'},
'Humor / Playfulness':{high:'You tend to use humor and play to lighten situations and connect with people.',mid:'Humor is present but not a dominant style.',low:'You may use less humor or playfulness in daily interaction.',prompt:'Does humor create connection, or sometimes avoid seriousness, vulnerability or accountability?'},
'Perseverance':{high:'You tend to keep working despite obstacles and finish what you start.',mid:'Persistence depends on the goal and context.',low:'You may disengage more quickly when progress becomes difficult.',prompt:'Are you persisting because the goal still matters, or because stopping feels like failure? When is adaptation wiser than persistence?'},
'Integrity / Honesty':{high:'You strongly endorse truthfulness, promise-keeping and trustworthiness.',mid:'Your honesty behavior may be more context-sensitive.',low:'Your answers suggest more willingness to bend truth or loyalty under pressure.',prompt:'What kind of cost most tempts you to become less honest: conflict, embarrassment, money, convenience or protecting your image?'},
'Judgment / Open-Mindedness':{high:'You tend to compare alternatives and think through different possibilities.',mid:'Deliberation and openness vary by context.',low:'You may decide with less comparison of alternatives or contradictory evidence.',prompt:'What evidence would genuinely change your mind? If the answer is “nothing,” what does that tell you?'},
'Kindness / Generosity':{high:'You tend to make time to help, encourage and support other people.',mid:'Kindness is selective or depends on capacity.',low:'You may be less inclined to spend time or energy helping others.',prompt:'Are you kind with good boundaries, or do you over-give, rescue, withdraw, or help selectively based on reciprocity?'},
'Leadership':{high:'You tend to coordinate people, take responsibility and influence group direction.',mid:'You lead in some settings and prefer support roles in others.',low:'You may be less comfortable directing groups or taking charge.',prompt:'Do people become more capable around your leadership, or more dependent, cautious or unheard?'},
'Love of Learning':{high:'You enjoy acquiring knowledge and learning for its own sake.',mid:'Learning interest depends on relevance and topic.',low:'You are less motivated by learning that is not immediately practical or required.',prompt:'Is learning changing how you think and act, or becoming collection without application?'},
'Modesty / Humility':{high:'You tend not to seek attention or emphasize your own accomplishments.',mid:'Your visibility and self-promotion vary by context.',low:'You may be more comfortable standing out and talking about achievements.',prompt:'Can you be accurately visible without needing admiration, and accurately humble without hiding useful competence?'},
'Originality / Creativity':{high:'You tend to generate unusual ideas and new approaches.',mid:'You combine established methods with occasional novelty.',low:'You tend to prefer proven methods over creating new ones.',prompt:'How often do your new ideas become tested, useful improvements rather than interesting possibilities?'},
'Perspective / Wisdom':{high:'You see yourself as able to identify what matters and offer useful perspective.',mid:'Perspective varies with domain and experience.',low:'You may feel less confident identifying the larger pattern or advising others.',prompt:'Whose feedback tests whether your “wisdom” is actually useful, accurate and humble?'},
'Prudence':{high:'You tend to think about consequences and avoid unnecessary risk.',mid:'Your caution varies by situation.',low:'You may be more comfortable acting before all consequences are known.',prompt:'What is the cost of waiting, and what is the cost of acting now? Which risk are you actually choosing?'},
'Self-Regulation / Self-Control':{high:'You report relatively strong control over urges and short-term temptations.',mid:'Self-control varies by domain and situation.',low:'Immediate urges may more often override longer-term intentions.',prompt:'Which environments, times, emotions or cues predict loss of control? Change those conditions before relying on willpower.'},
'Social / Emotional Intelligence':{high:'You tend to read social cues and other people’s emotions with confidence.',mid:'Your social reading is stronger in some contexts than others.',low:'You may find unfamiliar social situations or predicting reactions more difficult.',prompt:'How often do you verify your interpretation by asking rather than assuming you know what another person feels or means?'},
'Spirituality / Religiousness':{high:'You strongly endorsed items about spiritual identity, purpose and belief in God.',mid:'Your responses to the scale were mixed.',low:'You endorsed fewer of the scale’s spirituality/religiousness items.',prompt:'Treat this strictly as the questionnaire’s psychological construct. It does not measure doctrine, depth of faith, obedience or spiritual maturity.'},
'Bravery / Courage':{high:'You report willingness to take stands despite opposition or possible negative consequences.',mid:'Your willingness to confront risk varies by context.',low:'You may be more reluctant to speak or act when opposition is likely.',prompt:'Which risks are worth taking because something important is at stake, and which risks are unnecessary?'},
'Zest / Vitality':{high:'You tend to approach daily life with energy and enthusiasm.',mid:'Energy and enthusiasm vary by context.',low:'You may experience lower energy or less anticipation about daily activities.',prompt:'Is your energy pattern mainly personality, sleep/health, workload, meaning, stress, or environment? What evidence separates these possibilities?'}
};
function addStyles(){if(document.getElementById('psyInsightStyles'))return;const s=document.createElement('style');s.id='psyInsightStyles';s.textContent=`.psy-result-order{margin:0 0 14px;padding:14px 16px;border-radius:16px;background:#eef3ed;border:1px solid #d5ddd4;color:#4f5e55;line-height:1.5}.psy-result-order b{display:block;color:#263128;margin-bottom:4px}.psy-interpret-wrap{margin-top:22px}.psy-insight-list{display:grid;gap:10px}.psy-insight-item{background:#fff;border:1px solid #dfddd5;border-radius:16px;overflow:hidden}.psy-insight-item>summary{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 16px;cursor:pointer;font-weight:850;list-style:none}.psy-insight-item>summary::-webkit-details-marker{display:none}.psy-insight-item>summary span{min-width:0}.psy-insight-score{white-space:nowrap;font-size:12px;color:#617067}.psy-insight-body{border-top:1px solid #eceae4;padding:14px 16px;color:#56645c;line-height:1.55}.psy-insight-body p{margin:0 0 10px}.psy-insight-body b{color:#263128}.psy-selfq{background:#f2f5f1;border-radius:11px;padding:10px 12px}.psy-insight-item .psy-bible{margin-top:12px}.psy-insight-item .psy-bible summary:before{content:'📖 '}.psy-insight-item .psy-bible summary{color:#59685f}.psy-raw-data{margin-top:16px;background:#fff;border:1px dashed #cfd5ce;border-radius:16px;padding:12px 14px}.psy-raw-data summary{cursor:pointer;font-weight:850}.psy-raw-data pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:320px;overflow:auto;padding:10px;background:#f5f5f1;border-radius:10px;font-size:11px}.psy-raw-data button{min-height:42px;border:1px solid #cad0ca;border-radius:11px;padding:9px 12px;background:#fff;font-weight:800}.psy-purpose small{display:none!important}`;document.head.appendChild(s)}
function rewritePurpose(){const h=root.querySelector('.psy-main h1')?.textContent?.trim();if(h==='Choose the depth you need.'){const p=root.querySelector('.psy-purpose');if(p){p.innerHTML='<b>Use this for self-realization</b><p>Answer honestly, see the scored result first, then use the interpretation to notice patterns you may have normalized or overlooked. The goal is clearer self-awareness: strengths, blind spots, triggers, habits and recurring tendencies.</p><p>Scripture appears only after the psychological interpretation as an optional Christian reflection lens. It is not part of the psychometric score.</p>'}}}
function pageType(){const h=root.querySelector('.psy-main h1')?.textContent?.trim();if(h==='Your deep personality profile')return'neo';if(h==='Your character-strengths profile')return'via';if(h==='Your self-esteem score')return'rse';return''}
function scoreFrom(card){const v=Number(card.querySelector('.psy-meter b')?.textContent?.trim());return Number.isFinite(v)?v:null}
function bandFrom(card,score){const t=card.textContent||'';if(/Higher expression/i.test(t))return'high';if(/Lower expression/i.test(t))return'low';if(/Midrange|mixed/i.test(t))return'mid';return score==null?'mid':LEVEL(score)}
function rawPayload(type){const s=getState();if(type==='neo')return {instrument:'IPIP-NEO-120',scoredAt:s.neo?.result?.date||null,domains:s.neo?.result?.domains||{},facets:s.neo?.result?.facets||{},itemResponses:s.neo?.answers||{}};if(type==='via')return {instrument:'IPIP-VIA-R',scoredAt:s.via?.result?.date||null,scores:s.via?.result?.scores||{},itemResponses:s.via?.answers||{}};if(type==='rse')return {instrument:'Rosenberg Self-Esteem Scale',scoredAt:s.rse?.result?.date||null,total:s.rse?.result?.score??null,itemResponses:s.rse?.answers||{}};return {}}
function normalizeBible(d){if(!d)return null;d.open=false;const sm=d.querySelector('summary');if(sm)sm.textContent='Scripture reflection (optional)';const body=d.querySelector('.psy-bible-body');if(body){body.querySelectorAll('p').forEach(p=>{const txt=p.textContent||'';if(/^Direction:/i.test(txt))p.innerHTML='<b>Christian lens:</b>'+p.innerHTML.replace(/^<b>Direction:<\/b>/i,'');if(/^Practice:/i.test(txt))p.innerHTML='<b>Possible practice:</b>'+p.innerHTML.replace(/^<b>Practice:<\/b>/i,'')});body.querySelectorAll('.psy-bible-refs').forEach(p=>{if(/^Scripture:/i.test(p.textContent||''))p.textContent=(p.textContent||'').replace(/^Scripture:/i,'Scripture references:')})}return d}
function insightFor(title,level){const d=I[title]||GENERIC;return level==='high'?d.high||GENERIC.high:level==='low'?d.low||GENERIC.low:d.mid||GENERIC.mid}
function buildInterpretation(type,cards){const wrap=document.createElement('section');wrap.className='psy-interpret-wrap';wrap.dataset.psyInsight='1';wrap.innerHTML='<div class="psy-section">Interpretation & self-reflection</div><div class="psy-result-order"><b>Now interpret the numbers</b>The score above is the measurement. The notes below are prompts for noticing how the tendency appears in real life. They are not diagnoses, moral grades or fixed identity labels.</div><div class="psy-insight-list"></div>';const list=wrap.querySelector('.psy-insight-list');cards.forEach(card=>{const title=card.querySelector('h3')?.textContent?.trim();if(!title)return;const score=scoreFrom(card),level=bandFrom(card,score),old=normalizeBible(card.querySelector('details.psy-bible'));if(old)old.remove();const item=document.createElement('details');item.className='psy-insight-item';const scoreLabel=score==null?'':`${score.toFixed(2)} / 5`;item.innerHTML=`<summary><span>${esc(title)}</span><b class="psy-insight-score">${esc(scoreLabel)}</b></summary><div class="psy-insight-body"><p><b>What this may mean:</b> ${esc(insightFor(title,level))}</p><p class="psy-selfq"><b>Useful self-check:</b> ${esc((I[title]||GENERIC).prompt||GENERIC.prompt)}</p></div>`;if(old)item.querySelector('.psy-insight-body').appendChild(old);list.appendChild(item)});return wrap}
function buildRseInterpretation(panel){const s=getState(),score=Number(s.rse?.result?.score);const wrap=document.createElement('section');wrap.className='psy-interpret-wrap';wrap.dataset.psyInsight='1';const old=normalizeBible(panel?.querySelector('details.psy-bible'));if(old)old.remove();let mean='This questionnaire measures global self-regard. The number is most useful as a baseline for noticing how harshly or positively you evaluate yourself over time.';if(Number.isFinite(score)){if(score<=14)mean='Your answers show relatively more negative global self-evaluation on this administration. Do not turn the number into an identity label; use it to identify the situations and inner statements that repeatedly pull self-evaluation downward.';else if(score>=24)mean='Your answers show relatively positive global self-evaluation on this administration. Use the result to check whether confidence is stable and realistic rather than dependent on achievement, comparison or approval.';else mean='Your answers show a mixed-to-positive pattern of global self-evaluation. The useful information is where your self-view changes sharply by situation, relationship, success or failure.'}wrap.innerHTML=`<div class="psy-section">Interpretation & self-reflection</div><div class="psy-result-order"><b>Now interpret the number</b>The 0–30 total above is the test result. There is no universal diagnostic cutoff in this scale.</div><details class="psy-insight-item" open><summary><span>What this may reveal</span><b class="psy-insight-score">${Number.isFinite(score)?score+' / 30':''}</b></summary><div class="psy-insight-body"><p>${esc(mean)}</p><p class="psy-selfq"><b>Useful self-check:</b> What makes your view of yourself rise or fall most—performance, criticism, comparison, relationships, appearance, usefulness, or something else? Which of those changes are based on evidence and which are habitual self-talk?</p></div></details>`;if(old)wrap.querySelector('.psy-insight-body').appendChild(old);return wrap}
function insertRawData(type,after){if(!after||root.querySelector('.psy-raw-data'))return;const payload=rawPayload(type),json=JSON.stringify(payload,null,2),d=document.createElement('details');d.className='psy-raw-data';d.innerHTML=`<summary>View raw scored data and item responses</summary><p class="psy-note">This is the underlying local result data used by BibleQuest. Reverse-scored scale values are already reflected in the reported domain/facet results.</p><pre>${esc(json)}</pre><button type="button" data-copy-raw>Copy raw JSON</button><span class="psy-note" data-copy-status></span>`;after.after(d)}
function enhanceResults(){const type=pageType();if(!type)return;const main=root.querySelector('.psy-main');if(!main)return;let order=root.querySelector('.psy-result-order[data-top-order]');if(!order){order=document.createElement('div');order.className='psy-result-order';order.dataset.topOrder='1';order.innerHTML='<b>Result order</b>1) Raw scored results first. 2) Psychological interpretation and self-reflection. 3) Optional Scripture reflection. Scripture does not change the psychometric score.';const discern=root.querySelector('.psy-discern');if(discern){discern.replaceWith(order)}else{root.querySelector('.psy-lead')?.after(order)}}if(root.querySelector('[data-psy-insight]'))return;if(type==='rse'){const panel=root.querySelector('.psy-panel');if(panel){const wrap=buildRseInterpretation(panel);const source=root.querySelector('.psy-source');(source||panel).before(wrap);insertRawData(type,wrap)}return}const cards=[...root.querySelectorAll('.psy-result')];if(!cards.length)return;const wrap=buildInterpretation(type,cards);const source=root.querySelector('.psy-source');if(source)source.before(wrap);else main.appendChild(wrap);insertRawData(type,wrap)}
function enhance(){addStyles();rewritePurpose();enhanceResults()}
root.addEventListener('click',e=>{const b=e.target.closest?.('[data-copy-raw]');if(b){const type=pageType(),text=JSON.stringify(rawPayload(type),null,2);navigator.clipboard?.writeText(text).then(()=>{const s=root.querySelector('[data-copy-status]');if(s)s.textContent=' Copied.'}).catch(()=>{});return}setTimeout(enhance,20)});
const mo=new MutationObserver(()=>{clearTimeout(mo._t);mo._t=setTimeout(enhance,30)});mo.observe(root,{childList:true,subtree:true});setTimeout(enhance,30);
})();