(() => {
  'use strict';
  const KEY='biblequest_device_key_v1';let layer=null,devices=[],deletion=null;
  const account=()=>window.BQAccount,client=()=>account()?.client?.(),session=()=>account()?.session?.();
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
  function deviceKey(){let k=localStorage.getItem(KEY);if(!k){k=crypto.randomUUID();localStorage.setItem(KEY,k)}return k}
  function label(){const ua=navigator.userAgent||'',mobile=/Android|iPhone|iPad/i.test(ua);return `${mobile?'Mobile':'Computer'} · ${navigator.platform||'Browser'}`.slice(0,100)}
  async function register(){const c=client(),s=session();if(!c||!s?.user)return;await c.from('bible_devices').upsert({user_id:s.user.id,device_key:deviceKey(),label:label(),platform:(navigator.userAgent||'').slice(0,200),app_version:'production-upgrade-v1',trusted:true,last_seen_at:new Date().toISOString()},{onConflict:'user_id,device_key'}).catch(()=>{})}
  async function load(){const c=client(),s=session();if(!c||!s?.user)throw new Error('Sign in first.');await register();const [d,r]=await Promise.all([c.from('bible_devices').select('*').eq('user_id',s.user.id).order('last_seen_at',{ascending:false}),c.from('bible_account_deletion_requests').select('*').eq('user_id',s.user.id).eq('status','open').maybeSingle()]);if(d.error)throw d.error;if(r.error)throw r.error;devices=d.data||[];deletion=r.data||null;render()}
  function ensure(){if(layer)return layer;layer=document.createElement('div');layer.className='security-center-layer hidden';layer.id='bqSecurityCenter';document.body.appendChild(layer);return layer}
  function close(){ensure().classList.add('hidden');document.body.classList.remove('security-center-open')}
  function deviceRow(d){const current=d.device_key===deviceKey();return `<article><div><b>${current?'✓ This device':esc(d.label||'BibleQuest device')}</b><small>${esc(d.platform||'')} · Last seen ${new Date(d.last_seen_at).toLocaleString()}</small></div>${current?'<span>CURRENT</span>':`<button data-remove-device="${d.id}">Forget</button>`}</article>`}
  function render(error=''){const x=ensure();x.innerHTML=`<main class="security-center-app"><header><button data-security-close>← BibleQuest</button><div><small>ACCOUNT</small><b>Security & data</b></div><span>🔐</span></header>${error?`<div class="security-error">${esc(error)}</div>`:''}<section><h2>Devices</h2><p>These are BibleQuest device records, not invasive location tracking.</p><div class="security-devices">${devices.map(deviceRow).join('')||'<p>No registered device.</p>'}</div><button data-signout-others class="security-primary">Sign out other sessions</button><small>Supabase revokes the other sessions. An already-issued access token may remain valid until its normal expiry.</small></section><section><h2>Your data</h2><p>Export your own BibleQuest profile, learning progress and congregation-facing records as JSON. Recovery codes and other users’ private data are excluded.</p><button data-export-account>Export my BibleQuest data</button></section><section class="security-danger"><h2>Account deletion</h2><p>Request deletion if you want the Owner to permanently remove your BibleQuest account. Congregation/group ownership must be transferred first.</p>${deletion?'<div class="security-requested"><b>Deletion requested</b><small>Your request is open and awaiting Owner action.</small></div>':'<button data-request-deletion>Request account deletion</button>'}</section></main>`;x.classList.remove('hidden');document.body.classList.add('security-center-open');x.querySelector('[data-security-close]').onclick=close;x.querySelector('[data-signout-others]').onclick=signOutOthers;x.querySelector('[data-export-account]').onclick=exportData;x.querySelector('[data-request-deletion]')?.addEventListener('click',requestDeletion);x.querySelectorAll('[data-remove-device]').forEach(b=>b.onclick=()=>forgetDevice(b.dataset.removeDevice))}
  async function signOutOthers(){if(!confirm('Sign out all other BibleQuest sessions while keeping this device signed in?'))return;const r=await client().auth.signOut({scope:'others'});if(r.error){render(r.error.message);return}alert('Other sessions were revoked.');await load()}
  async function forgetDevice(id){const r=await client().from('bible_devices').delete().eq('id',id);if(r.error){render(r.error.message);return}await load()}
  async function exportData(){const c=client(),s=session(),uid=s.user.id,tables=['bible_profiles','bible_mastery','bible_attempts','bible_bookmarks','bible_highlights','bible_notes','bible_progress_snapshots','bible_daily_journey_status','bible_user_badges','bible_member_recognitions','bible_assignment_progress','bible_user_learning_profile'];const out={exported_at:new Date().toISOString(),account:{id:uid,email:s.user.email||null},data:{}};for(const t of tables){let q=c.from(t).select('*');if(t==='bible_member_recognitions')q=q.eq('user_id',uid);else if(t==='bible_assignment_progress')q=q.eq('user_id',uid);else q=q.eq('user_id',uid);const r=await q.limit(10000);out.data[t]=r.error?{error:'Unavailable in this export'}:r.data||[]}const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`biblequest-export-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function requestDeletion(){if(!confirm('Request permanent BibleQuest account deletion? This is not immediate; the Owner must review it and any owned ministry structures must be transferred first.'))return;const reason=prompt('Optional reason for the Owner:','');if(reason===null)return;const r=await client().from('bible_account_deletion_requests').insert({user_id:session().user.id,reason:String(reason||'').slice(0,1000)||null,status:'open'});if(r.error&&r.error.code!=='23505'){render(r.error.message);return}await load()}
  async function open(){try{await load()}catch(e){render(e.message||String(e))}}
  function inject(){if(!session()?.user)return;const root=document.querySelector('.profile-panel,.profile-card,.account-security,.modern-home');if(!root||document.querySelector('[data-security-center-open]'))return;const b=document.createElement('button');b.type='button';b.dataset.securityCenterOpen='1';b.className='security-center-entry';b.textContent='🔐 Security & data';b.onclick=open;root.appendChild(b)}
  document.addEventListener('click',e=>{if(e.target.closest?.('[data-security-center-open]'))open()});new MutationObserver(inject).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setTimeout(()=>{register().catch(()=>{});inject()},1500);window.BQSecurityCenter={open,refresh:load,deviceKey};
})();