(() => {
  'use strict';
  const cache=new Map();let manifest=null,layer=null,queued=false;
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
  const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const aliases={genesis:['gen'],exodus:['exod','exo'],leviticus:['lev'],numbers:['num'],deuteronomy:['deut'],joshua:['josh'],judges:['judg'],psalms:['psalm','ps'],proverbs:['prov'],ecclesiastes:['eccl','ecc'],isaiah:['isa'],jeremiah:['jer'],ezekiel:['ezek'],daniel:['dan'],matthew:['matt','mt'],mark:['mk'],luke:['lk'],john:['jn'],acts:['act'],romans:['rom'],corinthians:['cor'],galatians:['gal'],ephesians:['eph'],philippians:['phil'],colossians:['col'],thessalonians:['thess'],timothy:['tim'],titus:['tit'],philemon:['phlm'],hebrews:['heb'],james:['jas'],peter:['pet'],jude:['jud'],revelation:['rev']};
  function excluded(el){return !el||Boolean(el.closest('.reader-layer,#bqReaderLayer,.bq-transform-v2,#psychApp,.psy-main,[data-bq-no-verse-peek]'))}
  async function getManifest(){if(manifest)return manifest;const r=await fetch('data/packs/manifest.json');if(!r.ok)throw new Error('Bible pack index is unavailable.');manifest=await r.json();return manifest}
  function extract(text){const matches=[...String(text||'').matchAll(/((?:[1-3]\s*)?[A-Za-z]+(?:\s+[A-Za-z]+){0,2})\s+(\d{1,3}):(\d{1,3})(?:\s*[-–]\s*(\d{1,3}))?/g)];return matches.map(m=>({raw:m[0],book:m[1].trim(),chapter:Number(m[2]),start:Number(m[3]),end:Number(m[4]||m[3])}));}
  async function resolve(text){const m=await getManifest(),books=m.bible_books||[];for(const ref of extract(text)){const wanted=norm(ref.book),meta=books.find(b=>{const n=norm(b.name);if(n===wanted)return true;const words=String(b.name).toLowerCase().split(/\s+/),base=words.at(-1),prefix=/^[1-3]$/.test(words[0])?words[0]:'';const wantedPrefix=/^[1-3]/.test(ref.book)?ref.book.trim()[0]:'';if(prefix!==wantedPrefix)return false;return (aliases[base]||[]).some(a=>norm(prefix+a)===wanted||norm(a)===wanted)});if(meta)return {...ref,meta}}return null}
  async function passage(ref){const key=`${ref.meta.path}:${ref.chapter}:${ref.start}:${ref.end}`;if(cache.has(key))return cache.get(key);let rows=cache.get(ref.meta.path);if(!rows){const r=await fetch(ref.meta.path);if(!r.ok)throw new Error('This Bible book has not been cached yet. Connect once and retry.');rows=await r.json();cache.set(ref.meta.path,rows)}const verses=rows.filter(v=>Number(v.c)===ref.chapter&&Number(v.v)>=ref.start&&Number(v.v)<=ref.end);if(!verses.length)throw new Error('The referenced verse was not found in the current BSB pack.');cache.set(key,verses);return verses}
  function ensure(){if(layer)return layer;layer=document.createElement('div');layer.id='bqVersePeek';layer.className='verse-peek-layer hidden';layer.innerHTML='<div class="verse-peek-scrim" data-vp-close></div><section class="verse-peek-card" role="dialog" aria-modal="true" aria-labelledby="vpTitle"><header><div><small>ACTUAL BIBLE TEXT · BSB</small><h2 id="vpTitle">View Scripture</h2></div><button type="button" data-vp-close aria-label="Close">×</button></header><div data-vp-body></div></section>';document.body.appendChild(layer);layer.addEventListener('click',e=>{if(e.target.closest('[data-vp-close]'))close()});return layer}
  function close(){ensure().classList.add('hidden');document.body.classList.remove('verse-peek-open')}
  async function open(text){const x=ensure(),body=x.querySelector('[data-vp-body]');x.classList.remove('hidden');document.body.classList.add('verse-peek-open');body.innerHTML='<div class="verse-peek-loading">Loading the referenced Bible text…</div>';try{const ref=await resolve(text);if(!ref)throw new Error('BibleQuest could not resolve that reference.');const rows=await passage(ref);body.innerHTML=`<div class="verse-peek-ref">${esc(ref.raw)}</div><article class="verse-peek-verses" data-bq-scripture="BSB">${rows.map(v=>`<p><sup>${Number(v.v)}</sup>${esc(v.t)}</p>`).join('')}</article><div class="verse-peek-source"><b>Berean Standard Bible (BSB)</b><span>This overlay does not leave or reset your current game.</span></div>`}catch(err){body.innerHTML=`<div class="verse-peek-error"><b>Could not open this passage</b><p>${esc(err.message||String(err))}</p></div>`}}
  function decorate(el){if(!(el instanceof Element)||excluded(el)||el.dataset.bqVersePeekBound)return;const text=(el.textContent||'').trim();if(!/:\d/.test(text))return;el.dataset.bqVersePeekBound='1';el.classList.add('bq-verse-reference');const b=document.createElement('button');b.type='button';b.className='bq-verse-peek-button';b.textContent='📖 View verse';b.setAttribute('aria-label',`View Bible text for ${text.replace(/^📖\s*/,'')}`);b.onclick=e=>{e.preventDefault();e.stopPropagation();open(text)};el.insertAdjacentElement('afterend',b)}
  function scan(){queued=false;document.querySelectorAll('.ref,.room-refs,.ministry-refs span,.ref-chips span,[data-verse-ref],.story-ref,.source-ref').forEach(decorate);document.querySelectorAll('span').forEach(el=>{if(/^\s*📖\s*(?:[1-3]\s*)?[A-Za-z]/.test(el.textContent||''))decorate(el)})}
  function schedule(){if(queued)return;queued=true;queueMicrotask(scan)}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!ensure().classList.contains('hidden'))close()});new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(scan);
  window.BQVersePeek={open,resolve,close};
})();