(() => {
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let ctx={},message='';
  const account=()=>window.BQAccount,client=()=>account()?.client?.(),session=()=>account()?.session?.();
  function layer(){let x=document.getElementById('bqWorkspaceLayer');if(!x){x=document.createElement('div');x.id='bqWorkspaceLayer';x.className='innovation-layer hidden';document.body.appendChild(x)}return x}
  function show(html){const x=layer();x.innerHTML=`<main class="innovation-app workspace-app">${html}</main>`;x.classList.remove('hidden');document.body.classList.add('innovation-open');bind();x.scrollTop=0}
  function close(){layer().classList.add('hidden');document.body.classList.remove('innovation-open')}
  function readerContext(){const root=document.querySelector('#bqReaderLayer:not(.hidden) .reader-chapter');if(!root)return {};const practice=root.querySelector('[data-reader-practice]'),title=root.querySelector('.reader-title-row h1')?.textContent?.trim()||'',m=title.match(/^(.*)\s+(\d+)$/);return {bookCode:practice?.dataset.readerPractice||'',bookName:m?.[1]||'',chapter:Number(m?.[2])||null}}
  async function open(passed=null){ctx=passed||readerContext();if(!session()||!client())return show(`<header class="innovation-top"><button data-workspace-close>← BibleQuest</button><b>Bible Workspace</b><span>🔐</span></header><section class="innovation-hero"><h1>Sign in to use your cloud Bible workspace.</h1><p>Highlights, bookmarks, notes, and searches follow your account across devices.</p><button data-workspace-account>Open account</button></section>`);await home()}
  async function counts(){const uid=session().user.id;const [b,h,n]=await Promise.all([client().from('bible_bookmarks').select('id',{count:'exact',head:true}).eq('user_id',uid),client().from('bible_highlights').select('id',{count:'exact',head:true}).eq('user_id',uid),client().from('bible_notes').select('id',{count:'exact',head:true}).eq('user_id',uid)]);return {b:b.count||0,h:h.count||0,n:n.count||0}}
  async function home(){const c=await counts(),ref=ctx.bookName?`${ctx.bookName}${ctx.chapter?' '+ctx.chapter:''}`:'Bible';show(`<header class="innovation-top"><button data-workspace-close>← BibleQuest</button><b>Bible Workspace</b><span>📝</span></header><section class="innovation-hero"><small>PRIVATE · CLOUD-SYNCED</small><h1>${esc(ref)} workspace</h1><p>Highlight passages, bookmark chapters, keep study notes, and search what you have learned.</p></section>${message?`<div class="innovation-message">${esc(message)}</div>`:''}<div class="workspace-stats"><span><b>${c.h}</b>highlights</span><span><b>${c.b}</b>bookmarks</span><span><b>${c.n}</b>notes</span></div>${ctx.bookCode?`<section class="workspace-tools"><button data-workspace-bookmark>🔖 Bookmark ${esc(ref)}</button><button class="secondary" data-workspace-highlight>🖍️ Highlight verses</button><button class="secondary" data-workspace-note>📝 Write note</button></section>`:''}<section class="workspace-search"><input data-workspace-search placeholder="Search my notes, highlights, bookmarks…"><button data-workspace-search-btn>Search</button></section><div class="innovation-card-grid"><button data-workspace-list="notes"><span>📝</span><b>Notes</b><small>Questions, prayers, reflections, sermon notes</small></button><button data-workspace-list="highlights"><span>🖍️</span><b>Highlights</b><small>Color-coded passage markers</small></button><button data-workspace-list="bookmarks"><span>🔖</span><b>Bookmarks</b><small>Saved passages to revisit</small></button></div>`)}
  async function bookmark(){if(!ctx.bookCode)return;const r=await client().from('bible_bookmarks').insert({user_id:session().user.id,book_code:ctx.bookCode,book_name:ctx.bookName,chapter:ctx.chapter,label:`${ctx.bookName} ${ctx.chapter}`});if(r.error)throw r.error;message='Passage bookmarked.';await account()?.track?.('workspace','bookmark',{book:ctx.bookCode,chapter:ctx.chapter});home()}
  function highlightForm(){show(`<header class="innovation-top"><button data-workspace-home>← Workspace</button><b>Highlight passage</b><span>🖍️</span></header><section class="workspace-form"><h1>${esc(ctx.bookName)} ${ctx.chapter}</h1><form data-highlight-form><div class="workspace-ref-grid"><label>From verse<input name="start" type="number" min="1" required value="1"></label><label>To verse<input name="end" type="number" min="1" placeholder="optional"></label></div><label>Color<select name="color"><option value="gold">Gold · key idea</option><option value="green">Green · growth/action</option><option value="blue">Blue · promise/comfort</option><option value="rose">Rose · question/attention</option></select></label><button>Save highlight</button></form><div class="innovation-note">Highlights are private to your account. They do not affect rankings.</div></section>`)}
  async function saveHighlight(form){const fd=new FormData(form),start=Number(fd.get('start')),end=Number(fd.get('end'))||null,color=String(fd.get('color')||'gold');const r=await client().from('bible_highlights').upsert({user_id:session().user.id,book_code:ctx.bookCode,book_name:ctx.bookName,chapter:ctx.chapter,verse_start:start,verse_end:end,color},{onConflict:'user_id,book_code,chapter,verse_start,color'});if(r.error)throw r.error;message='Highlight saved.';await account()?.track?.('workspace','highlight',{book:ctx.bookCode,chapter:ctx.chapter});await applyReaderHighlights();home()}
  async function list(kind){const uid=session().user.id;if(kind==='notes'){const r=await client().from('bible_notes').select('*').eq('user_id',uid).order('updated_at',{ascending:false}).limit(200);return listView(kind,r.data||[])}if(kind==='highlights'){const r=await client().from('bible_highlights').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(300);return listView(kind,r.data||[])}const r=await client().from('bible_bookmarks').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(300);listView(kind,r.data||[])}
  function listView(kind,rows){show(`<header class="innovation-top"><button data-workspace-home>← Workspace</button><b>My ${esc(kind)}</b><span>${kind==='notes'?'📝':kind==='highlights'?'🖍️':'🔖'}</span></header><div class="workspace-list">${rows.map(r=>`<article><div><b>${esc(r.title||r.label||`${r.book_name||r.book_code||'General'} ${r.chapter||''}`)}</b><small>${esc(r.book_name||r.book_code||'')} ${r.chapter||''}${r.verse_start?`:${r.verse_start}${r.verse_end?'–'+r.verse_end:''}`:''}${r.color?' · '+r.color:''}</small>${r.body?`<p>${esc(r.body)}</p>`:''}</div>${kind!=='notes'?`<button data-workspace-delete="${r.id}" data-kind="${kind}">×</button>`:''}</article>`).join('')||'<div class="innovation-note">Nothing saved here yet.</div>'}</div>`)}
  async function search(term){term=String(term||'').trim().toLowerCase();if(!term)return;const uid=session().user.id,[notes,high,marks]=await Promise.all([client().from('bible_notes').select('*').eq('user_id',uid).order('updated_at',{ascending:false}).limit(250),client().from('bible_highlights').select('*').eq('user_id',uid).limit(300),client().from('bible_bookmarks').select('*').eq('user_id',uid).limit(300)]);const all=[...(notes.data||[]).map(x=>({...x,kind:'note'})),...(high.data||[]).map(x=>({...x,kind:'highlight'})),...(marks.data||[]).map(x=>({...x,kind:'bookmark'}))].filter(x=>JSON.stringify([x.title,x.body,x.tags,x.book_name,x.label,x.note_type]).toLowerCase().includes(term));show(`<header class="innovation-top"><button data-workspace-home>← Workspace</button><b>Search</b><span>🔎</span></header><section class="innovation-hero"><small>${all.length} RESULT${all.length===1?'':'S'}</small><h1>“${esc(term)}”</h1></section><div class="workspace-list">${all.map(r=>`<article><span>${r.kind==='note'?'📝':r.kind==='highlight'?'🖍️':'🔖'}</span><div><b>${esc(r.title||r.label||`${r.book_name||''} ${r.chapter||''}`)}</b><small>${esc(r.book_name||'')} ${r.chapter||''}</small>${r.body?`<p>${esc(r.body)}</p>`:''}</div></article>`).join('')||'<div class="innovation-note">No matching private Bible workspace items.</div>'}</div>`)}
  async function remove(id,kind){const table=kind==='highlights'?'bible_highlights':'bible_bookmarks';const r=await client().from(table).delete().eq('id',id).eq('user_id',session().user.id);if(r.error)throw r.error;message='Removed.';await applyReaderHighlights();list(kind)}
  async function applyReaderHighlights(){const root=document.querySelector('#bqReaderLayer:not(.hidden) .reader-chapter');if(!root||!session()||!client())return;const rc=readerContext();if(!rc.bookCode||!rc.chapter)return;root.querySelectorAll('.verse-list p').forEach(p=>{p.classList.remove('hl-gold','hl-green','hl-blue','hl-rose');p.removeAttribute('data-highlighted')});const r=await client().from('bible_highlights').select('verse_start,verse_end,color').eq('user_id',session().user.id).eq('book_code',rc.bookCode).eq('chapter',rc.chapter);for(const h of r.data||[]){const end=h.verse_end||h.verse_start;for(let v=h.verse_start;v<=end;v++){const p=root.querySelector(`.verse-list p[data-verse="${v}"]`);if(p){p.classList.add(`hl-${h.color}`);p.dataset.highlighted='1'}}}}
  function injectReader(){const actions=document.querySelector('#bqReaderLayer:not(.hidden) .reader-study-actions');if(actions&&!actions.querySelector('[data-reader-workspace]')){const b=document.createElement('button');b.className='reader-secondary';b.dataset.readerWorkspace='1';b.textContent='🗂️ Bible Workspace';actions.appendChild(b)}applyReaderHighlights().catch(()=>{})}
  function bind(){const x=layer();x.querySelectorAll('[data-workspace-close]').forEach(b=>b.onclick=close);x.querySelectorAll('[data-workspace-home]').forEach(b=>b.onclick=home);x.querySelector('[data-workspace-account]')?.addEventListener('click',()=>account()?.open?.());x.querySelector('[data-workspace-bookmark]')?.addEventListener('click',()=>bookmark().catch(e=>{message=e.message;home()}));x.querySelector('[data-workspace-highlight]')?.addEventListener('click',highlightForm);x.querySelector('[data-workspace-note]')?.addEventListener('click',()=>window.BQNotes?.open?.(ctx));x.querySelector('[data-highlight-form]')?.addEventListener('submit',e=>{e.preventDefault();saveHighlight(e.currentTarget).catch(err=>alert(err.message))});x.querySelectorAll('[data-workspace-list]').forEach(b=>b.onclick=()=>list(b.dataset.workspaceList));x.querySelector('[data-workspace-search-btn]')?.addEventListener('click',()=>search(x.querySelector('[data-workspace-search]').value));x.querySelector('[data-workspace-search]')?.addEventListener('keydown',e=>{if(e.key==='Enter')search(e.currentTarget.value)});x.querySelectorAll('[data-workspace-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.workspaceDelete,b.dataset.kind).catch(e=>alert(e.message)))}
  document.addEventListener('click',e=>{if(e.target.closest('[data-reader-workspace]')){ctx=readerContext();open(ctx)}});new MutationObserver(injectReader).observe(document.documentElement,{childList:true,subtree:true});injectReader();window.BQWorkspace={open,applyReaderHighlights};
})();
