const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const optionRows=rows=>rows.map(row=>`<option value="${esc(row.userId)}">${esc(row.displayName)} · ${esc(row.roleLabel)}</option>`).join('');
function memberRows(team){
  if(!team.members.length)return '<p>No team members are visible.</p>';
  return `<ul class="bq-team-member-list">${team.members.map(member=>`<li data-team-member="${esc(member.userId)}"><span><b>${esc(member.displayName)}</b> · ${esc(member.roleLabel)}</span>${team.canManage&&!member.isCreator?`<button type="button" class="bq-secondary-button" data-team-remove="${esc(team.id)}" data-team-user="${esc(member.userId)}">Remove</button>`:member.isCreator?'<span class="bq-team-creator-note">Creator</span>':''}</li>`).join('')}</ul>`;
}
function teamCard(team){
  return `<article class="bq-account-section bq-team-card" data-team-card="${esc(team.id)}"><div class="bq-team-card-head"><div><p class="bq-eyebrow">${esc(team.congregationName)} · ${esc(team.congregationRoleLabel)}</p><h2>${esc(team.name)}</h2></div><strong>${team.memberCount} member${team.memberCount===1?'':'s'}</strong></div>${memberRows(team)}${team.canManage?`<div class="bq-team-manage"><form class="bq-account-form" data-team-rename="${esc(team.id)}"><label>Team name<input name="name" maxlength="60" minlength="2" value="${esc(team.name)}" required></label><button type="submit" class="bq-secondary-button">Rename</button></form>${team.availableMembers.length?`<form class="bq-account-form" data-team-add="${esc(team.id)}"><label>Add congregation member<select name="user_id" required>${optionRows(team.availableMembers)}</select></label><button type="submit" class="bq-secondary-button">Add member</button></form>`:'<p>All active congregation members are already on this team.</p>'}${team.canArchive?`<button type="button" class="bq-secondary-button bq-team-danger" data-team-archive="${esc(team.id)}">Archive team</button>`:'<p class="bq-team-permission-note">Only the team creator or congregation admin can archive this team.</p>'}</div>`:`<p class="bq-team-permission-note">Your congregation role can view this team but cannot manage it.</p>`}</article>`;
}
export function teamCenterPage({teamCenter,onAccount,onBack}){
  return {title:'Team Center',html:'<section class="bq-panel bq-team-center" data-team-center-view></section>',mount(root){
    const view=root.querySelector('[data-team-center-view]');let busy=false,message='';
    const state=()=>teamCenter.snapshot();
    const back=()=>'<div class="bq-account-actions"><button type="button" class="bq-secondary-button" data-team-center-back>Back to More</button></div>';
    const bindCommon=()=>{view.querySelector('[data-team-center-back]')?.addEventListener('click',()=>onBack?.(),{once:true});view.querySelector('[data-team-center-account]')?.addEventListener('click',()=>onAccount?.(),{once:true})};
    const renderAuth=()=>{const current=state();view.innerHTML=`<p class="bq-eyebrow">TEAM CENTER</p><h1>Congregation teams</h1><p>${current.remoteAvailable?'Sign in to view your congregation teams.':'Team Center is disabled in local preview because teams are congregation cloud data.'}</p>${current.remoteAvailable?'<button type="button" class="bq-primary-button" data-team-center-account>Open account</button>':''}${back()}`;bindCommon()};
    const render=()=>{const current=state();if(!current.authenticated||!current.remoteAvailable)return renderAuth();const manageable=current.congregations.filter(row=>row.canManage);view.innerHTML=`<div class="bq-team-center-head"><div><p class="bq-eyebrow">CONGREGATION · TEAM CENTER</p><h1>Team Center</h1><p>View team rosters and congregation roles. Facilitators, leaders, pastors and admins can manage game teams through the trusted congregation workflow.</p></div>${back()}</div>${message?`<p class="bq-form-message" role="status">${esc(message)}</p>`:''}<div data-team-list>${current.teams.length?current.teams.map(teamCard).join(''):'<section class="bq-account-section"><h2>No active teams</h2><p>No Team Center game teams are active in your congregation yet.</p></section>'}</div>${manageable.length?`<section class="bq-account-section"><p class="bq-eyebrow">MINISTRY ROLE</p><h2>Create a team</h2><form class="bq-account-form" data-team-create><label>Congregation<select name="congregation_id" required>${manageable.map(row=>`<option value="${esc(row.id)}">${esc(row.name)} · ${esc(row.roleLabel)}</option>`).join('')}</select></label><label>Team name<input name="name" maxlength="60" minlength="2" required></label><button type="submit" class="bq-primary-button">Create team</button></form></section>`:''}<p class="bq-team-boundary"><b>Role boundary:</b> Team Center displays each member's existing congregation role. It does not create a separate team-role system. Management remains authorized by the congregation role and trusted server function.</p>`;bindCommon();bindActions()};
    async function load(){if(busy)return;busy=true;view.innerHTML='<p class="bq-eyebrow">TEAM CENTER</p><h1>Team Center</h1><p role="status">Loading teams…</p>';try{await teamCenter.load();message='';render()}catch(error){if(error?.code==='BQ_TEAM_CENTER_AUTH_REQUIRED'||error?.code==='BQ_TEAM_CENTER_REMOTE_DISABLED')renderAuth();else{view.innerHTML=`<p class="bq-eyebrow">TEAM CENTER</p><h1>Team Center</h1><p class="bq-form-message" role="alert">${esc(error?.message||'Team Center could not load.')}</p><button type="button" class="bq-secondary-button" data-team-center-retry>Try again</button>${back()}`;bindCommon();view.querySelector('[data-team-center-retry]')?.addEventListener('click',load,{once:true})}}finally{busy=false}}
    async function run(action,success,fallback){if(busy)return;busy=true;try{await action();message=success;render()}catch(error){message=error?.message||fallback;render()}finally{busy=false}}
    const submitCreate=event=>{event.preventDefault();const fd=new FormData(event.currentTarget);return run(()=>teamCenter.create({congregationId:fd.get('congregation_id'),name:fd.get('name')}),'Team created.','Could not create this team.')};
    const submitRename=event=>{event.preventDefault();const fd=new FormData(event.currentTarget),teamId=event.currentTarget.dataset.teamRename;return run(()=>teamCenter.rename(teamId,fd.get('name')),'Team renamed.','Could not rename this team.')};
    const submitAdd=event=>{event.preventDefault();const fd=new FormData(event.currentTarget),teamId=event.currentTarget.dataset.teamAdd;return run(()=>teamCenter.addMember(teamId,fd.get('user_id')),'Member added.','Could not add this member.')};
    const remove=(teamId,userId)=>{if(!window.confirm('Remove this member from the team?'))return;return run(()=>teamCenter.removeMember(teamId,userId),'Member removed.','Could not remove this member.')};
    const archive=teamId=>{if(!window.confirm('Archive this team? It will no longer appear as active.'))return;return run(()=>teamCenter.archive(teamId),'Team archived.','Could not archive this team.')};
    function bindActions(){view.querySelector('[data-team-create]')?.addEventListener('submit',submitCreate,{once:true});view.querySelectorAll('[data-team-rename]').forEach(form=>form.addEventListener('submit',submitRename,{once:true}));view.querySelectorAll('[data-team-add]').forEach(form=>form.addEventListener('submit',submitAdd,{once:true}));view.querySelectorAll('[data-team-remove]').forEach(button=>button.addEventListener('click',()=>remove(button.dataset.teamRemove,button.dataset.teamUser),{once:true}));view.querySelectorAll('[data-team-archive]').forEach(button=>button.addEventListener('click',()=>archive(button.dataset.teamArchive),{once:true}))}
    load();return()=>{busy=false};
  }};
}
