const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const reference=note=>`${note.book} ${note.chapter}${note.verseStart?`:${note.verseStart}${note.verseEnd&&note.verseEnd!==note.verseStart?`–${note.verseEnd}`:''}`:''}`;
const displayDate=value=>{const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleString():'Unknown date'};

export function cloudNotesPage({notes,onLearn,onAccount}){
  return{
    title:'Cloud Notes',
    html:'<section class="bq-panel bq-cloud-notes" data-cloud-notes-view></section>',
    mount(root){
      const view=root.querySelector('[data-cloud-notes-view]');let editingId=null,message='',busy=false;
      const status=()=>notes.status();
      const setMessage=text=>{message=String(text||'')};
      const authView=()=>{const state=status(),preview=!state.remoteAvailable;view.innerHTML=`<p class="bq-eyebrow">CLOUD · ACCOUNT</p><h1>Cloud Notes</h1><p data-cloud-auth>${preview?'Cloud account actions are disabled in local preview.':'Sign in to save Scripture notes to your BibleQuest account and access them on another signed-in device.'}</p><div class="bq-cloud-notes-actions">${preview?'':'<button type="button" class="bq-primary-button" data-cloud-account>Open Account</button>'}<button type="button" class="bq-secondary-button" data-cloud-learn>Back to Learn</button></div><p class="bq-cloud-notes-boundary">Private Notes remain device-only and are never uploaded automatically.</p>`;view.querySelector('[data-cloud-account]')?.addEventListener('click',()=>onAccount?.(),{once:true});view.querySelector('[data-cloud-learn]')?.addEventListener('click',()=>onLearn?.(),{once:true})};
      const listView=()=>{const items=notes.list();view.innerHTML=`<div class="bq-cloud-notes-head"><div><p class="bq-eyebrow">CLOUD · SIGNED IN</p><h1>Cloud Notes</h1><p>Scripture notes stored in your BibleQuest account. Private Notes on this device stay separate.</p></div><span class="bq-cloud-notes-count">${items.length} note${items.length===1?'':'s'}</span></div>${message?`<p class="bq-cloud-notes-message" role="status">${esc(message)}</p>`:''}<div class="bq-cloud-notes-actions"><button type="button" class="bq-primary-button" data-cloud-new>New cloud note</button><button type="button" class="bq-secondary-button" data-cloud-reload>Reload</button><button type="button" class="bq-secondary-button" data-cloud-learn>Back to Learn</button></div>${items.length?`<div class="bq-cloud-notes-list">${items.map(note=>`<button type="button" class="bq-cloud-note-card" data-cloud-open="${esc(note.id)}"><span><b>${note.isPinned?'★ ':''}${esc(note.title||reference(note))}</b><small>${esc(reference(note))} · Updated ${esc(displayDate(note.updatedAt))}</small></span><i aria-hidden="true">›</i></button>`).join('')}</div>`:'<div class="bq-cloud-notes-empty"><b>No cloud notes yet</b><p>Create a Scripture-linked note to keep with your signed-in account.</p></div>'}`;bindList()};
      const editor=note=>{editingId=note?.id||null;view.innerHTML=`<div class="bq-cloud-notes-head"><div><p class="bq-eyebrow">${note?'EDIT CLOUD NOTE':'NEW CLOUD NOTE'}</p><h1>${note?'Edit cloud note':'New cloud note'}</h1><p>This note is stored in your signed-in BibleQuest account.</p></div></div><form class="bq-cloud-note-form" data-cloud-form><div class="bq-cloud-reference-grid"><label>Book <input name="book" maxlength="80" required autocomplete="off" value="${esc(note?.book||'')}" placeholder="e.g. Romans"></label><label>Chapter <input name="chapter" type="number" min="1" max="999" required inputmode="numeric" value="${esc(note?.chapter||'')}"></label><label>Start verse <input name="verseStart" type="number" min="1" max="999" inputmode="numeric" value="${esc(note?.verseStart||'')}"></label><label>End verse <input name="verseEnd" type="number" min="1" max="999" inputmode="numeric" value="${esc(note?.verseEnd||'')}"></label></div><label>Title <input name="title" maxlength="120" autocomplete="off" value="${esc(note?.title||'')}" placeholder="Optional title"></label><label>Note <textarea name="content" maxlength="12000" rows="10" required placeholder="Write your Scripture note here…">${esc(note?.content||'')}</textarea></label><label>Tags <input name="tags" maxlength="400" autocomplete="off" value="${esc(note?.tags?.join(', ')||'')}" placeholder="prayer, study, question"></label><label class="bq-cloud-pin"><input name="isPinned" type="checkbox" ${note?.isPinned?'checked':''}> Pin this note</label><p class="bq-cloud-notes-message" data-cloud-message role="status"></p><div class="bq-cloud-notes-actions"><button type="submit" class="bq-primary-button">Save cloud note</button><button type="button" class="bq-secondary-button" data-cloud-cancel>Cancel</button>${note?'<button type="button" class="bq-secondary-button bq-cloud-note-delete" data-cloud-delete>Delete cloud note</button>':''}</div></form>`;bindEditor();view.querySelector('textarea')?.focus()};
      const formMessage=text=>{const node=view.querySelector('[data-cloud-message]');if(node)node.textContent=String(text||'')};
      const payload=form=>{const data=new FormData(form);return{book:data.get('book'),chapter:data.get('chapter'),verseStart:data.get('verseStart'),verseEnd:data.get('verseEnd'),title:data.get('title'),content:data.get('content'),tags:data.get('tags'),noteType:'general',isPinned:data.get('isPinned')==='on'}};
      async function reload(){if(busy)return;busy=true;view.innerHTML='<p class="bq-eyebrow">CLOUD · ACCOUNT</p><h1>Cloud Notes</h1><p role="status">Loading your cloud notes…</p>';try{await notes.load();message='';listView()}catch(error){if(error?.code==='BQ_CLOUD_NOTES_AUTH_REQUIRED')authView();else{view.innerHTML=`<p class="bq-eyebrow">CLOUD · ACCOUNT</p><h1>Cloud Notes</h1><p class="bq-cloud-notes-message" role="alert">${esc(error?.message||'Could not load Cloud Notes.')}</p><div class="bq-cloud-notes-actions"><button type="button" class="bq-secondary-button" data-cloud-retry>Try again</button><button type="button" class="bq-secondary-button" data-cloud-learn>Back to Learn</button></div>`;view.querySelector('[data-cloud-retry]')?.addEventListener('click',reload,{once:true});view.querySelector('[data-cloud-learn]')?.addEventListener('click',()=>onLearn?.(),{once:true})}}finally{busy=false}}
      function bindList(){view.querySelector('[data-cloud-new]')?.addEventListener('click',()=>editor(null),{once:true});view.querySelector('[data-cloud-reload]')?.addEventListener('click',reload,{once:true});view.querySelector('[data-cloud-learn]')?.addEventListener('click',()=>onLearn?.(),{once:true});view.querySelectorAll('[data-cloud-open]').forEach(button=>button.addEventListener('click',()=>{try{editor(notes.get(button.dataset.cloudOpen))}catch(error){setMessage(error?.message||'Could not open that cloud note.');listView()}},{once:true}))}
      function bindEditor(){const form=view.querySelector('[data-cloud-form]');form?.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;form.querySelector('button[type="submit"]').disabled=true;try{if(editingId)await notes.update(editingId,payload(form));else await notes.create(payload(form));editingId=null;setMessage('Cloud note saved.');listView()}catch(error){formMessage(error?.message||'Could not save this cloud note.');if(error?.code==='BQ_CLOUD_NOTES_CONFLICT'){const actions=view.querySelector('.bq-cloud-notes-actions');actions?.insertAdjacentHTML('beforeend','<button type="button" class="bq-secondary-button" data-cloud-conflict-reload>Reload latest</button>');view.querySelector('[data-cloud-conflict-reload]')?.addEventListener('click',reload,{once:true})}}finally{busy=false;const submit=form.querySelector('button[type="submit"]');if(submit)submit.disabled=false}});view.querySelector('[data-cloud-cancel]')?.addEventListener('click',()=>{editingId=null;message='';listView()},{once:true});view.querySelector('[data-cloud-delete]')?.addEventListener('click',async()=>{if(!editingId||busy||!window.confirm('Delete this cloud note from your account?'))return;busy=true;try{await notes.remove(editingId);editingId=null;setMessage('Cloud note deleted.');listView()}catch(error){formMessage(error?.message||'Could not delete this cloud note.')}finally{busy=false}},{once:true})}
      if(status().authenticated)reload();else authView();return()=>{editingId=null;busy=false};
    }
  }
}
