const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const relative=value=>{const time=Date.parse(value),minutes=Math.max(0,Math.floor((Date.now()-time)/60000));if(!Number.isFinite(time))return '';if(minutes<1)return 'Just now';if(minutes<60)return `${minutes}m ago`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours}h ago`;return new Date(time).toLocaleDateString()};

function groupCard(group,state){
  const rows=state.items.filter(item=>item.groupId===group.id).slice(0,8),sent=new Set(state.items.filter(item=>item.groupId===group.id&&item.senderId===state.userId&&item.day===new Date().toISOString().slice(0,10)).map(item=>item.kind));
  return `<article class="bq-account-section bq-encouragement-group" data-encouragement-group="${esc(group.id)}"><p class="bq-eyebrow">JOURNEY GROUP</p><h2>${esc(group.name)}</h2><p>Choose one simple encouragement for the whole group.</p><div class="bq-encouragement-presets">${Object.entries(state.presets).map(([kind,preset])=>`<button type="button" class="bq-secondary-button" data-send-encouragement="${esc(kind)}" data-group-id="${esc(group.id)}" ${sent.has(kind)?'disabled aria-disabled="true"':''}><span aria-hidden="true">${preset.emoji}</span> ${esc(preset.label)}${sent.has(kind)?' · sent':''}</button>`).join('')}</div><div class="bq-encouragement-feed" aria-label="Recent encouragements">${rows.length?rows.map(item=>`<p><span aria-hidden="true">${item.emoji}</span> <b>${item.senderId===state.userId?'You':'A group member'}</b> · ${esc(item.label)} <small>${esc(relative(item.createdAt))}</small></p>`).join(''):'<p class="bq-muted">No encouragements yet. Be the first.</p>'}</div></article>`;
}

export function encouragementsPage({encouragements,onBack,onAccount}){
  return{title:'Encouragements',html:'<section class="bq-panel bq-encouragements" data-encouragements-view></section>',mount(root){
    const view=root.querySelector('[data-encouragements-view]');let busy=false,message='';
    const bindNav=()=>{view.querySelector('[data-encouragements-back]')?.addEventListener('click',onBack);view.querySelector('[data-encouragements-account]')?.addEventListener('click',onAccount)};
    const renderAuth=()=>{const state=encouragements.snapshot();view.innerHTML=`<p class="bq-eyebrow">ENCOURAGEMENTS</p><h1>Small words. Real care.</h1><p>${state.remoteAvailable?'Sign in to encourage your Journey Groups.':'Encouragements are disabled in local preview because membership is cloud-backed.'}</p>${state.remoteAvailable?'<button type="button" class="bq-primary-button" data-encouragements-account>Open account</button>':''}<button type="button" class="bq-secondary-button" data-encouragements-back>Back to Journey Groups</button>`;bindNav()};
    const bind=()=>{bindNav();view.querySelectorAll('[data-send-encouragement]').forEach(button=>button.addEventListener('click',()=>send(button.dataset.groupId,button.dataset.sendEncouragement)))};
    const render=()=>{const state=encouragements.snapshot();if(!state.authenticated||!state.remoteAvailable)return renderAuth();view.innerHTML=`<div class="bq-encouragements-head"><div><p class="bq-eyebrow">PRESET-ONLY · GROUP-WIDE</p><h1>Encouragements</h1><p>Notice one another without creating another chat feed, ranking, or performance score.</p></div><button type="button" class="bq-secondary-button" data-encouragements-back>Back to Journey Groups</button></div>${message?`<p class="bq-form-message" role="status">${esc(message)}</p>`:''}${state.groups.length?state.groups.map(group=>groupCard(group,state)).join(''):'<section class="bq-account-section"><h2>No Journey Group yet</h2><p>Join a Journey Group before sending encouragements.</p></section>'}<p class="bq-encouragement-privacy"><b>Privacy:</b> Encouragements never include private notes, reflections, answers, completion status, rankings, or XP.</p>`;bind()};
    async function load(){if(busy)return;busy=true;view.innerHTML='<p class="bq-eyebrow">ENCOURAGEMENTS</p><h1>Encouragements</h1><p role="status">Loading encouragements…</p>';try{await encouragements.load();message='';render()}catch(error){if(error?.code==='BQ_ENCOURAGEMENTS_AUTH_REQUIRED'||error?.code==='BQ_ENCOURAGEMENTS_REMOTE_DISABLED')renderAuth();else{view.innerHTML=`<p class="bq-eyebrow">ENCOURAGEMENTS</p><h1>Encouragements</h1><p class="bq-form-message" role="alert">${esc(error?.message||'Encouragements could not load.')}</p><button type="button" class="bq-secondary-button" data-encouragements-retry>Try again</button><button type="button" class="bq-secondary-button" data-encouragements-back>Back</button>`;bindNav();view.querySelector('[data-encouragements-retry]')?.addEventListener('click',load,{once:true})}}finally{busy=false}}
    async function send(groupId,kind){if(busy)return;busy=true;try{await encouragements.send(groupId,kind);message='Encouragement sent.'}catch(error){message=error?.message||'Could not send that encouragement.'}finally{busy=false;render()}}
    load();return()=>{};
  }};
}
