const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const dateLabel=value=>{if(!value)return '';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})};
function recognitionRows(state){
  if(!state.recognitions.length)return '<section class="bq-account-section"><h2>No special recognition yet</h2><p>Leader, pastor and admin awards will appear here for congregation members.</p></section>';
  return `<section class="bq-account-section"><p class="bq-eyebrow">RECENT RECOGNITION</p><div class="bq-community-list">${state.recognitions.map(row=>`<article class="bq-community-row" data-recognition-row="${esc(row.id)}"><div><p class="bq-eyebrow">${esc(row.displayName)}</p><h3>${esc(row.icon)} ${esc(row.title)}</h3>${row.note?`<p>${esc(row.note)}</p>`:''}</div><span>${esc(dateLabel(row.createdAt))}</span></article>`).join('')}</div></section>`;
}
function badgeRows(state){
  const members=state.members.filter(row=>row.badges.length);
  if(!members.length)return '<section class="bq-account-section"><h2>Earned congregation badges</h2><p>No earned badges are visible yet.</p></section>';
  return `<section class="bq-account-section"><h2>Earned congregation badges</h2><p>Recent achievement badges for active congregation members.</p><div class="bq-community-list">${members.map(member=>`<article class="bq-community-row" data-recognition-member="${esc(member.userId)}"><div><h3>${esc(member.displayName)}</h3><p>${member.badges.slice(0,3).map(badge=>`${esc(badge.icon)} ${esc(badge.name)}`).join(' · ')}</p></div><span>${member.badges.length} badge${member.badges.length===1?'':'s'}</span></article>`).join('')}</div></section>`;
}
function awardForm(state){
  if(!state.canAward)return `<section class="bq-account-section"><p class="bq-eyebrow">AWARD PERMISSION</p><h2>Special recognition is leader-managed</h2><p>Your ${esc(state.roleLabel||'member')} role can view congregation recognition. Only leaders, pastors and admins can create persisted special recognition.</p></section>`;
  if(!state.members.length)return '<section class="bq-account-section"><h2>Give special recognition</h2><p>No active congregation member is available to recognize.</p></section>';
  return `<section class="bq-account-section"><p class="bq-eyebrow">LEADER · PASTOR · ADMIN</p><h2>Give special recognition</h2><form class="bq-account-form" data-recognition-award><label>Member<select name="user_id" required>${state.members.map(row=>`<option value="${esc(row.userId)}">${esc(row.displayName)}</option>`).join('')}</select></label><label>Award<select name="award_code" required>${state.presets.map(row=>`<option value="${esc(row.code)}">${esc(row.icon)} ${esc(row.title)}</option>`).join('')}</select></label><label>Custom title <small>(optional)</small><input name="title" maxlength="120" placeholder="Uses the selected award title if blank"></label><label>Congratulatory note <small>(optional)</small><textarea name="note" maxlength="1200" rows="3" placeholder="Why are you recognizing this person?"></textarea></label><button type="submit" class="bq-primary-button">Give recognition</button></form></section>`;
}
export function congregationRecognitionPage({recognition,onBack,onAccount,onLeaderboards}={}){
  return{title:'Congregation Recognition',html:'<section class="bq-panel" data-recognition-view></section>',mount(root){
    const view=root.querySelector('[data-recognition-view]');let busy=false,disposed=false,message='';
    const back=()=>'<button type="button" class="bq-secondary-button" data-recognition-back>Back to Community</button>';
    const bindCommon=()=>{view.querySelector('[data-recognition-back]')?.addEventListener('click',()=>onBack?.(),{once:true});view.querySelector('[data-recognition-account]')?.addEventListener('click',()=>onAccount?.(),{once:true});view.querySelector('[data-recognition-leaderboards]')?.addEventListener('click',()=>onLeaderboards?.(),{once:true});view.querySelector('[data-recognition-retry]')?.addEventListener('click',()=>load(),{once:true})};
    const renderSignedOut=remoteAvailable=>{view.innerHTML=`<p class="bq-eyebrow">CONGREGATION RECOGNITION</p><h1>Celebrate participation safely</h1><p>${remoteAvailable?'Sign in to view recognition from your congregation.':'Congregation recognition is unavailable in local preview because it is congregation cloud data.'}</p>${remoteAvailable?'<button type="button" class="bq-primary-button" data-recognition-account>Open account</button>':''}${back()}`;bindCommon()};
    const bindActions=()=>{
      view.querySelector('[data-recognition-congregation]')?.addEventListener('change',event=>load({congregationId:event.target.value}),{once:true});
      view.querySelector('[data-recognition-award]')?.addEventListener('submit',event=>{event.preventDefault();const fd=new FormData(event.currentTarget);void runAward({targetUserId:fd.get('user_id'),awardCode:fd.get('award_code'),title:fd.get('title'),note:fd.get('note')})},{once:true});
    };
    const render=state=>{if(disposed)return;if(!state.authenticated||!state.remoteAvailable)return renderSignedOut(state.remoteAvailable);const congregationSelect=state.congregations.length>1?`<label>Congregation<select data-recognition-congregation>${state.congregations.map(row=>`<option value="${esc(row.id)}" ${row.id===state.congregationId?'selected':''}>${esc(row.name)}</option>`).join('')}</select></label>`:'';view.innerHTML=`<div class="bq-team-center-head"><div><p class="bq-eyebrow">CONGREGATION RECOGNITION</p><h1>${esc(state.congregationName||'Recognition')}</h1><p>Celebrate learning and participation without treating activity as a measure of spiritual worth.</p></div>${back()}</div>${message?`<p class="bq-form-message" role="status">${esc(message)}</p>`:''}${state.congregations.length?`<section class="bq-account-section"><div class="bq-account-form">${congregationSelect}</div><div class="bq-account-actions"><button type="button" class="bq-secondary-button" data-recognition-leaderboards>Open Leaderboards</button></div><p><b>Privacy boundary:</b> This page uses public congregation identity, earned badges and visible recognition only. Private notes, answers, reflections, Couple Journey data and account credentials are not included.</p></section>${awardForm(state)}${recognitionRows(state)}${badgeRows(state)}`:'<section class="bq-account-section"><h2>No congregation yet</h2><p>Join an active congregation before viewing recognition.</p></section>'}`;bindCommon();bindActions()};
    async function load(overrides={}){if(busy||disposed)return;busy=true;const previous=recognition.snapshot();view.innerHTML='<p class="bq-eyebrow">CONGREGATION RECOGNITION</p><h1>Recognition</h1><p role="status">Loading congregation recognition…</p>';try{render(await recognition.load({congregationId:overrides.congregationId??previous.congregationId}))}catch(error){if(disposed)return;if(error?.code==='BQ_RECOGNITION_AUTH_REQUIRED'||error?.code==='BQ_RECOGNITION_REMOTE_DISABLED')renderSignedOut(error.code!=='BQ_RECOGNITION_REMOTE_DISABLED');else{view.innerHTML=`<p class="bq-eyebrow">CONGREGATION RECOGNITION</p><h1>Recognition could not load.</h1><p class="bq-form-message" role="alert">${esc(error?.message||'Try again.')}</p><button type="button" class="bq-secondary-button" data-recognition-retry>Try again</button>${back()}`;bindCommon()}}finally{busy=false}}
    async function runAward(payload){if(busy||disposed)return;busy=true;try{const state=await recognition.award(payload);message='Recognition saved.';render(state)}catch(error){message=error?.message||'Recognition could not be saved.';render(recognition.snapshot())}finally{busy=false}}
    void load();return()=>{disposed=true;busy=false};
  }};
}
