const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const JOURNEY=Object.freeze([
  Object.freeze({icon:'🙏',title:'Pray Honestly',question:'Ano ang gusto mong ipag-pray ng partner mo para sa’yo ngayon—at anong support ang helpful?',ref:'Philippians 1:9–11'}),
  Object.freeze({icon:'👂',title:'Listen First',question:'Share one concern for two minutes. Ang listener ay magpa-paraphrase muna bago magbigay ng advice.',ref:'James 1:19'}),
  Object.freeze({icon:'💛',title:'Notice the Good',question:'Name one specific thing your partner did recently that made life lighter or better.',ref:'1 Thessalonians 5:11'}),
  Object.freeze({icon:'🕊️',title:'Repair Gently',question:'Name one small recurring tension. Own one part without adding “pero ikaw…”.',ref:'Matthew 7:3–5'}),
  Object.freeze({icon:'🏠',title:'Build the Home',question:'Anong atmosphere ang gusto ninyong maramdaman sa bahay? What one habit can support it?',ref:'Colossians 3:12–15'}),
  Object.freeze({icon:'🤝',title:'Serve Together',question:'What realistic need can you serve together without overcommitting?',ref:'Galatians 5:13'}),
  Object.freeze({icon:'✝️',title:'Us & God',question:'What is one way your relationship can help each of you follow Christ more faithfully this month?',ref:'Hebrews 10:24–25'})
]);
const dateText=value=>{const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleDateString():'Unknown date'};

export function couplesCloudPage({couples,onBack,onAccount}){
  return{
    title:'Couple Journey',
    html:'<section class="bq-panel bq-couples-cloud" data-couples-cloud-view></section>',
    mount(root){
      const view=root.querySelector('[data-couples-cloud-view]');let busy=false,message='',activeStep=null;
      const state=()=>couples.snapshot();
      const messageHtml=()=>message?`<p class="bq-couples-cloud-message" role="status">${esc(message)}</p>`:'';
      const backButton=()=>'<button type="button" class="bq-secondary-button" data-couple-cloud-back>Back to More</button>';
      const authView=()=>{const current=state(),preview=!current.remoteAvailable;view.innerHTML=`<p class="bq-eyebrow">COUPLES · CLOUD</p><h1>Couple Journey</h1><p>${preview?'Couples cloud is disabled in local preview.':'Sign in with your own BibleQuest account before linking with your spouse. Each partner keeps a separate account and password.'}</p><div class="bq-couples-cloud-actions">${preview?'':'<button type="button" class="bq-primary-button" data-couple-cloud-account>Open Account</button>'}${backButton()}</div><div class="bq-couples-cloud-privacy"><b>Privacy rule</b><p>Pairing never shares Private Notes, Transformation results, passwords, or personal account data.</p></div>`;bindCommon()};
      const unpairedView=()=>{view.innerHTML=`<div class="bq-couples-cloud-head"><div><p class="bq-eyebrow">TWO ACCOUNTS · ONE SHARED JOURNEY</p><h1>Grow together without sharing a password.</h1><p>Create a private 8-character pair code, or enter the code your spouse created from their own account.</p></div>${backButton()}</div>${messageHtml()}<div class="bq-couples-cloud-pair-grid"><button type="button" data-couple-cloud-create><span>🔗</span><b>Create pair code</b><small>Share the code only with your spouse.</small></button><form data-couple-cloud-join><b>I have a pair code</b><input name="code" maxlength="8" minlength="8" pattern="[A-Za-z0-9]{8}" autocomplete="off" autocapitalize="characters" placeholder="ABC234XY" required><button type="submit" class="bq-primary-button">Link our accounts</button></form></div><div class="bq-couples-cloud-privacy"><b>Privacy rule</b><p>Only intentionally shared Couple Journey completions, commitments, and pair-linked couples challenge history belong to the pair.</p><p>Private Notes, Transformation results, passwords, and personal account data remain private.</p></div>`;bindCommon();bindPairing()};
      const pendingView=()=>{const current=state();view.innerHTML=`<div class="bq-couples-cloud-head"><div><p class="bq-eyebrow">WAITING FOR YOUR PARTNER</p><h1>Pair request created.</h1><p>${current.inviteCode?`Share this code with your spouse: <strong class="bq-couple-code">${esc(current.inviteCode)}</strong>`:'Generate a fresh code and share it with your spouse.'}</p></div>${backButton()}</div>${messageHtml()}<div class="bq-couples-cloud-actions"><button type="button" class="bq-primary-button" data-couple-cloud-create>${current.inviteCode?'Generate new code':'Get pair code'}</button><button type="button" class="bq-secondary-button" data-couple-cloud-reload>Check if partner joined</button><button type="button" class="bq-secondary-button" data-couple-cloud-leave>Cancel pairing</button></div><p class="bq-couples-cloud-note">Pair codes expire after 14 days. Generating a new code invalidates earlier unused codes for this pair.</p>`;bindCommon();bindPairing();bindActiveActions()};
      const activeView=()=>{const current=state(),rows=current.shared,done=new Set(rows.filter(item=>item.itemType==='journey').map(item=>item.body.split('|')[0])),commitments=rows.filter(item=>item.itemType==='commitment'),challenges=rows.filter(item=>item.itemType==='challenge');view.innerHTML=`<div class="bq-couples-cloud-head"><div><p class="bq-eyebrow">LINKED COUPLE ACCOUNTS</p><h1>One conversation at a time.</h1><p>No marriage score. The goal is honest conversation, better listening, concrete repair, and shared growth with Christ.</p></div><span class="bq-couples-cloud-count">${done.size}/7</span></div>${messageHtml()}<div class="bq-couples-cloud-journey">${JOURNEY.map((item,index)=>`<button type="button" class="${done.has(String(index+1))?'done':''}" data-couple-cloud-step="${index}"><span>${done.has(String(index+1))?'✓':item.icon}</span><div><b>${index+1}. ${esc(item.title)}</b><small>${esc(item.ref)}</small></div></button>`).join('')}</div><h2>Shared commitments</h2>${commitments.length?`<div class="bq-couples-cloud-history">${commitments.slice(0,30).map(item=>`<article><p>${esc(item.body)}</p><small>${esc(dateText(item.createdAt))}</small></article>`).join('')}</div>`:'<p class="bq-couples-cloud-empty">No shared commitments yet.</p>'}${challenges.length?`<h2>Shared challenge progress</h2><div class="bq-couples-cloud-history">${challenges.slice(0,12).map(item=>{const [key,title='Couples Challenge']=item.body.split('|'),day=key.split(':').pop()||'?';return`<article><p>🏁 ${esc(title)} · Day ${esc(day)}</p><small>Pair-linked completion · ${esc(dateText(item.createdAt))}</small></article>`}).join('')}</div>`:''}<div class="bq-couples-cloud-actions"><button type="button" class="bq-secondary-button" data-couple-cloud-reload>Reload shared journey</button>${backButton()}<button type="button" class="bq-secondary-button bq-couples-cloud-danger" data-couple-cloud-leave>Unlink couple accounts</button></div><p class="bq-couples-cloud-note">Shared history is append-only from the app. Individual challenge points remain personal.</p>`;bindCommon();bindActiveActions()};
      const stepView=index=>{activeStep=index;const item=JOURNEY[index];view.innerHTML=`<button type="button" class="bq-secondary-button" data-couple-cloud-journey>← Journey</button><article class="bq-couples-cloud-step"><p class="bq-eyebrow">STEP ${index+1} · ${esc(item.ref)}</p><span class="bq-couples-cloud-step-icon">${item.icon}</span><h1>${esc(item.title)}</h1><p class="bq-couples-cloud-question">${esc(item.question)}</p><div class="bq-couples-cloud-rule"><b>Conversation rule</b><p>Ask before assuming. Paraphrase before disagreeing. Scripture is not a weapon to win against your spouse.</p></div><form data-couple-cloud-complete><label>One shared commitment (optional)<textarea name="commitment" maxlength="800" rows="5" placeholder="This week we will…"></textarea></label><p data-couple-cloud-form-message role="status"></p><button type="submit" class="bq-primary-button">Complete this conversation</button></form></article>`;view.querySelector('[data-couple-cloud-journey]')?.addEventListener('click',activeView,{once:true});view.querySelector('[data-couple-cloud-complete]')?.addEventListener('submit',completeStep)};
      const render=()=>{const current=state();if(!current.authenticated||!current.remoteAvailable)return authView();if(!current.pair||current.pair.status==='ended')return unpairedView();if(current.pair.status==='pending')return pendingView();return activeView()};
      async function load(){if(busy)return;busy=true;view.innerHTML='<p class="bq-eyebrow">COUPLES · CLOUD</p><h1>Couple Journey</h1><p role="status">Loading your shared journey…</p>';try{await couples.load();message='';render()}catch(error){if(error?.code==='BQ_COUPLES_CLOUD_AUTH_REQUIRED'||error?.code==='BQ_COUPLES_CLOUD_REMOTE_DISABLED')authView();else{view.innerHTML=`<p class="bq-eyebrow">COUPLES · CLOUD</p><h1>Couple Journey</h1><p class="bq-couples-cloud-message" role="alert">${esc(error?.message||'Couple Journey could not load.')}</p><div class="bq-couples-cloud-actions"><button type="button" class="bq-secondary-button" data-couple-cloud-reload>Try again</button>${backButton()}</div>`;bindCommon();view.querySelector('[data-couple-cloud-reload]')?.addEventListener('click',load,{once:true})}}finally{busy=false}}
      async function createPair(){if(busy)return;busy=true;try{await couples.createPair();message='Pair code ready.';render()}catch(error){message=error?.message||'Could not create a pair code.';unpairedView()}finally{busy=false}}
      async function joinPair(event){event.preventDefault();if(busy)return;busy=true;const form=event.currentTarget;try{await couples.join(new FormData(form).get('code'));message='Accounts linked.';render()}catch(error){message=error?.message||'Could not link these accounts.';unpairedView()}finally{busy=false}}
      async function leavePair(){if(busy||!window.confirm('Unlink the couple accounts? Existing shared items stay in history, but this pair becomes inactive.'))return;busy=true;try{await couples.leave();message='Couple accounts unlinked.';unpairedView()}catch(error){message=error?.message||'Could not unlink the couple accounts.';render()}finally{busy=false}}
      async function completeStep(event){event.preventDefault();if(busy||activeStep===null)return;busy=true;const form=event.currentTarget,messageNode=form.querySelector('[data-couple-cloud-form-message]');try{const item=JOURNEY[activeStep];await couples.completeJourney(activeStep+1,item.title,new FormData(form).get('commitment'));message='Conversation saved to your shared Couple Journey.';activeStep=null;activeView()}catch(error){if(messageNode)messageNode.textContent=error?.message||'Could not save this shared conversation.'}finally{busy=false}}
      function bindCommon(){view.querySelectorAll('[data-couple-cloud-back]').forEach(button=>button.addEventListener('click',()=>onBack?.(),{once:true}));view.querySelector('[data-couple-cloud-account]')?.addEventListener('click',()=>onAccount?.(),{once:true})}
      function bindPairing(){view.querySelectorAll('[data-couple-cloud-create]').forEach(button=>button.addEventListener('click',createPair,{once:true}));view.querySelector('[data-couple-cloud-join]')?.addEventListener('submit',joinPair,{once:true})}
      function bindActiveActions(){view.querySelectorAll('[data-couple-cloud-reload]').forEach(button=>button.addEventListener('click',load,{once:true}));view.querySelectorAll('[data-couple-cloud-leave]').forEach(button=>button.addEventListener('click',leavePair,{once:true}));view.querySelectorAll('[data-couple-cloud-step]').forEach(button=>button.addEventListener('click',()=>stepView(Number(button.dataset.coupleCloudStep)),{once:true}))}
      load();return()=>{busy=false;activeStep=null};
    }
  };
}
