const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[char]));

export function transformPage({transform,onGrow}){
  return{title:'Transformation',html:'<section data-transform-page><div class="bq-panel"><p>Opening Transformation…</p></div></section>',mount(root){
    const host=root.querySelector('[data-transform-page]');let message='';
    const render=state=>{
      const answers=state.spiritual.answers||{},result=state.spiritual.result,items=transform.definitions.spiritual,answered=items.filter(item=>answers[item.id]).length;
      const resultHtml=result?`<section class="bq-panel bq-transform-result" data-transform-result><p class="bq-eyebrow">PRIVATE REFLECTION</p><h2>Your reflection</h2><p>This is a snapshot of your own answers, not a spiritual grade. Lower ratings simply identify areas you may want to practice deliberately.</p><div class="bq-transform-bars">${result.scores.map(row=>`<div><b>${escapeHtml(row.dimension)}</b><span><i style="width:${row.score*20}%"></i></span><strong>${row.score}/5</strong></div>`).join('')}</div><div class="bq-transform-focus"><h3>Suggested next focus</h3>${result.focus.map(row=>`<article><b>${escapeHtml(row.dimension)}</b><p>${escapeHtml(row.guide)}</p></article>`).join('')}</div></section>`:'';
      host.innerHTML=`<section class="bq-panel bq-transform-head"><p class="bq-eyebrow">TRANSFORMATION</p><h1>Faith & practice reflection</h1><p><b>Important:</b> this is private self-reflection, not a spiritual score, diagnosis, moral ranking, or measure of God’s approval. Use it to notice patterns and choose concrete practices.</p><p class="bq-transform-scale-note">1 = rarely true · 5 = consistently true</p></section><section class="bq-transform-list">${items.map(item=>`<article class="bq-panel bq-transform-item" data-transform-item="${escapeHtml(item.id)}"><div><b>${escapeHtml(item.dimension)}</b><p>${escapeHtml(item.text)}</p></div><div class="bq-transform-scale" role="group" aria-label="${escapeHtml(item.dimension)} rating">${[1,2,3,4,5].map(value=>`<button type="button" data-transform-rating="${escapeHtml(item.id)}" data-value="${value}" class="${answers[item.id]===value?'is-selected':''}" aria-pressed="${answers[item.id]===value}">${value}</button>`).join('')}</div></article>`).join('')}</section><section class="bq-panel bq-transform-actions"><div><b>${answered}/${items.length} answered</b><p class="bq-form-message" data-transform-message aria-live="polite">${escapeHtml(message)}</p></div><div><button type="button" class="bq-secondary-button" data-transform-back>Back to Grow</button><button type="button" class="bq-secondary-button" data-transform-reset ${answered?'':'disabled'}>Reset</button><button type="button" class="bq-primary-button" data-transform-calculate ${answered===items.length?'':'disabled'}>${result?'Reflection saved':'View reflection'}</button></div></section>${resultHtml}`;
    };
    const refresh=()=>render(transform.getState());
    const onClick=event=>{const target=event.target instanceof Element?event.target:null;if(!target)return;const rating=target.closest('[data-transform-rating]');if(rating){try{message='';transform.setSpiritualAnswer(rating.dataset.transformRating,Number(rating.dataset.value));refresh()}catch(error){message=error.message;refresh()}return}if(target.closest('[data-transform-calculate]')){try{const output=transform.calculateSpiritual();message=output.progressResult?.awardedXp?`Reflection saved · +${output.progressResult.awardedXp} XP`:'Reflection saved';render(output.state);queueMicrotask(()=>host.querySelector('[data-transform-result]')?.scrollIntoView({block:'start'}))}catch(error){message=error.message;refresh()}return}if(target.closest('[data-transform-reset]')){if(!window.confirm('Clear all 12 Transformation answers and the current result?'))return;try{message='Assessment cleared.';transform.resetSpiritual();refresh()}catch(error){message=error.message;refresh()}return}if(target.closest('[data-transform-back]'))onGrow()};
    host.addEventListener('click',onClick);
    try{const opened=transform.openBasic();if(opened.progressResult?.awardedXp)message=`Recovered saved reflection · +${opened.progressResult.awardedXp} XP`;render(opened.state)}catch(error){host.innerHTML=`<section class="bq-panel"><h1>Transformation unavailable</h1><p class="bq-form-message">${escapeHtml(error?.message||'Could not open Transformation.')}</p></section>`}
    return()=>host.removeEventListener('click',onClick);
  }};
}
