const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

export function couplesFamilyPage({couples,onBack,onReader}){
  return{
    title:'Grow Together',
    html:'<section class="bq-panel bq-couples" data-couples-view></section>',
    mount(root){
      const view=root.querySelector('[data-couples-view]');
      let session=null,message='';
      const header=(title,back='dashboard')=>`<div class="bq-couples-top"><button type="button" class="bq-secondary-button" data-couples-go="${back}">← ${back==='exit'?'More':'Couples'}</button><b>${esc(title)}</b></div>`;
      const status=()=>message?`<p class="bq-couples-message" role="status">${esc(message)}</p>`:'';
      const dashboard=()=>{
        session=null;const state=couples.snapshot(),active=couples.activePractice();
        view.innerHTML=`<div class="bq-couples-head"><div><p class="bq-eyebrow">COUPLES · LOCAL TO THIS DEVICE</p><h1>Grow Together</h1><p>Love deeper. Listen better. Follow Christ together. Your saved cards, practices and check-ins stay on this device; Couples cloud is a separate later milestone.</p></div><button type="button" class="bq-secondary-button" data-couples-go="exit">Back to More</button></div>${status()}<div class="bq-couples-hero"><b>Hindi contest ang marriage.</b><p>Goal: mas makilala ang isa’t isa, mas maayos makinig, mas mabilis mag-repair, at mas sabay lumago kay Christ.</p></div>${active?`<button type="button" class="bq-couples-active" data-couples-complete-practice><small>ACTIVE 7-DAY PRACTICE</small><b>${esc(active.text)}</b><span>Tap to complete →</span></button>`:''}<div class="bq-couples-mode-grid"><button type="button" data-couples-mode="card"><span>💬</span><b>One Card Tonight</b><small>Isang deep question, then switch.</small></button><button type="button" data-couples-mode="listen"><span>👂</span><b>Listen First</b><small>Practice understanding bago advice.</small></button><button type="button" data-couples-mode="checkin"><span>🌡️</span><b>Couple Check-in</b><small>Pass the phone, then compare gently.</small></button><button type="button" data-couples-mode="repair"><span>🕊️</span><b>Repair Room</b><small>For ordinary conflict, not blame.</small></button><button type="button" data-couples-mode="god"><span>✝️</span><b>Us & God</b><small>Faith, prayer, grace, shared direction.</small></button><button type="button" data-couples-mode="date"><span>✨</span><b>Date Night Deck</b><small>Friendship, gratitude, dreams, closeness.</small></button></div><div class="bq-couples-categories">${couples.categories().map(category=>`<button type="button" data-couples-category="${category.id}"><span>${category.icon}</span><b>${esc(category.label)}</b></button>`).join('')}</div><div class="bq-couples-principles"><b>Conversation rules</b><p>Makinig para maintindihan, hindi para manalo. Huwag gumamit ng Bible verse bilang weapon. Be curious before defensive. Specific behavior &gt; character attack.</p></div><div class="bq-couples-stats"><div><b>${state.history.length}</b><span>cards discussed</span></div><div><b>${state.checkins.length}</b><span>check-ins</span></div><div><b>${state.commitments.filter(item=>item.done).length}</b><span>practices done</span></div></div>`;
        bind();
      };
      const cardView=(card,label='DEEP QUESTION CARD')=>{
        session={kind:'card',card,label};const category=couples.categories().find(item=>item.id===card.cat),saved=couples.isFavorite(card.id);
        view.innerHTML=`${header(category?.label||'Couples')}<article class="bq-couples-card" data-couples-card-id="${card.id}"><div class="bq-couples-card-head"><span>${category?.icon||'💞'}</span><div><small>${esc(label)}</small><h1>${esc(card.title)}</h1></div></div>${status()}<div class="bq-couples-question"><small>PARTNER 1</small><p>${esc(card.prompt)}</p></div><div class="bq-couples-listen-note">Partner 2: huwag muna sumagot. I-paraphrase muna: <b>“Ang narinig ko ay…”</b> Then ask: <b>“Tama ba pagkaintindi ko?”</b></div><div class="bq-couples-question"><small>THEN SWITCH</small><p>${esc(card.follow)}</p></div><div class="bq-couples-scripture"><div><small>READ TOGETHER</small><b>📖 ${esc(card.ref)}</b><span>Open in BibleQuest Reader · BSB</span></div><button type="button" class="bq-secondary-button" data-couples-reader>Read BSB</button></div><div class="bq-couples-practice"><small>ONE SMALL PRACTICE</small><p>${esc(card.practice)}</p></div><div class="bq-couples-actions"><button type="button" class="bq-secondary-button" data-couples-favorite>${saved?'★ Saved':'☆ Save card'}</button><button type="button" class="bq-secondary-button" data-couples-practice>7-day practice</button><button type="button" class="bq-primary-button" data-couples-discussed>✓ Discussed</button></div><button type="button" class="bq-couples-next" data-couples-next>Another card →</button></article>`;
        bind();
      };
      const listenView=(step=0)=>{
        if(!session||session.kind!=='listen')session={kind:'listen',card:couples.pickCard({categories:['communication','conflict']}),step:0};session.step=step;const c=session.card;
        const steps=[`<small>SPEAKER</small><h2>Share for 2 minutes.</h2><p>${esc(c.prompt)}</p><div class="bq-couples-listen-note">No cross-examination. Describe your experience, not your spouse’s character.</div>`,`<small>LISTENER</small><h2>Mirror before response.</h2><p><b>“Ang narinig ko ay…”</b></p><p><b>“Parang mahalaga sa’yo ito dahil…”</b></p><p>Then ask: <b>“Tama ba pagkaintindi ko?”</b></p>`,`<small>SPEAKER</small><h2>Did you feel understood?</h2><div class="bq-couples-understood"><button type="button">Yes</button><button type="button">Almost</button><button type="button">Not yet</button></div><p class="bq-couples-listen-note">If not yet: clarify the missing part. Listener mirrors again—no defending yet.</p>`,`<small>SWITCH</small><h2>Palit ng role.</h2><p>${esc(c.follow)}</p><div class="bq-couples-listen-note">Same rule: understanding first, response second.</div>`,`<small>FINISH</small><h2>One useful sentence each.</h2><p>“Isang bagay na mas naiintindihan ko tungkol sa’yo ngayon ay…”</p><p>“Isang bagay na kaya kong gawin differently ay…”</p>`];
        view.innerHTML=`${header('Listen First')}<div class="bq-couples-progress"><i style="width:${((step+1)/steps.length)*100}%"></i></div><article class="bq-couples-card">${steps[step]}<div class="bq-couples-scripture"><div><small>ANCHOR</small><b>📖 James 1:19</b><span>Quick to listen, slow to speak · read in BSB Reader</span></div></div><div class="bq-couples-actions">${step?'<button type="button" class="bq-secondary-button" data-listen-prev>← Back</button>':''}<button type="button" class="bq-primary-button" data-listen-next>${step===steps.length-1?'Complete':'Next →'}</button></div></article>`;bind();
      };
      const startCheck=()=>{session={kind:'check',partner:1,a:{},b:{}};renderCheck()};
      const renderCheck=()=>{
        if(session.partner===3)return checkResults();
        if(session.partner==='pass'){view.innerHTML=`${header('Couple Check-in')}<div class="bq-couples-pass"><span>📱</span><h1>Pass the phone.</h1><p>Partner 1 done. Ibigay muna sa Partner 2 bago pindutin ang continue. Huwag munang i-discuss ang sagot.</p><button type="button" class="bq-primary-button" data-check-pass>Partner 2 ready</button></div>`;bind();return}
        const who=session.partner===1?'PARTNER 1':'PARTNER 2',answers=session.partner===1?session.a:session.b;
        view.innerHTML=`${header('Couple Check-in')}<div class="bq-couples-check-head"><p class="bq-eyebrow">${who}</p><h1>How did this week feel?</h1><p>1 = hindi ko halos naramdaman · 5 = strongly felt. Walang “correct” score.</p></div><div class="bq-couples-check-list">${couples.checkItems().map(item=>`<label><span>${esc(item.label)}</span><div><input type="range" min="1" max="5" value="${answers[item.id]||3}" data-check="${item.id}"><b data-check-value="${item.id}">${answers[item.id]||3}</b></div></label>`).join('')}</div><button type="button" class="bq-primary-button bq-couples-check-submit" data-check-submit>Save ${who} →</button>`;bind();
      };
      const checkResults=()=>{const result=couples.recordCheckin(session.a,session.b);session={kind:'result'};view.innerHTML=`${header('Check-in Result')}<div class="bq-couples-result"><p class="bq-eyebrow">NO WINNER · NO LOSER</p><h1>Compare with curiosity.</h1><p>Ang difference ng rating ay invitation para magtanong, hindi proof na mali ang isa.</p><div class="bq-couples-highlight good"><small>SHARED STRENGTH</small><b>${esc(result.strong.label)}</b><span>${result.strong.a} / ${result.strong.b}</span></div><div class="bq-couples-highlight"><small>BIGGEST PERCEPTION GAP</small><b>${esc(result.gap.label)}</b><span>${result.gap.a} / ${result.gap.b}</span></div><div class="bq-couples-table">${result.rows.map(row=>`<div><span>${esc(row.label)}</span><b>${row.a}</b><b>${row.b}</b></div>`).join('')}</div><div class="bq-couples-principles"><b>Start here:</b><p>Partner with the lower rating explains first. Other partner asks: “Ano ang isang specific moment this week na nakaapekto sa rating mo?” Then summarize before responding.</p></div><button type="button" class="bq-primary-button" data-couples-go="dashboard">Done</button></div>`;bind()};
      const repairView=(step=0)=>{session={kind:'repair',step};const item=couples.repairSteps()[step];view.innerHTML=`${header('Repair Room')}<div class="bq-couples-safety"><b>Safety boundary</b><p>For ordinary relationship conflict only. If there is fear, threats, coercion, stalking, or violence, huwag i-frame ito as “pareho lang may kasalanan.” Prioritize safety and trusted/professional support.</p></div><article class="bq-couples-card"><small>${esc(item.label)}</small><h1>${esc(item.title)}</h1><p>${esc(item.prompt)}</p><div class="bq-couples-scripture"><div><small>REFLECT</small><b>📖 Ephesians 4:26–32</b><span>Read together in BSB; don’t use the passage to win the argument.</span></div></div><div class="bq-couples-actions">${step?`<button type="button" class="bq-secondary-button" data-repair="${step-1}">← Back</button>`:''}<button type="button" class="bq-primary-button" data-repair="${step+1}">${step===couples.repairSteps().length-1?'Finish':'Next →'}</button></div></article>`;bind()};
      const chooseMode=mode=>{message='';if(mode==='card')return cardView(couples.pickCard());if(mode==='listen')return listenView(0);if(mode==='checkin')return startCheck();if(mode==='repair')return repairView(0);if(mode==='god')return cardView(couples.pickCard({categories:['christ','mission']}),'US & GOD');if(mode==='date')return cardView(couples.pickCard({categories:['gratitude','intimacy','mission']}),'DATE NIGHT CARD')};
      function bind(){
        view.querySelectorAll('[data-couples-go]').forEach(button=>button.addEventListener('click',()=>{const target=button.dataset.couplesGo;if(target==='exit')onBack?.();else dashboard()},{once:true}));
        view.querySelectorAll('[data-couples-mode]').forEach(button=>button.addEventListener('click',()=>chooseMode(button.dataset.couplesMode),{once:true}));
        view.querySelectorAll('[data-couples-category]').forEach(button=>button.addEventListener('click',()=>cardView(couples.pickCard({categoryId:button.dataset.couplesCategory}),couples.categories().find(item=>item.id===button.dataset.couplesCategory)?.label.toUpperCase()),{once:true}));
        view.querySelector('[data-couples-complete-practice]')?.addEventListener('click',()=>{couples.completeActivePractice();message='7-day practice marked complete on this device.';dashboard()},{once:true});
        view.querySelector('[data-couples-favorite]')?.addEventListener('click',()=>{const card=session?.card;if(!card)return;couples.toggleFavorite(card.id);message=couples.isFavorite(card.id)?'Card saved on this device.':'Card removed from saved cards.';cardView(card,session.label)},{once:true});
        view.querySelector('[data-couples-practice]')?.addEventListener('click',()=>{const card=session?.card;if(!card)return;couples.startPractice(card.id);message='7-day practice saved on this device.';dashboard()},{once:true});
        view.querySelector('[data-couples-discussed]')?.addEventListener('click',()=>{const card=session?.card;if(!card)return;couples.markDiscussed(card.id);message='Discussion saved on this device.';cardView(couples.pickCard({excludeId:card.id}))},{once:true});
        view.querySelector('[data-couples-next]')?.addEventListener('click',()=>{const card=session?.card;cardView(couples.pickCard({excludeId:card?.id}))},{once:true});
        view.querySelector('[data-couples-reader]')?.addEventListener('click',()=>{if(session?.card)onReader?.(session.card)},{once:true});
        view.querySelector('[data-listen-next]')?.addEventListener('click',()=>{if(session.step>=4){couples.recordListen();message='Listening practice completed on this device.';dashboard()}else listenView(session.step+1)},{once:true});
        view.querySelector('[data-listen-prev]')?.addEventListener('click',()=>listenView(Math.max(0,session.step-1)),{once:true});
        view.querySelectorAll('[data-check]').forEach(input=>input.addEventListener('input',event=>{const target=view.querySelector(`[data-check-value="${event.currentTarget.dataset.check}"]`),bag=session.partner===1?session.a:session.b;if(target)target.textContent=event.currentTarget.value;bag[event.currentTarget.dataset.check]=Number(event.currentTarget.value)}));
        view.querySelector('[data-check-submit]')?.addEventListener('click',()=>{const bag=session.partner===1?session.a:session.b;for(const item of couples.checkItems())if(!bag[item.id])bag[item.id]=Number(view.querySelector(`[data-check="${item.id}"]`)?.value||3);if(session.partner===1)session.partner='pass';else session.partner=3;renderCheck()},{once:true});
        view.querySelector('[data-check-pass]')?.addEventListener('click',()=>{session.partner=2;renderCheck()},{once:true});
        view.querySelectorAll('[data-repair]').forEach(button=>button.addEventListener('click',()=>{const next=Number(button.dataset.repair);if(next>=couples.repairSteps().length){message='Repair Room walkthrough completed.';dashboard()}else repairView(Math.max(0,next))},{once:true}));
      }
      dashboard();return()=>{session=null};
    }
  };
}
