export const DAILY_VARIETY_CUTOVER = '2026-09-22';

export const DAILY_PASSAGES = Object.freeze([
  Object.freeze({ book:'John', code:'JHN', chapter:15, from:1, to:12, title:'Remain in Christ', prompt:'What does Jesus connect with lasting fruit?', retrieve:Object.freeze({ q:'In John 15, what picture does Jesus use for Himself?', choices:Object.freeze(['The true vine','The city gate','The mustard seed','The lampstand']), answer:0, ref:'John 15:1', why:'Jesus says, “I am the true vine,” and describes His Father as the vinedresser.' }) }),
  Object.freeze({ book:'Matthew', code:'MAT', chapter:5, from:1, to:16, title:'Kingdom Character', prompt:'Which teaching challenges the way you normally respond?', retrieve:Object.freeze({ q:'In Matthew 5:13, what does Jesus call His disciples?', choices:Object.freeze(['Salt of the earth','Kings of the earth','Judges of Israel','Builders of the temple']), answer:0, ref:'Matthew 5:13', why:'Jesus calls His disciples the salt of the earth before also describing them as light.' }) }),
  Object.freeze({ book:'Luke', code:'LUK', chapter:10, from:25, to:37, title:'Love Your Neighbor', prompt:'Who is easy for you to overlook?', retrieve:Object.freeze({ q:'Who stopped and cared for the wounded man in Jesus’ story?', choices:Object.freeze(['A Samaritan','A priest','A Levite','A Roman centurion']), answer:0, ref:'Luke 10:33–35', why:'The Samaritan had compassion, treated the man’s wounds, and arranged continued care.' }) }),
  Object.freeze({ book:'Philippians', code:'PHP', chapter:2, from:1, to:11, title:'The Mind of Christ', prompt:'What does humility look like in one real situation today?', retrieve:Object.freeze({ q:'According to Philippians 2, whose mindset are believers told to have?', choices:Object.freeze(['Christ Jesus','Caesar','Moses alone','The philosophers']), answer:0, ref:'Philippians 2:5', why:'Paul tells believers to have the same mindset that was in Christ Jesus.' }) }),
  Object.freeze({ book:'James', code:'JAS', chapter:1, from:19, to:27, title:'Hear and Do', prompt:'Where do you need to move from hearing to doing?', retrieve:Object.freeze({ q:'James says believers should be doers of what?', choices:Object.freeze(['The word','Their own plans','Public opinion','Signs and wonders']), answer:0, ref:'James 1:22', why:'James warns against hearing the word without putting it into practice.' }) }),
  Object.freeze({ book:'Romans', code:'ROM', chapter:12, from:1, to:21, title:'A Living Sacrifice', prompt:'What practical act of love can you do today?', retrieve:Object.freeze({ q:'Romans 12:1 urges believers to present their bodies as what?', choices:Object.freeze(['A living sacrifice','A public monument','A royal offering','A hidden treasure']), answer:0, ref:'Romans 12:1', why:'Paul appeals to believers to present their bodies as a living, holy sacrifice acceptable to God.' }) }),
  Object.freeze({ book:'Psalms', code:'PSA', chapter:23, from:1, to:6, title:'The Shepherd', prompt:'Which line speaks most directly to your present situation?', retrieve:Object.freeze({ q:'Psalm 23 begins, “The LORD is my…” what?', choices:Object.freeze(['Shepherd','Judge','Teacher','Messenger']), answer:0, ref:'Psalm 23:1', why:'Psalm 23 opens with the confession that the LORD is the psalmist’s shepherd.' }) }),
  Object.freeze({ book:'Proverbs', code:'PRO', chapter:3, from:1, to:12, title:'Trust the Lord', prompt:'What are you tempted to lean on instead of God?', retrieve:Object.freeze({ q:'Proverbs 3:5 says not to lean on what?', choices:Object.freeze(['Your own understanding','Your neighbor','Your work','Your possessions']), answer:0, ref:'Proverbs 3:5', why:'The passage says to trust in the LORD with all your heart and not lean on your own understanding.' }) }),
  Object.freeze({ book:'1 Corinthians', code:'1CO', chapter:13, from:1, to:13, title:'The Way of Love', prompt:'Which description of love is hardest to practice?', retrieve:Object.freeze({ q:'At the end of 1 Corinthians 13, which is called the greatest?', choices:Object.freeze(['Love','Faith','Hope','Knowledge']), answer:0, ref:'1 Corinthians 13:13', why:'Faith, hope, and love remain, and Paul says the greatest of these is love.' }) }),
  Object.freeze({ book:'Galatians', code:'GAL', chapter:5, from:13, to:26, title:'Walk by the Spirit', prompt:'Which fruit of the Spirit needs deliberate practice today?', retrieve:Object.freeze({ q:'Which of these is named as fruit of the Spirit in Galatians 5?', choices:Object.freeze(['Self-control','Pride','Jealousy','Rivalry']), answer:0, ref:'Galatians 5:22–23', why:'The fruit of the Spirit includes love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control.' }) }),
  Object.freeze({ book:'Ephesians', code:'EPH', chapter:6, from:10, to:20, title:'Stand Firm', prompt:'Where do you most need to stand firm rather than react impulsively?', retrieve:Object.freeze({ q:'In Ephesians 6, what is described as the belt in the armor of God?', choices:Object.freeze(['Truth','Peace','Faith','Salvation']), answer:0, ref:'Ephesians 6:14', why:'Paul tells believers to stand with the belt of truth fastened around them.' }) }),
  Object.freeze({ book:'Micah', code:'MIC', chapter:6, from:6, to:8, title:'What the Lord Requires', prompt:'Which part of justice, mercy, or humility needs attention in your life today?', retrieve:Object.freeze({ q:'Micah 6:8 says to walk in what way with God?', choices:Object.freeze(['Humbly','Fearfully','Secretly','Silently']), answer:0, ref:'Micah 6:8', why:'Micah summarizes the response God requires as doing justice, loving mercy, and walking humbly with God.' }) }),
  Object.freeze({ book:'Colossians', code:'COL', chapter:3, from:12, to:17, title:'Put On Love', prompt:'What would compassion or forgiveness look like in one relationship today?', retrieve:Object.freeze({ q:'Above all these virtues, what does Colossians 3 tell believers to put on?', choices:Object.freeze(['Love','Success','Influence','Silence']), answer:0, ref:'Colossians 3:14', why:'Paul says to put on love, which binds the virtues together in perfect unity.' }) }),
  Object.freeze({ book:'Hebrews', code:'HEB', chapter:12, from:1, to:3, title:'Run with Endurance', prompt:'What weight or distraction is slowing your faithful next step?', retrieve:Object.freeze({ q:'Hebrews 12 says believers should fix their eyes on whom?', choices:Object.freeze(['Jesus','Moses','Abraham','The crowd']), answer:0, ref:'Hebrews 12:2', why:'The passage calls believers to run with endurance while fixing their eyes on Jesus.' }) }),
  Object.freeze({ book:'1 Peter', code:'1PE', chapter:5, from:6, to:11, title:'Cast Your Cares', prompt:'What anxiety can you entrust to God instead of carrying alone?', retrieve:Object.freeze({ q:'According to 1 Peter 5:7, why can believers cast their anxiety on God?', choices:Object.freeze(['Because He cares for them','Because anxiety is imaginary','Because trouble always disappears','Because other people cannot help']), answer:0, ref:'1 Peter 5:7', why:'Peter tells believers to cast all their anxiety on God because He cares for them.' }) }),
  Object.freeze({ book:'Isaiah', code:'ISA', chapter:40, from:28, to:31, title:'Renewed Strength', prompt:'Where are you weary, and what would waiting on the Lord look like there?', retrieve:Object.freeze({ q:'Isaiah 40 says those who hope in the LORD will renew what?', choices:Object.freeze(['Their strength','Their wealth','Their reputation','Their plans']), answer:0, ref:'Isaiah 40:31', why:'Isaiah says those who hope in the LORD will renew their strength.' }) }),
  Object.freeze({ book:'Joshua', code:'JOS', chapter:1, from:1, to:9, title:'Strong and Courageous', prompt:'What faithful action are you avoiding because it feels intimidating?', retrieve:Object.freeze({ q:'What repeated command does God give Joshua in Joshua 1?', choices:Object.freeze(['Be strong and courageous','Build a larger army','Return to Egypt','Wait for another leader']), answer:0, ref:'Joshua 1:6–9', why:'God repeatedly tells Joshua to be strong and courageous as he leads the people forward.' }) }),
  Object.freeze({ book:'Genesis', code:'GEN', chapter:12, from:1, to:9, title:'Go Where God Leads', prompt:'What step of obedience requires trust before you can see the whole outcome?', retrieve:Object.freeze({ q:'Who is told to leave his country and go to the land God would show him?', choices:Object.freeze(['Abram','Joseph','Moses','David']), answer:0, ref:'Genesis 12:1', why:'The LORD tells Abram to leave his country, people, and father’s household for the land He would show him.' }) }),
  Object.freeze({ book:'Exodus', code:'EXO', chapter:3, from:1, to:15, title:'Called by Name', prompt:'Where might God be calling you to pay closer attention and respond?', retrieve:Object.freeze({ q:'What unusual sight drew Moses’ attention in Exodus 3?', choices:Object.freeze(['A bush burning without being consumed','A river turning to blood','A pillar of fire moving','A mountain splitting open']), answer:0, ref:'Exodus 3:2–3', why:'Moses saw a bush that was on fire but did not burn up, and he went over to look.' }) }),
  Object.freeze({ book:'Deuteronomy', code:'DEU', chapter:6, from:4, to:9, title:'Love God Wholeheartedly', prompt:'What ordinary part of your day could become a place to remember God’s word?', retrieve:Object.freeze({ q:'Deuteronomy 6 says to love the LORD with all your heart, soul, and what else?', choices:Object.freeze(['Strength','Possessions','Status','Knowledge']), answer:0, ref:'Deuteronomy 6:5', why:'The command is to love the LORD with all your heart, all your soul, and all your strength.' }) }),
  Object.freeze({ book:'Psalms', code:'PSA', chapter:1, from:1, to:6, title:'Planted by Streams', prompt:'What habit is shaping your thoughts most strongly right now?', retrieve:Object.freeze({ q:'Psalm 1 compares the faithful person to what?', choices:Object.freeze(['A tree planted by streams of water','A tower on a hill','A ship on the sea','A lamp in a house']), answer:0, ref:'Psalm 1:3', why:'The psalm compares that person to a tree planted by streams of water that yields fruit in season.' }) }),
  Object.freeze({ book:'Psalms', code:'PSA', chapter:46, from:1, to:11, title:'Be Still', prompt:'What fear becomes smaller when you remember who God is?', retrieve:Object.freeze({ q:'Psalm 46:10 begins with which instruction?', choices:Object.freeze(['Be still','Run quickly','Speak loudly','Build walls']), answer:0, ref:'Psalm 46:10', why:'Psalm 46:10 says, “Be still, and know that I am God.”' }) }),
  Object.freeze({ book:'Proverbs', code:'PRO', chapter:15, from:1, to:4, title:'A Gentle Answer', prompt:'Which conversation today would benefit from a gentler response?', retrieve:Object.freeze({ q:'According to Proverbs 15:1, what turns away wrath?', choices:Object.freeze(['A gentle answer','A stronger argument','Silence in every case','Public correction']), answer:0, ref:'Proverbs 15:1', why:'Proverbs says a gentle answer turns away wrath, while a harsh word stirs up anger.' }) }),
  Object.freeze({ book:'Matthew', code:'MAT', chapter:6, from:25, to:34, title:'Do Not Worry', prompt:'What concern is taking more attention than today’s faithful responsibility?', retrieve:Object.freeze({ q:'What creatures does Jesus point to as an example of the Father’s care in Matthew 6?', choices:Object.freeze(['Birds of the air','Fish of the sea','Horses in a field','Lions in the wilderness']), answer:0, ref:'Matthew 6:26', why:'Jesus tells His listeners to look at the birds of the air and consider how the heavenly Father feeds them.' }) }),
  Object.freeze({ book:'Mark', code:'MRK', chapter:10, from:35, to:45, title:'Greatness Through Service', prompt:'Who can you serve without needing recognition for it?', retrieve:Object.freeze({ q:'In Mark 10:45, the Son of Man says He came to do what?', choices:Object.freeze(['Serve and give His life','Claim an earthly throne','Avoid suffering','Gather political power']), answer:0, ref:'Mark 10:45', why:'Jesus says the Son of Man came not to be served but to serve and to give His life as a ransom for many.' }) }),
  Object.freeze({ book:'Luke', code:'LUK', chapter:15, from:11, to:32, title:'The Welcoming Father', prompt:'Where do you need either repentance or a more gracious welcome toward someone else?', retrieve:Object.freeze({ q:'What did the father do when he saw his returning son while he was still far away?', choices:Object.freeze(['Ran to him and embraced him','Sent a servant to question him','Closed the gate','Demanded repayment first']), answer:0, ref:'Luke 15:20', why:'The father was filled with compassion, ran to his son, embraced him, and kissed him.' }) }),
  Object.freeze({ book:'John', code:'JHN', chapter:13, from:1, to:17, title:'Jesus Washes Feet', prompt:'What humble act of service can you do for someone today?', retrieve:Object.freeze({ q:'What did Jesus wash during the meal in John 13?', choices:Object.freeze(['His disciples’ feet','The serving cups','The doorway','The disciples’ hands']), answer:0, ref:'John 13:5', why:'Jesus poured water into a basin and began washing His disciples’ feet.' }) }),
  Object.freeze({ book:'Acts', code:'ACT', chapter:2, from:42, to:47, title:'Devoted Together', prompt:'Which practice of the early believers could strengthen your Christian community life?', retrieve:Object.freeze({ q:'Acts 2:42 says the believers devoted themselves to the apostles’ teaching, fellowship, breaking of bread, and what?', choices:Object.freeze(['Prayer','Travel','Fasting only','Debate']), answer:0, ref:'Acts 2:42', why:'The verse lists the apostles’ teaching, fellowship, breaking of bread, and prayer.' }) }),
  Object.freeze({ book:'Romans', code:'ROM', chapter:8, from:31, to:39, title:'Nothing Can Separate', prompt:'Which fear needs to be answered by the security of God’s love in Christ?', retrieve:Object.freeze({ q:'Romans 8 concludes that what can separate believers from the love of God in Christ?', choices:Object.freeze(['Nothing in all creation','Only hardship','Only persecution','Only death']), answer:0, ref:'Romans 8:38–39', why:'Paul lists many powers and circumstances and concludes that nothing in all creation can separate believers from God’s love in Christ Jesus.' }) }),
  Object.freeze({ book:'Ephesians', code:'EPH', chapter:2, from:1, to:10, title:'Saved by Grace', prompt:'How does grace reshape the way you view both achievement and good works?', retrieve:Object.freeze({ q:'Ephesians 2 says people are saved by grace through what?', choices:Object.freeze(['Faith','Perfect performance','Religious status','Family background']), answer:0, ref:'Ephesians 2:8', why:'Paul writes that believers have been saved by grace through faith, and that this is God’s gift.' }) }),
  Object.freeze({ book:'Ruth', code:'RUT', chapter:1, from:6, to:18, title:'Faithful Commitment', prompt:'Where is faithful presence more important than convenience today?', retrieve:Object.freeze({ q:'Who chose to stay with Naomi and go with her to Judah?', choices:Object.freeze(['Ruth','Orpah','Miriam','Deborah']), answer:0, ref:'Ruth 1:16–18', why:'Ruth chose to remain with Naomi and committed herself to Naomi’s people and God.' }) }),
  Object.freeze({ book:'1 Samuel', code:'1SA', chapter:16, from:1, to:13, title:'God Looks at the Heart', prompt:'Where are you tempted to judge by appearance rather than character?', retrieve:Object.freeze({ q:'Whom did Samuel finally anoint among Jesse’s sons?', choices:Object.freeze(['David','Eliab','Abinadab','Shammah']), answer:0, ref:'1 Samuel 16:12–13', why:'After the older brothers passed before Samuel, David was brought in and Samuel anointed him.' }) }),
  Object.freeze({ book:'2 Samuel', code:'2SA', chapter:9, from:1, to:13, title:'Kindness for Jonathan’s Sake', prompt:'Who could receive kindness from you without being able to repay it?', retrieve:Object.freeze({ q:'Whom did David welcome to eat regularly at the king’s table?', choices:Object.freeze(['Mephibosheth','Joab','Absalom','Nathan']), answer:0, ref:'2 Samuel 9:7–13', why:'David showed covenant kindness to Jonathan’s son Mephibosheth and gave him a place at the king’s table.' }) }),
  Object.freeze({ book:'1 Kings', code:'1KI', chapter:3, from:5, to:14, title:'Ask for Wisdom', prompt:'What decision today requires wisdom more than speed or confidence?', retrieve:Object.freeze({ q:'What did Solomon ask God to give him for leading the people?', choices:Object.freeze(['A discerning heart','A larger army','Long life first','More territory']), answer:0, ref:'1 Kings 3:9', why:'Solomon asked for a discerning heart so he could govern the people and distinguish right from wrong.' }) }),
  Object.freeze({ book:'Nehemiah', code:'NEH', chapter:2, from:11, to:20, title:'Rise and Build', prompt:'What broken situation can you begin addressing with prayerful, practical action?', retrieve:Object.freeze({ q:'What did Nehemiah invite the people of Jerusalem to rebuild?', choices:Object.freeze(['The city wall','The royal palace','The temple altar only','The road to Egypt']), answer:0, ref:'Nehemiah 2:17', why:'Nehemiah described Jerusalem’s ruined condition and called the people to rebuild its wall.' }) }),
  Object.freeze({ book:'Esther', code:'EST', chapter:4, from:10, to:17, title:'Courage for This Moment', prompt:'Where might courage require you to act even when the outcome is uncertain?', retrieve:Object.freeze({ q:'What did Esther ask the Jews in Susa to do before she approached the king?', choices:Object.freeze(['Fast for her','Leave the city','Prepare weapons','Send gifts']), answer:0, ref:'Esther 4:15–16', why:'Esther asked the Jews in Susa to fast for her before she went to the king.' }) }),
  Object.freeze({ book:'Job', code:'JOB', chapter:1, from:20, to:22, title:'Worship in Loss', prompt:'What truth about God do you need to hold onto in disappointment or loss?', retrieve:Object.freeze({ q:'What did Job do after hearing of his devastating losses?', choices:Object.freeze(['He worshiped','He left the land','He blamed his servants','He demanded a new family']), answer:0, ref:'Job 1:20–22', why:'Job grieved deeply, yet he bowed down in worship and did not charge God with wrongdoing.' }) }),
  Object.freeze({ book:'Psalms', code:'PSA', chapter:27, from:1, to:6, title:'The Lord Is My Light', prompt:'Which fear needs to be faced with confidence in God rather than avoidance?', retrieve:Object.freeze({ q:'Psalm 27 begins by calling the LORD the psalmist’s light and what?', choices:Object.freeze(['Salvation','Harvest','Shelter only','Teacher']), answer:0, ref:'Psalm 27:1', why:'The psalm opens by confessing that the LORD is the psalmist’s light and salvation.' }) }),
  Object.freeze({ book:'Psalms', code:'PSA', chapter:121, from:1, to:8, title:'Help from the Lord', prompt:'Where do you need to remember that your help is not limited to your own strength?', retrieve:Object.freeze({ q:'Psalm 121 says the psalmist’s help comes from whom?', choices:Object.freeze(['The LORD','The mountains','The king','The army']), answer:0, ref:'Psalm 121:1–2', why:'The psalmist says help comes from the LORD, the Maker of heaven and earth.' }) }),
  Object.freeze({ book:'Proverbs', code:'PRO', chapter:4, from:20, to:27, title:'Guard Your Heart', prompt:'What influence deserves closer attention because it is shaping your inner life?', retrieve:Object.freeze({ q:'Proverbs 4:23 says to guard what above all else?', choices:Object.freeze(['Your heart','Your reputation','Your money','Your schedule']), answer:0, ref:'Proverbs 4:23', why:'The passage tells the reader to guard the heart because the issues of life flow from it.' }) }),
  Object.freeze({ book:'Ecclesiastes', code:'ECC', chapter:3, from:1, to:8, title:'A Time for Everything', prompt:'What season are you in, and what faithful response fits this season?', retrieve:Object.freeze({ q:'Ecclesiastes 3 says there is a time for every what?', choices:Object.freeze(['Purpose under heaven','Nation to rule','Person to prosper','Question to be answered']), answer:0, ref:'Ecclesiastes 3:1', why:'The passage introduces its poem by saying there is a season and a time for every purpose under heaven.' }) }),
  Object.freeze({ book:'Isaiah', code:'ISA', chapter:6, from:1, to:8, title:'Here I Am, Send Me', prompt:'Where could willingness to serve matter more than feeling fully prepared?', retrieve:Object.freeze({ q:'How did Isaiah respond when the Lord asked whom He should send?', choices:Object.freeze(['Here I am; send me','Send someone stronger','Give me more time','I cannot hear You']), answer:0, ref:'Isaiah 6:8', why:'Isaiah responded to the Lord’s call with willingness: “Here I am; send me.”' }) }),
  Object.freeze({ book:'Jeremiah', code:'JER', chapter:29, from:4, to:14, title:'Seek God Wholeheartedly', prompt:'What would seeking God wholeheartedly look like in your present circumstances?', retrieve:Object.freeze({ q:'Jeremiah 29 says the people will find God when they seek Him with what?', choices:Object.freeze(['All their heart','Perfect circumstances','Public influence','Material success']), answer:0, ref:'Jeremiah 29:13', why:'The promise says they will seek God and find Him when they seek Him with all their heart.' }) }),
  Object.freeze({ book:'Lamentations', code:'LAM', chapter:3, from:21, to:26, title:'New Mercies', prompt:'What reason for hope can you deliberately remember today?', retrieve:Object.freeze({ q:'Lamentations 3 says the Lord’s mercies are new when?', choices:Object.freeze(['Every morning','Every seventh year','Only after success','Only in the temple']), answer:0, ref:'Lamentations 3:22–23', why:'The passage says the Lord’s steadfast love does not cease and His mercies are new every morning.' }) }),
  Object.freeze({ book:'Ezekiel', code:'EZK', chapter:36, from:24, to:28, title:'A New Heart', prompt:'What inner change do you need God to form rather than merely an outward adjustment?', retrieve:Object.freeze({ q:'What does God promise to give His people in Ezekiel 36?', choices:Object.freeze(['A new heart and a new spirit','A new capital city','A stronger army','A new trade route']), answer:0, ref:'Ezekiel 36:26', why:'God promises to give His people a new heart and put a new spirit within them.' }) }),
  Object.freeze({ book:'Daniel', code:'DAN', chapter:3, from:13, to:28, title:'Faithful Under Pressure', prompt:'Where are you pressured to compromise a conviction simply to fit in?', retrieve:Object.freeze({ q:'Why were Shadrach, Meshach, and Abednego thrown into the furnace?', choices:Object.freeze(['They would not worship the king’s image','They refused to pay taxes','They left Babylon','They challenged Daniel']), answer:0, ref:'Daniel 3:16–20', why:'They refused to worship Nebuchadnezzar’s image, even under threat of the fiery furnace.' }) }),
  Object.freeze({ book:'Jonah', code:'JON', chapter:3, from:1, to:10, title:'Respond to God’s Warning', prompt:'Where do you need to respond to correction instead of defending your current path?', retrieve:Object.freeze({ q:'How did the people of Nineveh respond to Jonah’s warning?', choices:Object.freeze(['They believed God and turned from evil','They expelled Jonah immediately','They ignored him completely','They attacked Israel']), answer:0, ref:'Jonah 3:5–10', why:'The people believed God, humbled themselves, and turned from their evil ways.' }) }),
  Object.freeze({ book:'Matthew', code:'MAT', chapter:11, from:28, to:30, title:'Come and Rest', prompt:'What burden do you need to bring to Jesus rather than carrying alone?', retrieve:Object.freeze({ q:'Whom does Jesus invite to come to Him in Matthew 11:28?', choices:Object.freeze(['Those who are weary and burdened','Only religious leaders','Only the wealthy','Only His twelve disciples']), answer:0, ref:'Matthew 11:28', why:'Jesus invites the weary and burdened to come to Him and receive rest.' }) }),
  Object.freeze({ book:'Matthew', code:'MAT', chapter:22, from:34, to:40, title:'Love God and Neighbor', prompt:'What would wholehearted love for God and practical love for a neighbor look like today?', retrieve:Object.freeze({ q:'What two loves summarize the greatest commandments in Matthew 22?', choices:Object.freeze(['Love God and love your neighbor','Love wisdom and wealth','Love work and rest','Love family and nation']), answer:0, ref:'Matthew 22:37–40', why:'Jesus summarizes the law with wholehearted love for God and love for one’s neighbor.' }) }),
  Object.freeze({ book:'Mark', code:'MRK', chapter:2, from:1, to:12, title:'Faith That Brings a Friend', prompt:'Who might need practical help from you to get closer to Jesus?', retrieve:Object.freeze({ q:'How did the friends bring the paralyzed man to Jesus when the house was crowded?', choices:Object.freeze(['They lowered him through the roof','They waited outside for days','They asked soldiers to clear the room','They carried him to the synagogue']), answer:0, ref:'Mark 2:3–4', why:'The friends opened the roof above Jesus and lowered the man down on his mat.' }) }),
  Object.freeze({ book:'Luke', code:'LUK', chapter:5, from:1, to:11, title:'Follow Me', prompt:'What familiar security might you need to hold more loosely in order to obey Jesus?', retrieve:Object.freeze({ q:'What new kind of work did Jesus tell Simon he would do?', choices:Object.freeze(['Catch people','Build boats','Collect taxes','Teach in Jerusalem']), answer:0, ref:'Luke 5:10–11', why:'Jesus told Simon not to be afraid and said that from then on he would catch people.' }) }),
  Object.freeze({ book:'John', code:'JHN', chapter:4, from:4, to:26, title:'Living Water', prompt:'Where are you looking for satisfaction that cannot carry the weight of your deepest needs?', retrieve:Object.freeze({ q:'What did Jesus offer the Samaritan woman at the well?', choices:Object.freeze(['Living water','A new home','A place in Jerusalem','A royal position']), answer:0, ref:'John 4:10–14', why:'Jesus spoke to the Samaritan woman about the living water He could give.' }) }),
  Object.freeze({ book:'John', code:'JHN', chapter:20, from:19, to:31, title:'From Doubt to Faith', prompt:'What honest doubt or question should you bring into the light rather than hide?', retrieve:Object.freeze({ q:'Which disciple said he wanted to see and touch Jesus’ wounds before believing?', choices:Object.freeze(['Thomas','Andrew','Philip','James']), answer:0, ref:'John 20:24–29', why:'Thomas said he needed to see the wounds; later Jesus met him and called him to believe.' }) }),
  Object.freeze({ book:'Acts', code:'ACT', chapter:9, from:1, to:19, title:'A Life Redirected', prompt:'Where might God be redirecting a plan, identity, or assumption you have held tightly?', retrieve:Object.freeze({ q:'Who was sent to Saul in Damascus after Saul encountered Jesus?', choices:Object.freeze(['Ananias','Barnabas','Peter','Philip']), answer:0, ref:'Acts 9:10–17', why:'The Lord sent a disciple named Ananias to Saul, despite Ananias’s initial fear.' }) }),
  Object.freeze({ book:'Acts', code:'ACT', chapter:16, from:22, to:34, title:'Faith in the Night', prompt:'How can you practice faithful worship or witness in a difficult situation?', retrieve:Object.freeze({ q:'What were Paul and Silas doing in prison around midnight?', choices:Object.freeze(['Praying and singing hymns','Planning an escape','Arguing with the jailer','Writing to Rome']), answer:0, ref:'Acts 16:25', why:'Paul and Silas were praying and singing hymns to God while the other prisoners listened.' }) }),
  Object.freeze({ book:'1 Corinthians', code:'1CO', chapter:12, from:12, to:27, title:'One Body, Many Parts', prompt:'Whose contribution do you need to value instead of comparing it with your own?', retrieve:Object.freeze({ q:'What image does Paul use for believers with many different members and gifts?', choices:Object.freeze(['One body with many parts','One army with one rank','One school with one teacher','One field with one crop']), answer:0, ref:'1 Corinthians 12:12–27', why:'Paul compares the church to one body made up of many parts that need one another.' }) }),
  Object.freeze({ book:'2 Corinthians', code:'2CO', chapter:5, from:14, to:21, title:'New Creation', prompt:'What old pattern needs to give way to the new life Christ is forming in you?', retrieve:Object.freeze({ q:'What does 2 Corinthians 5 call someone who is in Christ?', choices:Object.freeze(['A new creation','A perfect judge','A hidden prophet','A ruler of nations']), answer:0, ref:'2 Corinthians 5:17', why:'Paul says that if anyone is in Christ, that person is a new creation.' }) }),
  Object.freeze({ book:'Philippians', code:'PHP', chapter:4, from:4, to:9, title:'Practice What Is True', prompt:'What thought deserves less attention, and what true or honorable thing can replace it?', retrieve:Object.freeze({ q:'Philippians 4 tells believers to think about things that are true, honorable, just, pure, lovely, and what else?', choices:Object.freeze(['Commendable','Profitable','Popular','Easy']), answer:0, ref:'Philippians 4:8', why:'Paul lists qualities including what is true, honorable, just, pure, lovely, and commendable.' }) }),
  Object.freeze({ book:'Colossians', code:'COL', chapter:1, from:15, to:20, title:'Christ Above All', prompt:'What area of life needs to be reordered around the supremacy of Christ?', retrieve:Object.freeze({ q:'Colossians 1 calls Christ the image of whom?', choices:Object.freeze(['The invisible God','The Roman emperor','Moses','The church']), answer:0, ref:'Colossians 1:15', why:'The passage calls Christ the image of the invisible God and describes His supremacy over creation.' }) }),
  Object.freeze({ book:'2 Timothy', code:'2TI', chapter:3, from:14, to:17, title:'Equipped by Scripture', prompt:'What part of Scripture can you return to for teaching, correction, or training today?', retrieve:Object.freeze({ q:'According to 2 Timothy 3, Scripture is useful for teaching, rebuking, correcting, and what?', choices:Object.freeze(['Training in righteousness','Predicting every event','Winning arguments','Gaining status']), answer:0, ref:'2 Timothy 3:16', why:'Paul says Scripture is useful for teaching, rebuking, correcting, and training in righteousness.' }) })
]);

const LEGACY_PASSAGE_COUNT = 10;
const APPLY_PROMPTS = Object.freeze([
  'Write one concrete action you can take today because of this passage.',
  'Name one specific choice you can make today that reflects this passage.',
  'What is one small act of obedience you can practice before the day ends?',
  'Identify one relationship, task, or decision where you can apply this passage today.',
  'Write one behavior you will start, stop, or change because of what you read.',
  'Turn the passage into one practical next step you can actually complete today.'
]);
const REFLECT_PROMPTS = Object.freeze([
  'Write one sentence you want to remember from today’s journey.',
  'What truth from this passage do you most want to carry into tomorrow?',
  'Summarize today’s passage in one sentence you can recall later.',
  'What did this passage correct, encourage, or clarify for you today?',
  'Write one short reminder from this passage that would help you under pressure.',
  'What is the clearest thing you learned or noticed in today’s journey?'
]);

function serialFor(dateKey) {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(dateKey || ''));
  if (!match) throw new Error('Daily Journey requires a YYYY-MM-DD civil date.');
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const stamp = Date.UTC(year, month - 1, day);
  const check = new Date(stamp);
  if (check.getUTCFullYear() !== year || check.getUTCMonth() !== month - 1 || check.getUTCDate() !== day) throw new Error('Daily Journey civil date is invalid.');
  return Math.floor(stamp / 86400000);
}

function seededNumber(text) {
  let hash = 2166136261;
  for (const char of String(text)) {
    hash ^= char.codePointAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

function seededShuffle(values, seedText) {
  const output = [...values];
  let seed = seededNumber(seedText) || 1;
  for (let index = output.length - 1; index > 0; index--) {
    seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
    const swap = seed % (index + 1);
    [output[index], output[swap]] = [output[swap], output[index]];
  }
  return output;
}

function legacyDate(dateKey) {
  return String(dateKey) < DAILY_VARIETY_CUTOVER;
}

export function selectDailyPassage(dateKey) {
  const serial = serialFor(dateKey);
  if (legacyDate(dateKey)) {
    const index = ((serial % LEGACY_PASSAGE_COUNT) + LEGACY_PASSAGE_COUNT) % LEGACY_PASSAGE_COUNT;
    return DAILY_PASSAGES[index];
  }
  const cutoverSerial = serialFor(DAILY_VARIETY_CUTOVER);
  const offset = serial - cutoverSerial;
  const startIndex = LEGACY_PASSAGE_COUNT;
  const index = ((startIndex + offset) % DAILY_PASSAGES.length + DAILY_PASSAGES.length) % DAILY_PASSAGES.length;
  return DAILY_PASSAGES[index];
}

function retrievalFor(dateKey, passage) {
  if (legacyDate(dateKey)) return passage.retrieve;
  const shuffled = seededShuffle(passage.retrieve.choices, `${dateKey}:${passage.code}:${passage.chapter}:retrieve`);
  const correct = passage.retrieve.choices[passage.retrieve.answer];
  return Object.freeze({
    ...passage.retrieve,
    choices:Object.freeze(shuffled),
    answer:shuffled.indexOf(correct)
  });
}

function promptFor(list, dateKey, salt) {
  return list[seededNumber(`${dateKey}:${salt}`) % list.length];
}

export function buildDailyMissionDefinition(dateKey) {
  const passage = selectDailyPassage(dateKey);
  const retrieve = retrievalFor(dateKey, passage);
  const reference = `${passage.book} ${passage.chapter}:${passage.from}–${passage.to}`;
  const legacy = legacyDate(dateKey);
  return Object.freeze({
    id: `daily-mission:${dateKey}`,
    version: legacy ? 1 : 2,
    title: `Daily Journey · ${passage.title}`,
    steps: Object.freeze([
      Object.freeze({ id:'retrieve', type:'choice', prompt:retrieve.q, choices:retrieve.choices, answer:retrieve.answer, reference:retrieve.ref, feedback:Object.freeze({ correct:retrieve.why, incorrect:retrieve.why }) }),
      Object.freeze({ id:'context', type:'confirm', prompt:`Read ${reference} in the Bible Reader. Notice who is speaking, who is listening, and what comes before and after the key lines.`, reference, feedback:Object.freeze({ response:'Passage reading confirmed.' }) }),
      Object.freeze({ id:'learn', type:'confirm', prompt:passage.prompt, reference, feedback:Object.freeze({ response:'Connection reviewed.' }) }),
      Object.freeze({ id:'apply', type:'text', prompt:legacy ? APPLY_PROMPTS[0] : promptFor(APPLY_PROMPTS, dateKey, 'apply'), reference, maxLength:1200, feedback:Object.freeze({ response:'Action saved.' }) }),
      Object.freeze({ id:'reflect', type:'text', prompt:legacy ? REFLECT_PROMPTS[0] : promptFor(REFLECT_PROMPTS, dateKey, 'reflect'), reference, maxLength:1200, feedback:Object.freeze({ response:'Reflection saved.' }) })
    ])
  });
}
