const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function groupCards(rows){if(!rows.length)return '<section class="bq-account-section bq-journey-groups-empty"><p class="bq-eyebrow">YOUR GROUPS</p><h2>No Journey Group yet</h2><p>Join with an 8-character code, or ask a congregation leader to create a group.</p></section>';return rows.map(group=>`<article class="bq-account-section bq-journey-group-card" data-journey-group="${esc(group.id)}"><div class="bq-journey-group-head"><div><p class="bq-eyebrow">${group.isLeader?'LEADER':'MEMBER'}</p><h2>${esc(group.name)}</h2></div><strong>${group.memberCount}/${group.maxMembers}</strong></div>${group.scheduleText?`<p><b>Schedule:</b> ${esc(group.scheduleText)}</p>`:''}${group.description?`<p>${esc(group.description)}</p>`:''}<p>${esc(String(group.memberCount))} active member${group.memberCount===1?'':'s'} · Your role: ${esc(group.role)}</p><div class="bq-account-actions">${group.isLeader?`<button type="button" class="bq-secondary-button" data-journey-group-code="${esc(group.id)}">New group code</button>`:''}${group.canLeave?`<button type="button" class="bq-secondary-button bq-journey-group-danger" data-journey-group-leave="${esc(group.id)}">Leave group</button>`:'<span class="bq-journey-group-owner-note">Group owner cannot leave until leadership is transferred or the group is archived.</span>'}</div></article>`).join('')}
const createOptions=rows=>rows.filter(row=>row.canCreate).map(row=>`<option value="${esc(row.id)}">${esc(row.name)} · ${esc(row.roleLabel)}</option>`).join('');
export function journeyGroupsPage({journeyGroups,onAccount,onBack}){
  return{title:'Journey Groups',html:'<section class="bq-panel bq-journey-groups" data-journey-groups-view></section>',mount(root){
    const view=root.querySelector('[data-journey-groups-view]');let busy=false,message='';const state=()=>journeyGroups.snapshot();const common=()=>'<div class="bq-account-actions"><button type="button" class="bq-secondary-button" data-journey-groups-back>Back to More</button></div>';
    const bindCommon=()=>{view.querySelector('[data-journey-groups-back]')?.addEventListener('click',()=>onBack?.(),{once:true});view.querySelector('[data-journey-groups-account]')?.addEventListener('click',()=>onAccount?.(),{once:true})};
    const renderAuth=()=>{const current=state();view.innerHTML=`<p class="bq-eyebrow">JOURNEY GROUPS</p><h1>Grow with 2–6 people.</h1><p>${current.remoteAvailable?'Sign in to view or join your congregation Journey Groups.':'Journey Groups are disabled in local preview because membership is cloud-backed.'}</p>${current.remoteAvailable?'<button type="button" class="bq-primary-button" data-journey-groups-account>Open account</button>':''}${common()}`;bindCommon()};
    const render=()=>{const current=state(),createRows=current.congregations.filter(row=>row.canCreate);if(!current.authenticated||!current.remoteAvailable)return renderAuth();view.innerHTML=`<div class="bq-journey-groups-head"><div><p class="bq-eyebrow">2–6 PEOPLE · ONE CONGREGATION</p><h1>Journey Groups</h1><p>Create, join, view and leave small groups without exposing private study notes or answers.</p></div>${common()}</div>${message?`<p class="bq-form-message" role="status">${esc(message)}</p>`:''}${current.inviteCode?`<section class="bq-account-section bq-journey-group-code"><p class="bq-eyebrow">NEW GROUP CODE</p><code>${esc(current.inviteCode)}</code><p>Share this only with people in the same congregation. Creating a new code replaces the old one.</p></section>`:''}<div data-journey-groups-list>${groupCards(current.groups)}</div><section class="bq-account-section"><h2>Join a Journey Group</h2><form class="bq-account-form" data-journey-groups-join><label>8-character group code<input name="code" maxlength="8" minlength="8" pattern="[A-Za-z0-9]{8}" autocomplete="off" autocapitalize="characters" required></label><button type="submit" class="bq-primary-button">Join group</button></form></section>${createRows.length?`<section class="bq-account-section"><h2>Leader: create a Journey Group</h2><form class="bq-account-form" data-journey-groups-create><label>Congregation<select name="congregation_id" required>${createOptions(createRows)}</select></label><label>Group name<input name="name" maxlength="60" required></label><label>Weekly schedule<input name="schedule_text" maxlength="100"></label><label>Short description<textarea name="description" maxlength="240" rows="3"></textarea></label><label>Maximum members<select name="max_members">${[6,5,4,3,2].map(n=>`<option value="${n}">${n}</option>`).join('')}</select></label><button type="submit" class="bq-primary-button">Create group</button></form></section>`:''}<p class="bq-journey-group-privacy"><b>Privacy boundary:</b> Journey Groups show group membership only. Encouragements, daily completion sharing, assignments and presence remain separate rebuild milestones.</p>`;bindCommon();bindActions()};
    async function load(){if(busy)return;busy=true;view.innerHTML='<p class="bq-eyebrow">JOURNEY GROUPS</p><h1>Journey Groups</h1><p role="status">Loading memberships…</p>';try{await journeyGroups.load();message='';render()}catch(error){if(error?.code==='BQ_JOURNEY_GROUPS_AUTH_REQUIRED'||error?.code==='BQ_JOURNEY_GROUPS_REMOTE_DISABLED')renderAuth();else{view.innerHTML=`<p class="bq-eyebrow">JOURNEY GROUPS</p><h1>Journey Groups</h1><p class="bq-form-message" role="alert">${esc(error?.message||'Journey Groups could not load.')}</p><button type="button" class="bq-secondary-button" data-journey-groups-retry>Try again</button>${common()}`;bindCommon();view.querySelector('[data-journey-groups-retry]')?.addEventListener('click',load,{once:true})}}finally{busy=false}}
    async function submitJoin(event){event.preventDefault();if(busy)return;busy=true;try{await journeyGroups.join(new FormData(event.currentTarget).get('code'));message='Journey Group joined.';render()}catch(error){message=error?.message||'Could not join this Journey Group.';render()}finally{busy=false}}
    async function submitCreate(event){event.preventDefault();if(busy)return;busy=true;const fd=new FormData(event.currentTarget);try{await journeyGroups.create({congregationId:fd.get('congregation_id'),name:fd.get('name'),scheduleText:fd.get('schedule_text'),description:fd.get('description'),maxMembers:Number(fd.get('max_members'))});message='Journey Group created.';render()}catch(error){message=error?.message||'Could not create this Journey Group.';render()}finally{busy=false}}
    async function rotate(groupId){if(busy)return;busy=true;try{await journeyGroups.rotateCode(groupId);message='New group code created.';render()}catch(error){message=error?.message||'Could not create a new group code.';render()}finally{busy=false}}
    async function leave(groupId){if(busy||!window.confirm('Leave this Journey Group?'))return;busy=true;try{await journeyGroups.leave(groupId);message='You left the Journey Group.';render()}catch(error){message=error?.message||'Could not leave this Journey Group.';render()}finally{busy=false}}
    function bindActions(){view.querySelector('[data-journey-groups-join]')?.addEventListener('submit',submitJoin,{once:true});view.querySelector('[data-journey-groups-create]')?.addEventListener('submit',submitCreate,{once:true});view.querySelectorAll('[data-journey-group-code]').forEach(button=>button.addEventListener('click',()=>rotate(button.dataset.journeyGroupCode),{once:true}));view.querySelectorAll('[data-journey-group-leave]').forEach(button=>button.addEventListener('click',()=>leave(button.dataset.journeyGroupLeave),{once:true}))}
    load();return()=>{busy=false};
  }};
}
