import {createLinkedActivitiesService} from '../../app/linked-activities.js';
import {requestNavigation} from '../../app/router.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const labels=Object.freeze({reading:'Reading','guided-study':'Guided Study',mission:'Mission',quiz:'Quiz',reflection:'Reflection',couples:'Couples',group:'Group activity',custom:'Custom'});
const ministryRoles=new Set(['facilitator','leader','pastor','admin']);
const statusLabel=status=>status==='completed'?'Completed':status==='started'?'Started':'Assigned';
const dueLabel=state=>state==='scheduled'?'Scheduled':state==='overdue'?'Overdue':state==='completed'?'Completed':'Open';
const formatDate=value=>{if(!value)return'No deadline';try{return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))}catch{return String(value)}};
const recurrenceLabel=value=>value==='FREQ=WEEKLY'?'Weekly':value==='FREQ=MONTHLY'?'Monthly':String(value||'').replace(/^FREQ=/,'').toLowerCase();
const typeOptions=Object.entries(labels).map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join('');
const audienceLabels=Object.freeze({all:'Everyone',member:'One member',team:'One team',group:'One Journey Group'});

function advancedMeta(row){
  const bits=[];
  if(row.scheduleAt)bits.push(`Opens ${formatDate(row.scheduleAt)}`);
  if(row.reminderAt)bits.push(`Reminder ${formatDate(row.reminderAt)}`);
  if(row.recurrenceRule)bits.push(`${recurrenceLabel(row.recurrenceRule)} recurrence rule`);
  if(row.requiredReflection)bits.push('Written response required');
  if(row.evidenceType==='text'&&!row.requiredReflection)bits.push('Written evidence required');
  if(row.evidenceType==='confirmation')bits.push('Completion confirmation required');
  if(row.minQuizScore!==null)bits.push(`Quiz score ≥ ${row.minQuizScore}%`);
  return bits;
}

function listView(state){
  if(!state.assignments.length)return '<section class="bq-account-section"><h2>No active assignments</h2><p>No currently visible task has been assigned to this account in the selected congregation.</p></section>';
  return `<section class="bq-account-section"><h2>${ministryRoles.has(state.role)?'Congregation assignments':'Assigned to you'}</h2><div class="bq-team-member-list">${state.assignments.map(row=>`<article data-assignment-row="${esc(row.id)}"><span><b>${esc(row.title)}</b><small>${esc(labels[row.type]||row.type)} · ${esc(statusLabel(row.progress.status))} · ${esc(dueLabel(row.dueState))}${row.dueAt?` · ${esc(formatDate(row.dueAt))}`:''}</small></span><button type="button" class="bq-secondary-button" data-assignment-open="${esc(row.id)}">Open task</button></article>`).join('')}</div></section>`;
}

function responseReviewView(state,row,readOnly){
  const review=state.activeReview;
  if(!review||review.assignmentId!==row.id)return '<section class="bq-account-section"><h3>Responses received</h3><p>Open response status to see who has completed this task.</p></section>';
  if(review.status==='loading')return '<section class="bq-account-section"><h3>Responses received</h3><p role="status">Loading response status…</p></section>';
  if(review.status==='error')return `<section class="bq-account-section"><h3>Responses received</h3><p class="bq-form-message" role="alert">${esc(review.error||'Response status could not load.')}</p><button type="button" class="bq-secondary-button" data-assignment-review-refresh="${esc(row.id)}">Retry response status</button></section>`;
  const responders=review.responders||[];
  const names=responders.length?`<div class="bq-team-member-list">${responders.map(item=>`<article><span><b>${esc(item.displayName)}</b><small>Responded ${esc(formatDate(item.completedAt))}</small></span><span class="bq-source-label">Completed</span></article>`).join('')}</div>`:'<p>No member has completed this task yet.</p>';
  const privateAnswers=readOnly?`<div data-assignment-private-responses><h3>Private member answers</h3>${(review.responses||[]).length?review.responses.map(item=>`<article class="bq-form-message" data-private-response-user="${esc(item.userId)}"><b>${esc(item.displayName)}</b><small> · ${esc(formatDate(item.completedAt))}</small><p>${item.submission?esc(item.submission):'<em>No written text submitted.</em>'}</p>${item.leaderFeedback?`<small>Leader feedback: ${esc(item.leaderFeedback)}</small>`:''}</article>`).join(''):'<p>No completed responses are available yet.</p>'}<p><small>Answer text is visible only to authorized ministry roles. Members receive only the responder-name/completion list above.</small></p></div>`:'';
  return `<section class="bq-account-section" data-assignment-response-review><div class="bq-team-center-head"><div><h3>Responses received</h3><p>${responders.length} member${responders.length===1?'':'s'} completed this task.</p></div><button type="button" class="bq-secondary-button" data-assignment-review-refresh="${esc(row.id)}">Refresh</button></div>${names}${privateAnswers}</section>`;
}

function detailView(state,linkedActivities){
  const row=state.assignments.find(item=>item.id===state.activeId);if(!row)return'';
  const progress=row.progress,readOnly=ministryRoles.has(state.role),scheduled=row.dueState==='scheduled',refs=row.scriptureRefs.length?`<div class="bq-account-actions" aria-label="Scripture references">${row.scriptureRefs.map(ref=>`<span class="bq-source-label">${esc(ref)}</span>`).join('')}</div>`:'';
  const response=progress.submission?`<div class="bq-form-message"><b>Your submitted response</b><p>${esc(progress.submission)}</p></div>`:'';
  const feedback=progress.leaderFeedback?`<div class="bq-form-message"><b>Leader feedback</b><p>${esc(progress.leaderFeedback)}</p></div>`:'';
  const meta=advancedMeta(row),advanced=meta.length?`<div class="bq-account-actions" data-assignment-advanced-meta>${meta.map(item=>`<span class="bq-source-label">${esc(item)}</span>`).join('')}</div>`:'';
  const linked=readOnly?null:linkedActivities.describe(row);
  const linkedAction=!readOnly&&progress.status!=='completed'&&!scheduled&&linked?.present?(linked.available?`<button type="button" class="bq-secondary-button" data-assignment-linked="${esc(row.id)}">${progress.status==='started'?'Reopen linked activity':'Start linked activity'}</button>`:`<p class="bq-form-message" data-assignment-linked-unavailable>This linked activity is not available in the verified v3 rebuild yet.</p>`):'';
  const start=!readOnly&&!linked?.present&&progress.status==='assigned'&&!scheduled?`<button type="button" class="bq-secondary-button" data-assignment-start="${esc(row.id)}">Start task</button>`:'';
  const handoff=!readOnly&&linked?.present&&linked.available&&progress.status!=='completed'?'<p class="bq-form-message" data-linked-completion-handoff>After finishing the linked activity, return to this assignment and use Mark complete. The linked feature cannot award assignment completion or points by itself.</p>':'';
  const reflectionRequired=row.requiredReflection||row.evidenceType==='text';
  const responseLabel=reflectionRequired?'Required written response / reflection':'Optional response to your leader';
  const responsePlaceholder=reflectionRequired?'Write the response, reflection or evidence required for this assignment.':'Share only what you intentionally want your leader to receive.';
  const quiz=row.minQuizScore!==null?`<label>Quiz score (%)<input name="quizScore" type="number" min="0" max="100" required placeholder="Minimum ${esc(String(row.minQuizScore))}%"></label>`:'';
  const confirmation=row.evidenceType==='confirmation'?'<label><input name="confirmed" type="checkbox" required> I confirm I completed the assigned activity.</label>':'';
  const completion=!readOnly&&progress.status!=='completed'?(scheduled?`<p class="bq-form-message" data-assignment-scheduled>This task opens ${esc(formatDate(row.scheduleAt))}. Start and completion are unavailable until then.</p>`:`<form class="bq-account-form" data-assignment-complete="${esc(row.id)}"><label>${esc(responseLabel)}<textarea name="submission" maxlength="4000" rows="4" ${reflectionRequired?'required':''} placeholder="${esc(responsePlaceholder)}"></textarea></label>${quiz}${confirmation}<small>Your submitted text is private to authorized ministry roles. Other assigned members can see only that you responded, not what you wrote. Private Bible notes, journal, Transform answers and Couple Journey data are never attached.</small><button type="submit" class="bq-primary-button">Mark complete</button></form>`):'';
  const leaderNote=readOnly?'<p class="bq-form-message">Member answer text is private to authorized ministry roles. The congregation-facing status below exposes only who has responded and when.</p>':'';
  return `<section class="bq-account-section" data-assignment-detail="${esc(row.id)}"><div class="bq-team-center-head"><div><p class="bq-eyebrow">${esc(labels[row.type]||row.type)} · ${esc(statusLabel(progress.status))} · ${esc(dueLabel(row.dueState))}</p><h2>${esc(row.title)}</h2></div><button type="button" class="bq-secondary-button" data-assignment-close>Close task</button></div>${row.instructions?`<p>${esc(row.instructions)}</p>`:'<p>No additional instructions were provided.</p>'}${refs}<p><b>Due:</b> ${esc(formatDate(row.dueAt))} · <b>Completion points:</b> ${esc(String(row.points))}</p>${advanced}${row.recurrenceRule?'<p><small>Recurrence is stored for the assignment. BibleQuest does not generate recurring copies automatically.</small></p>':''}${leaderNote}<div class="bq-account-actions">${linkedAction}${start}</div>${handoff}${completion}${response}${feedback}</section>${responseReviewView(state,row,readOnly)}`;
}

function targetOptions(state,scope){
  const rows=scope==='member'?state.publishTargets?.members:scope==='team'?state.publishTargets?.teams:scope==='group'?state.publishTargets?.groups:[];
  return (rows||[]).map(row=>`<option value="${esc(row.id)}">${esc(row.label)}</option>`).join('');
}

function publisherView(state){
  if(!ministryRoles.has(state.role))return'';
  const hasTargets=(state.publishTargets?.members?.length||0)+(state.publishTargets?.teams?.length||0)+(state.publishTargets?.groups?.length||0)>0;
  return `<section class="bq-account-section" data-assignment-publisher><div class="bq-team-center-head"><div><p class="bq-eyebrow">MINISTRY AUTHORING</p><h2>Publish assignment</h2><p>Write a task, question, activity or reflection prompt and send it through the trusted congregation workflow.</p></div><button type="button" class="bq-secondary-button" data-assignment-targets>${hasTargets?'Refresh audiences':'Load audiences'}</button></div><form class="bq-account-form" data-assignment-publish><label>Title<input name="title" maxlength="120" required placeholder="Read and reflect on John 1"></label><label>Message / instructions<textarea name="instructions" maxlength="4000" rows="4" placeholder="Write the question, activity, task, or reflection prompt members should respond to."></textarea></label><label>Type<select name="assignmentType">${typeOptions}</select></label><label>Scripture references<textarea name="scriptureRefs" rows="2" placeholder="John 1, Psalm 23"></textarea></label><label>Audience<select name="targetScope" data-assignment-target-scope>${Object.entries(audienceLabels).map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join('')}</select></label><label data-assignment-target-row hidden>Audience target<select name="targetId" data-assignment-target-id><option value="">Choose a target</option></select></label><label>Deadline<input name="dueAt" type="datetime-local"></label><label>Completion points<input name="points" type="number" min="0" max="25" value="5"></label><label>Scheduled opening<input name="scheduleAt" type="datetime-local"></label><label>Reminder metadata<input name="reminderAt" type="datetime-local"></label><label>Recurrence metadata<select name="recurrenceRule"><option value="">None</option><option value="FREQ=WEEKLY">Weekly</option><option value="FREQ=MONTHLY">Monthly</option></select></label><label><input name="requiredReflection" type="checkbox"> Require a written response / reflection</label><label>Minimum quiz score (%)<input name="minQuizScore" type="number" min="0" max="100" placeholder="Optional"></label><label>Evidence requirement<select name="evidenceType"><option value="none">None</option><option value="text">Written evidence</option><option value="confirmation">Completion confirmation</option></select></label><small>Choose “Require a written response / reflection” when members must answer in text. Submitted text is private to ministry; responder names/status are visible to other assigned members.</small><button type="submit" class="bq-primary-button">Publish assignment</button></form></section>`;
}

export function assignmentsPage({assignments,onBack,onAccount}={}){
  const linkedActivities=createLinkedActivitiesService({assignments});
  return{title:'Assignments',html:'<section class="bq-panel" data-assignments-view></section>',mount(root){
    const view=root.querySelector('[data-assignments-view]');let disposed=false,busy=false,stopRemote=null,message='';
    const stopWatch=()=>{if(stopRemote){try{stopRemote()}catch{}stopRemote=null}assignments.stopSync?.()};
    const back=()=>'<button type="button" class="bq-secondary-button" data-assignments-back>Back to Community</button>';
    const bindCommon=()=>{view.querySelector('[data-assignments-back]')?.addEventListener('click',()=>onBack?.(),{once:true});view.querySelector('[data-assignments-account]')?.addEventListener('click',()=>onAccount?.(),{once:true});view.querySelector('[data-assignments-retry]')?.addEventListener('click',()=>load(),{once:true})};
    const bindPublisher=state=>{
      const scope=view.querySelector('[data-assignment-target-scope]'),row=view.querySelector('[data-assignment-target-row]'),target=view.querySelector('[data-assignment-target-id]');
      const refreshTarget=()=>{if(!scope||!row||!target)return;const value=scope.value;row.hidden=value==='all';target.required=value!=='all';target.innerHTML=value==='all'?'<option value="">Everyone</option>':`<option value="">Choose a target</option>${targetOptions(state,value)}`};
      refreshTarget();scope?.addEventListener('change',refreshTarget);
      view.querySelector('[data-assignment-targets]')?.addEventListener('click',async()=>{if(busy)return;busy=true;message='';try{const next=await assignments.loadPublishTargets();message='Audience directory refreshed.';render(next)}catch(error){message=error?.message||'Audience directory could not load.';render(assignments.snapshot())}finally{busy=false}}, {once:true});
      view.querySelector('[data-assignment-publish]')?.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;message='';const submit=event.currentTarget.querySelector('button[type="submit"]');if(submit)submit.disabled=true;try{const formData=new FormData(event.currentTarget),next=await assignments.publish({title:formData.get('title'),instructions:formData.get('instructions'),assignmentType:formData.get('assignmentType'),scriptureRefs:formData.get('scriptureRefs'),targetScope:formData.get('targetScope'),targetId:formData.get('targetId'),dueAt:formData.get('dueAt'),points:formData.get('points'),scheduleAt:formData.get('scheduleAt'),reminderAt:formData.get('reminderAt'),recurrenceRule:formData.get('recurrenceRule'),requiredReflection:formData.get('requiredReflection')==='on',minQuizScore:formData.get('minQuizScore'),evidenceType:formData.get('evidenceType')});message='Assignment published. Server truth has been refreshed.';render(next)}catch(error){message=error?.message||'Assignment could not be published.';render(assignments.snapshot())}finally{busy=false}});
    };
    const loadReview=async id=>{render(assignments.open(id));const next=await assignments.loadReview(id);if(!disposed)render(next)};
    const render=state=>{
      if(disposed)return;
      if(state.status==='signed-out'){view.innerHTML=`<p class="bq-eyebrow">CONGREGATION TASKS</p><h1>Assignments</h1><p>Sign in to receive and complete congregation assignments across your devices.</p><button type="button" class="bq-primary-button" data-assignments-account>Open account</button>${back()}`;bindCommon();return}
      if(state.status==='local-preview'){view.innerHTML=`<p class="bq-eyebrow">CONGREGATION TASKS</p><h1>Assignments</h1><p>Assignments are cloud-backed and unavailable in local preview.</p>${back()}`;bindCommon();return}
      if(state.status==='no-congregation'){view.innerHTML=`<p class="bq-eyebrow">CONGREGATION TASKS</p><h1>Assignments</h1><p>Join an active congregation before receiving assignments.</p>${back()}`;bindCommon();return}
      const congregationSelect=state.congregations.length>1?`<label>Congregation<select data-assignment-congregation>${state.congregations.map(row=>`<option value="${esc(row.id)}" ${row.id===state.congregationId?'selected':''}>${esc(row.name)}</option>`).join('')}</select></label>`:'';
      view.innerHTML=`<div class="bq-team-center-head"><div><p class="bq-eyebrow">CONGREGATION TASKS</p><h1>${esc(state.congregationName||'Assignments')}</h1><p>${ministryRoles.has(state.role)?'Publish and review congregation assignments through your ministry account.':'Receive, open and complete tasks through your signed-in congregation account.'}</p></div>${back()}</div>${message?`<p class="bq-form-message" role="status">${esc(message)}</p>`:''}${congregationSelect?`<section class="bq-account-section"><div class="bq-account-form">${congregationSelect}</div></section>`:''}${publisherView(state)}${listView(state)}${detailView(state,linkedActivities)}<section class="bq-account-section"><h2>Privacy boundary</h2><p>Members assigned to the same task can see who has responded. They cannot see one another’s answer text. Submitted answer text is available only to authorized ministry roles. Private study notes and other personal BibleQuest data stay outside Assignments.</p></section>`;
      bindCommon();bindPublisher(state);
      view.querySelector('[data-assignment-congregation]')?.addEventListener('change',event=>{stopWatch();void load({congregationId:event.target.value})},{once:true});
      view.querySelectorAll('[data-assignment-open]').forEach(button=>button.addEventListener('click',()=>{message='';void loadReview(button.dataset.assignmentOpen)},{once:true}));
      view.querySelector('[data-assignment-review-refresh]')?.addEventListener('click',async event=>{message='';render(await assignments.loadReview(event.currentTarget.dataset.assignmentReviewRefresh))},{once:true});
      view.querySelector('[data-assignment-close]')?.addEventListener('click',()=>{message='';render(assignments.close())},{once:true});
      view.querySelector('[data-assignment-linked]')?.addEventListener('click',async event=>{if(busy)return;busy=true;message='';try{const result=await linkedActivities.launch(event.currentTarget.dataset.assignmentLinked);message='Linked activity started. Return to Assignments when finished to mark it complete.';render(result.state);requestNavigation(result.route)}catch(error){message=error?.message||'Linked activity could not be opened.';render(assignments.snapshot())}finally{busy=false}}, {once:true});
      view.querySelector('[data-assignment-start]')?.addEventListener('click',async event=>{if(busy)return;busy=true;message='';try{render(await assignments.start(event.currentTarget.dataset.assignmentStart));message='Task started.';render(assignments.snapshot())}catch(error){message=error?.message||'Task could not be started.';render(assignments.snapshot())}finally{busy=false}}, {once:true});
      view.querySelector('[data-assignment-complete]')?.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;message='';try{const id=event.currentTarget.dataset.assignmentComplete,formData=new FormData(event.currentTarget),submission=formData.get('submission')||'',requirements={confirmed:formData.get('confirmed')==='on',quizScore:formData.get('quizScore')??null},linked=linkedActivities.describe(id),result=linked.present?await linkedActivities.complete(id,submission,requirements):await assignments.complete(id,submission,requirements);message=result.alreadyCompleted?'This task was already completed.':`Task completed${result.awarded?` · +${result.awarded} pts`:''}.`;render(result.state)}catch(error){message=error?.message||'Task could not be completed.';render(assignments.snapshot())}finally{busy=false}});
    };
    async function startWatch(){stopWatch();try{stopRemote=await assignments.watch((next,error)=>{if(disposed)return;if(error){message='Assignment status changed, but refresh failed. Use Retry.';render(assignments.snapshot());return}message='Assignment status synced.';render(next)})}catch{stopRemote=null}}
    async function load(overrides={}){if(busy||disposed)return;busy=true;message='';view.innerHTML='<p class="bq-eyebrow">CONGREGATION TASKS</p><h1>Assignments</h1><p role="status">Loading assignments…</p>';try{const state=await assignments.load(overrides);render(state);if(state.status==='ready')void startWatch()}catch(error){if(disposed)return;view.innerHTML=`<p class="bq-eyebrow">CONGREGATION TASKS</p><h1>Assignments</h1><p class="bq-form-message" role="alert">${esc(error?.message||'Assignments could not load.')}</p><button type="button" class="bq-secondary-button" data-assignments-retry>Try again</button>${back()}`;bindCommon()}finally{busy=false}}
    void load();return()=>{disposed=true;stopWatch();assignments.close?.()};
  }};
}
