import { getContentProvenance } from '../../core/content-provenance.js';
import { sourceLabel } from '../../ui/source-labels.js';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[char]));
const GAME_SOURCE=sourceLabel(getContentProvenance('bq-game'),{compact:true});
const RECALL_SOURCE=sourceLabel(getContentProvenance('bq-recall'),{compact:true});

export function gamesPage({games,onHome}){
  return{
    title:'Play',html:'<section data-games-page></section>',
    mount(root){
      const host=root.querySelector('[data-games-page]');let disposed=false,memoryTimer=null;
      const clearMemoryTimer=()=>{if(memoryTimer!==null){clearTimeout(memoryTimer);memoryTimer=null}};
      const memoryWidth=()=>Math.max(1,Math.round(root.getBoundingClientRect().width||window.innerWidth||390));
      const render=state=>{
        if(disposed)return;
        if(state.phase==='launcher'){
          const memory=games.kidsMemory.mode;
          host.innerHTML=`<section class="bq-panel bq-games-head"><p class="bq-eyebrow">PLAY</p><h1>Bible games for every kind of practice</h1><p>Choose a game to review Scripture, strengthen recall, or play together. Your progress stays consistent across supported modes.</p></section><section class="bq-game-launcher" aria-label="BibleQuest games">${games.modes.map(mode=>{const last=mode.id==='per-book-recall'?null:games.lastResult(mode.id);return `<article class="bq-panel bq-game-card"><span>${escapeHtml(mode.kicker)}</span><h2>${escapeHtml(mode.title)}</h2><p>${escapeHtml(mode.description)}</p>${last?`<p class="bq-game-score" data-game-last="${escapeHtml(mode.id)}">Last result: <b>${last.score}/${last.total}</b> · +${last.gained} XP</p>`:''}<button type="button" class="bq-primary-button" data-game-launch="${escapeHtml(mode.id)}">${mode.id==='per-book-recall'?'Open recall library':`Play ${escapeHtml(mode.title)}`}</button></article>`}).join('')}<article class="bq-panel bq-game-card" data-memory-launch-card><span>${escapeHtml(memory.kicker)}</span><h2>${escapeHtml(memory.title)}</h2><p>${escapeHtml(memory.description)}</p><button type="button" class="bq-primary-button" data-memory-open>Play ${escapeHtml(memory.title)}</button></article><article class="bq-panel bq-game-card" data-same-room-card><span>PASS-AND-PLAY</span><h2>Play Together</h2><p>Share one device with 2–6 players, rotate turns, and keep a local scoreboard.</p><button type="button" class="bq-primary-button" data-same-room-open>Play Together</button></article></section><div class="bq-game-footer"><button type="button" class="bq-secondary-button" data-game-home>Back home</button></div>`;return;
        }
        if(state.phase==='memory'){
          host.innerHTML=`<section class="bq-game-topline"><button type="button" class="bq-secondary-button" data-game-launcher>All games</button><div class="bq-game-score" data-memory-moves>Moves <b>${state.moves}</b></div></section><section class="bq-panel bq-memory-meadow" data-memory-meadow><p class="bq-eyebrow">KIDS · MEMORY</p><div class="bq-memory-mark" aria-hidden="true">🦊</div><h1>Memory Meadow</h1><p>Find all ${state.pairs} pairs. Pick two cards at a time.</p><div class="bq-memory-grid" data-memory-grid style="--memory-columns:${state.columns}" aria-label="Memory Meadow cards">${state.cards.map((card,index)=>{const face=card.open||card.done,className=card.done?' is-matched':card.open?' is-open':'';return `<button type="button" class="bq-memory-card${className}" data-memory-index="${index}" aria-label="${face?`Card ${index+1}: ${escapeHtml(card.icon)}${card.done?', matched':''}`:`Card ${index+1}: hidden`}" ${state.locked||card.open||card.done?'disabled':''}><span aria-hidden="true">${face?escapeHtml(card.icon):'?'}</span></button>`}).join('')}</div><p class="bq-memory-status" aria-live="polite">${state.locked?'Checking this pair…':'Choose a card.'}</p></section>`;return;
        }
        if(state.phase==='memory-complete'){
          host.innerHTML=`<section class="bq-panel bq-game-result" data-memory-complete><p class="bq-eyebrow">MEMORY MEADOW COMPLETE</p><div class="bq-game-medal" aria-hidden="true">🦊</div><h1>All friends matched!</h1><p>You matched every pair in ${state.moves} moves.</p><div class="bq-game-stats"><div><b>${state.stars} ⭐</b><span>stars earned</span></div><div><b>${state.coins} 🪙</b><span>coins earned</span></div><div><b>0</b><span>XP — not awarded</span></div></div><p class="bq-memory-wallet">Total: ${state.totalStars} ⭐ · ${state.totalCoins} 🪙</p><div class="bq-game-actions"><button type="button" class="bq-primary-button" data-memory-replay>Play again</button><button type="button" class="bq-secondary-button" data-game-launcher>Choose another game</button><button type="button" class="bq-secondary-button" data-game-home>Back home</button></div></section>`;return;
        }
        if(state.phase==='same-room-setup'){
          host.innerHTML=`<section class="bq-panel bq-games-head" data-same-room-setup><p class="bq-eyebrow">PLAY TOGETHER</p><h1>How many players?</h1><p>Pass this device after each question. Scores stay local to this session and do not award profile XP.</p><div class="bq-game-actions">${[2,3,4,5,6].map(count=>`<button type="button" class="bq-primary-button" data-same-room-start="${count}">${count} players</button>`).join('')}</div><button type="button" class="bq-secondary-button" data-game-launcher>All games</button></section>`;return;
        }
        if(state.phase==='same-room-question'){
          const q=state.question,progressPct=Math.round((state.index/Math.max(1,state.total))*100);
          host.innerHTML=`<section class="bq-game-topline"><button type="button" class="bq-secondary-button" data-game-launcher>All games</button><div class="bq-game-score" data-same-room-turn>Turn: <b>${escapeHtml(state.currentPlayer.name)}</b></div></section><section class="bq-panel bq-question-card" data-same-room-question="${escapeHtml(q.id)}"><p class="bq-eyebrow">PLAY TOGETHER · QUESTION ${state.index+1} OF ${state.total}</p><div class="bq-game-progress" aria-hidden="true"><i style="width:${progressPct}%"></i></div><div class="bq-game-stats" data-same-room-scoreboard>${state.players.map(player=>`<div data-same-room-player="${escapeHtml(player.id)}"><b>${player.score}</b><span>${escapeHtml(player.name)}${player.active?' · turn':''}</span></div>`).join('')}</div><h1>${escapeHtml(q.q)}</h1><div class="bq-game-choices">${q.choices.map((choice,index)=>{const isCorrect=state.locked&&index===q.answer,isWrong=state.locked&&index===state.selected&&!state.correct,className=isCorrect?' is-correct':isWrong?' is-wrong':'';return `<button type="button" class="bq-game-choice${className}" data-same-room-answer="${index}" ${state.locked?'disabled':''}><span aria-hidden="true">${String.fromCharCode(65+index)}</span><b>${escapeHtml(choice)}</b></button>`}).join('')}</div>${state.locked?`<div class="bq-game-explanation" data-same-room-feedback><strong>${state.correct?'Correct':'Review this one'}</strong><p>${escapeHtml(q.why)}</p><span>📖 ${escapeHtml(q.ref)}</span></div><button type="button" class="bq-primary-button" data-same-room-next>${state.index+1===state.total?'See final scoreboard':'Pass to next player'}</button>`:''}<div class="bq-game-footer"><button type="button" class="bq-secondary-button" data-same-room-finish>Finish game</button></div>${GAME_SOURCE}</section>`;return;
        }
        if(state.phase==='same-room-complete'){
          const top=Math.max(...state.players.map(player=>player.score)),winners=state.players.filter(player=>player.score===top).map(player=>player.name),result=winners.length===1?`Winner: ${winners[0]}`:`Tie: ${winners.join(' & ')}`;
          host.innerHTML=`<section class="bq-panel bq-game-result" data-same-room-complete><p class="bq-eyebrow">PLAY TOGETHER COMPLETE</p><h1>${escapeHtml(result)}</h1><div class="bq-game-stats" data-same-room-scoreboard>${state.players.map(player=>`<div data-same-room-player="${escapeHtml(player.id)}"><b>${player.score}</b><span>${escapeHtml(player.name)}</span></div>`).join('')}</div><div class="bq-game-actions"><button type="button" class="bq-primary-button" data-same-room-open>Play again</button><button type="button" class="bq-secondary-button" data-game-launcher>All games</button></div></section>`;return;
        }
        if(state.phase==='detective'){
          const item=state.detectiveItem;
          host.innerHTML=`<section class="bq-game-topline"><button type="button" class="bq-secondary-button" data-game-launcher>All games</button><div class="bq-game-score" data-detective-score>Score <b>${state.score}</b> · +${state.gained} XP</div></section><section class="bq-panel bq-question-card bq-detective-card" data-detective="${escapeHtml(item.id)}"><p class="bq-eyebrow">BIBLE DETECTIVE</p><div class="bq-detective-mark" aria-hidden="true">🕵️</div><h1>Who am I?</h1><div class="bq-detective-clues">${item.clues.map((clue,index)=>`<div><span>${index+1}</span><p>${escapeHtml(clue)}</p></div>`).join('')}</div>${state.locked?`<div class="bq-game-explanation" data-detective-feedback><strong>${state.correct?'Correct':'Answer: '+escapeHtml(item.answer)}</strong><p>${state.correct?`You identified ${escapeHtml(item.answer)} from the clues.`:`Your answer was “${escapeHtml(state.detectiveAnswer)}”. Review the clues and Scripture reference.`}</p><span>📖 ${escapeHtml(item.ref)}</span><small>CHARACTER / CLUES</small></div><div class="bq-game-actions"><button type="button" class="bq-primary-button" data-detective-replay>Another detective</button><button type="button" class="bq-secondary-button" data-game-launcher>Choose another game</button></div>`:`<form class="bq-detective-form bq-recall-search" data-detective-form><label><span>Your answer</span><input type="text" required maxlength="80" autocomplete="off" autocapitalize="words" placeholder="Type the Bible character…" data-detective-answer></label><button type="submit" class="bq-primary-button" data-detective-submit>Check answer</button></form>`}${GAME_SOURCE}</section>`;return;
        }
        if(state.phase==='timeline'){
          const item=state.timelineItem;
          host.innerHTML=`<section class="bq-game-topline"><button type="button" class="bq-secondary-button" data-game-launcher>All games</button><div class="bq-game-score" data-timeline-score>Score <b>${state.score}</b> · +${state.gained} XP</div></section><section class="bq-panel bq-question-card bq-timeline-card" data-timeline="${escapeHtml(item.id)}"><p class="bq-eyebrow">TIMELINE CHALLENGE</p><h1>${escapeHtml(item.title)}</h1><p>Move the events until they are in chronological order, then check your timeline.</p><div class="bq-timeline-list">${state.timelineCurrent.map((event,index)=>`<div class="bq-timeline-row" data-timeline-row="${index}"><span class="bq-timeline-number">${index+1}</span><b>${escapeHtml(event)}</b><span class="bq-timeline-moves"><button type="button" aria-label="Move ${escapeHtml(event)} up" data-timeline-move="${index},-1" ${state.locked||index===0?'disabled':''}>↑</button><button type="button" aria-label="Move ${escapeHtml(event)} down" data-timeline-move="${index},1" ${state.locked||index===state.timelineCurrent.length-1?'disabled':''}>↓</button></span></div>`).join('')}</div>${state.timelineFeedback==='wrong'?`<div class="bq-game-explanation" data-timeline-feedback><strong>Not yet</strong><p>Your arrangement is preserved. Move the uncertain events and check again. The first miss awards review XP once; repeated checks cannot farm XP.</p></div>`:''}${state.timelineFeedback==='correct'?`<div class="bq-game-explanation" data-timeline-feedback><strong>Correct order</strong><p>You placed every event in chronological order.</p><small>TIMELINE / SEQUENCE</small></div>`:''}${GAME_SOURCE}<div class="bq-game-actions">${state.locked?`<button type="button" class="bq-primary-button" data-timeline-replay>Next timeline</button><button type="button" class="bq-secondary-button" data-game-launcher>Choose another game</button>`:`<button type="button" class="bq-primary-button" data-timeline-check>Check order</button>`}</div></section>`;return;
        }
        if(state.phase==='recall-library'){
          const books=games.visibleRecallBooks();
          host.innerHTML=`<section class="bq-panel bq-games-head" data-recall-library><p class="bq-eyebrow">PER-BOOK RECALL</p><h1>Choose one Bible book</h1><p>Only the selected book pack is loaded. Reveal each reference answer, then mark it for review or remembered.</p><label class="bq-recall-search"><span>Search books</span><input type="search" maxlength="80" value="${escapeHtml(state.recallQuery)}" placeholder="Ruth, John, Romans…" data-recall-search></label></section><section class="bq-recall-books">${books.length?books.map(book=>{const summary=games.recallSummary(book.code);return `<button type="button" class="bq-panel bq-recall-book" data-recall-book="${escapeHtml(book.code)}"><span class="bq-recall-icon" aria-hidden="true">📘</span><span><b>${escapeHtml(book.name)}</b><small>${book.questions} questions · <span data-recall-summary="${escapeHtml(book.code)}">${summary.review} review${summary.seen?` · ${summary.seen} studied`:''}${summary.last?` · last ${summary.last.remembered}/${summary.last.total}`:''}</span></small></span><strong aria-hidden="true">›</strong></button>`}).join(''):'<section class="bq-panel"><h2>No matching books</h2><p>Try a different book name.</p></section>'}</section><section class="bq-panel bq-recall-source"><p><strong>Source:</strong> ${escapeHtml(state.source)} · ${escapeHtml(state.license)}. These are open study questions and reference answers; Scripture remains the primary text to examine.</p></section><div class="bq-game-footer"><button type="button" class="bq-secondary-button" data-game-launcher>All games</button></div>`;return;
        }
        if(state.phase==='recall-question'){
          const item=state.recallItem,progressPct=Math.round((state.index/Math.max(1,state.total))*100);
          host.innerHTML=`<section class="bq-game-topline"><button type="button" class="bq-secondary-button" data-recall-library>Recall library</button><div class="bq-game-score">Remembered <b>${state.remembered}</b> · +${state.gained} XP</div></section><section class="bq-panel bq-question-card" data-recall-question="${escapeHtml(item.id)}"><div class="bq-game-meta"><span>${escapeHtml(state.recallBook.name)} · Recall Deck</span><span data-recall-progress>Question ${state.index+1} of ${state.total}</span></div><div class="bq-game-progress" aria-hidden="true"><i style="width:${progressPct}%"></i></div><div class="bq-recall-mark" aria-hidden="true">🧠</div><h1>${escapeHtml(item.question)}</h1>${state.revealed?`<div class="bq-recall-answer" data-recall-answer><small>REFERENCE ANSWER</small><p>${escapeHtml(item.answer)}</p>${item.reference?`<strong>📖 ${escapeHtml(state.recallBook.name)} ${escapeHtml(item.reference)}</strong>`:''}</div>${item.contextNote?`<aside class="bq-recall-context" data-recall-context><b>BibleQuest context</b><p>${escapeHtml(item.contextNote)}</p></aside>`:''}<div class="bq-recall-ratings"><button type="button" class="bq-secondary-button" data-recall-rate="again">Review again</button><button type="button" class="bq-primary-button" data-recall-rate="got">Got it</button></div>`:`<p class="bq-recall-think">Try to answer from memory before revealing the reference answer.</p><button type="button" class="bq-primary-button" data-recall-reveal>Reveal answer</button>`}<p class="bq-recall-license">${escapeHtml(state.source)} · ${escapeHtml(state.license)}</p></section>`;return;
        }
        if(state.phase==='recall-complete'){
          host.innerHTML=`<section class="bq-panel bq-game-result" data-recall-complete><p class="bq-eyebrow">${escapeHtml(state.recallBook.name)} DECK COMPLETE</p><div class="bq-game-medal" aria-hidden="true">🗃️</div><h1>${state.remembered}/${state.total}</h1><p>${state.reviewAgain?`${state.reviewAgain} item${state.reviewAgain===1?'':'s'} will return in a future ${escapeHtml(state.recallBook.name)} session.`:'Everything in this round was marked remembered.'}</p><div class="bq-game-stats"><div><b>+${state.gained}</b><span>XP</span></div><div><b>${state.remembered}</b><span>got it</span></div><div><b>${state.remainingReview}</b><span>book review</span></div></div><div class="bq-game-actions"><button type="button" class="bq-primary-button" data-recall-replay>Study ${escapeHtml(state.recallBook.name)} again</button><button type="button" class="bq-secondary-button" data-recall-library>Choose another book</button><button type="button" class="bq-secondary-button" data-game-launcher>All games</button></div></section>`;return;
        }
        if(state.phase==='complete'){
          const pct=Math.round((state.score/Math.max(1,state.total))*100),message=pct>=90?'Excellent recall. Keep connecting the details to the bigger story.':pct>=70?'Good round. Review the explanations and keep strengthening the weak spots.':'Useful round. The misses point to what to review next.';
          host.innerHTML=`<section class="bq-panel bq-game-result" data-game-complete><p class="bq-eyebrow">ROUND COMPLETE</p><div class="bq-game-medal" aria-hidden="true">${pct>=90?'🏆':pct>=70?'🌟':'🌱'}</div><h1>${state.score}/${state.total}</h1><p>${escapeHtml(message)}</p><div class="bq-game-stats"><div><b>${pct}%</b><span>accuracy</span></div><div><b>+${state.gained}</b><span>XP</span></div><div><b>${escapeHtml(state.modeTitle)}</b><span>mode</span></div></div><div class="bq-game-actions"><button type="button" class="bq-primary-button" data-game-replay>Play again</button><button type="button" class="bq-secondary-button" data-game-launcher>Choose another game</button><button type="button" class="bq-secondary-button" data-game-home>Back home</button></div></section>`;return;
        }
        const q=state.question,typeLabel=q.mode==='connection'?'Connections':q.level>=2?'Context':'Recall',progressPct=Math.round((state.index/Math.max(1,state.total))*100);
        host.innerHTML=`<section class="bq-game-topline"><button type="button" class="bq-secondary-button" data-game-launcher>All games</button><div class="bq-game-score" data-game-score>Score <b>${state.score}</b> · +${state.gained} XP</div></section><section class="bq-panel bq-question-card" data-game-question="${escapeHtml(q.id)}"><div class="bq-game-meta"><span>${escapeHtml(q.book)} · ${escapeHtml(typeLabel)}</span><span data-game-progress>Question ${state.index+1} of ${state.total}</span></div><div class="bq-game-progress" aria-hidden="true"><i style="width:${progressPct}%"></i></div><h1>${escapeHtml(q.q)}</h1><div class="bq-game-choices">${q.choices.map((choice,index)=>{const isCorrect=state.locked&&index===q.answer,isWrong=state.locked&&index===state.selected&&!state.correct,className=isCorrect?' is-correct':isWrong?' is-wrong':'';return `<button type="button" class="bq-game-choice${className}" data-game-answer="${index}" ${state.locked?'disabled':''}><span aria-hidden="true">${String.fromCharCode(65+index)}</span><b>${escapeHtml(choice)}</b></button>`}).join('')}</div><div class="bq-game-feedback" aria-live="polite">${state.locked?`<div class="bq-game-explanation" data-game-feedback><strong>${state.correct?'Correct':'Review this one'}</strong><p>${escapeHtml(q.why)}</p><span>📖 ${escapeHtml(q.ref)}</span><small>${q.mode==='basic'?'DIRECT / RECALL':'CONTEXT / CONNECTION'}</small></div><button type="button" class="bq-primary-button" data-game-next>${state.index+1===state.total?'See results':'Next question'}</button>`:''}</div>${RECALL_SOURCE}</section>`;
      };
      const loading=text=>{host.innerHTML=`<section class="bq-panel" role="status"><p class="bq-eyebrow">PLAY</p><h1>${escapeHtml(text)}</h1><p>Loading only the content this activity needs.</p></section>`};
      const showError=error=>{clearMemoryTimer();host.innerHTML=`<section class="bq-panel" role="alert"><h1>Game could not continue</h1><p>${escapeHtml(error?.message||'Unknown game error.')}</p><button type="button" class="bq-secondary-button" data-game-launcher>Back to games</button></section>`};
      const scheduleMemory=pending=>{clearMemoryTimer();if(!pending)return;memoryTimer=setTimeout(()=>{memoryTimer=null;if(disposed)return;try{const result=games.kidsMemory.resolve(pending.token);if(result.applied)render(result.state)}catch(error){showError(error)}},pending.delayMs)};
      const onClick=async event=>{
        const target=event.target instanceof Element?event.target:null;if(!target)return;
        try{
          if(target.closest('[data-game-home]')){clearMemoryTimer();games.leave();onHome();return}
          if(target.closest('[data-game-launcher]')){clearMemoryTimer();render(games.showLauncher());return}
          if(target.closest('[data-memory-open]')){clearMemoryTimer();render(games.kidsMemory.start(memoryWidth()));return}
          if(target.closest('[data-memory-replay]')){clearMemoryTimer();render(games.kidsMemory.replay(memoryWidth()));return}
          const memoryCard=target.closest('[data-memory-index]');if(memoryCard){const result=games.kidsMemory.flip(memoryCard.dataset.memoryIndex);render(result.state);scheduleMemory(result.pending);return}
          if(target.closest('[data-same-room-open]')){render(games.getSameRoomState());return}
          const sameStart=target.closest('[data-same-room-start]');if(sameStart){render(games.startSameRoom(sameStart.dataset.sameRoomStart));return}
          const sameAnswer=target.closest('[data-same-room-answer]');if(sameAnswer){render(games.answerSameRoom(sameAnswer.dataset.sameRoomAnswer));return}
          if(target.closest('[data-same-room-next]')){render(games.nextSameRoom());return}
          if(target.closest('[data-same-room-finish]')){render(games.finishSameRoom());return}
          if(target.closest('[data-detective-replay]')){render(games.replayDetective());return}
          if(target.closest('[data-timeline-replay]')){render(games.replayTimeline());return}
          if(target.closest('[data-timeline-check]')){render(games.checkTimeline());return}
          const move=target.closest('[data-timeline-move]');if(move){const [index,direction]=move.dataset.timelineMove.split(',');render(games.moveTimeline(index,direction));return}
          if(target.closest('[data-recall-library]')){loading('Opening recall library…');render(await games.returnRecallLibrary());return}
          if(target.closest('[data-recall-reveal]')){render(games.revealRecall());return}
          const rate=target.closest('[data-recall-rate]');if(rate){render(games.rateRecall(rate.dataset.recallRate));return}
          if(target.closest('[data-recall-replay]')){loading('Preparing this book again…');render(await games.replayRecall());return}
          const book=target.closest('[data-recall-book]');if(book){loading('Loading selected Bible book…');render(await games.startRecallBook(book.dataset.recallBook));return}
          const launch=target.closest('[data-game-launch]');if(launch){if(launch.dataset.gameLaunch==='per-book-recall'){loading('Opening recall library…');render(await games.openRecallLibrary())}else render(games.start(launch.dataset.gameLaunch));return}
          const answer=target.closest('[data-game-answer]');if(answer){render(games.answer(answer.dataset.gameAnswer));return}
          if(target.closest('[data-game-next]')){render(games.next());return}
          if(target.closest('[data-game-replay]')){render(games.replay());return}
        }catch(error){showError(error)}
      };
      const onInput=event=>{const target=event.target instanceof Element?event.target:null;if(target?.matches('[data-recall-search]'))render(games.setRecallQuery(target.value))};
      const onSubmit=event=>{const form=event.target instanceof HTMLFormElement?event.target:null;if(!form?.matches('[data-detective-form]'))return;event.preventDefault();try{const input=form.querySelector('[data-detective-answer]');render(games.answerDetective(input?.value||''))}catch(error){showError(error)}};
      host.addEventListener('click',onClick);host.addEventListener('input',onInput);host.addEventListener('submit',onSubmit);render(games.showLauncher());
      return()=>{disposed=true;clearMemoryTimer();host.removeEventListener('click',onClick);host.removeEventListener('input',onInput);host.removeEventListener('submit',onSubmit);games.leave()};
    }
  };
}
