const esc=(value='')=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const ago=iso=>{if(!iso)return'—';const minutes=Math.floor(Math.max(0,Date.now()-new Date(iso).getTime())/60000);return minutes<1?'now':minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`};
const when=iso=>iso?new Intl.DateTimeFormat('en-PH',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(iso)):'—';
const empty=text=>`<div class="bq-ops-empty">${esc(text)}</div>`;
const matches=(row,filter)=>filter==='all'||row?.congregationId===filter;

function header(state){return `<section class="bq-panel bq-ops-top"><button type="button" class="bq-secondary-button" data-ops-back>← Admin</button><div><p class="bq-eyebrow">MINISTRY OPERATIONS</p><h1>Operational status</h1><p class="bq-muted">Online presence · assignments · messages · polls · curated media · live rooms</p></div><span class="bq-ops-role">${esc(state.role==='owner'?'Owner':state.role==='admin'?'Admin':'Checking…')}</span></section>`}
function health(state){
  const health=state.dashboard.health||{},frontend=state.frontend||{},counts=health.counts||{},mismatch=frontend.packPolicy!=='?'&&frontend.runtimePolicy!=='?'&&frontend.packPolicy!==frontend.runtimePolicy;
  return `<section class="bq-panel bq-ops-section" data-ops-health><div class="bq-ops-section-head"><div><h2>System health</h2><p class="bq-muted">Current runtime identity and privileged cloud diagnostics.</p></div><b>${health.clientErrors24h?.length||0} errors / 24h</b></div><div class="bq-ops-health-grid"><div><b>v${esc(frontend.pwa||'?')}</b><span>PWA cache</span></div><div><b>${esc(String(health.opsVersion||'?'))}</b><span>Admin backend</span></div><div class="${mismatch?'bad':'good'}"><b>${esc(frontend.packPolicy||'?')} → ${esc(frontend.runtimePolicy||'?')}</b><span>Doctrinal pack → runtime</span></div><div><b>${esc(String(frontend.build||'main').slice(0,12))}</b><span>Build identity</span></div></div><div class="bq-ops-counts">${Object.entries(counts).map(([key,value])=>`<span><b>${Number(value)||0}</b> ${esc(key.replace(/^bible_/,'').replaceAll('_',' '))}</span>`).join('')}</div>${mismatch?'<div class="bq-ops-warning"><b>Release blocker</b><div>Generated doctrinal policy does not match the runtime classifier. Do not mark the corpus reconciled until regenerated and audited.</div></div>':''}<div class="bq-ops-list">${health.clientErrors24h?.length?health.clientErrors24h.slice(0,12).map(item=>`<article class="bq-ops-row"><div><h3>${esc(item.message)}</h3><p>${esc(item.surface)} · ${esc(item.appVersion)}</p></div><span class="bq-ops-meta">${esc(ago(item.createdAt))}</span></article>`).join(''):empty('No sanitized client runtime errors recorded in the last 24 hours.')}</div></section>`;
}
function summary(state,filter){
  const data=state.dashboard,online=data.online.filter(row=>matches(row,filter)),assignments=data.assignments.filter(row=>matches(row,filter)),messages=data.messages.filter(row=>matches(row,filter)),polls=data.polls.filter(row=>matches(row,filter)),media=data.media.filter(row=>matches(row,filter)),rooms=data.rooms.filter(row=>matches(row,filter));
  return `<section class="bq-ops-summary" aria-label="Operational summary"><div class="bq-panel bq-ops-stat"><b>${online.length}</b><span>Online now</span></div><div class="bq-panel bq-ops-stat"><b>${assignments.filter(row=>row.active).length}</b><span>Active assignments</span></div><div class="bq-panel bq-ops-stat"><b>${messages.filter(row=>row.active).length}</b><span>Recent messages</span></div><div class="bq-panel bq-ops-stat"><b>${polls.filter(row=>row.active).length}</b><span>Persistent polls</span></div><div class="bq-panel bq-ops-stat"><b>${media.filter(row=>row.active).length}</b><span>Curated media</span></div><div class="bq-panel bq-ops-stat"><b>${rooms.filter(row=>row.status!=='ended').length}</b><span>Live rooms</span></div></section>`;
}
function online(data,filter){const rows=data.online.filter(row=>matches(row,filter));return `<section class="bq-panel bq-ops-section"><div class="bq-ops-section-head"><div><h2>Who is online</h2><p class="bq-muted">Presence expires after about two minutes.</p></div><b>${rows.length}</b></div><div class="bq-ops-list">${rows.length?rows.map(row=>`<article class="bq-ops-row"><div class="bq-ops-online"><span class="bq-ops-dot" aria-hidden="true"></span><div><h3>${esc(row.displayName)}</h3><p>${esc(row.congregationName)} · ${esc(row.role)} · ${esc(row.surface)}</p></div></div><span class="bq-ops-meta">${esc(ago(row.lastSeenAt))}</span></article>`).join(''):empty('No one is currently showing online.')}</div></section>`}
function assignments(data,filter){const rows=data.assignments.filter(row=>matches(row,filter));return `<section class="bq-panel bq-ops-section"><div class="bq-ops-section-head"><div><h2>Leader / pastor assignments</h2><p class="bq-muted">Requirements, schedule and completion status.</p></div><b>${rows.length}</b></div><div class="bq-ops-list">${rows.length?rows.map(row=>`<article class="bq-ops-row"><div><h3>${esc(row.title)}</h3><p>${esc(row.creatorName)} · ${esc(row.creatorRole)} · ${esc(row.congregationName)}</p><div class="bq-ops-tags"><span class="bq-ops-tag">${esc(row.assignmentType)}</span><span class="bq-ops-tag">${row.started} started</span><span class="bq-ops-tag">${row.completed} completed</span>${row.scheduleAt?`<span class="bq-ops-tag">Opens ${esc(when(row.scheduleAt))}</span>`:''}${row.recurrenceRule?`<span class="bq-ops-tag">${esc(row.recurrenceRule)}</span>`:''}${row.requiredReflection?'<span class="bq-ops-tag">Reflection required</span>':''}${row.minQuizScore!==null?`<span class="bq-ops-tag">Quiz ≥ ${Number(row.minQuizScore)}%</span>`:''}</div></div><span class="bq-ops-meta">${esc(when(row.createdAt))}</span></article>`).join(''):empty('No assignments have been created yet.')}</div></section>`}
function messages(data,filter){const rows=data.messages.filter(row=>matches(row,filter));return `<section class="bq-panel bq-ops-section"><div class="bq-ops-section-head"><div><h2>Devotionals & announcements</h2><p class="bq-muted">Includes scheduled and pinned media announcements.</p></div><b>${rows.length}</b></div><div class="bq-ops-list">${rows.length?rows.map(row=>`<article class="bq-ops-row"><div><h3>${row.pinned?'📌 ':''}${esc(row.title)}</h3><p>${esc(row.creatorName)} · ${esc(row.creatorRole)} · ${esc(row.congregationName)}</p><div class="bq-ops-tags"><span class="bq-ops-tag">${esc(row.messageType)}</span>${row.mediaPath?'<span class="bq-ops-tag">Image/banner</span>':''}${row.publishAt&&new Date(row.publishAt)>new Date()?'<span class="bq-ops-tag">Scheduled</span>':''}</div></div><span class="bq-ops-meta">${esc(when(row.publishAt))}</span></article>`).join(''):empty('No ministry messages have been published yet.')}</div></section>`}
function polls(data,filter){const rows=data.polls.filter(row=>matches(row,filter));return `<section class="bq-panel bq-ops-section"><div class="bq-ops-section-head"><div><h2>Congregation polls</h2><p class="bq-muted">Persistent poll aggregates; individual voter records are not displayed.</p></div><b>${rows.length}</b></div><div class="bq-ops-list">${rows.length?rows.map(row=>`<article class="bq-ops-row"><div><h3>${esc(row.prompt)}</h3><p>${esc(row.creatorName)} · ${esc(row.congregationName)}</p><div class="bq-ops-tags"><span class="bq-ops-tag">${esc(row.pollType)}</span><span class="bq-ops-tag">${esc(row.resultsVisibility)}</span><span class="bq-ops-tag">${row.votes} votes</span>${row.totals.map(total=>`<span class="bq-ops-tag">${esc(total.label)}: ${total.total}</span>`).join('')}</div></div><span class="bq-ops-meta">${esc(when(row.createdAt))}</span></article>`).join(''):empty('No persistent polls have been created yet.')}</div></section>`}
function media(data,filter){const rows=data.media.filter(row=>matches(row,filter));return `<section class="bq-panel bq-ops-section"><div class="bq-ops-section-head"><div><h2>Handpicked videos & channels</h2><p class="bq-muted">Curated congregation YouTube media metadata.</p></div><b>${rows.length}</b></div><div class="bq-ops-list">${rows.length?rows.map(row=>`<article class="bq-ops-row"><div><h3>${row.featured?'★ ':''}${esc(row.title)}</h3><p>${esc(row.creatorName)} · ${esc(row.creatorRole)} · ${esc(row.congregationName)}</p><div class="bq-ops-tags"><span class="bq-ops-tag">${esc(row.mediaType.replace('youtube_',''))}</span><span class="bq-ops-tag">order ${row.displayOrder}</span>${row.publishAt&&new Date(row.publishAt)>new Date()?'<span class="bq-ops-tag">Scheduled</span>':''}${!row.active?'<span class="bq-ops-tag">Archived</span>':''}</div></div><span class="bq-ops-meta">${esc(when(row.publishAt))}</span></article>`).join(''):empty('No curated videos, playlists or channels have been published yet.')}</div></section>`}
function rooms(data,filter){const rows=data.rooms.filter(row=>matches(row,filter));return `<section class="bq-panel bq-ops-section"><div class="bq-ops-section-head"><div><h2>Live rooms & live polls</h2><p class="bq-muted">Host, status and participant count.</p></div><b>${rows.length}</b></div><div class="bq-ops-list">${rows.length?rows.map(row=>`<article class="bq-ops-row"><div><h3>${esc(row.title)}</h3><p>${esc(row.creatorName)} · ${esc(row.congregationName)}</p><div class="bq-ops-tags"><span class="bq-ops-tag">${esc(row.status)}</span><span class="bq-ops-tag">${row.participants} participants</span></div></div><span class="bq-ops-meta">${esc(when(row.createdAt))}</span></article>`).join(''):empty('No live rooms have been hosted yet.')}</div></section>`}

export function adminOperationsPage({operations,onBack,onAccount}={}){
  return {title:'Ministry Operations',html:'<div class="bq-ops-shell" data-admin-operations-view></div>',mount(root){
    const view=root.querySelector('[data-admin-operations-view]');let disposed=false,busy=false,filter='all';
    const bindBase=()=>{view.querySelector('[data-ops-back]')?.addEventListener('click',()=>onBack?.(),{once:true});view.querySelector('[data-ops-account]')?.addEventListener('click',()=>onAccount?.(),{once:true});view.querySelector('[data-ops-retry]')?.addEventListener('click',load,{once:true})};
    const render=state=>{
      if(disposed)return;
      if(state.status==='signed-out'){view.innerHTML=`${header(state)}<section class="bq-panel"><h2>Sign in required</h2><p>Ministry Operations has no guest authority.</p><button type="button" class="bq-primary-button" data-ops-account>Open account</button></section>`;bindBase();return}
      if(state.status==='unauthorized'){view.innerHTML=`${header(state)}<section class="bq-panel"><h2>Owner/Admin access required</h2><p>This account does not have active BibleQuest platform operations access.</p></section>`;bindBase();return}
      if(state.status==='error'){view.innerHTML=`${header(state)}<section class="bq-panel"><h2>Admin operations unavailable</h2><p class="bq-form-message" role="alert">${esc(state.error||'Try again.')}</p><button type="button" class="bq-secondary-button" data-ops-retry>Try again</button></section>`;bindBase();return}
      if(state.status!=='ready'){view.innerHTML=`${header(state)}<section class="bq-panel"><h2>Refreshing BibleQuest health…</h2></section>`;bindBase();return}
      const data=state.dashboard,options=data.congregations.map(item=>`<option value="${esc(item.id)}" ${filter===item.id?'selected':''}>${esc(item.name)}</option>`).join('');
      view.innerHTML=`${header(state)}<section class="bq-panel bq-ops-toolbar"><label>Congregation<select data-ops-filter><option value="all">All congregations</option>${options}</select></label><button type="button" class="bq-secondary-button" data-ops-refresh ${busy||state.busy?'disabled':''}>Refresh status</button></section><div class="bq-ops-warning"><b>Evidence rule</b><div>Zero records means implemented but not field-proven. Health checks do not replace real multi-account/mobile acceptance.</div></div>${health(state)}${summary(state,filter)}${online(data,filter)}${assignments(data,filter)}${messages(data,filter)}${polls(data,filter)}${media(data,filter)}${rooms(data,filter)}`;
      bindBase();view.querySelector('[data-ops-filter]')?.addEventListener('change',event=>{filter=event.currentTarget.value;render(operations.getState())});view.querySelector('[data-ops-refresh]')?.addEventListener('click',load,{once:true});
    };
    async function load(){if(disposed||busy)return;busy=true;render({...operations.getState(),status:'loading'});await operations.refresh();busy=false;render(operations.getState())}
    void load();return()=>{disposed=true;operations.clear()};
  }};
}
