const rows = [
  ["p1","Can forgiveness exist without restored trust?","Compare forgiveness, repentance, wisdom, reconciliation, and boundaries. Avoid assuming that one word must perform every function.",[["Matthew 18:21–35","MAT",18],["Luke 17:3–4","LUK",17],["Proverbs 22:3","PRO",22]],["Yes, they are distinct","No, trust must return immediately","Only if the offense was minor","I need more context"]],
  ["p2","When does “trusting God” become an excuse for poor planning?","Consider faith, uncertainty, stewardship, and the possibility that planning itself can either express wisdom or become an attempt at control.",[["Proverbs 21:5","PRO",21],["Luke 14:28–30","LUK",14],["James 4:13–15","JAS",4]],["Planning always shows weak faith","Faith and planning can coexist","Planning is always superior to intuition","I need more context"]],
  ["p3","Is doing the right thing still virtuous when the main motive is fear of punishment?","Compare outward action, motive, moral formation, love, fear, and whether mixed motives can still produce genuine obedience.",[["1 John 4:18","1JN",4],["Proverbs 1:7","PRO",1],["1 Corinthians 13:3","1CO",13]],["Yes without qualification","No without qualification","Partly; action and motive both matter","I need more context"]],
  ["p4","Can someone be sincere in faith and still be seriously mistaken?","Consider sincerity, teachability, evidence, correction, and the limits of human understanding.",[["Acts 18:24–26","ACT",18],["Proverbs 12:1","PRO",12],["1 Corinthians 13:12","1CO",13]],["Yes","No","Only on minor matters","I need more context"]],
  ["p5","Is refusing to choose sometimes a moral choice in itself?","Delay can be prudent, fearful, manipulative, or responsible depending on what the delay does to other people and available options.",[["James 4:17","JAS",4],["Proverbs 22:3","PRO",22],["Ecclesiastes 3:1–8","ECC",3]],["Delay is neutral","Delay can carry responsibility","Every decision should be immediate","I need more context"]],
  ["p6","When does protecting peace become avoiding necessary conflict?","Distinguish peacemaking from conflict avoidance. Ask whether silence repairs relationships or merely postpones truth.",[["Matthew 5:9","MAT",5],["Matthew 18:15","MAT",18],["Romans 12:18","ROM",12]],["Peace requires silence","Necessary correction can serve peace","Conflict is always spiritually harmful","I need more context"]],
  ["p7","Can humility require disagreeing publicly with someone you respect?","Consider respect, truth, proportionality, audience harm, and whether private correction has been attempted or is sufficient.",[["Acts 18:24–26","ACT",18],["Galatians 2:11–14","GAL",2],["1 Peter 5:5","1PE",5]],["Never","Sometimes","Always if you think you are right","I need more context"]],
  ["p8","If two biblical principles point in different practical directions, what should decide the action?","Many wisdom problems involve competing goods rather than good versus obvious evil. Think about context, responsibility, consequences, and textual priority without turning consequences into the only standard.",[["Philippians 1:9–10","PHP",1],["Proverbs 2:6–11","PRO",2],["Romans 14:5","ROM",14]],["Use one favorite verse","Compare context and duties","Choose the easier option","I need more context"]],
  ["p9","Does a good outcome justify a misleading method if the underlying cause is true?","Separate truth of the goal from truthfulness of the means. Consider whether urgency changes the duty not to deceive.",[["Romans 3:8","ROM",3],["2 Corinthians 4:2","2CO",4],["Ephesians 4:25","EPH",4]],["Usually yes","No; means also matter","Only if nobody is harmed","I need more context"]],
  ["p10","Can generosity become irresponsible?","Consider generosity alongside obligations to dependents, future commitments, and whether sacrifice is being imposed on people who did not choose it.",[["2 Corinthians 8:12–14","2CO",8],["1 Timothy 5:8","1TI",5],["Proverbs 21:20","PRO",21]],["No, more giving is always better","Yes, stewardship can limit a gift","Only for nonreligious causes","I need more context"]],
  ["p11","Is loyalty still a virtue when it prevents you from naming wrongdoing?","Explore the difference between loyalty to a person, loyalty to truth, protection from gossip, and concealment that enables harm.",[["Proverbs 17:17","PRO",17],["Ephesians 5:11","EPH",5],["Proverbs 11:13","PRO",11]],["Loyalty requires silence","Loyalty and correction can coexist","Wrongdoing ends every relationship","I need more context"]],
  ["p12","Can obeying authority become a way of avoiding personal moral responsibility?","Authority can coordinate legitimate action, but delegated responsibility does not necessarily erase conscience, truthfulness, or accountability.",[["Romans 13:1–7","ROM",13],["Acts 5:29","ACT",5],["Daniel 6:10","DAN",6]],["Authority removes personal responsibility","Authority matters but is not absolute","All authority should be distrusted","I need more context"]],
  ["p13","When is “setting a boundary” actually selfishness?","Boundaries can protect legitimate responsibilities or become a polished name for refusing sacrifice. The hard work is identifying what duty actually belongs to you.",[["Galatians 6:2,5","GAL",6],["Philippians 2:4","PHP",2],["Mark 1:35–38","MRK",1]],["Boundaries are always healthy","Boundaries can be selfish or wise","Self-sacrifice forbids boundaries","I need more context"]],
  ["p14","Should equal treatment always mean identical treatment?","Consider impartiality, different needs, different responsibilities, and whether fairness sometimes requires relevant distinctions.",[["James 2:1–9","JAS",2],["Acts 6:1–6","ACT",6],["Matthew 20:1–16","MAT",20]],["Yes, fairness means identical outcomes","No, relevant differences can matter","Only leaders may decide","I need more context"]],
  ["p15","Can a person be responsible for harm they did not intend?","Intent matters, but so can negligence, foreseeable consequences, and what someone does after learning about the harm.",[["Exodus 21:28–36","EXO",21],["Luke 12:47–48","LUK",12],["Philippians 2:4","PHP",2]],["No intent means no responsibility","Responsibility can exist without intent","All unintended harm is equally blameworthy","I need more context"]],
  ["p16","When does confidence in a conviction become closed-mindedness?","Conviction need not mean refusing correction. Ask what evidence could change your mind and whether the belief is central, inferred, or uncertain.",[["Acts 17:11","ACT",17],["Proverbs 18:13","PRO",18],["2 Timothy 1:12","2TI",1]],["Strong conviction is closed-minded","Conviction and teachability can coexist","Every belief should remain equally uncertain","I need more context"]],
  ["p17","Is reconciliation always the most loving immediate goal after serious conflict?","Reconciliation is valuable, but timing, truth, repentance, safety, and the possibility of continued harm may affect what love requires first.",[["Romans 12:18","ROM",12],["Luke 17:3–4","LUK",17],["Proverbs 22:3","PRO",22]],["Yes, restore closeness immediately","Not always; truth and safety may come first","Never after serious conflict","I need more context"]],
  ["p18","Can spiritual language make an ordinary preference sound like a divine command?","Reflect on the difference between Scripture, conscience, wisdom, personal impressions, and claiming certainty about God’s specific direction.",[["James 4:13–15","JAS",4],["1 Thessalonians 5:21","1TH",5],["Proverbs 15:22","PRO",15]],["Personal conviction equals command","Impressions should be tested humbly","Spiritual impressions have no value","I need more context"]]
];

function freezeQuestion([id,prompt,reflection,rawReferences,rawOptions]) {
  const references = Object.freeze(rawReferences.map(([label,code,chapter])=>Object.freeze({label,code,chapter})));
  const options = Object.freeze([...rawOptions]);
  const reference = references.map(item=>item.label).join(' · ');
  const steps = Object.freeze([
    Object.freeze({id:'response',type:'choice',prompt,choices:options,feedback:Object.freeze({response:'Your response is saved for this reflection. Deep Questions does not score this as a right or wrong spiritual answer.'})}),
    Object.freeze({id:'reflection',type:'content',prompt:reflection,reference}),
    Object.freeze({id:'note',type:'text',prompt:'Write a private note about what you notice, what remains difficult, or what you want to examine in Scripture.',reference,maxLength:3000,feedback:Object.freeze({response:'Private note saved on this device through the shared Lesson session.'})})
  ]);
  return Object.freeze({id,prompt,reflection,references,options,definition:Object.freeze({id:`deep-question:${id}`,version:1,title:prompt,steps})});
}

export const DEEP_QUESTIONS = Object.freeze(rows.map(freezeQuestion));

export function getDeepQuestion(id) {
  const question = DEEP_QUESTIONS.find(item=>item.id===String(id||''));
  if (!question) throw new Error(`Unknown Deep Question: ${id||'missing'}.`);
  return question;
}
