export const COUPLES_CATEGORIES=Object.freeze([
  {id:'christ',icon:'✝️',label:'Us & God'},
  {id:'communication',icon:'👂',label:'Listen & Understand'},
  {id:'conflict',icon:'🕊️',label:'Repair & Forgive'},
  {id:'gratitude',icon:'💛',label:'Friendship & Gratitude'},
  {id:'stewardship',icon:'🏠',label:'Money & Responsibilities'},
  {id:'intimacy',icon:'🤍',label:'Closeness & Affection'},
  {id:'family',icon:'🌱',label:'Parenting & Family'},
  {id:'mission',icon:'🧭',label:'Purpose & Future'}
].map(item=>Object.freeze(item)));

export const COUPLES_TRACKS=Object.freeze([
  Object.freeze({id:'couples',label:'Couples Track',description:'Communication, repair, friendship, stewardship, closeness, faith, and shared purpose.',categories:Object.freeze(['christ','communication','conflict','gratitude','stewardship','intimacy','mission'])}),
  Object.freeze({id:'family',label:'Family Track',description:'Parenting, home atmosphere, family boundaries, faith at home, and shared responsibility.',categories:Object.freeze(['family','christ','stewardship','gratitude'])})
]);

export const COUPLES_CARDS=Object.freeze([
  {id:'c01',cat:'christ',title:'Same direction?',prompt:'Sa season natin ngayon, saan mo pinaka-nararamdaman na hinihila tayo ni Christ na mag-grow bilang mag-asawa?',follow:'Ano ang isang maliit na spiritual habit na kaya nating gawin together nang realistic?',practice:'10 minutes this week: read, pray, then share one sentence each.',ref:'Colossians 3:12–17',code:'COL',chapter:3},
  {id:'c02',cat:'christ',title:'Faith without performance',prompt:'May part ba ng spiritual life natin na ginagawa natin dahil “dapat,” pero hindi na natin pinag-uusapan nang totoo?',follow:'Ano ang makakatulong para maging mas honest at less performative ang faith natin sa bahay?',practice:'Ask one honest faith question without trying to fix the answer.',ref:'Psalm 139:23–24',code:'PSA',chapter:139},
  {id:'c03',cat:'christ',title:'Pray for me like this',prompt:'Kung isang bagay lang ang ipagpe-pray mo para sa akin this month, ano iyon—and why?',follow:'Ano ang ayaw mong gawing “project” kita habang ipinagpe-pray kita?',practice:'Pray one specific, non-corrective prayer for your spouse.',ref:'Philippians 1:9–11',code:'PHP',chapter:1},
  {id:'c04',cat:'christ',title:'Grace at home',prompt:'Saan ako pinakamadaling bigyan ng grace ng ibang tao pero pinakamahirap bigyan ng grace sa bahay?',follow:'Paano natin mapaghihiwalay ang grace sa pag-iwas sa accountability?',practice:'Name one grace you received from your spouse this week.',ref:'Ephesians 4:1–3',code:'EPH',chapter:4},
  {id:'c05',cat:'communication',title:'Do you feel heard?',prompt:'Kailan mo huling naramdaman na talagang naintindihan kita—not just narinig?',follow:'Ano ang ginawa ko noon na gusto mong ulitin ko?',practice:'For one conversation, summarize before giving your opinion.',ref:'Proverbs 18:13',code:'PRO',chapter:18},
  {id:'c06',cat:'communication',title:'What I miss',prompt:'Anong signal mo kapag pagod, worried, o overwhelmed ka na madalas kong nami-miss?',follow:'Ano ang pinaka-helpful kong response kapag nakikita ko ang signal na iyon?',practice:'Agree on one simple phrase that means “I need support, not solutions.”',ref:'1 Thessalonians 5:14–15',code:'1TH',chapter:5},
  {id:'c07',cat:'communication',title:'Advice or presence?',prompt:'Kapag may problema ka, paano ko malalaman kung gusto mo ng advice, tulong, prayer, o simpleng kasama lang?',follow:'May example ba recently na maling mode ang ginamit ko?',practice:'Ask: “Makikinig lang ba ako, tutulong, or mag-iisip tayo ng solution?”',ref:'Romans 12:15–16',code:'ROM',chapter:12},
  {id:'c08',cat:'communication',title:'Hard truth, gentle delivery',prompt:'Ano ang isang concern na gusto mong mas safe sabihin sa akin nang hindi ako agad defensive?',follow:'Anong wording o timing ang makakatulong para marinig ko ito nang maayos?',practice:'Use one specific observation, not “always” or “never.”',ref:'Ephesians 4:25–29',code:'EPH',chapter:4},
  {id:'c09',cat:'conflict',title:'The real issue',prompt:'Kapag paulit-ulit ang argument natin, ano sa tingin mo ang deeper need sa ilalim ng topic?',follow:'Ano ang fear o assumption na baka hindi natin nasasabi?',practice:'Name the issue in one sentence without blame.',ref:'James 4:1–3',code:'JAS',chapter:4},
  {id:'c10',cat:'conflict',title:'My part',prompt:'Sa isang recent conflict, ano ang part ko na kaya kong akuin kahit may part ka rin?',follow:'Ano ang sincere repair na mas meaningful kaysa simpleng “sorry”?',practice:'Own one specific action without adding “pero ikaw kasi…”.',ref:'Matthew 7:1–5',code:'MAT',chapter:7},
  {id:'c11',cat:'conflict',title:'Forgiveness and trust',prompt:'May bagay ba na napatawad na natin in principle pero kailangan pa rin ng rebuilding ng trust?',follow:'Anong consistent action—not promise—ang makakatulong?',practice:'Choose one observable trust-building behavior for 7 days.',ref:'Proverbs 28:13',code:'PRO',chapter:28},
  {id:'c12',cat:'conflict',title:'When to pause',prompt:'Ano ang signs na hindi na productive ang usapan natin at kailangan muna nating huminto?',follow:'Paano tayo magpa-pause nang hindi mukhang abandonment o silent treatment?',practice:'Agree on a pause phrase and a concrete return time.',ref:'Proverbs 17:14',code:'PRO',chapter:17},
  {id:'c13',cat:'gratitude',title:'I noticed this',prompt:'Anong effort ko recently ang napansin mo pero baka hindi mo pa nasasabi?',follow:'Bakit meaningful iyon sa iyo?',practice:'Give one specific appreciation today—behavior, impact, gratitude.',ref:'1 Thessalonians 5:11',code:'1TH',chapter:5},
  {id:'c14',cat:'gratitude',title:'Still my friend',prompt:'Ano ang bagay na nami-miss mong gawin natin as friends—not just as spouses/parents/workers?',follow:'Ano ang cheapest, simplest version na puwede nating gawin this month?',practice:'Schedule one low-pressure shared activity.',ref:'Genesis 2:18–24',code:'GEN',chapter:2},
  {id:'c15',cat:'gratitude',title:'What I admire now',prompt:'Ano ang quality ko na mas naa-appreciate mo ngayon kaysa noong bago pa tayo?',follow:'Saan mo nakikita na nag-grow ako?',practice:'Say one admiration without joking it away.',ref:'Romans 12:9–10',code:'ROM',chapter:12},
  {id:'c16',cat:'gratitude',title:'Best small memory',prompt:'Anong maliit at ordinaryong memory natin ang unexpectedly precious sa iyo?',follow:'Ano ang sinasabi nito tungkol sa klase ng life na gusto nating buuin?',practice:'Recreate one simple thing you both enjoyed before.',ref:'Philippians 1:3–5',code:'PHP',chapter:1},
  {id:'c17',cat:'stewardship',title:'Money means what?',prompt:'Kapag pinag-uusapan natin ang money, ano ang pinaka-malakas na emotion mo: security, freedom, fear, responsibility, generosity, status, o iba?',follow:'Saan kaya galing ang meaning na iyon sa family history mo?',practice:'Discuss one money decision by values first, numbers second.',ref:'Matthew 6:19–24',code:'MAT',chapter:6},
  {id:'c18',cat:'stewardship',title:'Invisible work',prompt:'Anong responsibility sa bahay/family ang tingin mo hindi masyadong nakikita o naa-appreciate?',follow:'May task ba na kailangang i-redistribute, simplify, or stop?',practice:'Transfer or simplify one recurring burden this week.',ref:'Galatians 6:2–5',code:'GAL',chapter:6},
  {id:'c19',cat:'stewardship',title:'Enough',prompt:'Ano ang ibig sabihin ng “enough” para sa family natin—money, house, possessions, work hours?',follow:'Ano ang ayaw nating isakripisyo para lang kumita o umangat?',practice:'Write one family boundary around work, spending, or time.',ref:'1 Timothy 6:6–10',code:'1TI',chapter:6},
  {id:'c20',cat:'stewardship',title:'Generosity together',prompt:'Saan tayo gustong maging generous bilang couple—family, church, neighbors, strangers, time, skills?',follow:'Paano tayo magiging generous nang hindi irresponsible sa sariling household?',practice:'Choose one planned act of generosity together.',ref:'2 Corinthians 9:6–8',code:'2CO',chapter:9},
  {id:'c21',cat:'intimacy',title:'Loved in ordinary days',prompt:'Anong ordinary action ang pinaka-nagpaparamdam sa iyo na loved ka?',follow:'Ano ang ginagawa kong sincere pero hindi ganoon ka-meaningful sa iyo?',practice:'Do one small affection your spouse actually values.',ref:'1 Corinthians 13:4–7',code:'1CO',chapter:13},
  {id:'c22',cat:'intimacy',title:'Closeness needs safety',prompt:'Ano ang nagpapadali para maging emotionally open at affectionate ka sa akin?',follow:'Ano ang behavior na mabilis magsara ng loob mo?',practice:'Create one distraction-free 15-minute connection window.',ref:'Colossians 3:12–14',code:'COL',chapter:3},
  {id:'c23',cat:'intimacy',title:'Ask, don’t assume',prompt:'May need ba sa closeness, affection, rest, or attention na ina-assume nating obvious pero hindi pala napag-uusapan?',follow:'Paano natin ito mapag-uusapan nang walang pressure o entitlement?',practice:'Ask clearly for one form of connection and accept an honest answer.',ref:'Philippians 2:3–4',code:'PHP',chapter:2},
  {id:'c24',cat:'intimacy',title:'Protect our us-time',prompt:'Ano ang pinakamalaking kumakain ng couple connection natin ngayon?',follow:'Ano ang realistic protection—not ideal fantasy—na kaya nating gawin?',practice:'Protect one small recurring couple window this week.',ref:'Genesis 2:18–24',code:'GEN',chapter:2},
  {id:'c25',cat:'family',title:'What are we teaching?',prompt:'Anong value ang gusto nating makita ng mga anak/family sa paraan ng pakikitungo natin sa isa’t isa?',follow:'Ano ang nakikita nila ngayon na gusto nating baguhin?',practice:'Model one respectful repair in front of family when appropriate.',ref:'Proverbs 20:7',code:'PRO',chapter:20},
  {id:'c26',cat:'family',title:'Same team parenting',prompt:'Saan tayo pinaka-aligned sa parenting at saan tayo madalas magkaiba?',follow:'Ano ang rule o principle na kailangan nating pag-usapan privately bago harapin ang bata?',practice:'Agree on one consistent parenting response.',ref:'Deuteronomy 6:4–9',code:'DEU',chapter:6},
  {id:'c27',cat:'family',title:'Family pressure',prompt:'May pressure ba mula sa extended family, culture, church, or expectations na nakakaapekto sa marriage natin?',follow:'Anong boundary ang dapat nating hawakan together?',practice:'Use “we decided” rather than leaving one spouse alone to defend the boundary.',ref:'Genesis 2:23–24',code:'GEN',chapter:2},
  {id:'c28',cat:'family',title:'Home atmosphere',prompt:'Kung may isang word na gusto nating maramdaman sa bahay—peaceful, joyful, safe, disciplined, welcoming—ano iyon?',follow:'Anong habit ang pinaka-supportive at ano ang pinaka-sumasabotahe dito?',practice:'Pick one home atmosphere habit for seven days.',ref:'Colossians 3:12–17',code:'COL',chapter:3},
  {id:'c29',cat:'mission',title:'What are we building?',prompt:'Kung titingnan natin ang marriage natin 10 years from now, anong klaseng couple ang gusto nating maging—not just anong meron tayo?',follow:'Anong trait ang kailangan nating simulan ngayon?',practice:'Write one sentence describing the couple you want to become.',ref:'Psalm 127:1–2',code:'PSA',chapter:127},
  {id:'c30',cat:'mission',title:'Serve together',prompt:'Anong need sa paligid natin ang pareho nating napapansin at may realistic tayong maitutulong?',follow:'Paano ito magiging shared mission at hindi dagdag na burden sa isang spouse?',practice:'Choose one small act of service you can do together.',ref:'Galatians 5:13–14',code:'GAL',chapter:5},
  {id:'c31',cat:'mission',title:'Dream without pressure',prompt:'Anong dream mo na gusto mong marinig ko nang hindi ko agad kino-correct, kino-cost, o kino-convert into plan?',follow:'Ano ang part ng dream na pinaka-importanteng maintindihan ko?',practice:'Give your spouse five uninterrupted minutes to describe a dream.',ref:'Proverbs 20:5',code:'PRO',chapter:20},
  {id:'c32',cat:'mission',title:'Next faithful step',prompt:'Sa biggest decision natin ngayon, ano ang alam na nating tamang next step kahit hindi pa malinaw ang buong future?',follow:'Ano ang fear na nagpapa-delay sa atin?',practice:'Choose one reversible next step and a date to revisit it.',ref:'James 1:5–8',code:'JAS',chapter:1},
  {id:'c33',cat:'christ',title:'When faith feels dry',prompt:'Kapag spiritually tired o dry ka, ano ang pinaka-kailangan mo mula sa akin: prayer, space, encouragement, honesty, o simpleng presence?',follow:'Ano ang ginagawa ko na nakakatulong—at ano ang puwedeng maging pressure kahit good ang intention?',practice:'Ask once this week: “Paano kita masusuportahan spiritually ngayon?” Then accept the answer without correcting it.',ref:'Isaiah 40:28–31',code:'ISA',chapter:40},
  {id:'c34',cat:'christ',title:'What is God forming in us?',prompt:'Sa current season natin, anong character quality ang tingin mong tina-train ni God sa marriage natin—patience, courage, contentment, forgiveness, faithfulness, o iba?',follow:'Saan mo nakikita na may progress na tayo kahit maliit?',practice:'Name one evidence of growth in your spouse and thank God for it together.',ref:'Galatians 5:22–25',code:'GAL',chapter:5},
  {id:'c35',cat:'christ',title:'Honest before God',prompt:'May worry, disappointment, o prayer ba na nahihirapan kang sabihin kay God—and gusto mong marinig ko without trying to fix it?',follow:'Ano ang magiging supportive response ko pagkatapos mong mag-share?',practice:'Spend five quiet minutes together: one honest sentence each to God, then no advice unless asked.',ref:'Psalm 62:5–8',code:'PSA',chapter:62},
  {id:'c36',cat:'christ',title:'Rest is spiritual too',prompt:'Saan tayo pinaka-pagod bilang couple ngayon, at paano naaapektuhan ng pagod ang patience, faith, at connection natin?',follow:'Anong small form of rest can we protect without guilt this week?',practice:'Protect one shared low-demand rest window and keep it free from problem-solving.',ref:'Mark 6:30–32',code:'MRK',chapter:6},
  {id:'c37',cat:'communication',title:'What I did not say',prompt:'May bagay ba this week na gusto mong sabihin sa akin pero pinili mong huwag dahil pagod tayo, busy, o natakot kang ma-misunderstand?',follow:'Ano ang kailangan mong marinig o maramdaman para mas safe sabihin ang ganitong bagay next time?',practice:'Give each other three uninterrupted minutes to finish one thought that was left unsaid.',ref:'James 1:19–20',code:'JAS',chapter:1},
  {id:'c38',cat:'communication',title:'When I shut down',prompt:'Kapag quiet, defensive, sarcastic, o withdrawn ako, ano usually ang nangyayari sa loob ko bago mo makita ang reaction?',follow:'Anong gentle signal ang puwede nating gamitin para sabihing “I am getting overwhelmed” nang hindi tinatapos ang connection?',practice:'Choose one shared reset phrase and promise a specific return time to the conversation.',ref:'Proverbs 17:27–28',code:'PRO',chapter:17},
  {id:'c39',cat:'communication',title:'The story I tell myself',prompt:'Kapag hindi malinaw ang intention mo, anong negative assumption ang pinakamadali kong buuin tungkol sa iyo?',follow:'Anong question ang puwede kong itanong bago maniwala sa assumption na iyon?',practice:'Replace one assumption this week with: “Help me understand what you meant.”',ref:'Proverbs 18:17',code:'PRO',chapter:18},
  {id:'c40',cat:'communication',title:'How to reach me',prompt:'Kapag kailangan mong sabihin sa akin ang mahirap na feedback, anong timing, tone, o approach ang pinaka-nakakatulong para hindi ako agad mag-defend?',follow:'Ano naman ang paraan na halos guaranteed na magsasara ako?',practice:'Before one hard conversation, ask: “Good time ba ngayon, or kailan tayo mas ready?”',ref:'Proverbs 15:23',code:'PRO',chapter:15},
  {id:'c41',cat:'conflict',title:'Our repeating cycle',prompt:'Sa recurring conflict natin, ano ang usual cycle—sino ang humahabol, umiwas, nagde-defend, nagiging sharp, o nananahimik?',follow:'Saan sa cycle pinakamadaling gumawa ng maliit na interruption bago lumala?',practice:'Name the cycle as the enemy this week, not your spouse: “Nandito na naman tayo sa pattern natin.”',ref:'Ephesians 4:26–32',code:'EPH',chapter:4},
  {id:'c42',cat:'conflict',title:'Repair language that works',prompt:'Pagkatapos ng tension, anong klaseng apology o repair ang tunay na nakakabawas ng distance para sa iyo?',follow:'May apology style ba ako na parang sincere sa akin pero kulang o frustrating para sa iyo?',practice:'Use a four-part repair once: what I did, impact, no excuse, what I will do differently.',ref:'Matthew 5:23–24',code:'MAT',chapter:5},
  {id:'c43',cat:'conflict',title:'What still hurts?',prompt:'May maliit o malaking hurt ba na technically “tapos na” pero may part mo pa ring hindi fully heard?',follow:'Ano ang kailangan: clarification, ownership, changed behavior, time, boundary, o prayer?',practice:'Listen to one unresolved hurt without debating whether your spouse “should” still feel it.',ref:'Romans 12:15–18',code:'ROM',chapter:12},
  {id:'c44',cat:'conflict',title:'Protect my dignity',prompt:'Kapag upset tayo, anong behavior ang pinaka-nakakaramdam sa iyo na nire-respeto pa rin kita kahit disagree tayo?',follow:'Anong behavior ang gusto nating parehong gawing off-limits during conflict?',practice:'Agree on two non-negotiable conflict boundaries and write them down.',ref:'Romans 12:9–10',code:'ROM',chapter:12},
  {id:'c45',cat:'gratitude',title:'I still choose you here',prompt:'Sa anong ordinary moment mo pinaka-nararamdaman na pinipili pa rin kita—kahit walang romance, event, o special occasion?',follow:'Ano ang maliit na gesture na puwedeng magparamdam nito more often?',practice:'Do one “I choose us” action this week without announcing it first.',ref:'Genesis 2:23–24',code:'GEN',chapter:2},
  {id:'c46',cat:'gratitude',title:'Let us laugh again',prompt:'Ano ang klase ng humor, memory, o activity na mabilis magaan ang atmosphere natin?',follow:'Kailan tayo naging sobrang serious lately na kailangan natin ng konting lightness?',practice:'Create one intentionally silly or playful 15-minute moment this week.',ref:'Proverbs 17:22',code:'PRO',chapter:17},
  {id:'c47',cat:'gratitude',title:'Strength you may not see',prompt:'Anong strength mo ang tingin kong ginagamit mo every week pero baka hindi mo napapansin sa sarili mo?',follow:'Paano nakakatulong ang strength na iyon sa marriage o family natin?',practice:'Tell your spouse one strength, one example, and one impact.',ref:'1 Thessalonians 5:11',code:'1TH',chapter:5},
  {id:'c48',cat:'gratitude',title:'The care behind the task',prompt:'Anong routine task o sacrifice mo ang mas gusto kong makita hindi lang as “responsibility” kundi as an act of care?',follow:'Ano ang responsibility ko na gusto mo ring makita ko with more appreciation?',practice:'Thank each other for one invisible or repetitive act of care today.',ref:'Philippians 2:3–4',code:'PHP',chapter:2},
  {id:'c49',cat:'stewardship',title:'Work is following us home',prompt:'Anong part ng work stress natin ang madalas sumunod hanggang bahay at kumakain ng patience o attention?',follow:'Anong transition ritual ang makakatulong para hindi lahat ng stress pumasok sa relationship?',practice:'Try a 10-minute decompression ritual before discussing logistics after work.',ref:'Psalm 127:1–2',code:'PSA',chapter:127},
  {id:'c50',cat:'stewardship',title:'Fair is not always equal',prompt:'Sa responsibilities natin ngayon, alin ang mukhang 50/50 sa papel pero hindi fair dahil magkaiba ang energy, schedule, o mental load?',follow:'Ano ang temporary adjustment na mas fair sa current season?',practice:'Rebalance one task for seven days, then review without scorekeeping.',ref:'Galatians 6:2–5',code:'GAL',chapter:6},
  {id:'c51',cat:'stewardship',title:'Mental load',prompt:'Anong bagay ang palagi mong kailangang tandaan, planuhin, o i-anticipate na hindi ko masyadong nakikita?',follow:'Ano ang isang part ng planning na puwede kong akuin from start to finish—not just “help” when asked?',practice:'Transfer ownership of one recurring planning task completely for one week.',ref:'Philippians 2:3–4',code:'PHP',chapter:2},
  {id:'c52',cat:'stewardship',title:'What makes us feel secure?',prompt:'Ano ang pinaka-nagbibigay sa iyo ng sense of security ngayon: savings, stable routine, emergency plan, less debt, more time, family support, faith, o iba?',follow:'May difference ba sa definition natin ng “secure” na kailangan nating i-respect?',practice:'Choose one small security-building action you both agree on.',ref:'1 Timothy 6:17–19',code:'1TI',chapter:6},
  {id:'c53',cat:'intimacy',title:'Safe enough to be soft',prompt:'Ano ang ginagawa ko na nagpaparamdam sa iyo na safe maging vulnerable, affectionate, o emotionally soft sa akin?',follow:'Ano ang maliit na bagay na nakakawala ng safety kahit hindi intentional?',practice:'Repeat one safety-building behavior your spouse names this week.',ref:'Ephesians 4:31–32',code:'EPH',chapter:4},
  {id:'c54',cat:'intimacy',title:'Affection menu',prompt:'Anong forms of affection ang pinaka-natural at welcome sa iyo ngayon—words, touch, time, practical help, humor, prayer, or something else?',follow:'May form of affection ba na gusto mong mas itanong ko kaysa i-assume?',practice:'Each choose one welcome form of affection for this week; consent and comfort come first.',ref:'1 Corinthians 13:4–5',code:'1CO',chapter:13},
  {id:'c55',cat:'intimacy',title:'Attention feels like love',prompt:'Kailan mo pinaka-nararamdaman na nasa iyo talaga ang attention ko—not just physically present?',follow:'Ano ang pinakamadalas na distraction na nagpuputol ng connection natin?',practice:'Create one phone-down 20-minute window this week with no logistics talk for the first 10 minutes.',ref:'Philippians 2:3–4',code:'PHP',chapter:2},
  {id:'c56',cat:'intimacy',title:'Coming back after distance',prompt:'Kapag emotionally distant tayo for a few days, ano ang pinakamagandang first step para makabalik ang closeness without forcing it?',follow:'Ano ang approach na nagiging pressure o lalo kang lumalayo?',practice:'Use one low-pressure reconnect invitation: walk, tea, prayer, hug, or ten-minute talk—your spouse may choose.',ref:'Colossians 3:12–14',code:'COL',chapter:3},
  {id:'c57',cat:'family',title:'Parenting triggers us too',prompt:'Anong behavior ng anak/family situation ang mabilis mag-trigger sa atin, at ano ang pinanggagalingan ng reaction natin?',follow:'Paano tayo pwedeng mag-support sa isa’t isa bago tayo maubusan ng patience?',practice:'Agree on one handoff signal when one parent is nearing overload.',ref:'James 1:19–20',code:'JAS',chapter:1},
  {id:'c58',cat:'family',title:'What should our children remember?',prompt:'Kung aalalahanin ng mga anak/family natin ang atmosphere ng home natin years from now, ano ang gusto nating maalala nila?',follow:'Anong ordinary weekly habit ang puwedeng gumawa ng memory na iyon?',practice:'Start one simple repeatable family ritual this week.',ref:'Psalm 78:4–7',code:'PSA',chapter:78},
  {id:'c59',cat:'family',title:'Protect the couple inside the family',prompt:'Sa dami ng parenting at family responsibilities, saan nawawala ang “us” bilang couple?',follow:'Ano ang minimum connection habit na gusto nating protektahan kahit busy?',practice:'Choose one 10–20 minute couple ritual that survives busy weeks.',ref:'Genesis 2:23–24',code:'GEN',chapter:2},
  {id:'c60',cat:'family',title:'Correct privately, support publicly',prompt:'Kapag hindi tayo aligned sa parenting decision, paano natin gustong i-handle iyon para hindi tayo nag-uundermine sa harap ng bata?',follow:'Anong issues ang kailangan nating i-save for private discussion?',practice:'Use one phrase this week: “Pag-uusapan muna namin ito, then babalikan ka namin.”',ref:'Philippians 2:2–4',code:'PHP',chapter:2},
  {id:'c61',cat:'mission',title:'Five years from now',prompt:'Kung healthy at faithful ang next five years natin, ano ang gusto mong mas marami sa life natin—and ano ang gusto mong mas kaunti?',follow:'Anong one-year step ang connected sa vision na iyon?',practice:'Write two “more of” and two “less of” items, then choose one first step.',ref:'Proverbs 16:9',code:'PRO',chapter:16},
  {id:'c62',cat:'mission',title:'Open our table',prompt:'Sino ang tao o family na gusto nating mas maging intentional i-welcome, encourage, o include sa life natin?',follow:'Ano ang hospitality na realistic sa energy at budget natin ngayon?',practice:'Invite or encourage one person together in a simple, sustainable way.',ref:'Romans 12:9–13',code:'ROM',chapter:12},
  {id:'c63',cat:'mission',title:'Different callings, same team',prompt:'May personal calling, growth goal, ministry, study, or career direction ba ang isa sa atin na kailangan ng mas malinaw na support from the other?',follow:'Paano natin susuportahan iyon without making the other spouse disappear or carry everything?',practice:'Name one concrete support and one boundary that keeps the partnership healthy.',ref:'Ecclesiastes 4:9–12',code:'ECC',chapter:4},
  {id:'c64',cat:'mission',title:'What legacy are we practicing now?',prompt:'Anong klaseng marriage story ang gusto nating makita ng family, church, at friends—not perfect, but faithful and real?',follow:'Anong habit natin ngayon ang already shaping that legacy for better or worse?',practice:'Choose one legacy habit to practice for the next month and review it together.',ref:'Matthew 5:14–16',code:'MAT',chapter:5}
].map(item=>Object.freeze(item)));

export const COUPLES_CHECK_ITEMS=Object.freeze([
  {id:'heard',label:'Naramdaman kong pinakinggan at inintindi ako.'},
  {id:'affection',label:'Naramdaman ko ang affection, warmth, at closeness natin.'},
  {id:'team',label:'Pakiramdam ko magkakampi tayo sa responsibilities at decisions.'},
  {id:'faith',label:'May meaningful space tayo para kay Christ, prayer, o Scripture.'},
  {id:'appreciation',label:'Naramdaman kong naa-appreciate ang effort ko.'},
  {id:'safety',label:'Safe akong magsabi ng concern nang hindi agad natatakot sa reaction.'}
].map(item=>Object.freeze(item)));

export const COUPLES_REPAIR_STEPS=Object.freeze([
  {label:'1 · PAUSE',title:'Name one issue only',prompt:'“Ang issue na gusto kong ayusin ay…” Keep it specific. No history dump.'},
  {label:'2 · IMPACT',title:'Describe impact without attack',prompt:'“Kapag nangyayari ang ___, nararamdaman ko ___, at ang kailangan kong maintindihan mo ay ___.”'},
  {label:'3 · MIRROR',title:'Prove understanding first',prompt:'Listener: “Ang narinig ko ay…” Speaker corrects gently until accurate.'},
  {label:'4 · OWN',title:'Own your part',prompt:'Each person names one thing they did, failed to do, or assumed—without adding a counterattack.'},
  {label:'5 · REPAIR',title:'Choose one next behavior',prompt:'Agree on one observable action, one boundary if needed, and when you will revisit the issue.'}
].map(item=>Object.freeze(item)));
