export const COUPLES_CATEGORIES=Object.freeze([
  {id:'christ',icon:'✝️',label:'Us & God'},
  {id:'communication',icon:'👂',label:'Listen & Understand'},
  {id:'conflict',icon:'🕊️',label:'Repair & Forgive'},
  {id:'gratitude',icon:'💛',label:'Friendship & Gratitude'},
  {id:'stewardship',icon:'🏠',label:'Money & Responsibilities'},
  {id:'intimacy',icon:'🤍',label:'Closeness & Affection'},
  {id:'family',icon:'🌱',label:'Parenting & Family'},
  {id:'mission',icon:'🧭',label:'Purpose & Future'}
].map(item=>Object.freeze(item)));

export const COUPLES_CARDS=Object.freeze([
  {id:'c01',cat:'christ',title:'Same direction?',prompt:'Sa season natin ngayon, saan mo pinaka-nararamdaman na hinihila tayo ni Christ na mag-grow bilang mag-asawa?',follow:'Ano ang isang maliit na spiritual habit na kaya nating gawin together nang realistic?',practice:'10 minutes this week: read, pray, then share one sentence each.',ref:'Colossians 3:12–14',code:'COL',chapter:3},
  {id:'c02',cat:'christ',title:'Faith without performance',prompt:'May part ba ng spiritual life natin na ginagawa natin dahil “dapat,” pero hindi na natin pinag-uusapan nang totoo?',follow:'Ano ang makakatulong para maging mas honest at less performative ang faith natin sa bahay?',practice:'Ask one honest faith question without trying to fix the answer.',ref:'Psalm 139:23–24',code:'PSA',chapter:139},
  {id:'c03',cat:'christ',title:'Pray for me like this',prompt:'Kung isang bagay lang ang ipagpe-pray mo para sa akin this month, ano iyon—and why?',follow:'Ano ang ayaw mong gawing “project” kita habang ipinagpe-pray kita?',practice:'Pray one specific, non-corrective prayer for your spouse.',ref:'Philippians 1:9–11',code:'PHP',chapter:1},
  {id:'c04',cat:'christ',title:'Grace at home',prompt:'Saan ako pinakamadaling bigyan ng grace ng ibang tao pero pinakamahirap bigyan ng grace sa bahay?',follow:'Paano natin mapaghihiwalay ang grace sa pag-iwas sa accountability?',practice:'Name one grace you received from your spouse this week.',ref:'Ephesians 4:2–3',code:'EPH',chapter:4},
  {id:'c05',cat:'communication',title:'Do you feel heard?',prompt:'Kailan mo huling naramdaman na talagang naintindihan kita—not just narinig?',follow:'Ano ang ginawa ko noon na gusto mong ulitin ko?',practice:'For one conversation, summarize before giving your opinion.',ref:'James 1:19',code:'JAS',chapter:1},
  {id:'c06',cat:'communication',title:'What I miss',prompt:'Anong signal mo kapag pagod, worried, o overwhelmed ka na madalas kong nami-miss?',follow:'Ano ang pinaka-helpful kong response kapag nakikita ko ang signal na iyon?',practice:'Agree on one simple phrase that means “I need support, not solutions.”',ref:'Proverbs 18:13',code:'PRO',chapter:18},
  {id:'c07',cat:'communication',title:'Advice or presence?',prompt:'Kapag may problema ka, paano ko malalaman kung gusto mo ng advice, tulong, prayer, o simpleng kasama lang?',follow:'May example ba recently na maling mode ang ginamit ko?',practice:'Ask: “Makikinig lang ba ako, tutulong, or mag-iisip tayo ng solution?”',ref:'Romans 12:15',code:'ROM',chapter:12},
  {id:'c08',cat:'communication',title:'Hard truth, gentle delivery',prompt:'Ano ang isang concern na gusto mong mas safe sabihin sa akin nang hindi ako agad defensive?',follow:'Anong wording o timing ang makakatulong para marinig ko ito nang maayos?',practice:'Use one specific observation, not “always” or “never.”',ref:'Ephesians 4:15',code:'EPH',chapter:4},
  {id:'c09',cat:'conflict',title:'The real issue',prompt:'Kapag paulit-ulit ang argument natin, ano sa tingin mo ang deeper need sa ilalim ng topic?',follow:'Ano ang fear o assumption na baka hindi natin nasasabi?',practice:'Name the issue in one sentence without blame.',ref:'Proverbs 15:1',code:'PRO',chapter:15},
  {id:'c10',cat:'conflict',title:'My part',prompt:'Sa isang recent conflict, ano ang part ko na kaya kong akuin kahit may part ka rin?',follow:'Ano ang sincere repair na mas meaningful kaysa simpleng “sorry”?',practice:'Own one specific action without adding “pero ikaw kasi…”.',ref:'Matthew 7:3–5',code:'MAT',chapter:7},
  {id:'c11',cat:'conflict',title:'Forgiveness and trust',prompt:'May bagay ba na napatawad na natin in principle pero kailangan pa rin ng rebuilding ng trust?',follow:'Anong consistent action—not promise—ang makakatulong?',practice:'Choose one observable trust-building behavior for 7 days.',ref:'Colossians 3:13',code:'COL',chapter:3},
  {id:'c12',cat:'conflict',title:'When to pause',prompt:'Ano ang signs na hindi na productive ang usapan natin at kailangan muna nating huminto?',follow:'Paano tayo magpa-pause nang hindi mukhang abandonment o silent treatment?',practice:'Agree on a pause phrase and a concrete return time.',ref:'Proverbs 17:14',code:'PRO',chapter:17},
  {id:'c13',cat:'gratitude',title:'I noticed this',prompt:'Anong effort ko recently ang napansin mo pero baka hindi mo pa nasasabi?',follow:'Bakit meaningful iyon sa iyo?',practice:'Give one specific appreciation today—behavior, impact, gratitude.',ref:'1 Thessalonians 5:11',code:'1TH',chapter:5},
  {id:'c14',cat:'gratitude',title:'Still my friend',prompt:'Ano ang bagay na nami-miss mong gawin natin as friends—not just as spouses/parents/workers?',follow:'Ano ang cheapest, simplest version na puwede nating gawin this month?',practice:'Schedule one low-pressure shared activity.',ref:'Ecclesiastes 4:9–10',code:'ECC',chapter:4},
  {id:'c15',cat:'gratitude',title:'What I admire now',prompt:'Ano ang quality ko na mas naa-appreciate mo ngayon kaysa noong bago pa tayo?',follow:'Saan mo nakikita na nag-grow ako?',practice:'Say one admiration without joking it away.',ref:'Philippians 4:8',code:'PHP',chapter:4},
  {id:'c16',cat:'gratitude',title:'Best small memory',prompt:'Anong maliit at ordinaryong memory natin ang unexpectedly precious sa iyo?',follow:'Ano ang sinasabi nito tungkol sa klase ng life na gusto nating buuin?',practice:'Recreate one simple thing you both enjoyed before.',ref:'Psalm 90:12',code:'PSA',chapter:90},
  {id:'c17',cat:'stewardship',title:'Money means what?',prompt:'Kapag pinag-uusapan natin ang money, ano ang pinaka-malakas na emotion mo: security, freedom, fear, responsibility, generosity, status, o iba?',follow:'Saan kaya galing ang meaning na iyon sa family history mo?',practice:'Discuss one money decision by values first, numbers second.',ref:'Luke 14:28',code:'LUK',chapter:14},
  {id:'c18',cat:'stewardship',title:'Invisible work',prompt:'Anong responsibility sa bahay/family ang tingin mo hindi masyadong nakikita o naa-appreciate?',follow:'May task ba na kailangang i-redistribute, simplify, or stop?',practice:'Transfer or simplify one recurring burden this week.',ref:'Galatians 6:2',code:'GAL',chapter:6},
  {id:'c19',cat:'stewardship',title:'Enough',prompt:'Ano ang ibig sabihin ng “enough” para sa family natin—money, house, possessions, work hours?',follow:'Ano ang ayaw nating isakripisyo para lang kumita o umangat?',practice:'Write one family boundary around work, spending, or time.',ref:'1 Timothy 6:6–8',code:'1TI',chapter:6},
  {id:'c20',cat:'stewardship',title:'Generosity together',prompt:'Saan tayo gustong maging generous bilang couple—family, church, neighbors, strangers, time, skills?',follow:'Paano tayo magiging generous nang hindi irresponsible sa sariling household?',practice:'Choose one planned act of generosity together.',ref:'2 Corinthians 9:7',code:'2CO',chapter:9},
  {id:'c21',cat:'intimacy',title:'Loved in ordinary days',prompt:'Anong ordinary action ang pinaka-nagpaparamdam sa iyo na loved ka?',follow:'Ano ang ginagawa kong sincere pero hindi ganoon ka-meaningful sa iyo?',practice:'Do one small affection your spouse actually values.',ref:'1 Corinthians 13:4–7',code:'1CO',chapter:13},
  {id:'c22',cat:'intimacy',title:'Closeness needs safety',prompt:'Ano ang nagpapadali para maging emotionally open at affectionate ka sa akin?',follow:'Ano ang behavior na mabilis magsara ng loob mo?',practice:'Create one distraction-free 15-minute connection window.',ref:'1 Peter 3:7',code:'1PE',chapter:3},
  {id:'c23',cat:'intimacy',title:'Ask, don’t assume',prompt:'May need ba sa closeness, affection, rest, or attention na ina-assume nating obvious pero hindi pala napag-uusapan?',follow:'Paano natin ito mapag-uusapan nang walang pressure o entitlement?',practice:'Ask clearly for one form of connection and accept an honest answer.',ref:'Philippians 2:3–4',code:'PHP',chapter:2},
  {id:'c24',cat:'intimacy',title:'Protect our us-time',prompt:'Ano ang pinakamalaking kumakain ng couple connection natin ngayon?',follow:'Ano ang realistic protection—not ideal fantasy—na kaya nating gawin?',practice:'Protect one small recurring couple window this week.',ref:'Genesis 2:24',code:'GEN',chapter:2},
  {id:'c25',cat:'family',title:'What are we teaching?',prompt:'Anong value ang gusto nating makita ng mga anak/family sa paraan ng pakikitungo natin sa isa’t isa?',follow:'Ano ang nakikita nila ngayon na gusto nating baguhin?',practice:'Model one respectful repair in front of family when appropriate.',ref:'Deuteronomy 6:6–7',code:'DEU',chapter:6},
  {id:'c26',cat:'family',title:'Same team parenting',prompt:'Saan tayo pinaka-aligned sa parenting at saan tayo madalas magkaiba?',follow:'Ano ang rule o principle na kailangan nating pag-usapan privately bago harapin ang bata?',practice:'Agree on one consistent parenting response.',ref:'Ephesians 6:4',code:'EPH',chapter:6},
  {id:'c27',cat:'family',title:'Family pressure',prompt:'May pressure ba mula sa extended family, culture, church, or expectations na nakakaapekto sa marriage natin?',follow:'Anong boundary ang dapat nating hawakan together?',practice:'Use “we decided” rather than leaving one spouse alone to defend the boundary.',ref:'Genesis 2:24',code:'GEN',chapter:2},
  {id:'c28',cat:'family',title:'Home atmosphere',prompt:'Kung may isang word na gusto nating maramdaman sa bahay—peaceful, joyful, safe, disciplined, welcoming—ano iyon?',follow:'Anong habit ang pinaka-supportive at ano ang pinaka-sumasabotahe dito?',practice:'Pick one home atmosphere habit for seven days.',ref:'Colossians 3:15',code:'COL',chapter:3},
  {id:'c29',cat:'mission',title:'What are we building?',prompt:'Kung titingnan natin ang marriage natin 10 years from now, anong klaseng couple ang gusto nating maging—not just anong meron tayo?',follow:'Anong trait ang kailangan nating simulan ngayon?',practice:'Write one sentence describing the couple you want to become.',ref:'Joshua 24:15',code:'JOS',chapter:24},
  {id:'c30',cat:'mission',title:'Serve together',prompt:'Anong need sa paligid natin ang pareho nating napapansin at may realistic tayong maitutulong?',follow:'Paano ito magiging shared mission at hindi dagdag na burden sa isang spouse?',practice:'Choose one small act of service you can do together.',ref:'Galatians 5:13',code:'GAL',chapter:5},
  {id:'c31',cat:'mission',title:'Dream without pressure',prompt:'Anong dream mo na gusto mong marinig ko nang hindi ko agad kino-correct, kino-cost, o kino-convert into plan?',follow:'Ano ang part ng dream na pinaka-importanteng maintindihan ko?',practice:'Give your spouse five uninterrupted minutes to describe a dream.',ref:'Proverbs 16:3',code:'PRO',chapter:16},
  {id:'c32',cat:'mission',title:'Next faithful step',prompt:'Sa biggest decision natin ngayon, ano ang alam na nating tamang next step kahit hindi pa malinaw ang buong future?',follow:'Ano ang fear na nagpapa-delay sa atin?',practice:'Choose one reversible next step and a date to revisit it.',ref:'James 1:5',code:'JAS',chapter:1}
].map(item=>Object.freeze(item)));

export const COUPLES_CHECK_ITEMS=Object.freeze([
  {id:'heard',label:'Naramdaman kong pinakinggan at inintindi ako.'},
  {id:'affection',label:'Naramdaman ko ang affection, warmth, at closeness natin.'},
  {id:'team',label:'Pakiramdam ko magkakampi tayo sa responsibilities at decisions.'},
  {id:'faith',label:'May meaningful space tayo para kay Christ, prayer, o Scripture.'},
  {id:'appreciation',label:'Naramdaman kong naa-appreciate ang effort ko.'},
  {id:'safety',label:'Safe akong magsabi ng concern nang hindi agad natatakot sa reaction.'}
].map(item=>Object.freeze(item)));

export const COUPLES_REPAIR_STEPS=Object.freeze([
  {label:'1 · PAUSE',title:'Name one issue only',prompt:'“Ang issue na gusto kong ayusin ay…” Keep it specific. No history dump.'},
  {label:'2 · IMPACT',title:'Describe impact without attack',prompt:'“Kapag nangyayari ang ___, nararamdaman ko ___, at ang kailangan kong maintindihan mo ay ___.”'},
  {label:'3 · MIRROR',title:'Prove understanding first',prompt:'Listener: “Ang narinig ko ay…” Speaker corrects gently until accurate.'},
  {label:'4 · OWN',title:'Own your part',prompt:'Each person names one thing they did, failed to do, or assumed—without adding a counterattack.'},
  {label:'5 · REPAIR',title:'Choose one next behavior',prompt:'Agree on one observable action, one boundary if needed, and when you will revisit the issue.'}
].map(item=>Object.freeze(item)));
