const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

export function openReviewPage({review,onLearn}){
  const initial=review.overview();
  return{
    title:'Open Smart Review',
    html:`<section class="bq-panel bq-open-review" data-open-review-view><p class="bq-eyebrow">OPEN BIBLE LIBRARY</p><h1>Open Smart Review</h1><p>Answer from memory, reveal the source answer, then rate your own recall. Due and weak-area questions return sooner; remembered items are spaced farther apart.</p><div class="bq-open-review-metrics"><div><b>${initial.due}</b><span>Due now</span></div><div><b>${initial.accuracy}%</b><span>Open recall accuracy</span></div><div><b>${esc(initial.weakest||'Baseline')}</b><span>Weak-area focus</span></div></div><div class="bq-open-review-actions">${initial.hasActive?'<button type="button" class="bq-primary-button" data-open-review-resume>Resume review</button>':'<button type="button" class="bq-primary-button" data-open-review-start>Start 7-question review</button>'}<button type="button" class="bq-secondary-button" data-open-review-learn>Back to Learn</button></div></section>`,
    mount(root){
      const view=root.querySelector('[data-open-review-view]');let busy=false,current=null;
      const progressNumber=state=>Math.min(7,Math.floor((state?.index||0)/2)+1);
      const renderLauncher=(message='')=>{const o=review.overview();view.innerHTML=`<p class="bq-eyebrow">OPEN BIBLE LIBRARY</p><h1>Open Smart Review</h1><p>Answer from memory, reveal the source answer, then rate your own recall. Due and weak-area questions return sooner; remembered items are spaced farther apart.</p>${message?`<p class="bq-open-review-error" role="alert">${esc(message)}</p>`:''}<div class="bq-open-review-metrics"><div><b>${o.due}</b><span>Due now</span></div><div><b>${o.accuracy}%</b><span>Open recall accuracy</span></div><div><b>${esc(o.weakest||'Baseline')}</b><span>Weak-area focus</span></div></div><div class="bq-open-review-actions">${o.hasActive?'<button type="button" class="bq-primary-button" data-open-review-resume>Resume review</button>':'<button type="button" class="bq-primary-button" data-open-review-start>Start 7-question review</button>'}<button type="button" class="bq-secondary-button" data-open-review-learn>Back to Learn</button></div>`;bind()};
      const render=snapshot=>{current=snapshot;if(snapshot.phase==='complete'){const s=snapshot.summary,o=snapshot.overview;view.innerHTML=`<p class="bq-eyebrow">OPEN REVIEW COMPLETE</p><h1>${s.got}/${s.total} remembered</h1><p>${s.again?`${s.again} item${s.again===1?'':'s'} will return sooner.`:'Everything was recalled. These items will return later instead of being drilled immediately.'}</p><div class="bq-open-review-metrics"><div><b>+${s.gained}</b><span>XP</span></div><div><b>${o.accuracy}%</b><span>Open recall accuracy</span></div><div><b>${o.due}</b><span>Due now</span></div></div><div class="bq-open-review-actions"><button type="button" class="bq-primary-button" data-open-review-another>Start another review</button><button type="button" class="bq-secondary-button" data-open-review-learn>Back to Learn</button></div>`;bind();return}
        const item=snapshot.item,number=progressNumber(snapshot.state),percent=Math.round(((number-1)/7)*100);if(snapshot.phase==='question'){view.innerHTML=`<div class="bq-open-review-head"><button type="button" class="bq-secondary-button" data-open-review-learn>← Learn</button><span>Open Smart Review</span><b>${number}/7</b></div><div class="bq-open-review-progress"><i style="width:${percent}%"></i></div><p class="bq-eyebrow">${esc(snapshot.kind)} · ${esc(item.book)}</p><h1>${esc(item.question)}</h1><p>Answer from memory first. Then reveal the source answer.</p><button type="button" class="bq-primary-button" data-open-review-reveal>Reveal answer</button><p class="bq-open-review-license">${esc(item.source)} · ${esc(item.license)}</p>`}else{view.innerHTML=`<div class="bq-open-review-head"><button type="button" class="bq-secondary-button" data-open-review-learn>← Learn</button><span>Open Smart Review</span><b>${number}/7</b></div><div class="bq-open-review-progress"><i style="width:${percent}%"></i></div><p class="bq-eyebrow">REFERENCE ANSWER · ${esc(item.book)}</p><h1>${esc(item.question)}</h1><div class="bq-open-review-answer"><p>${esc(item.answer)}</p>${item.reference?`<b>📖 ${esc(item.reference)}</b>`:''}</div><p>Rate your recall, not whether your wording matched exactly.</p><div class="bq-open-review-actions"><button type="button" class="bq-secondary-button" data-open-review-again>Review again</button><button type="button" class="bq-primary-button" data-open-review-got>Got it</button></div><p class="bq-open-review-license">${esc(item.source)} · ${esc(item.license)}</p>`}bind()};
      const run=async task=>{if(busy)return;busy=true;try{render(await task())}catch(error){renderLauncher(error?.message||'Open Review is unavailable.')}finally{busy=false}};
      function bind(){
        view.querySelector('[data-open-review-start]')?.addEventListener('click',()=>run(()=>review.start()),{once:true});
        view.querySelector('[data-open-review-resume]')?.addEventListener('click',()=>run(()=>review.resume()),{once:true});
        view.querySelector('[data-open-review-another]')?.addEventListener('click',()=>run(()=>review.another()),{once:true});
        view.querySelector('[data-open-review-reveal]')?.addEventListener('click',()=>{try{render(review.reveal())}catch(error){renderLauncher(error?.message||'Could not reveal this answer.')}},{once:true});
        view.querySelector('[data-open-review-again]')?.addEventListener('click',()=>{try{render(review.rate('again'))}catch(error){renderLauncher(error?.message||'Could not save this rating.')}},{once:true});
        view.querySelector('[data-open-review-got]')?.addEventListener('click',()=>{try{render(review.rate('got'))}catch(error){renderLauncher(error?.message||'Could not save this rating.')}},{once:true});
        view.querySelectorAll('[data-open-review-learn]').forEach(button=>button.addEventListener('click',()=>onLearn?.(),{once:true}));
      }
      bind();return()=>{review.close();current=null};
    }
  }
}
