import { getContentProvenance } from '../../core/content-provenance.js';
import { DOCTRINAL_SAFETY } from '../../core/doctrinal-safety.js';
import { sourceGuide } from '../../ui/source-labels.js';

export function learnPage({ onReader, onStudy, onDeepQuestions, onStoryJourney, onWisdomSituations, onAdaptiveLearning, onOpenReview, onBibleWorld, onPrivateNotes, onCloudNotes, translations = [], recallSource = null }) {
  const guide = sourceGuide({
    translations,
    recall: recallSource,
    custom: [getContentProvenance('bq-study'), getContentProvenance('bq-retelling'), getContentProvenance('bq-wisdom'), getContentProvenance('bq-recall'), getContentProvenance('bq-game')]
  });
  return {
    title: 'Learn',
    html: `<section class="bq-panel"><p class="bq-eyebrow">LEARN</p><h1>Learn</h1><p>Read Scripture directly, follow a guided study, examine a deep question, walk through a Bible story, practice difficult Scripture-informed judgment, explore the biblical story map, review weak areas with spaced retrieval, or keep notes locally or with your signed-in account.</p><div class="bq-learning-grid"><button type="button" class="bq-learning-card" data-open-reader><b>Bible Reader</b><span>English BSB + Tagalog ULB · search · verse tools</span></button><button type="button" class="bq-learning-card" data-open-study><b>Guided Study</b><span>Passage · context · observation · reflection · application</span></button><button type="button" class="bq-learning-card" data-open-deep-questions><b>Deep Questions</b><span>Question · Scripture · open reflection · private note</span></button><button type="button" class="bq-learning-card" data-open-story-journey><b>Story Journey</b><span>Five Bible scenes · Scripture checkpoint · replay</span></button><button type="button" class="bq-learning-card" data-open-wisdom-situations><b>Wisdom Situations</b><span>Complex scenario · strongest judgment · rationale · Scripture</span></button><button type="button" class="bq-learning-card" data-open-bible-world><b>Bible World</b><span>Nine story regions · exploration evidence · Scripture routes</span></button><button type="button" class="bq-learning-card" data-open-adaptive-learning><b>Adaptive Learning</b><span>Due multiple-choice questions · weak areas · spaced Smart Review</span></button><button type="button" class="bq-learning-card" data-open-open-review><b>Open Smart Review</b><span>Answer from memory · reveal source answer · Got it / Review again</span></button><button type="button" class="bq-learning-card" data-open-private-notes><b>Private Notes</b><span>Device-only · create · edit · delete · export</span></button><button type="button" class="bq-learning-card" data-open-cloud-notes><b>Cloud Notes</b><span>Account-based · Scripture-linked · cross-device</span></button></div></section><section class="bq-panel" data-doctrinal-policy><p class="bq-eyebrow">CONTENT SAFETY</p><h2>How scored Bible questions are handled</h2><p>Binary-scored questions must stay tied to an explicit Scripture reference and pass doctrinal-safety review. A disputed or universal doctrine claim is quarantined instead of being guessed into a right/wrong answer. Passage-sensitive material stays contextual, while Deep Questions and Wisdom remain interpretive or applied exercises rather than spiritual-quality scores.</p><p><small>${DOCTRINAL_SAFETY.authority}</small></p></section>${guide}`,
    mount(root) {
      const reader = root.querySelector('[data-open-reader]'), study = root.querySelector('[data-open-study]'), deep = root.querySelector('[data-open-deep-questions]'), story = root.querySelector('[data-open-story-journey]'), wisdom = root.querySelector('[data-open-wisdom-situations]'), bibleWorld = root.querySelector('[data-open-bible-world]'), adaptive = root.querySelector('[data-open-adaptive-learning]'), openReview = root.querySelector('[data-open-open-review]'), privateNotes = root.querySelector('[data-open-private-notes]'), cloudNotes = root.querySelector('[data-open-cloud-notes]');
      const goReader = () => onReader?.(), goStudy = () => onStudy?.(), goDeep = () => onDeepQuestions?.(), goStory = () => onStoryJourney?.(), goWisdom = () => onWisdomSituations?.(), goBibleWorld = () => onBibleWorld?.(), goAdaptive = () => onAdaptiveLearning?.(), goOpenReview = () => onOpenReview?.(), goPrivateNotes = () => onPrivateNotes?.(), goCloudNotes = () => onCloudNotes?.();
      reader?.addEventListener('click', goReader); study?.addEventListener('click', goStudy); deep?.addEventListener('click', goDeep); story?.addEventListener('click', goStory); wisdom?.addEventListener('click', goWisdom); bibleWorld?.addEventListener('click', goBibleWorld); adaptive?.addEventListener('click', goAdaptive); openReview?.addEventListener('click', goOpenReview); privateNotes?.addEventListener('click', goPrivateNotes); cloudNotes?.addEventListener('click', goCloudNotes);
      return () => { reader?.removeEventListener('click', goReader); study?.removeEventListener('click', goStudy); deep?.removeEventListener('click', goDeep); story?.removeEventListener('click', goStory); wisdom?.removeEventListener('click', goWisdom); bibleWorld?.removeEventListener('click', goBibleWorld); adaptive?.removeEventListener('click', goAdaptive); openReview?.removeEventListener('click', goOpenReview); privateNotes?.removeEventListener('click', goPrivateNotes); cloudNotes?.removeEventListener('click', goCloudNotes); };
    }
  };
}