export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

export function renderLauncher(state,{games}){
  if(state.phase!=='launcher')return null;
  const memory=games.kidsMemory.mode;
  return `<section class="bq-panel bq-games-head"><p class="bq-eyebrow">PLAY</p><h1>Bible games for every kind of practice</h1><p>Choose a game to review Scripture, strengthen recall, or play together. Your progress stays consistent across supported modes.</p></section><section class="bq-game-launcher" aria-label="BibleQuest games">${games.modes.map(mode=>{const last=mode.id==='per-book-recall'?null:games.lastResult(mode.id);return `<article class="bq-panel bq-game-card"><span>${escapeHtml(mode.kicker)}</span><h2>${escapeHtml(mode.title)}</h2><p>${escapeHtml(mode.description)}</p>${last?`<p class="bq-game-score" data-game-last="${escapeHtml(mode.id)}">Last result: <b>${last.score}/${last.total}</b> · +${last.gained} XP</p>`:''}<button type="button" class="bq-primary-button" data-game-launch="${escapeHtml(mode.id)}">${mode.id==='per-book-recall'?'Open recall library':`Play ${escapeHtml(mode.title)}`}</button></article>`}).join('')}<article class="bq-panel bq-game-card" data-memory-launch-card><span>${escapeHtml(memory.kicker)}</span><h2>${escapeHtml(memory.title)}</h2><p>${escapeHtml(memory.description)}</p><button type="button" class="bq-primary-button" data-memory-open>Play ${escapeHtml(memory.title)}</button></article><article class="bq-panel bq-game-card" data-same-room-card><span>PASS-AND-PLAY</span><h2>Play Together</h2><p>Share one device with 2–6 players, rotate turns, and keep a local scoreboard.</p><button type="button" class="bq-primary-button" data-same-room-open>Play Together</button></article></section><div class="bq-game-footer"><button type="button" class="bq-secondary-button" data-game-home>Back home</button></div>`;
}

export function renderMemory(state){
  if(state.phase==='memory')return `<section class="bq-game-topline"><button type="button" class="bq-secondary-button" data-game-launcher>All games</button><div class="bq-game-score" data-memory-moves>Moves <b>${state.moves}</b></div></section><section class="bq-panel bq-memory-meadow" data-memory-meadow><p class="bq-eyebrow">KIDS · MEMORY</p><div class="bq-memory-mark" aria-hidden="true">🦊</div><h1>Memory Meadow</h1><p>Find all ${state.pairs} pairs. Pick two cards at a time.</p><div class="bq-memory-grid" data-memory-grid style="--memory-columns:${state.columns}" aria-label="Memory Meadow cards">${state.cards.map((card,index)=>{const face=card.open||card.done,className=card.done?' is-matched':card.open?' is-open':'';return `<button type="button" class="bq-memory-card${className}" data-memory-index="${index}" aria-label="${face?`Card ${index+1}: ${escapeHtml(card.icon)}${card.done?', matched':''}`:`Card ${index+1}: hidden`}" ${state.locked||card.open||card.done?'disabled':''}><span aria-hidden="true">${face?escapeHtml(card.icon):'?'}</span></button>`}).join('')}</div><p class="bq-memory-status" aria-live="polite">${state.locked?'Checking this pair…':'Choose a card.'}</p></section>`;
  if(state.phase==='memory-complete')return `<section class="bq-panel bq-game-result" data-memory-complete><p class="bq-eyebrow">MEMORY MEADOW COMPLETE</p><div class="bq-game-medal" aria-hidden="true">🦊</div><h1>All friends matched!</h1><p>You matched every pair in ${state.moves} moves.</p><div class="bq-game-stats"><div><b>${state.stars} ⭐</b><span>stars earned</span></div><div><b>${state.coins} 🪙</b><span>coins earned</span></div><div><b>0</b><span>XP — not awarded</span></div></div><p class="bq-memory-wallet">Total: ${state.totalStars} ⭐ · ${state.totalCoins} 🪙</p><div class="bq-game-actions"><button type="button" class="bq-primary-button" data-memory-replay>Play again</button><button type="button" class="bq-secondary-button" data-game-launcher>Choose another game</button><button type="button" class="bq-secondary-button" data-game-home>Back home</button></div></section>`;
  return null;
}

export function renderSameRoom(state,{gameSource}){
  if(state.phase==='same-room-setup')return `<section class="bq-panel bq-games-head" data-same-room-setup><p class="bq-eyebrow">PLAY TOGETHER</p><h1>How many players?</h1><p>Pass this device after each question. Scores stay local to this session and do not award profile XP.</p><div class="bq-game-actions">${[2,3,4,5,6].map(count=>`<button type="button" class="bq-primary-button" data-same-room-start="${count}">${count} players</button>`).join('')}</div><button type="button" class="bq-secondary-button" data-game-launcher>All games</button></section>`;
  if(state.phase==='same-room-question'){const q=state.question,progressPct=Math.round((state.index/Math.max(1,state.total))*100);return `<section class="bq-game-topline"><button type="button" class="bq-secondary-button" data-game-launcher>All games</button><div class="bq-game-score" data-same-room-turn>Turn: <b>${escapeHtml(state.currentPlayer.name)}</b></div></section><section class="bq-panel bq-question-card" data-same-room-question="${escapeHtml(q.id)}"><p class="bq-eyebrow">PLAY TOGETHER · QUESTION ${state.index+1} OF ${state.total}</p><div class="bq-game-progress" aria-hidden="true"><i style="width:${progressPct}%"></i></div><div class="bq-game-stats" data-same-room-scoreboard>${state.players.map(player=>`<div data-same-room-player="${escapeHtml(player.id)}"><b>${player.score}</b><span>${escapeHtml(player.name)}${player.active?' · turn':''}</span></div>`).join('')}</div><h1>${escapeHtml(q.q)}</h1><div class="bq-game-choices">${q.choices.map((choice,index)=>{const isCorrect=state.locked&&index===q.answer,isWrong=state.locked&&index===state.selected&&!state.correct,className=isCorrect?' is-correct':isWrong?' is-wrong':'';return `<button type="button" class="bq-game-choice${className}" data-same-room-answer="${index}" ${state.locked?'disabled':''}><span aria-hidden="true">${String.fromCharCode(65+index)}</span><b>${escapeHtml(choice)}</b></button>`}).join('')}</div>${state.locked?`<div class="bq-game-explanation" data-same-room-feedback><strong>${state.correct?'Correct':'Review this one'}</strong><p>${escapeHtml(q.why)}</p><span>📖 ${escapeHtml(q.ref)}</span></div><button type="button" class="bq-primary-button" data-same-room-next>${state.index+1===state.total?'See final scoreboard':'Pass to next player'}</button>`:''}<div class="bq-game-footer"><button type="button" class="bq-secondary-button" data-same-room-finish>Finish game</button></div>${gameSource}</section>`;}
  if(state.phase==='same-room-complete'){const top=Math.max(...state.players.map(player=>player.score)),winners=state.players.filter(player=>player.score===top).map(player=>player.name),result=winners.length===1?`Winner: ${winners[0]}`:`Tie: ${winners.join(' & ')}`;return `<section class="bq-panel bq-game-result" data-same-room-complete><p class="bq-eyebrow">PLAY TOGETHER COMPLETE</p><h1>${escapeHtml(result)}</h1><div class="bq-game-stats" data-same-room-scoreboard>${state.players.map(player=>`<div data-same-room-player="${escapeHtml(player.id)}"><b>${player.score}</b><span>${escapeHtml(player.name)}</span></div>`).join('')}</div><div class="bq-game-actions"><button type="button" class="bq-primary-button" data-same-room-open>Play again</button><button type="button" class="bq-secondary-button" data-game-launcher>All games</button></div></section>`;}
  return null;
}
