export function renderRecallLibraryView({state,games,escapeHtml}) {
  const books=games.visibleRecallBooks();
  return `<section class="bq-panel bq-games-head" data-recall-library><p class="bq-eyebrow">PER-BOOK RECALL</p><h1>Choose one Bible book</h1><p>Only the selected book pack is loaded. Reveal each reference answer, then mark it for review or remembered.</p><label class="bq-recall-search"><span>Search books</span><input type="search" maxlength="80" value="${escapeHtml(state.recallQuery)}" placeholder="Ruth, John, Romans…" data-recall-search></label></section><section class="bq-recall-books">${books.length?books.map(book=>{const summary=games.recallSummary(book.code);return `<button type="button" class="bq-panel bq-recall-book" data-recall-book="${escapeHtml(book.code)}"><span class="bq-recall-icon" aria-hidden="true"><img src="assets/v4/games/game-recall-deck.png" alt=""></span><span><b>${escapeHtml(book.name)}</b><small>${book.questions} questions · <span data-recall-summary="${escapeHtml(book.code)}">${summary.review} review${summary.seen?` · ${summary.seen} studied`:''}${summary.last?` · last ${summary.last.remembered}/${summary.last.total}`:''}</span></small></span><strong aria-hidden="true">›</strong></button>`}).join(''):'<section class="bq-panel"><h2>No matching books</h2><p>Try a different book name.</p></section>'}</section><section class="bq-panel bq-recall-source"><p><strong>Source:</strong> ${escapeHtml(state.source)} · ${escapeHtml(state.license)}. These are open study questions and reference answers; Scripture remains the primary text to examine.</p></section><div class="bq-game-footer"><button type="button" class="bq-secondary-button" data-game-launcher>All games</button></div>`;
}

export function renderRecallQuestionView({state,escapeHtml}) {
  const item=state.recallItem;
  const progressPct=Math.round((state.index/Math.max(1,state.total))*100);
  return `<section class="bq-game-topline"><button type="button" class="bq-secondary-button" data-recall-library>Recall library</button><div class="bq-game-score">Remembered <b>${state.remembered}</b> · +${state.gained} XP</div></section><section class="bq-panel bq-question-card" data-recall-question="${escapeHtml(item.id)}"><div class="bq-game-meta"><span>${escapeHtml(state.recallBook.name)} · Recall Deck</span><span data-recall-progress>Question ${state.index+1} of ${state.total}</span></div><div class="bq-game-progress" aria-hidden="true"><i style="width:${progressPct}%"></i></div><div class="bq-recall-mark" aria-hidden="true"><img src="assets/v4/games/game-recall-deck.png" alt=""></div><h1>${escapeHtml(item.question)}</h1>${state.revealed?`<div class="bq-recall-answer" data-recall-answer><small>REFERENCE ANSWER</small><p>${escapeHtml(item.answer)}</p>${item.reference?`<strong>📖 ${escapeHtml(state.recallBook.name)} ${escapeHtml(item.reference)}</strong>`:''}</div>${item.contextNote?`<aside class="bq-recall-context" data-recall-context><b>BibleQuest context</b><p>${escapeHtml(item.contextNote)}</p></aside>`:''}<div class="bq-recall-ratings"><button type="button" class="bq-secondary-button" data-recall-rate="again">Review again</button><button type="button" class="bq-primary-button" data-recall-rate="got">Got it</button></div>`:`<p class="bq-recall-think">Try to answer from memory before revealing the reference answer.</p><button type="button" class="bq-primary-button" data-recall-reveal>Reveal answer</button>`}<p class="bq-recall-license">${escapeHtml(state.source)} · ${escapeHtml(state.license)}</p></section>`;
}

export function renderRecallCompleteView({state,escapeHtml}) {
  return `<section class="bq-panel bq-game-result" data-recall-complete><p class="bq-eyebrow">${escapeHtml(state.recallBook.name)} DECK COMPLETE</p><div class="bq-game-medal" aria-hidden="true"><img src="assets/v4/games/game-recall-deck.png" alt=""></div><h1>${state.remembered}/${state.total}</h1><p>${state.reviewAgain?`${state.reviewAgain} item${state.reviewAgain===1?'':'s'} will return in a future ${escapeHtml(state.recallBook.name)} session.`:'Everything in this round was marked remembered.'}</p><div class="bq-game-stats"><div><b>+${state.gained}</b><span>XP</span></div><div><b>${state.remembered}</b><span>got it</span></div><div><b>${state.remainingReview}</b><span>book review</span></div></div><div class="bq-game-actions"><button type="button" class="bq-primary-button" data-recall-replay>Study ${escapeHtml(state.recallBook.name)} again</button><button type="button" class="bq-secondary-button" data-recall-library>Choose another book</button><button type="button" class="bq-secondary-button" data-game-launcher>All games</button></div></section>`;
}
