export function renderSoloCompleteView({state,escapeHtml,resultView}) {
  const pct=resultView.accuracyPercent;
  const message=pct>=90?'Excellent recall. Keep connecting the details to the bigger story.':pct>=70?'Good round. Review the explanations and keep strengthening the weak spots.':'Useful round. The misses point to what to review next.';
  return `<section class="bq-panel bq-game-result" data-game-complete data-v6-game-presentation="result"><p class="bq-eyebrow">ROUND COMPLETE</p><div class="bq-game-medal" aria-hidden="true"><img src="assets/v4/games/game-winner-trophy.png" alt=""></div><h1>${escapeHtml(resultView.scoreLabel)}</h1><p>${escapeHtml(message)}</p><div class="bq-game-stats"><div><b>${pct}%</b><span>accuracy</span></div><div><b>${escapeHtml(resultView.xpLabel)}</b><span>earned</span></div><div><b>${escapeHtml(state.modeTitle)}</b><span>mode</span></div></div><div class="bq-game-actions"><button type="button" class="bq-primary-button" data-game-replay>Play again</button><button type="button" class="bq-secondary-button" data-game-launcher>Choose another game</button><button type="button" class="bq-secondary-button" data-game-home>Back home</button></div></section>`;
}

export function renderSoloQuestionView({state,escapeHtml,presentation,recallSource}) {
  const q=state.question,view=presentation.question,feedback=presentation.feedback;
  const typeLabel=q.mode==='connection'?'Connections':q.level>=2?'Context':'Recall';
  return `<section class="bq-game-topline"><button type="button" class="bq-secondary-button" data-game-launcher>All games</button><div class="bq-game-score" data-game-score>Score <b>${state.score}</b> · +${state.gained} XP</div></section><section class="bq-panel bq-question-card" data-game-question="${escapeHtml(view.questionId)}" data-v6-game-presentation="question"><div class="bq-game-meta"><span>${escapeHtml(q.book)} · ${escapeHtml(typeLabel)}</span><span data-game-progress>${escapeHtml(view.progressLabel)}</span></div><div class="bq-game-progress" aria-hidden="true"><i style="width:${presentation.progressPercent}%"></i></div><h1>${escapeHtml(view.prompt)}</h1><div class="bq-game-choices">${view.choices.map(choice=>{const isCorrect=choice.correct===true,isWrong=state.locked&&choice.selected&&choice.correct===false,className=isCorrect?' is-correct':isWrong?' is-wrong':'';return `<button type="button" class="bq-game-choice${className}" data-game-answer="${choice.index}" aria-label="${escapeHtml(choice.accessibleLabel)}" ${state.locked?'disabled':''}><span aria-hidden="true">${escapeHtml(choice.marker)}</span><b>${escapeHtml(choice.text)}</b></button>`}).join('')}</div><div class="bq-game-feedback" aria-live="polite">${feedback?`<div class="bq-game-explanation" data-game-feedback><strong>${escapeHtml(feedback.heading)}</strong><p>${escapeHtml(feedback.explanation)}</p><span>📖 ${escapeHtml(feedback.reference)}</span><small>${q.mode==='basic'?'DIRECT / RECALL':'CONTEXT / CONNECTION'}</small></div><button type="button" class="bq-primary-button" data-game-next>${state.index+1===state.total?'See results':'Next question'}</button>`:''}</div>${recallSource}</section>`;
}
