create schema if not exists private;

create table if not exists public.bible_telemetry_visitors (
  visitor_id uuid primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  first_route text not null default 'home',
  last_route text not null default 'home',
  platform text not null default 'unknown',
  locale text not null default 'unknown',
  app_version text not null default 'v6',
  is_pwa boolean not null default false,
  screen_bucket text not null default 'unknown',
  first_user_id uuid references auth.users(id) on delete set null,
  last_user_id uuid references auth.users(id) on delete set null
);

create table if not exists public.bible_telemetry_sessions (
  session_id uuid primary key,
  visitor_id uuid not null references public.bible_telemetry_visitors(visitor_id) on delete cascade,
  started_user_id uuid references auth.users(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  ended_at timestamptz,
  authenticated_at timestamptz,
  entry_route text not null default 'home',
  last_route text not null default 'home',
  event_count integer not null default 0 check (event_count >= 0),
  platform text not null default 'unknown',
  locale text not null default 'unknown',
  app_version text not null default 'v6',
  is_pwa boolean not null default false,
  screen_bucket text not null default 'unknown'
);

create table if not exists public.bible_telemetry_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null references public.bible_telemetry_visitors(visitor_id) on delete cascade,
  session_id uuid not null references public.bible_telemetry_sessions(session_id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null check (char_length(event_name) between 1 and 64),
  feature text not null check (char_length(feature) between 1 and 80),
  route text not null check (char_length(route) between 1 and 80),
  properties jsonb not null default '{}'::jsonb check (octet_length(properties::text) <= 2000),
  occurred_at timestamptz not null default now()
);

create table if not exists private.bible_telemetry_rate_limits (
  rate_key text primary key,
  window_start timestamptz not null default now(),
  request_count integer not null default 1 check (request_count >= 0)
);

create index if not exists bible_telemetry_events_occurred_at_idx on public.bible_telemetry_events (occurred_at desc);
create index if not exists bible_telemetry_events_user_time_idx on public.bible_telemetry_events (user_id, occurred_at desc) where user_id is not null;
create index if not exists bible_telemetry_events_visitor_time_idx on public.bible_telemetry_events (visitor_id, occurred_at desc);
create index if not exists bible_telemetry_events_feature_time_idx on public.bible_telemetry_events (feature, event_name, occurred_at desc);
create index if not exists bible_telemetry_sessions_user_time_idx on public.bible_telemetry_sessions (user_id, started_at desc) where user_id is not null;
create index if not exists bible_telemetry_sessions_visitor_time_idx on public.bible_telemetry_sessions (visitor_id, started_at desc);

alter table public.bible_telemetry_visitors enable row level security;
alter table public.bible_telemetry_sessions enable row level security;
alter table public.bible_telemetry_events enable row level security;

revoke all on public.bible_telemetry_visitors from public, anon, authenticated;
revoke all on public.bible_telemetry_sessions from public, anon, authenticated;
revoke all on public.bible_telemetry_events from public, anon, authenticated;
revoke all on private.bible_telemetry_rate_limits from public, anon, authenticated;
grant select, delete on public.bible_telemetry_visitors to service_role;
grant select, delete on public.bible_telemetry_sessions to service_role;
grant select, delete on public.bible_telemetry_events to service_role;

create or replace function public.bible_record_telemetry_batch(
  p_visitor_id uuid,
  p_session_id uuid,
  p_events jsonb default '[]'::jsonb,
  p_context jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_headers jsonb := '{}'::jsonb;
  v_ip text := 'unknown';
  v_rate_key text;
  v_rate_count integer := 0;
  v_platform text := 'unknown';
  v_locale text := 'unknown';
  v_app_version text := 'v6';
  v_screen_bucket text := 'unknown';
  v_is_pwa boolean := false;
  v_entry_route text := 'home';
  v_last_route text := 'home';
  v_event jsonb;
  v_name text;
  v_feature text;
  v_route text;
  v_props jsonb;
  v_accepted integer := 0;
  v_requested integer := 0;
  v_has_session_end boolean := false;
begin
  if p_visitor_id is null or p_session_id is null then raise exception 'visitor_id and session_id are required'; end if;
  if p_events is null or jsonb_typeof(p_events) <> 'array' then raise exception 'events must be a JSON array'; end if;
  v_requested := jsonb_array_length(p_events);
  if v_requested > 25 then raise exception 'telemetry batch exceeds 25 events'; end if;
  if p_context is null or jsonb_typeof(p_context) <> 'object' then p_context := '{}'::jsonb; end if;

  begin
    v_headers := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  exception when others then
    v_headers := '{}'::jsonb;
  end;
  v_ip := split_part(coalesce(v_headers->>'x-forwarded-for', 'unknown'), ',', 1);
  v_rate_key := md5(v_ip || ':' || to_char(v_now at time zone 'UTC', 'YYYY-MM-DD HH24:MI'));
  insert into private.bible_telemetry_rate_limits(rate_key, window_start, request_count)
  values (v_rate_key, date_trunc('minute', v_now), 1)
  on conflict (rate_key) do update set request_count = private.bible_telemetry_rate_limits.request_count + 1
  returning request_count into v_rate_count;
  if v_rate_count > 180 then raise exception 'telemetry rate limit exceeded'; end if;

  if coalesce(p_context->>'platform','') ~ '^[A-Za-z0-9 ._/-]{1,40}$' then v_platform := p_context->>'platform'; end if;
  if coalesce(p_context->>'locale','') ~ '^[A-Za-z0-9_-]{1,24}$' then v_locale := p_context->>'locale'; end if;
  if coalesce(p_context->>'app_version','') ~ '^[A-Za-z0-9._+-]{1,40}$' then v_app_version := p_context->>'app_version'; end if;
  if coalesce(p_context->>'screen_bucket','') = any(array['xs','sm','md','lg','xl','unknown']) then v_screen_bucket := p_context->>'screen_bucket'; end if;
  v_is_pwa := lower(coalesce(p_context->>'is_pwa','false')) in ('true','1','yes');

  if v_requested > 0 then
    v_event := p_events->0;
    if coalesce(v_event->>'route','') ~ '^[A-Za-z0-9._/-]{1,80}$' then v_entry_route := left(v_event->>'route',80); end if;
    v_last_route := v_entry_route;
  end if;

  insert into public.bible_telemetry_visitors(visitor_id,first_seen_at,last_seen_at,first_route,last_route,platform,locale,app_version,is_pwa,screen_bucket,first_user_id,last_user_id)
  values(p_visitor_id,v_now,v_now,v_entry_route,v_entry_route,v_platform,v_locale,v_app_version,v_is_pwa,v_screen_bucket,v_user_id,v_user_id)
  on conflict (visitor_id) do update set
    last_seen_at=excluded.last_seen_at,last_route=excluded.last_route,platform=excluded.platform,locale=excluded.locale,
    app_version=excluded.app_version,is_pwa=excluded.is_pwa,screen_bucket=excluded.screen_bucket,
    first_user_id=coalesce(public.bible_telemetry_visitors.first_user_id,excluded.first_user_id),
    last_user_id=coalesce(excluded.last_user_id,public.bible_telemetry_visitors.last_user_id);

  insert into public.bible_telemetry_sessions(session_id,visitor_id,started_user_id,user_id,started_at,last_seen_at,authenticated_at,entry_route,last_route,platform,locale,app_version,is_pwa,screen_bucket)
  values(p_session_id,p_visitor_id,v_user_id,v_user_id,v_now,v_now,case when v_user_id is not null then v_now else null end,v_entry_route,v_entry_route,v_platform,v_locale,v_app_version,v_is_pwa,v_screen_bucket)
  on conflict (session_id) do update set
    last_seen_at=excluded.last_seen_at,
    user_id=coalesce(excluded.user_id,public.bible_telemetry_sessions.user_id),
    authenticated_at=coalesce(public.bible_telemetry_sessions.authenticated_at,case when excluded.user_id is not null then excluded.last_seen_at else null end),
    last_route=excluded.last_route,platform=excluded.platform,locale=excluded.locale,app_version=excluded.app_version,is_pwa=excluded.is_pwa,screen_bucket=excluded.screen_bucket;

  for v_event in select value from jsonb_array_elements(p_events) limit 25 loop
    v_name := lower(trim(coalesce(v_event->>'event_name','')));
    if v_name !~ '^[a-z0-9][a-z0-9._-]{0,63}$' then continue; end if;
    v_feature := lower(trim(coalesce(v_event->>'feature','app')));
    if v_feature !~ '^[a-z0-9][a-z0-9._/-]{0,79}$' then v_feature := 'app'; end if;
    v_route := lower(trim(coalesce(v_event->>'route',v_feature)));
    if v_route !~ '^[a-z0-9][a-z0-9._/-]{0,79}$' then v_route := v_feature; end if;
    v_last_route := v_route;

    select coalesce(jsonb_object_agg(key,value),'{}'::jsonb) into v_props
    from jsonb_each(case when jsonb_typeof(v_event->'properties')='object' then v_event->'properties' else '{}'::jsonb end)
    where key=any(array['action','element','source','status','result','error_name','visibility','install_state','offline','duration_bucket','count','content_type','difficulty','completion','reason_code','language','role','assignment_type','book_code','chapter','game','mode'])
      and (jsonb_typeof(value) in ('number','boolean','null') or (jsonb_typeof(value)='string' and char_length(value #>> '{}')<=120));

    insert into public.bible_telemetry_events(visitor_id,session_id,user_id,event_name,feature,route,properties,occurred_at)
    values(p_visitor_id,p_session_id,v_user_id,v_name,v_feature,v_route,v_props,v_now);
    v_accepted := v_accepted + 1;
    if v_name='session_end' then v_has_session_end := true; end if;
  end loop;

  update public.bible_telemetry_sessions set
    last_seen_at=v_now,last_route=v_last_route,event_count=event_count+v_accepted,
    ended_at=case when v_has_session_end then v_now else ended_at end,
    user_id=coalesce(v_user_id,user_id),
    authenticated_at=coalesce(authenticated_at,case when v_user_id is not null then v_now else null end)
  where session_id=p_session_id;

  update public.bible_telemetry_visitors set last_seen_at=v_now,last_route=v_last_route,last_user_id=coalesce(v_user_id,last_user_id)
  where visitor_id=p_visitor_id;

  return jsonb_build_object('ok',true,'accepted',v_accepted,'requested',v_requested,'authenticated',v_user_id is not null);
end;
$$;

revoke all on function public.bible_record_telemetry_batch(uuid,uuid,jsonb,jsonb) from public, anon, authenticated;
grant execute on function public.bible_record_telemetry_batch(uuid,uuid,jsonb,jsonb) to anon, authenticated, service_role;

create or replace function public.bible_prune_telemetry(p_before timestamptz default now()-interval '180 days')
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_events bigint; v_sessions bigint; v_visitors bigint; v_rate bigint;
begin
  delete from public.bible_telemetry_events where occurred_at<p_before; get diagnostics v_events=row_count;
  delete from public.bible_telemetry_sessions s where s.last_seen_at<p_before and not exists(select 1 from public.bible_telemetry_events e where e.session_id=s.session_id); get diagnostics v_sessions=row_count;
  delete from public.bible_telemetry_visitors v where v.last_seen_at<p_before and not exists(select 1 from public.bible_telemetry_sessions s where s.visitor_id=v.visitor_id); get diagnostics v_visitors=row_count;
  delete from private.bible_telemetry_rate_limits where window_start<now()-interval '2 hours'; get diagnostics v_rate=row_count;
  return jsonb_build_object('events',v_events,'sessions',v_sessions,'visitors',v_visitors,'rate_rows',v_rate);
end;
$$;
revoke all on function public.bible_prune_telemetry(timestamptz) from public, anon, authenticated;
grant execute on function public.bible_prune_telemetry(timestamptz) to service_role;

create or replace view public.bible_telemetry_daily with (security_invoker=true) as
select date_trunc('day',started_at) day,count(*)::bigint sessions,count(distinct visitor_id)::bigint visitors,
count(distinct user_id) filter(where user_id is not null)::bigint registered_users,
count(*) filter(where started_user_id is null and user_id is null)::bigint guest_only_sessions,
count(*) filter(where started_user_id is null and user_id is not null)::bigint guest_to_registered_sessions,
sum(event_count)::bigint events,
round(avg(extract(epoch from(last_seen_at-started_at))/60.0)::numeric,2) avg_session_minutes
from public.bible_telemetry_sessions group by 1;

create or replace view public.bible_telemetry_feature_daily with (security_invoker=true) as
select date_trunc('day',occurred_at) day,feature,event_name,count(*)::bigint events,count(distinct visitor_id)::bigint visitors,
count(distinct user_id) filter(where user_id is not null)::bigint registered_users
from public.bible_telemetry_events group by 1,2,3;

revoke all on public.bible_telemetry_daily from public, anon, authenticated;
revoke all on public.bible_telemetry_feature_daily from public, anon, authenticated;
grant select on public.bible_telemetry_daily to service_role;
grant select on public.bible_telemetry_feature_daily to service_role;

comment on table public.bible_telemetry_events is
  'V6 privacy-safe product telemetry. Event properties are server-whitelisted; no user-authored text, email, password, note, reflection, or message content is accepted.';
comment on function public.bible_record_telemetry_batch(uuid,uuid,jsonb,jsonb) is
  'Intentional write-only telemetry endpoint for anon/authenticated clients. Inputs are bounded and sanitized, user_id is derived from auth.uid(), and request IP is only used transiently to build a rotating rate-limit hash.';
