create extension if not exists pgcrypto;
create schema if not exists private;

-- BibleQuest backend blueprint. This file is not deployed to the user's other Supabase projects.
-- Apply only to a dedicated BibleQuest project.

create table if not exists public.bible_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  xp integer not null default 0 check (xp >= 0),
  streak integer not null default 0 check (streak >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bible_questions (
  id uuid primary key default gen_random_uuid(), external_id text unique,
  question_type text not null, book text, chapter integer, verse_start integer, verse_end integer,
  difficulty smallint not null default 1 check (difficulty between 1 and 5),
  prompt text not null, choices jsonb, answer jsonb, explanation text, reference_text text,
  content_class text not null default 'fact' check (content_class in ('fact','context','interpretation','wisdom','open_question')),
  source_name text not null, source_version text, source_url text, license text, attribution text,
  reviewed boolean not null default false, created_at timestamptz not null default now()
);

create table if not exists public.bible_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id uuid references public.bible_questions(id) on delete set null,
  external_question_id text, correct boolean not null, response jsonb,
  xp_earned integer not null default 0, created_at timestamptz not null default now()
);

create table if not exists public.bible_mastery (
  user_id uuid not null references auth.users(id) on delete cascade,
  topic text not null, score numeric(5,2) not null default 0 check (score between 0 and 100),
  attempts integer not null default 0, correct integer not null default 0,
  next_review_at timestamptz, updated_at timestamptz not null default now(),
  primary key (user_id, topic)
);

create table if not exists public.bible_polls (
  id uuid primary key default gen_random_uuid(), prompt text not null, context text,
  options jsonb not null, scripture_refs jsonb, content_class text not null default 'open_question',
  active boolean not null default true, created_at timestamptz not null default now()
);

create table if not exists public.bible_poll_votes (
  poll_id uuid not null references public.bible_polls(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  option_index integer not null, created_at timestamptz not null default now(),
  primary key (poll_id, user_id)
);

create table if not exists public.bible_congregations (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete restrict,
  name text not null check (char_length(name) between 2 and 100),
  slug text unique,
  timezone text not null default 'Asia/Tokyo',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.bible_congregation_members (
  congregation_id uuid not null references public.bible_congregations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('member','facilitator','leader','admin')),
  display_name text,
  active boolean not null default true,
  joined_at timestamptz not null default now(),
  primary key (congregation_id, user_id)
);

-- Generic teams support couples, families, small groups, and game teams.
-- Private conversation answers are deliberately not stored here.
create table if not exists public.bible_teams (
  id uuid primary key default gen_random_uuid(),
  congregation_id uuid not null references public.bible_congregations(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete restrict,
  team_type text not null check (team_type in ('couple','family','small_group','game_team')),
  name text not null check (char_length(name) between 2 and 80),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.bible_team_members (
  team_id uuid not null references public.bible_teams(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (team_id, user_id)
);

create table if not exists public.bible_shared_sessions (
  id uuid primary key default gen_random_uuid(),
  congregation_id uuid not null references public.bible_congregations(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete restrict,
  session_type text not null check (session_type in ('team_sprint','detective','verse_hunt','conversation_circle','wisdom_table','pair_share','couples','poll','other')),
  title text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.bible_session_participants (
  session_id uuid not null references public.bible_shared_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  team_id uuid references public.bible_teams(id) on delete set null,
  participation_points integer not null default 0 check (participation_points between 0 and 100),
  created_at timestamptz not null default now(),
  primary key (session_id, user_id)
);

-- Immutable dated events are the source for Today / This Week / All Time leaderboards.
-- Direct browser writes are intentionally forbidden. A trusted Edge Function/server should validate
-- game/session evidence and derive these events to prevent forged or spammed scores.
create table if not exists public.bible_score_events (
  id bigint generated by default as identity primary key,
  congregation_id uuid not null references public.bible_congregations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  team_id uuid references public.bible_teams(id) on delete set null,
  category text not null check (category in ('knowledge','reading','wisdom','mastery','consistency','group','couples')),
  points integer not null check (points between 1 and 100),
  source text not null,
  source_event_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (congregation_id, user_id, source_event_id)
);

create index if not exists bible_score_events_congregation_date_idx on public.bible_score_events (congregation_id, created_at desc);
create index if not exists bible_score_events_lane_idx on public.bible_score_events (congregation_id, category, created_at desc);
create index if not exists bible_score_events_user_idx on public.bible_score_events (user_id, created_at desc);

create table if not exists public.bible_badge_catalog (
  id text primary key,
  icon text not null,
  name text not null,
  category text not null,
  description text not null,
  threshold jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.bible_user_badges (
  congregation_id uuid not null references public.bible_congregations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  badge_id text not null references public.bible_badge_catalog(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb,
  earned_at timestamptz not null default now(),
  primary key (congregation_id, user_id, badge_id)
);

-- Backward-compatible personal groups; congregation features should prefer bible_teams/shared_sessions.
create table if not exists public.bible_groups (
  id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null, created_at timestamptz not null default now()
);

-- Security-definer membership helper avoids recursive RLS on the membership table.
-- It returns only a boolean and has an empty search_path to minimize privilege risk.
create or replace function private.is_bible_congregation_member(target_congregation uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.bible_congregation_members m
    where m.congregation_id = target_congregation
      and m.user_id = (select auth.uid())
      and m.active
  );
$$;

revoke all on function private.is_bible_congregation_member(uuid) from public;
grant usage on schema private to authenticated;
grant execute on function private.is_bible_congregation_member(uuid) to authenticated;

alter table public.bible_profiles enable row level security;
alter table public.bible_questions enable row level security;
alter table public.bible_attempts enable row level security;
alter table public.bible_mastery enable row level security;
alter table public.bible_polls enable row level security;
alter table public.bible_poll_votes enable row level security;
alter table public.bible_groups enable row level security;
alter table public.bible_congregations enable row level security;
alter table public.bible_congregation_members enable row level security;
alter table public.bible_teams enable row level security;
alter table public.bible_team_members enable row level security;
alter table public.bible_shared_sessions enable row level security;
alter table public.bible_session_participants enable row level security;
alter table public.bible_score_events enable row level security;
alter table public.bible_badge_catalog enable row level security;
alter table public.bible_user_badges enable row level security;

create policy "profiles read own" on public.bible_profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy "profiles insert own" on public.bible_profiles for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "profiles update own" on public.bible_profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "questions public read" on public.bible_questions for select to anon, authenticated using (reviewed = true);
create policy "attempts read own" on public.bible_attempts for select to authenticated using ((select auth.uid()) = user_id);
create policy "attempts insert own" on public.bible_attempts for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "mastery read own" on public.bible_mastery for select to authenticated using ((select auth.uid()) = user_id);
create policy "mastery insert own" on public.bible_mastery for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "mastery update own" on public.bible_mastery for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "polls public read" on public.bible_polls for select to anon, authenticated using (active = true);
create policy "votes read own" on public.bible_poll_votes for select to authenticated using ((select auth.uid()) = user_id);
create policy "votes insert own" on public.bible_poll_votes for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "votes update own" on public.bible_poll_votes for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "groups read own" on public.bible_groups for select to authenticated using ((select auth.uid()) = owner_id);
create policy "groups insert own" on public.bible_groups for insert to authenticated with check ((select auth.uid()) = owner_id);

create policy "congregations member read" on public.bible_congregations for select to authenticated using (
  owner_id = (select auth.uid()) or private.is_bible_congregation_member(id)
);
create policy "congregations owner insert" on public.bible_congregations for insert to authenticated with check (owner_id = (select auth.uid()));
create policy "congregations owner update" on public.bible_congregations for update to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));

create policy "members congregation read" on public.bible_congregation_members for select to authenticated using (
  private.is_bible_congregation_member(congregation_id)
  or exists (select 1 from public.bible_congregations c where c.id=congregation_id and c.owner_id=(select auth.uid()))
);
-- Owners may create only their own initial membership row from the browser.
-- Joining other users and changing roles should be trusted-server operations after invite/join-code validation.
create policy "owner self membership insert" on public.bible_congregation_members for insert to authenticated with check (
  user_id=(select auth.uid()) and exists (
    select 1 from public.bible_congregations c where c.id=congregation_id and c.owner_id=(select auth.uid())
  )
);

create policy "teams congregation read" on public.bible_teams for select to authenticated using (
  private.is_bible_congregation_member(congregation_id)
);
create policy "teams member create" on public.bible_teams for insert to authenticated with check (
  created_by=(select auth.uid()) and private.is_bible_congregation_member(congregation_id)
);
create policy "team members congregation read" on public.bible_team_members for select to authenticated using (exists (
  select 1 from public.bible_teams t where t.id=team_id and private.is_bible_congregation_member(t.congregation_id)
));
create policy "team creator self insert" on public.bible_team_members for insert to authenticated with check (
  user_id=(select auth.uid()) and exists (
    select 1 from public.bible_teams t where t.id=team_id and t.created_by=(select auth.uid()) and private.is_bible_congregation_member(t.congregation_id)
  )
);

create policy "sessions congregation read" on public.bible_shared_sessions for select to authenticated using (
  private.is_bible_congregation_member(congregation_id)
);
create policy "sessions member create" on public.bible_shared_sessions for insert to authenticated with check (
  created_by=(select auth.uid()) and private.is_bible_congregation_member(congregation_id)
);
create policy "participants congregation read" on public.bible_session_participants for select to authenticated using (exists (
  select 1 from public.bible_shared_sessions s where s.id=session_id and private.is_bible_congregation_member(s.congregation_id)
));
create policy "participants self insert" on public.bible_session_participants for insert to authenticated with check (
  user_id=(select auth.uid()) and exists (
    select 1 from public.bible_shared_sessions s where s.id=session_id and private.is_bible_congregation_member(s.congregation_id)
  )
);

create policy "score events congregation read" on public.bible_score_events for select to authenticated using (
  private.is_bible_congregation_member(congregation_id)
);
-- No INSERT/UPDATE/DELETE policy for score events: trusted backend only.

create policy "badge catalog read" on public.bible_badge_catalog for select to authenticated using (active=true);
create policy "earned badges congregation read" on public.bible_user_badges for select to authenticated using (
  private.is_bible_congregation_member(congregation_id)
);
-- No browser write policy for earned badges: trusted backend derives them from verified events.

revoke all on public.bible_profiles, public.bible_questions, public.bible_attempts, public.bible_mastery, public.bible_polls, public.bible_poll_votes, public.bible_groups,
  public.bible_congregations, public.bible_congregation_members, public.bible_teams, public.bible_team_members, public.bible_shared_sessions,
  public.bible_session_participants, public.bible_score_events, public.bible_badge_catalog, public.bible_user_badges from anon, authenticated;

grant select on public.bible_questions, public.bible_polls to anon, authenticated;
grant select, insert, update on public.bible_profiles, public.bible_attempts, public.bible_mastery, public.bible_poll_votes, public.bible_groups to authenticated;
grant select, insert, update on public.bible_congregations to authenticated;
grant select, insert on public.bible_congregation_members to authenticated;
grant select, insert on public.bible_teams, public.bible_team_members, public.bible_shared_sessions, public.bible_session_participants to authenticated;
grant select on public.bible_score_events, public.bible_badge_catalog, public.bible_user_badges to authenticated;
