create or replace function private.bible_can_review_content(target_congregation uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    exists (
      select 1
      from public.bible_app_access a
      where a.user_id = (select auth.uid())
        and a.active
        and a.role in ('owner','admin')
    )
    or exists (
      select 1
      from public.bible_congregation_members m
      where m.congregation_id = target_congregation
        and m.user_id = (select auth.uid())
        and m.active
        and m.role in ('leader','pastor','admin')
    );
$$;

revoke all on function private.bible_can_review_content(uuid) from public;
grant execute on function private.bible_can_review_content(uuid) to authenticated;

create table if not exists public.bible_content_reports (
  id bigint generated by default as identity primary key,
  congregation_id uuid not null references public.bible_congregations(id) on delete cascade,
  reporter_id uuid references auth.users(id) on delete set null,
  content_key text not null check (char_length(content_key) between 3 and 180),
  content_type text not null default 'question' check (content_type in ('question','statement','answer','explanation','story','reader','other')),
  content_source text not null default 'app' check (char_length(content_source) <= 120),
  content_ref text check (content_ref is null or char_length(content_ref) <= 160),
  content_text text not null check (char_length(content_text) between 1 and 4000),
  content_payload jsonb not null default '{}'::jsonb,
  reason text not null default 'other' check (reason in ('doctrinal','accuracy','wording','inappropriate','duplicate','source','other')),
  note text check (note is null or char_length(note) <= 1200),
  status text not null default 'open' check (status in ('open','reviewed','closed')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bible_content_reports_queue_idx
  on public.bible_content_reports(congregation_id,status,created_at desc);
create index if not exists bible_content_reports_key_idx
  on public.bible_content_reports(congregation_id,content_key);
create index if not exists bible_content_reports_reporter_idx
  on public.bible_content_reports(reporter_id,created_at desc);

alter table public.bible_content_reports enable row level security;
revoke all on table public.bible_content_reports from anon, authenticated;
grant select, insert, update on table public.bible_content_reports to authenticated;

drop policy if exists "content reports submit own" on public.bible_content_reports;
create policy "content reports submit own"
on public.bible_content_reports for insert
to authenticated
with check (
  reporter_id = (select auth.uid())
  and private.is_bible_congregation_member(congregation_id)
);

drop policy if exists "content reports read own or reviewer" on public.bible_content_reports;
create policy "content reports read own or reviewer"
on public.bible_content_reports for select
to authenticated
using (
  reporter_id = (select auth.uid())
  or private.bible_can_review_content(congregation_id)
);

drop policy if exists "content reports reviewer update" on public.bible_content_reports;
create policy "content reports reviewer update"
on public.bible_content_reports for update
to authenticated
using (private.bible_can_review_content(congregation_id))
with check (private.bible_can_review_content(congregation_id));

create table if not exists public.bible_content_decisions (
  congregation_id uuid not null references public.bible_congregations(id) on delete cascade,
  content_key text not null check (char_length(content_key) between 3 and 180),
  content_type text not null default 'question' check (content_type in ('question','statement','answer','explanation','story','reader','other')),
  origin text not null default 'review' check (origin in ('quarantine','user_report','review')),
  decision text not null check (decision in ('include','exempt','remove')),
  content_ref text check (content_ref is null or char_length(content_ref) <= 160),
  content_snapshot jsonb not null default '{}'::jsonb,
  rationale text check (rationale is null or char_length(rationale) <= 1200),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (congregation_id,content_key)
);

create index if not exists bible_content_decisions_state_idx
  on public.bible_content_decisions(congregation_id,decision,updated_at desc);

alter table public.bible_content_decisions enable row level security;
revoke all on table public.bible_content_decisions from anon, authenticated;
grant select, insert, update on table public.bible_content_decisions to authenticated;

drop policy if exists "content decisions congregation read" on public.bible_content_decisions;
create policy "content decisions congregation read"
on public.bible_content_decisions for select
to authenticated
using (
  private.is_bible_congregation_member(congregation_id)
  or private.bible_can_review_content(congregation_id)
);

drop policy if exists "content decisions reviewer insert" on public.bible_content_decisions;
create policy "content decisions reviewer insert"
on public.bible_content_decisions for insert
to authenticated
with check (
  private.bible_can_review_content(congregation_id)
  and reviewed_by = (select auth.uid())
);

drop policy if exists "content decisions reviewer update" on public.bible_content_decisions;
create policy "content decisions reviewer update"
on public.bible_content_decisions for update
to authenticated
using (private.bible_can_review_content(congregation_id))
with check (
  private.bible_can_review_content(congregation_id)
  and reviewed_by = (select auth.uid())
);

drop policy if exists "content reviewers read congregations" on public.bible_congregations;
create policy "content reviewers read congregations"
on public.bible_congregations for select
to authenticated
using (private.bible_can_review_content(id));
